### ISSUE TITLE
How to get a refresh token?

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#10]
How to get a refresh token using spapi_oauth_code ?

**Comment by jlevers** [comment]
Just to make sure I'm understanding your question properly, are you referring to the code you're given as a query parameter when someone authorizes your app?

**Comment by Nilanth** [comment]
@jlevers Yes

**Comment by jlevers** [comment]
This should do it (I'll integrate this into the library at some point):

```php
$client = new GuzzleHttp\Client();
$res = $client->post("https://api.amazon.com/auth/o2/token", [
    GuzzleHttp\RequestOptions::JSON => [
        "grant_type" => "authorization_code",
        "code" => $oauthCode,
        "client_id" => $_ENV["LWA_CLIENT_ID"],
        "client_secret" => $_ENV["LWA_CLIENT_SECRET"],
    ]
]);

// Parse out the refresh token (long-lived), the access token (short-lived), and the
// number of seconds until the access token expires
$body = json_decode($res->getBody(), true);
[
    "refresh_token" => $refreshToken,
    "access_token" => $accessToken,
    "expires_in" => $secsTillExpiration,
] = $body;
```

**Comment by Nilanth** [comment]
@jlevers Thanks for the quick reply!  
Do we support **/authorization/v1/authorizationCode** API also?

**Comment by jlevers** [comment]
https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/AuthorizationApi.md#getauthorizationcode

**Comment by sunil11475-dev** [comment]
> This should do it (I'll integrate this into the library at some point):
> 
> ```
> $client = new GuzzleHttp\Client();
> $res = $client->post("https://api.amazon.com/auth/o2/token", [
>     GuzzleHttp\RequestOptions::JSON => [
>         "grant_type" => "authorization_code",
>         "code" => $oauthCode,
>         "client_id" => $_ENV["LWA_CLIENT_ID"],
>         "client_secret" => $_ENV["LWA_CLIENT_SECRET"],
>     ]
> ]);
> 
> // Parse out the refresh token (long-lived), the access token (short-lived), and the
> // number of seconds until the access token expires
> $body = json_decode($res->getBody(), true);
> [
>     "refresh_token" => $refreshToken,
>     "access_token" => $accessToken,
>     "expires_in" => $secsTillExpiration,
> ] = $body;
> ```
Hi @jlevers 

You are Super Dev.... I reading and searching for 4 months but no success and today I found your post and got the solution; nobody provided, not even Amazon API support helped... May be i was on wrong direction. 

Just to say - Thank you very much for your answer. Very happy, no word to describe. 

Also thanks to @Nilanth asking this question.

**Comment by sunil11475-dev** [comment]
> This should do it (I'll integrate this into the library at some point):
> 
> ```
> $client = new GuzzleHttp\Client();
> $res = $client->post("https://api.amazon.com/auth/o2/token", [
>     GuzzleHttp\RequestOptions::JSON => [
>         "grant_type" => "authorization_code",
>         "code" => $oauthCode,
>         "client_id" => $_ENV["LWA_CLIENT_ID"],
>         "client_secret" => $_ENV["LWA_CLIENT_SECRET"],
>     ]
> ]);
> 
> // Parse out the refresh token (long-lived), the access token (short-lived), and the
> // number of seconds until the access token expires
> $body = json_decode($res->getBody(), true);
> [
>     "refresh_token" => $refreshToken,
>     "access_token" => $accessToken,
>     "expires_in" => $secsTillExpiration,
> ] = $body;
> ```
Hi @jlevers 

You are Super Dev.... I reading and searching for 4 months but no success and today I found your post and got the solution; nobody provided, not even Amazon API support helped... May be i was on wrong direction. 

Just to say - Thank you very much for your answer. Very happy, no word to describe. 

Also thanks to @Nilanth asking this question.
