### ISSUE TITLE
[getCatalogItem] May get InvalidArgumentException when includedData include images

### ISSUE THREAD

**Issue by astelink** [jlevers/selling-partner-api#100]
Could you change the processing of `ItemImage::setVariant()` ?

I ran this
`$api->getCatalogItem('B00PVAQ2WO', 'A1VC38T7YXB528', ['images', 'summaries', 'salesRanks', 'variations', 'attributes']);`

result
`Error: [InvalidArgumentException] Invalid value 'PT11' for 'variant', must be one of 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06', 'PT07', 'PT08', 'SWCH'`

This ASIN (B00PVAQ2WO) has images variant 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06', 'PT07', 'PT11', 'PT16'

This time 'PT11', 'PT16' raised error
There may be other products with values other than `ItemImage::getVariantAllowableValues()`
But all I need is 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06'

It's okay if you can't get values other than getVariantAllowableValues(), so it would be helpful if you could prevent the error from occurring.

**Comment by jlevers** [comment]
I removed the image variants enum in `v4.0.0`, so you shouldn't run into this issue anymore once you upgrade to that version.  Any value of `variant` is now allowed. Thanks for reporting!
