### ISSUE TITLE
access to request resource denied

### ISSUE THREAD

**Issue by jmshofstall** [jlevers/selling-partner-api#108]
At first I was getting this response because I didn't have the config completely right, but I fixed that and had a successful createReport() request that returned a report_id (it says report_id, but in reality it gave me the same kind of number that was in the MWS api as a ReportRequestId, I don't know if they changed this since their docs seem to be meant to confuse instead of help). I saved and tried to use that report_id to do a getReport(report_id) but got access denied, and now no matter what function I try to use (getReport, getReports, trying another createReport), it errors with access denied. Started a new issue because I didn't see anywhere someone had the same issue where it worked and stopped working. Using basically the sample code, but here it is anyway

```php
$config = new \SellingPartnerApi\Configuration([
    "lwaClientId" => $this->spClientId,
    "lwaClientSecret" => $this->spClientSecret,
    "lwaRefreshToken" => Crypt::decryptString($access->refresh_token),
    "accessToken" => Crypt::decryptString($access->access_token),
    "accessTokenExpiration" => strtotime($access->expires_at),
    "awsAccessKeyId" => $this->iamKeyId,
    "awsSecretAccessKey" => $this->iamSecret,
    "endpoint" => \SellingPartnerApi\Endpoint::NA,  // or another endpoint from lib/Endpoints.php
    'roleArn' => $this->iamRole
]);
        
$apiInstance = new \SellingPartnerApi\Api\ReportsApi($config);
$body = new \SellingPartnerApi\Model\Reports\CreateReportSpecification(); // \SellingPartnerApi\Model\Reports\CreateReportSpecification
$body->setMarketplaceIds([$this->marketplaceId]);
$body->setReportType('GET_MERCHANT_LISTINGS_ALL_DATA');
$body->setDataEndTime(Carbon::now()->toISOString());
$body->setDataStartTime(Carbon::parse('2002-08-31')->toISOString());
try {
    $result = $apiInstance->createReport($body);
    print_r($result);
} catch (Exception $e) {

}`

**Comment by jlevers** [comment]
The report IDs returned by the SP API and MWS look the same, so that's not a problem. Your code looks fine, assuming all the credentials are set correctly.

Have you tried generating a new refresh token and using that?

**Comment by jmshofstall** [comment]
Yes I tried a new token, and even tried completely reauthorizing. It's just weird that it worked to give me the report id but then 20 minutes later I get access denied for every request.

**Comment by jmshofstall** [comment]
<img width="672" alt="Screen Shot 2021-10-17 at 10 31 30 AM" src="https://user-images.githubusercontent.com/20341191/137634198-73ae7c56-b78a-4ba7-9e79-225674e790d7.png">

I've only tried the one report type, I figured there's nothing wrong with the request itself since it says access denied and not bad request. I tried adding the other two roles and reauthorizing but still got access denied

**Comment by jlevers** [comment]
Different report types require access to different roles, which is why I think it might be worth trying a different role. But you have access to the Inventory and Order Tracking role, which should let you use the `GET_MERCHANT_LISTINGS_ALL_DATA` report.

Try making the start time a max of 2 years ago, and see if that solves the problem -- I've had issues before when trying to retrieve too large of a time range at once. Since you're getting Access Denied rather than Invalid Input, I doubt that's the problem, but it's worth a try.

If that doesn't work, I recommend opening a case on Seller Central and/or creating a new issue in the main documentation repository (amzn/selling-partner-api-docs).

**Comment by jmshofstall** [comment]
Thanks for the suggestions and help, going to try them today. I'm leaning toward it not being a this library issue as well, just hoped to get an idea of why it's denied.

**Comment by abhitheawesomecoder** [comment]
@jmshofstall Can I get response (Seller Product/Inventory List) in Json or Array format using reports(GET_MERCHANT_LISTINGS_ALL_DATA)?
