### ISSUE TITLE
fees estimate request returning null

### ISSUE THREAD

**Issue by yassersebai** [jlevers/selling-partner-api#11]
![image](https://user-images.githubusercontent.com/42872824/113853273-266d6180-97a6-11eb-8920-23bb74b39554.png)

when trying to retrieve a product's estimated fees, the documentation stated that I have to pass an object from ```GetMyFeesEstimateRequest``` as a parameter, while this object is directly returning null, and eventually no data are being retrieved.

any clue on why this is happening  ?

**Comment by jlevers** [comment]
The `GetMyFeesEstimateRequest` object has to be passed data when it is constructed (as do most models). For example:

```php
use SellingPartnerApi\Api;
use SellingPartnerApi\Model\Fees;

$feesEstimateRequest = new Fees\GetMyFeesEstimateRequest([
    "fees_estimate_request" => new Fees\FeesEstimateRequest([
        "marketplace_id" => "ATVPDKIKX0DER",
        "price_to_estimate_fees" => new Fees\PriceToEstimateFees([
            "listing_price" => new Fees\MoneyType([
                "currency_code" => "USD",
                "amount" => "21.99",
            ]),
            "shipping_price" => new Fees\MoneyType([
                "currency_code" => "USD",
                "amount" => "4.23",
            ]),
            "identifier" => "some_unique_value",
    ]),
]);

$api = new Api\FeesApi();
$response = $api->getMyFeesEstimateForSKU("your_sku", $feesEstimateRequest);
```
(I haven't tested that code snippet, but it should at least be close enough to correct to get you up and running.)

As you can see on its documentation page, the [`GetMyFeesEstimateRequest`](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/Fees/GetMyFeesEstimateRequest.md) model has an inner attribute called `fees_estimate_request`, which should be an instance of the `FeesEstimateRequest` model. Then that model has some inner attributes, some of which are other models...you can keep clicking through the links on the documentation pages until you've checked the sub-attributes of every attribute required by the model you're using. Many models have optional attributes, which will be marked `optional` on the model's documentation page.

**Comment by jlevers** [comment]
@yassersebai did you resolve this issue? If so, I'd like to close it.

**Comment by jlevers** [comment]
I'm going to close this -- please feel free to reopen it if necessary.
