### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by RonJeremyR6** [jlevers/selling-partner-api#114]
Fatal error: Uncaught Error: Object of class DateTime could not be converted to string in \vendor\guzzlehttp\psr7\src\Query.php:96

Since latest update I get the above error message for all calls where $query_start_date is involved.

The code is: 
```
$apiInstance = new \SellingPartnerApi\Api\FbaOutboundApi($config);
$query_start_date = new \DateTime("2021-01-20T19:20:30+01:00"); 
$next_token = '';

try
{
    $result = $apiInstance->listAllFulfillmentOrders($query_start_date, $next_token);
    print_r($result);
} 
catch (Exception $e) 
{
    echo 'Exception when calling FbaOutboundApi->listAllFulfillmentOrders: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by jlevers** [comment]
@RonJeremyR6 since I haven't heard from you I'm going to assume that you figured out the problem, but if you need any more help feel free to reopen the issue.
