### ISSUE TITLE
Use own Guzzle Client in Document upload 

### ISSUE THREAD

**Issue by stevenbrookes** [jlevers/selling-partner-api#117]
It would be useful for us to be able to pass in our own Guzzle Client into the Document class to be used on upload.  We have a handler stack we normally use for logging etc.  We can use it for the main API calls, but the upload is invisible as we can't get to the Client created in the upload function.  

Maybe it could be passed in the constructor optionally?  Or in the upload function itself.  

Other than that just wanted to say thanks for this library as it's been a real pleasure to use so far.

**Comment by jlevers** [comment]
Hey @stevenbrookes, good idea! I think passing it in the constructor makes the most sense, in case the Guzzle client needs to be used in other parts of the `Document` class in the future. I'll make the update sometime soon and comment here once I've released it.

**Comment by jlevers** [comment]
Released in `v4.1.2` -- let me know if you run into any issues!

**Comment by stevenbrookes** [comment]
Hi @jlevers thanks so much.  Will give it a try.
