### ISSUE TITLE
400 InvalidInput Error for FbaInventoryApi->getInventorySummaries

### ISSUE THREAD

**Issue by steverobison** [jlevers/selling-partner-api#118]
Hello,

I'm using the following code to get inventory.  I haven't used FbaInventory yet but have used 6 of the other apis in this project without error.

$fba_inventory_api = new FbaInventoryApi($config)
$fba_inventory_api->getInventorySummaries('Marketplace', ['ATVPDKIKX0DER'], ['ATVPDKIKX0DER']);

Exception when calling FbaInventoryApi->getInventorySummaries: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Input",
      "details": ""
    }
  ]
}

With some digging, I found the amazon url being called, which looks right to me.
  
https://sellingpartnerapi-na.amazon.com/fba/inventory/v1/summaries?details=0&granularityType=Marketplace&granularityId=ATVPDKIKX0DER&marketplaceIds=ATVPDKIKX0DER

Let me know if you need additional information from me.  Thanks!

**Comment by jlevers** [comment]
I think this is probably an issue on Amazon's end -- I recommend opening a support case with them on Seller Central and/or creating an issue in the main SP API documentation repository: https://github.com/amzn/selling-partner-api-docs/issues

Sorry I can't be of more help!
