### ISSUE TITLE
Is there a change log with the major version updates for breaking changes?

### ISSUE THREAD

**Issue by cpiggott** [jlevers/selling-partner-api#121]
Is there a change log that is made for major revisions? I've got tests set up, but it would be nice to know ahead of time what I might need to change, since some of the major version revisions have required some re-architecting at times from a consumption of the API.

**Comment by jlevers** [comment]
Yep, whenever I publish a new release the changes are in the release notes. As an example, the notes for the last release are here: https://github.com/jlevers/selling-partner-api/releases/tag/v4.1.2

Does that get you the info you need?

**Comment by cpiggott** [comment]
That's perfect. I was looking under tags and not releases. My bad!
