### ISSUE TITLE
Invalid value for enum '\SellingPartnerApi\Model\FbaInbound\ShipmentStatus' must be one of...

### ISSUE THREAD

**Issue by HeBuguM** [jlevers/selling-partner-api#124]
There is status "**READY_TO_SHIP**" that is missing from Amazon's documentation and I get an error if there is a shipment with this status returned by SellingPartnerApi\Api\FbaInboundApi->getShipments();

Can you add a constant in **\SellingPartnerApi\Model\FbaInbound\ShipmentStatus** to fix the issue.

**Comment by jlevers** [comment]
Should be fixed in `v4.1.7`. Please give it a try and close the issue if it's resolved.

**Comment by HeBuguM** [comment]
All good thank you!
