### ISSUE TITLE
getFBAOrderPreview - Invalid value for enum

### ISSUE THREAD

**Issue by HeBuguM** [jlevers/selling-partner-api#125]
Another undocumented value in the response causes the error. (Invalid value 'POUNDS' for 'unit', must be one of 'KG', 'LB' )

Can you please add "**POUNDS**" in \SellingPartnerApi\Model\FbaOutbound\Weight

**Comment by jlevers** [comment]
Should be fixed in `v4.1.7`. Please give it a try and close the issue if it's resolved.

**Comment by HeBuguM** [comment]
All good thank you!
