### ISSUE TITLE
Exception when calling VendorDirectFulfillmentOrdersApi->getOrders:

### ISSUE THREAD

**Issue by ait1ispring** [jlevers/selling-partner-api#128]
Hi, when I tried to get orders from vendor DF, It causes exception, please take a look, thank you.

Code start:
$apiInstance = new SellingPartnerApi\Api\VendorDirectFulfillmentOrdersApi($vc_dfa_config);
$created_after = new \DateTime("2013-10-20T19:20:30+01:00"); // \DateTime | Purchase orders that became available after this date and time will be included in the result. Must be in ISO-8601 date/time format.
$created_before = new \DateTime("2013-10-20T19:20:30+01:00"); // \DateTime | Purchase orders that became available before this date and time will be included in the result. Must be in ISO-8601 date/time format.

try {
    $result = $apiInstance->getOrders($created_after, $created_before);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling VendorDirectFulfillmentOrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}

Code End.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Error message start:
PHP Warning:  rawurlencode() expects parameter 1 to be string, object given in 
vendor/guzzlehttp/psr7/src/Query.php on line 97
PHP Warning:  rawurlencode() expects parameter 1 to be string, object given in 
vendor/guzzlehttp/psr7/src/Query.php on line 97
Exception when calling VendorDirectFulfillmentOrdersApi->getOrders: [400] {
  "errors": [
    {
     "message": "Missing or invalid request parameters: [createdBefore, createdAfter]",
     "code": "InvalidInput"
    }
  ]
}
Error message end.

**Comment by jlevers** [comment]
$created_before and $created_after need to be passed as UTC date strings, not as objects -- try this:

```php
$apiInstance = new SellingPartnerApi\Api\VendorDirectFulfillmentOrdersApi($vc_dfa_config);
$created_after = new \DateTime("2013-10-20T18:20:30"); // \DateTime | Purchase orders that became available after this date and time will be included in the result. Must be in ISO-8601 date/time format.
$after_str = $created_after->format('Y-m-d\TH:i:s');
$created_before = new \DateTime("2013-10-20T18:20:30"); // \DateTime | Purchase orders that became available before this date and time will be included in the result. Must be in ISO-8601 date/time format.
$before_str = $created_before->format('Y-m-d\TH:i:s');

try {
    $result = $apiInstance->getOrders($after_str, $before_str);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling VendorDirectFulfillmentOrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by ait1ispring** [comment]
It fixed, thank you. the document has not upload yet.
