### ISSUE TITLE
Exception when calling FbaInventoryApi->getInventorySummaries

### ISSUE THREAD

**Issue by rcgang8** [jlevers/selling-partner-api#130]
```php
$apiInstance = new SellingPartnerApi\Api\FbaInventoryApi($config);
$granularity_type = 'Marketplace';
$granularity_id = 'ATVPDKIKX0DER';
$marketplace_ids = array('ATVPDKIKX0DER'); 
$details = true; 
$start_date_time = "2021-11-01T00:00:00Z"; 
$seller_skus = null; 
$next_token = null; 
try {
    $result = $apiInstance->getInventorySummaries($granularity_type, $granularity_id, $marketplace_ids, $details, $start_date_time);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling FbaInventoryApi->getInventorySummaries: ', $e->getMessage(), PHP_EOL;
}
```

Reposnse:
Exception when calling FbaInventoryApi->getInventorySummaries: [400] { "errors": [ { "code": "InvalidInput", "message": "Invalid Input", "details": "" } ] }
Can you please help me with this.

**Comment by jlevers** [comment]
Make `$details` a string instead of a boolean: `$details = 'true';`. I know it's a little weird, but it has to do with a bug in Amazon's API models that can't be fully fixed in this library. See #75 for details.

**Comment by rcgang8** [comment]
Thank you so much @jlevers. It worked
