### ISSUE TITLE
How to download FileContents?

### ISSUE THREAD

**Issue by plastic-craft** [jlevers/selling-partner-api#132]
I know the `SellingPartnerApi\Document` class handles the downloads for report documents, but is there anything that can be used to retrieve the file contents from a `createShipment` call (to get the label)?

The response includes the `FileContents` model which contains the data for printing labels in the form of a Base64-encoded, GZip-compressed string, but I'm not too sure how to convert this to an actual .PNG file. Is this something that can done by the library or is there another way that this has to be done? If you could help guide me in the right direction I would appreciate your help. 

Also, as an unrelated side note, the `FileType` model needs to be updated to include an emtpy const as the `cancelShipment` response contains a blank `FileType` string (similar to the `LabelFormat` model). I was getting an invalid enum error for this particular call and fixed it by doing the above.

**Comment by jlevers** [comment]
Are you referring to the `createShipment`/`cancelShipment` calls from the Shipping API or from the Merchant Fulfillment API?

**Comment by plastic-craft** [comment]
Sorry, I was referring to the Merchant Fulfillment API.

I actually managed to figure out the original issue by parsing the `Contents` string from the response and decoding it by doing the following:

```php
$createShipmentResponse = $apiInstance->createShipment($body);
$jsonResponse = json_decode($createShipmentResponse, true);

$fileContents = $jsonResponse['payload']['Label']['FileContents']['Contents'];
$labelPng = gzdecode(base64_decode($fileContents));

return $labelPng;
```

However, the issue regarding the `FileType` model in the Merchant Fulfillment API still remains here:

https://github.com/jlevers/selling-partner-api/blob/74b0615a73782632e32ca3ffa4843edc1fd709d3/lib/Model/MerchantFulfillment/FileType.php#L40-L48

I was getting an invalid enum error whenever attempting any `cancelShipment` call and I believe it is due to the response returning an empty string `FileType` in the `FileContents` object. I think adding an empty enum value would fix this. I can provide a sample `cancelShipment` response if you need to verify this

**Comment by jlevers** [comment]
Give `v4.1.8` a try and let me know if it solves this issue for you.

**Comment by plastic-craft** [comment]
Perfect, seems to work now
