### ISSUE TITLE
Application do not have access to some or all requested resource"

### ISSUE THREAD

**Issue by ait1ispring** [jlevers/selling-partner-api#133]
Hi, I tried to get all the orders from amazon seller central, when I used 

getOrder($order_id, $data_elements): \SellingPartnerApi\Model\Orders\GetOrderResponse, 

it is working fine, but when I used 

getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements): \SellingPartnerApi\Model\Orders\GetOrdersResponse

it keeps giving the "Application do not have access to some or all requested resource", I checked my APP registration Roles, and I selected all the roles that allow application to get access. 

My code below:

```php
$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('marketplace_ids_example'); // string[] | A list of MarketplaceId values. Used to select orders that were placed in the specified marketplaces.


try {
    $result = $apiInstance->getOrders($marketplace_ids);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}
```

Is there anything that you can help. Thank you.

**Comment by jlevers** [comment]
In your actual code, did you replace `marketplace_ids_example` with an [actual marketplace ID](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#marketplaceid-values)?

**Comment by ait1ispring** [comment]
Yes. I did. 

It looks like:

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER'); // string[] | A list of MarketplaceId values. Used to select orders that were placed in the specified marketplaces.

try {
$result = $apiInstance->getOrders($marketplace_ids);
print_r($result);
} catch (Exception $e) {
echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}

**Comment by jlevers** [comment]
Amazon requires that you pass a value for either `$created_after` or `$last_updated_after` when calling `getOrders`. Try passing a UTC datetime string for one of those two parameters (should look something like `2021-11-17T00:00:00Z`) and see if that fixes your problem.

**Comment by ait1ispring** [comment]
I tried your suggestion but the same result.

My code:

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER'); // string | A marketplace identifier. Specifies the marketplace for which prices are returned.
$created_after = new \DateTime("2021-06-01");
$after_str = $created_after->format('Y-m-d\TH:i:s');

try {
    $result = $apiInstance->getOrders($marketplace_ids,$after_str);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ProductPricingApi->getItemOffers: ', $e->getMessage(), PHP_EOL;
}

response:
{
"errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}

**Comment by jlevers** [comment]
You're missing a `Z` at the end of the date string -- try adding that in and see if tat helps.

**Comment by ait1ispring** [comment]
I tried and still the same error response.

My code:

~~~
$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER'); // string | A marketplace identifier. Specifies the marketplace for which prices are returned.
$created_after = new \DateTime("2021-06-01");
//first
$after_str = $created_after->format(DateTime::ATOM);
//second
$after_str = $created_after->format('Y-m-dTH:i:sZ');
//third
$after_str = date(DATE_ISO8601, strtotime('2021-10-30 23:21:46'));

try {
    $result = $apiInstance->getOrders($marketplace_ids,$after_str);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ProductPricingApi->getItemOffers: ', $e->getMessage(), PHP_EOL;
}
~~~

Response:
~~~
{
"errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}

**Comment by jlevers** [comment]
Those format strings still aren't correct -- you need a backslash after the `T` and the `Z`, like so:

```php
$after_str = $created_after->format('Y-m-d\TH:i:s\Z');
```

**Comment by jlevers** [comment]
Since I haven't heard from you, I'm going to assume you resolved the issue. Please feel free to reopen it if you're still having problems.
