### ISSUE TITLE
Issue in blog manual.

### ISSUE THREAD

**Issue by vladles** [jlevers/selling-partner-api#135]
Hello Jesse, 
I read your manual on blog https://jesseevers.com/spapi-oauth/
And I stuck on the final step when we should do the test request. 
In the manual you wrote that we should put in the SellingPartnerApi\Configuration class only "refreshToken" and I expectedly get the error that I should fill in required params. (lwaClientId, lwaClientSecret, awsAccessKeyId, awsSecretAccessKey, endpoint). 

But could you tell me in which param I should fill received refreshToken and accessToken from oAuth? 

Part of code from the Blog post.
```
// Construct a Configuration object using the new refresh token we retrieved
 $config = new SellingPartnerApi\Configuration(["refreshToken" => $refreshToken]);
 // Create a new SellersApi instance with the above config
 $api = new SellingPartnerApi\Api\SellersApi($config);

 $params = $body;
 try {
     // Call the Selling Partner API
     $result = $api->getMarketplaceParticipations();
     $params["success"] = true;
 } catch (Exception $e) {
     print_r($e);
 }
```

**Comment by jlevers** [comment]
Hey @vladles, sorry about that -- not sure how I never caught that error. Here's what it should actually look like:

```php
    [
        "refresh_token" => $refreshToken,
        "access_token" => $accessToken,
        "expires_in" => $secsTillExpiration,
    ] = $body;

    $config = new SellingPartnerApi\Configuration([
        "lwaClientId" => "<LWA client ID>",
        "lwaClientSecret" => "<LWA client secret>",
        "lwaRefreshToken" => $refreshToken,
        // If you don't pass the lwaAccessToken key/value, the library will automatically generate an access
        // token based on the refresh token above
        "lwaAccessToken" => $accessToken,
        "awsAccessKeyId" => "<AWS access key ID>",
        "awsSecretAccessKey" => "<AWS secret access key>",
        "endpoint" => SellingPartnerApi\Endpoint::NA,
    ]);
    $api = new SellingPartnerApi\Api\SellersApi($config);

    $params = $body;
    try {
        $result = $api->getMarketplaceParticipations();
        $params["success"] = true;
    } catch (Exception $e) {
        print_r($e);
    }
```

I'll update the blog post to contain the above code.

**Comment by vladles** [comment]
@jlevers 
Perfect! thank you, but I am already found this code example in issues! 
Thank you for clarifying! 

By the way, I was faced with a new error. Maybe you know. 
When I put only refresh token, your lib did **requestLWAToken**, and in response to this request (update token), I received error.
![image](https://user-images.githubusercontent.com/4676405/142681569-e886288f-45c9-4ab5-a5b9-25274ba22ff6.png)

This may be due to the problem that you described (policy on the IAM 3step) in your article when registering the application?

**Comment by vladles** [comment]
@jlevers
Perfect! thank you, but I am already found this code example in issues!
Thank you for clarifying!

After I faced with this error.
![image](https://user-images.githubusercontent.com/4676405/142682546-25518b68-f258-45a9-ac44-c8604d8928a9.png)

What do you think? This may be due to the problem that you described (policy on the IAM 3step) in your article when registering the application?

**Comment by jlevers** [comment]
Do you have access to the Selling Partner Insights role when you look at your developer profile on Seller Central? If so, do you have that role selected in your SP API application?

**Comment by vladles** [comment]
Sorry, for asking, where I can find it? 
In https://console.aws.amazon.com/iamv2/home#/users ?

**Comment by jlevers** [comment]
Your developer profile is here: https://sellercentral.amazon.com/developer/register

Your application config will be under one of the `Edit` pages here: https://sellercentral.amazon.com/sellingpartner/developerconsole/ref=xx_DevCon_dnav_xx

**Comment by vladles** [comment]
or maybe you mean it? on this page, where we register developer.
https://sellercentral.amazon.de/developer/register
![image](https://user-images.githubusercontent.com/4676405/142683714-05010352-9771-4430-b388-4e539f3d1450.png)

Yes, I have access

**Comment by jlevers** [comment]
Yep, that's what I was referring to.

If you're trying to authorize a seller from the EU, did you change the `endpoint` in the `Configuration` object from `Endpoint::NA` to `Endpoint::EU`?

**Comment by vladles** [comment]
Sure, by the way, should I provide roleArn in request?

**Comment by jlevers** [comment]
Is your SP API application configured with a role ARN or a user ARN? If it's a role ARN, then you need to pass the ARN as a parameter into `Configuration`: `"roleArn" => "<your role ARN>"`

**Comment by vladles** [comment]
Hm,  and the same I should pass in configuration?
![image](https://user-images.githubusercontent.com/4676405/142684730-56baa10a-f9a7-47fb-a473-3ff410fbe878.png)

**Comment by vladles** [comment]
What about this? should I set Yes? 
![image](https://user-images.githubusercontent.com/4676405/142685234-c13d8a7a-35aa-49de-89a4-6e3c5895c75a.png)

**Comment by vladles** [comment]
After set roleArn param, new exception and error:
![image](https://user-images.githubusercontent.com/4676405/142685601-926e1481-b53b-46a3-b2a6-5c7799959cb1.png)

**Comment by vladles** [comment]
So, I resolve the issue, and received a successful response! 
I create an inline policy and remove `roleArn` param from ` Configuration class`. 
In your blog post you were right, 3-5 steps (when we create AWS user) add more problems. 

Thank you @jlevers! 
I think we can close the issue.

**Comment by jlevers** [comment]
Great, glad you got it working.
