### ISSUE TITLE
Amazon blocked my IP Address this morning

### ISSUE THREAD

**Issue by ait1ispring** [jlevers/selling-partner-api#137]
Hi, It looks Amazon.com blocked my IP Address this morning for about 3 hours, is there any way that I can set up the request rate or set up the proxy to avoid my IP address is blocked again?

**Comment by jlevers** [comment]
There's some info about using proxies in #52. I also know that Amazon will sometimes increase your rate limits if you open a support case with them and provide a compelling reason why you need the limits increased.

(Disclaimer: I am not a lawyer, and am not recommending that you do anything that breaks Amazon's SP API ToS, Data Protection Policy, Acceptable Use Policy, or any other rules they have set in place.)
