### ISSUE TITLE
can not get whole shipping_address and buyer_info

### ISSUE THREAD

**Issue by adaipan** [jlevers/selling-partner-api#138]
**when I use getOrders api   I can not get  whole shipping_address and buyer_info**

**Comment by Abbotton** [comment]
You need to update the developer profile before you can apply for PII permissions.

**Comment by jlevers** [comment]
@adaipan, if you don't have access to the restricted roles in your SP API developer profile, you won't be able to retrieve that info. You'll have to go through the approval process for getting access to PII if you need that data.
