### ISSUE TITLE
I try to getOrder but it said "[403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }" 

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#140]
Dear Jlevers thank for great package,
I still have trouble that cannot getOrder

step 1:
I go https://aws.amazon.com to create IAM user and get awsAccessKeyId , awsSecretAccessKey, role Arn
step 2: 
I go  https://vendorcentral.amazon.com/sellingpartner/developerconsole
to create app and add role Arn that I have from step 1 to AIM ARN
step 3:
I get lwaClientId, lwaClientSecret, lwaRefreshToken on the app I have from step 2

step 4:
I get your package
and fill some parameters as bellow

```
protected $config ;
    public function __construct()
    {
        $this->config = new Configuration([
            "lwaClientId" =>  $this->ClientID,
            "lwaClientSecret" => $this->ClientSecret,
            "lwaRefreshToken" => $this->RefreshToken,
            "awsAccessKeyId" => $this->AwsAccessKey,
            "awsSecretAccessKey" => $this->AwsSecretKey,
            "endpoint" =>Endpoint::NA,
            "roleArn" =>$this->RoleArn
        ]);
    }
public function test()
    {
        $apiInstance = new VendorDirectFulfillmentOrdersApi($this->config);
        $purchase_order_number = 'M4n7X68T3'; // 

        try {
        $result = $apiInstance->getOrder($purchase_order_number);
        print_r($result);
        } catch (Exception $e) {
        echo 'Exception when calling VendorDirectFulfillmentOrdersApi->getOrder: ', $e->getMessage(), PHP_EOL;
        }
    }
```

    BUT WHEN I RUN IT. 
    IT RETURN THE ERROR: "[403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }" .

I thinks almost problem come from permission on vendor for my app
but I am not sure so  PLS HELP ME HOW TO FIX IT ?

THANKS

**Comment by jlevers** [comment]
Could you post a screenshot of your enabled roles in the SP API application's configuration?

**Comment by dangquanghai** [comment]
![DetailAppOnVendor](https://user-images.githubusercontent.com/31786668/144093693-ca470131-6ee8-4a1e-a2fe-836926468014.png)

**Comment by dangquanghai** [comment]
Hi jlevers ,
Is this screen?

**Comment by jlevers** [comment]
Yep, that's it -- I'm not that familiar with how the permissions work for Vendors, so I'm not 100% sure about this, but I think that you probably need access to the Direct-to-Consumer Fulfillment SP API role in order to call `getOrders` on the `VendorDirectFulfillmentApi`.  To get that access, you'll have to go back to your developer profile, select that role, and fill in all the PII-related questions that Amazon requires you answer before they grant you access to any PII.

**Comment by dangquanghai** [comment]
Hi jlevers ,
Actually, I call VendorDirectFulfillmentOrdersApi just for testing . I replaced calling VendorDirectFulfillmentOrdersApi  by
calling ![getMarketplaceParticipations](https://user-images.githubusercontent.com/31786668/144157485-b855c428-00a6-4e1a-a67e-03fd8ca6e662.png) likes your instruction

 ```
 public function test()
    {
       $api = new SellersApi($this->config);
        try {
        $result = $api->getMarketplaceParticipations();
        print_r($result);
        } catch (Exception $e) {
        echo 'Exception when calling SellersApi->getMarketplaceParticipations: ',
        $e->getMessage(),
        PHP_EOL;
        }
}
```
The same error happen as the file attached. PLS give me some advice

**Comment by jlevers** [comment]
You don't have access to the Selling Partner Insights role either, so you won't be able to call `getMarketplaceParticipations`.

Try using the [`VendorOrders`](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/VendorOrdersApi.md) and see if that works for you!

**Comment by dangquanghai** [comment]
Dear jlevers,
I try to call VendorOrders 
But there are 03 parameters I am not sure
1. $next_token ? Because it is the first time to call it so I set $next_token =null; 
2. $po_item_state ? I set  $po_item_state ='Confirmed';
3. $purchase_order_state ? I set $purchase_order_state =null;

the error as the file attached

PLS help me correct its
Thanks

All my code is


```
 public function test()
    {
        $apiInstance = new VendorOrdersApi($this->config);
        $limit = 56; // int | The limit to the number of records returned. Default value is 100 records.
      
        $created_after = new \DateTime("2021-11-20T19:20:30+01:00"); 
        $created_after= $created_after->format('Ymd\THis\Z');
        $created_before = new \DateTime("2021-11-20T19:20:30+01:00");
        $created_before = $created_before->format('Ymd\THis\Z');
        $sort_order = 'DESC'; 
        $next_token = null; 
        $include_details = true; 
        $changed_after = new \DateTime("2021-11-20T19:20:30+01:00"); 
        $changed_after= $changed_after->format('Ymd\THis\Z');
        $changed_before = new \DateTime("2021-11-20T19:20:30+01:00");
        $changed_before= $changed_before->format('Ymd\THis\Z');
        $po_item_state = 'Confirmed'; 
        $is_po_changed = true;
        $purchase_order_state = null; 
        $ordering_vendor_code = 'Yes4A'; 

        try {
        $result = $apiInstance->getPurchaseOrders($limit, $created_after, $created_before, $sort_order, $next_token, $include_details, $changed_after, $changed_before, $po_item_state, $is_po_changed, $purchase_order_state, $ordering_vendor_code);
        print_r($result);
        } catch (Exception $e) {
        echo 'Exception when calling VendorOrdersApi->getPurchaseOrders: ', $e->getMessage(), PHP_EOL;
        }
    }
```
![GetOrder](https://user-images.githubusercontent.com/31786668/144186025-bee7a78e-9764-4ad2-a641-82f90028bba8.png)

**Comment by jlevers** [comment]
Give this a try:

```php
$apiInstance = new VendorOrdersApi($this->config);
$limit = 56; // int | The limit to the number of records returned. Default value is 100 records.
$created_after = new \DateTime("2021-11-20T19:20:30+01:00"); 
$created_after = $created_after->format('Ymd\THis\Z');

try {
    $result = $apiInstance->getPurchaseOrders($limit, $created_after);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling VendorOrdersApi->getPurchaseOrders: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by dangquanghai** [comment]
Dear jlevers,
Thanks for your response!
I try 
![image](https://user-images.githubusercontent.com/31786668/144336944-4c401549-98c3-4b62-954f-a0dba1f5e66e.png)

But the error
![image](https://user-images.githubusercontent.com/31786668/144336987-8b7b62b7-8ee5-487c-882e-961d427c23c4.png)

**Comment by jlevers** [comment]
Hmm, that seems like it's probably an SP API problem, not a problem with your code or my library. The only other thing I can recommend is to try changing this line:

```php
$created_after = $created_after->format('Ymd\THis\Z');
```

to this:

```php
$created_after = $created_after->format('Y-m-d\TH:i:s\Z');
```

**Comment by dangquanghai** [comment]
Thank jlevers,
Something better,
but another thing
PLS help me
Thanks


![image](https://user-images.githubusercontent.com/31786668/144340228-a7f2f49b-d949-4410-bb1c-859a2b3b3cbb.png)

**Comment by dangquanghai** [comment]
Dear jlevers,
It seems I passed over Sign in request(your code is great)

My purpose is getting  GET_VENDOR_SALES_DIAGNOSTIC_REPORT report so
I wrote

```
$apiInstance = new ReportsApi($this->config);
 $body = new \SellingPartnerApi\Model\Reports\CreateReportSpecification([
 "report_type" => "GET_VENDOR_SALES_DIAGNOSTIC_REPORT",
        "marketplace_ids" => ["ATVPDKIKX0DER"]
  ]);
      
  $result = $apiInstance->createReport($body);
  $response = json_decode($result, true);
  $reportId = $response['reportId'];
   $status = $response['processing_status'];
   $a = $apiInstance->getReport($reportId);
    dd($a); 

```
we can see Report Document ID as the picture 

![image](https://user-images.githubusercontent.com/31786668/144368696-d4042cb1-5bf3-40c6-b7f0-29f53c34e829.png)

PLASE HELP HOW TO CALL TO DOWNLOAD IT 

THANKS

**Comment by jlevers** [comment]
Check out this part of the README: https://github.com/jlevers/selling-partner-api#downloading-a-report-document

**Comment by dangquanghai** [comment]
Great jlevers
