### ISSUE TITLE
Application does not have access to one or more requested data elements

### ISSUE THREAD

**Issue by SARANGHAJA** [jlevers/selling-partner-api#141]
Dear Sir,

It succeeded in obtaining basic order information using the getOrders API, and the following error occurred when additional "buyerInfo, dippingAddress" information was requested as follows.

__MY CODE__
...
`$data_elements` = array("buyerInfo", "shippingAddress");

try{
&nbsp;&nbsp;&nbsp;&nbsp;$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, `$data_elements`);
&nbsp;...
}catche($e){
&nbsp;...
}

__RESPONSE__
{
&nbsp;&nbsp;"errors": [
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"code": "InvalidInput",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"message": "Application does not have access to one or more requested data elements: [buyerInfo, shippingAddress]",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"details": ""
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;]
}

Need updates like Amazon policies or roles?
I don't know what the problem is.

Thank you.

**Comment by jlevers** [comment]
To request the `buyerInfo` and/or `shippingAddress` data, you need to have access to at least one of the restricted SP API roles that allows you to retrieve PII. It looks like you don't have access to any of those roles, which is why you're unable to retrieve that data.

**Comment by SARANGHAJA** [comment]
"Restricted" items are not checked in "Developer Profile".
Should I check the items and update the profile?

Thank you.

------------------------------------------------

![cp](https://user-images.githubusercontent.com/94588653/143965499-c8635d5c-8747-4469-8724-ed3c7f9a36d8.PNG)

**Comment by jlevers** [comment]
Yep, that's correct. I recommend only checking the ones you actually need, because they're fairly strict about giving out PII access.

**Comment by SARANGHAJA** [comment]
Thank you~~~~~~~~
