### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by iteahmad** [jlevers/selling-partner-api#142]
Hi,
After registering my application in the vendor central (including checking the PII roles).

I am receiving 403 error :
````
Exception when calling: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] } 
````
when calling : 
````
$api = new Api\VendorOrdersApi($config);
try {
    $result = $api->getPurchaseOrder($orderNumber);
} catch (Exception $e) {
    echo 'Exception when calling: ', $e->getMessage(), PHP_EOL;
}
````

I authorized my application following Amazon documentation.
Any Help would be appreciated

**Comment by jlevers** [comment]
Could you please post a screenshot of your SP API application config from Seller Central?

**Comment by iteahmad** [comment]
Thanks, the problem was setting and authorizing the application using the user-arn instead of the rule-arn.
