### ISSUE TITLE
 syntax error, unexpected ')' in ...jlevers/selling-partner-api/lib/Authentication.php on line 270

### ISSUE THREAD

**Issue by moiloal** [jlevers/selling-partner-api#143]
Hello, I have a problem. When I make a basic call ( copy & paste the code of getMarketplaceParticipations sample ) it appears  syntax error, unexpected ')' in Authentication.php on line 270.

I use correct configuration in the code as lwaClientId, lwaClientSecret, lwaRefreshToken, awsAccessKeyId, awsSecretAccessKey and endpoint (Endpoint::EU) but not works.

Please I need help. Thanks.

**Comment by jlevers** [comment]
Could you please share your full code?

**Comment by moiloal** [comment]
Hi, thanks for your answer.

Full code is ( copy and paste from samples is Github ):

<?php
error_reporting(E_ALL); 
ini_set('display_errors', '1');

require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

// Next configuration fields I hide full info with "xxxxx", but I copy & paste all info from my app in Seller Central and from AWS Amazon

$config = new Configuration([
    "lwaClientId" => "amzn1.application-oa2-client.xxxxxxx",
    "lwaClientSecret" => "d3a790ce3bxxxxx",
    "lwaRefreshToken" => "Atzr|IwEBIKpd3XnbACOjKUwcGhlR_xxxxxxxxx",
    "awsAccessKeyId" => "AKIATA72SQExxxxxxxx",
    "awsSecretAccessKey" => "cLjPCExxxxxxx",
    "endpoint" => Endpoint::EU
]);

$api = new Api\SellersApi($config);
try {
    $result = $api->getMarketplaceParticipations();
    $headers = $result->getHeaders();
    print_r($headers);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}
?>

Result of execute last code is:

Parse error: syntax error, unexpected ')' in xxxxxxx/vendor/jlevers/selling-partner-api/lib/Authentication.php on line 270

Thank you very much!.

**Comment by jlevers** [comment]
What version of PHP are you using? If it's `<7.3`, I think that's probably the issue. This library only supports PHP 7.3 and above.

**Comment by moiloal** [comment]
Thanks, it's solved. My PHP version was 7.2.x and for this reason I had this error. Sorry for the inconvenience, I didn't read about PHP version.

Thank you very much for your help.
