### ISSUE TITLE
listFinancialEvents - doesn't accept datetime object, needs string

### ISSUE THREAD

**Issue by steverobison** [jlevers/selling-partner-api#146]
No big deal but I noticed that the example docs aren't correct.  Need to pass a string date instead of the datetime object.

So this 
$result = $financesAPI->listFinancialEvents($max_results_per_page, '2021-12-01', '2021-12-03');

instead of
        $posted_after = new \DateTime("2013-10-20T19:20:30+01:00"); // \DateTime | A date used for selecting financial events posted after (or at) a specified time. The date-time must be no later than two minutes before the request was submitted, in ISO 8601 date time format.
        $posted_before = new \DateTime("2013-10-20T19:20:30+01:00"); // \DateTime | A date used for selecting financial events posted before (but not at) a specified time. The date-time must be later than PostedAfter and no later than two minutes before the request was submitted, in ISO 8601 date time format. If PostedAfter and PostedBefore are more than 180 days apart, no financial events are returned. You must specify the PostedAfter parameter if you specify the PostedBefore parameter. Default: Now minus two minutes.

$result = $financesAPI->listFinancialEvents($max_results_per_page, $posted_after, $posted_before);

**Comment by jlevers** [comment]
Thanks for the heads up. I'll fix this.

The docs are far from perfect, because they're autogenerated and I haven't had a chance to go through and improve them...feel free to let me know if you find any other discrepancies.

**Comment by jlevers** [comment]
This is (sorta) fixed -- fixing it 100% properly was going to take a lot more effort than it was worth, but it's now clear in the docs that the value should be a string.

**Comment by steverobison** [comment]
Cool.  I figured it was something like that.  No worries.  Thanks again for your work through this extension.  I'm slowly going through everything as I upgrade our system from MWS.

**Comment by jlevers** [comment]
Of course -- thank you so much for your sponsorship, I really appreciate it!

**Comment by steverobison** [comment]
No problem.  Happy to help.  If you ever need help testing or whatever with this app, let me know.
