### ISSUE TITLE
GetShipmentLabels  in  VendorShipment API does not exist

### ISSUE THREAD

**Issue by iteahmad** [jlevers/selling-partner-api#147]
Hi,

While working with this awesome package, I need to request the following endpoint : `/vendor/shipping/v1/transportLabels`, but I am unable to find a corresponding method for this endpoint.

Best Regards

**Comment by jlevers** [comment]
Hi @iteahmad,

That endpoint isn't documented by Amazon [in their own docs](https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-shipments-api/vendorShipments.md), either -- where did you find that endpoint URL?

**Comment by iteahmad** [comment]
It is documented in the documentation file downloaded from the vendor central.

**Comment by jlevers** [comment]
In that case, I recommend you open a case either in the [main SP API documentation repository](https://github.com/amzn/selling-partner-api-docs/) or create a case on Seller Central. Since they don't mention the endpoint in their SP API documentation, I'm unable to support it.
