### ISSUE TITLE
Question regards to Order API issue

### ISSUE THREAD

**Issue by dhdhxk** [jlevers/selling-partner-api#148]
Hi, I just cloned the repo and looking into this at a moment and I keep getting errors for OrderAPI.

'Exception when calling OrdersApi->getOrders: [400]'

Do you know why I get this error? I've attached the code I've added. (Just made empty for the credentials)

`<?php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
    "lwaClientId" => "",
    "lwaClientSecret" => "",
    "lwaRefreshToken" => "",
    "awsAccessKeyId" => "",
    "awsSecretAccessKey" => "",
    "endpoint" => Endpoint::NA,  // or another endpoint from lib/Endpoint.php
    "roleArn" => ""
]);
$config->setDebug(true);
// To redirect debug info to a file:
$config->setDebugFile('./debug.log');

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER');
$created_after = null;
$created_before = null;
$last_updated_after = null;
$last_updated_before = null;
$order_statuses = array(null);
$fulfillment_channels = array(null);
$payment_methods = array(null);
$buyer_email = null;
$seller_order_id = null;
$max_results_per_page = 56;
$easy_ship_shipment_statuses = array(null);
$next_token = null;
$amazon_order_ids = array(null);
$actual_fulfillment_supply_source_id = null;
$store_chain_store_id = null;
$data_elements = array('shippingAddress');

try {
    $result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements);
    print_r($result);
} catch (Exception $e) {
    echo "<pre>";
    var_dump($e);
    echo "</pre>";
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}`

When I check the exception, it shows

When I dump the exception, I got this

`  ["trace":"Exception":private]=>
  array(7) {
    [0]=>
    array(6) {
      ["file"]=>
      string(83) "C:\xampp\htdocs\spapi_test\vendor\jlevers\selling-partner-api\lib\Api\TokensApi.php"
      ["line"]=>
      int(125)
      ["function"]=>
      string(37) "createRestrictedDataTokenWithHttpInfo"
      ["class"]=>
      string(31) "SellingPartnerApi\Api\TokensApi"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(SellingPartnerApi\Model\Tokens\CreateRestrictedDataTokenRequest)#90 (1) {
          ["container":protected]=>
          array(2) {
            ["target_application"]=>
            NULL
            ["restricted_resources"]=>
            array(1) {
              [0]=>
              object(SellingPartnerApi\Model\Tokens\RestrictedResource)#89 (1) {
                ["container":protected]=>
                array(3) {
                  ["method"]=>
                  string(3) "GET"
                  ["path"]=>
                  string(17) "/orders/v0/orders"
                  ["data_elements"]=>
                  array(1) {
                    [0]=>
                    string(15) "shippingAddress"
                  }
                }
              }
            }
          }
        }
      }
    }
    [1]=>
    array(6) {
      ["file"]=>
      string(84) "C:\xampp\htdocs\spapi_test\vendor\jlevers\selling-partner-api\lib\Authentication.php"
      ["line"]=>
      int(326)
      ["function"]=>
      string(25) "createRestrictedDataToken"
      ["class"]=>
      string(31) "SellingPartnerApi\Api\TokensApi"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        object(SellingPartnerApi\Model\Tokens\CreateRestrictedDataTokenRequest)#90 (1) {
          ["container":protected]=>
          array(2) {
            ["target_application"]=>
            NULL
            ["restricted_resources"]=>
            array(1) {
              [0]=>
              object(SellingPartnerApi\Model\Tokens\RestrictedResource)#89 (1) {
                ["container":protected]=>
                array(3) {
                  ["method"]=>
                  string(3) "GET"
                  ["path"]=>
                  string(17) "/orders/v0/orders"
                  ["data_elements"]=>
                  array(1) {
                    [0]=>
                    string(15) "shippingAddress"
                  }
                }
              }
            }
          }
        }
      }
    }
    [2]=>
    array(6) {
      ["file"]=>
      string(84) "C:\xampp\htdocs\spapi_test\vendor\jlevers\selling-partner-api\lib\Authentication.php"
      ["line"]=>
      int(175)
      ["function"]=>
      string(22) "getRestrictedDataToken"
      ["class"]=>
      string(32) "SellingPartnerApi\Authentication"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(4) {
        [0]=>
        string(17) "/orders/v0/orders"
        [1]=>
        string(3) "GET"
        [2]=>
        bool(true)
        [3]=>
        array(1) {
          [0]=>
          string(15) "shippingAddress"
        }
      }
    }
    [3]=>
    array(6) {
      ["file"]=>
      string(83) "C:\xampp\htdocs\spapi_test\vendor\jlevers\selling-partner-api\lib\Configuration.php"
      ["line"]=>
      int(396)
      ["function"]=>
      string(11) "signRequest"
      ["class"]=>
      string(32) "SellingPartnerApi\Authentication"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(4) {
        [0]=>
        object(GuzzleHttp\Psr7\Request)#50 (7) {
          ["method":"GuzzleHttp\Psr7\Request":private]=>
          string(3) "GET"
          ["requestTarget":"GuzzleHttp\Psr7\Request":private]=>
          NULL
          ["uri":"GuzzleHttp\Psr7\Request":private]=>
          object(GuzzleHttp\Psr7\Uri)#49 (8) {
            ["scheme":"GuzzleHttp\Psr7\Uri":private]=>
            string(5) "https"
            ["userInfo":"GuzzleHttp\Psr7\Uri":private]=>
            string(0) ""
            ["host":"GuzzleHttp\Psr7\Uri":private]=>
            string(31) "sellingpartnerapi-na.amazon.com"
            ["port":"GuzzleHttp\Psr7\Uri":private]=>
            NULL
            ["path":"GuzzleHttp\Psr7\Uri":private]=>
            string(17) "/orders/v0/orders"
            ["query":"GuzzleHttp\Psr7\Uri":private]=>
            string(152) "OrderStatuses=&MarketplaceIds=ATVPDKIKX0DER&FulfillmentChannels=&PaymentMethods=&MaxResultsPerPage=56&EasyShipShipmentStatuses=&AmazonOrderIds=&IsISPU=1"
            ["fragment":"GuzzleHttp\Psr7\Uri":private]=>
            string(0) ""
            ["composedComponents":"GuzzleHttp\Psr7\Uri":private]=>
            NULL
          }
          ["headers":"GuzzleHttp\Psr7\Request":private]=>
          array(4) {
            ["Host"]=>
            array(1) {
              [0]=>
              string(31) "sellingpartnerapi-na.amazon.com"
            }
            ["User-Agent"]=>
            array(1) {
              [0]=>
              string(48) "jlevers/selling-partner-api/4.2.2 (Language=PHP)"
            }
            ["Accept"]=>
            array(1) {
              [0]=>
              string(16) "application/json"
            }
            ["Content-Type"]=>
            array(1) {
              [0]=>
              string(16) "application/json"
            }
          }
          ["headerNames":"GuzzleHttp\Psr7\Request":private]=>
          array(4) {
            ["user-agent"]=>
            string(10) "User-Agent"
            ["accept"]=>
            string(6) "Accept"
            ["content-type"]=>
            string(12) "Content-Type"
            ["host"]=>
            string(4) "Host"
          }
          ["protocol":"GuzzleHttp\Psr7\Request":private]=>
          string(3) "1.1"
          ["stream":"GuzzleHttp\Psr7\Request":private]=>
          NULL
        }
        [1]=>
        NULL
        [2]=>
        string(17) "/orders/v0/orders"
        [3]=>
        string(9) "getOrders"
      }
    }
    [4]=>
    array(6) {
      ["file"]=>
      string(83) "C:\xampp\htdocs\spapi_test\vendor\jlevers\selling-partner-api\lib\Api\OrdersApi.php"
      ["line"]=>
      int(2066)
      ["function"]=>
      string(11) "signRequest"
      ["class"]=>
      string(31) "SellingPartnerApi\Configuration"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(4) {
        [0]=>
        object(GuzzleHttp\Psr7\Request)#47 (7) {
          ["method":"GuzzleHttp\Psr7\Request":private]=>
          string(3) "GET"
          ["requestTarget":"GuzzleHttp\Psr7\Request":private]=>
          NULL
          ["uri":"GuzzleHttp\Psr7\Request":private]=>
          object(GuzzleHttp\Psr7\Uri)#48 (8) {
            ["scheme":"GuzzleHttp\Psr7\Uri":private]=>
            string(5) "https"
            ["userInfo":"GuzzleHttp\Psr7\Uri":private]=>
            string(0) ""
            ["host":"GuzzleHttp\Psr7\Uri":private]=>
            string(31) "sellingpartnerapi-na.amazon.com"
            ["port":"GuzzleHttp\Psr7\Uri":private]=>
            NULL
            ["path":"GuzzleHttp\Psr7\Uri":private]=>
            string(17) "/orders/v0/orders"
            ["query":"GuzzleHttp\Psr7\Uri":private]=>
            string(181) "OrderStatuses=&MarketplaceIds=ATVPDKIKX0DER&FulfillmentChannels=&PaymentMethods=&MaxResultsPerPage=56&EasyShipShipmentStatuses=&AmazonOrderIds=&IsISPU=1&dataElements=shippingAddress"
            ["fragment":"GuzzleHttp\Psr7\Uri":private]=>
            string(0) ""
            ["composedComponents":"GuzzleHttp\Psr7\Uri":private]=>
            NULL
          }
          ["headers":"GuzzleHttp\Psr7\Request":private]=>
          array(4) {
            ["User-Agent"]=>
            array(1) {
              [0]=>
              string(48) "jlevers/selling-partner-api/4.2.2 (Language=PHP)"
            }
            ["Accept"]=>
            array(1) {
              [0]=>
              string(16) "application/json"
            }
            ["Content-Type"]=>
            array(1) {
              [0]=>
              string(16) "application/json"
            }
            ["Host"]=>
            array(1) {
              [0]=>
              string(31) "sellingpartnerapi-na.amazon.com"
            }
          }
          ["headerNames":"GuzzleHttp\Psr7\Request":private]=>
          array(4) {
            ["user-agent"]=>
            string(10) "User-Agent"
            ["accept"]=>
            string(6) "Accept"
            ["content-type"]=>
            string(12) "Content-Type"
            ["host"]=>
            string(4) "Host"
          }
          ["protocol":"GuzzleHttp\Psr7\Request":private]=>
          string(3) "1.1"
          ["stream":"GuzzleHttp\Psr7\Request":private]=>
          NULL
        }
        [1]=>
        NULL
        [2]=>
        string(17) "/orders/v0/orders"
        [3]=>
        string(9) "getOrders"
      }
    }
    [5]=>
    array(6) {
      ["file"]=>
      string(83) "C:\xampp\htdocs\spapi_test\vendor\jlevers\selling-partner-api\lib\Api\OrdersApi.php"
      ["line"]=>
      int(2029)
      ["function"]=>
      string(21) "getOrdersWithHttpInfo"
      ["class"]=>
      string(31) "SellingPartnerApi\Api\OrdersApi"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(18) {
        [0]=>
        array(1) {
          [0]=>
          string(13) "ATVPDKIKX0DER"
        }
        [1]=>
        NULL
        [2]=>
        NULL
        [3]=>
        NULL
        [4]=>
        NULL
        [5]=>
        array(1) {
          [0]=>
          NULL
        }
        [6]=>
        array(1) {
          [0]=>
          NULL
        }
        [7]=>
        array(1) {
          [0]=>
          NULL
        }
        [8]=>
        NULL
        [9]=>
        NULL
        [10]=>
        int(56)
        [11]=>
        array(1) {
          [0]=>
          NULL
        }
        [12]=>
        NULL
        [13]=>
        array(1) {
          [0]=>
          NULL
        }
        [14]=>
        NULL
        [15]=>
        bool(true)
        [16]=>
        NULL
        [17]=>
        array(1) {
          [0]=>
          string(15) "shippingAddress"
        }
      }
    }
    [6]=>
    array(6) {
      ["file"]=>
      string(36) "C:\xampp\htdocs\spapi_test\index.php"
      ["line"]=>
      int(60)
      ["function"]=>
      string(9) "getOrders"
      ["class"]=>
      string(31) "SellingPartnerApi\Api\OrdersApi"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(18) {
        [0]=>
        array(1) {
          [0]=>
          string(13) "ATVPDKIKX0DER"
        }
        [1]=>
        NULL
        [2]=>
        NULL
        [3]=>
        NULL
        [4]=>
        NULL
        [5]=>
        array(1) {
          [0]=>
          NULL
        }
        [6]=>
        array(1) {
          [0]=>
          NULL
        }
        [7]=>
        array(1) {
          [0]=>
          NULL
        }
        [8]=>
        NULL
        [9]=>
        NULL
        [10]=>
        int(56)
        [11]=>
        array(1) {
          [0]=>
          NULL
        }
        [12]=>
        NULL
        [13]=>
        array(1) {
          [0]=>
          NULL
        }
        [14]=>
        NULL
        [15]=>
        bool(true)
        [16]=>
        NULL
        [17]=>
        array(1) {
          [0]=>
          string(15) "shippingAddress"
        }
      }
    }
  }`

Any clue for this?

Thanks a lot!!

**Comment by dhdhxk** [comment]
FYI, $result = $api->getMarketplaceParticipations(); worked to me and I was able to get the list of marketplaces.

I guess some settings have issues or the API credential does not have permission to access Order API.

Thank you.

**Comment by jlevers** [comment]
A couple problems:
* either `$created_after` or `$last_updated_after` must be passed
* `$data_elements` isn't a required parameter -- you only need to pass it if you're trying to access restricted data. I'm guessing that if you don't pass `['shippingAddress']` for `$data_elements`, you'll be able to call `getOrders` successfully. More info on that here: https://github.com/jlevers/selling-partner-api/blob/main/README.md#restricted-operations

Try this code:

```php
<?php
require_once(DIR . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
    "lwaClientId" => "",
    "lwaClientSecret" => "",
    "lwaRefreshToken" => "",
    "awsAccessKeyId" => "",
    "awsSecretAccessKey" => "",
    "endpoint" => Endpoint::NA, // or another endpoint from lib/Endpoint.php
    "roleArn" => ""
]);
$config->setDebug(true);
// To redirect debug info to a file:
$config->setDebugFile('./debug.log');

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER');
$created_after = null;
$created_before = null;
$last_updated_after = null;
$last_updated_before = null;
$order_statuses = array(null);
$fulfillment_channels = array(null);
$payment_methods = array(null);
$buyer_email = null;
$seller_order_id = null;
$max_results_per_page = 56;

try {
    $result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses, $fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page);
    print_r($result);
} catch (Exception $e) {
    var_dump($e);
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by dhdhxk** [comment]
Thank you for the update.

After I update created_after and fulfillment_channels, I get the 400 error again.

Exception when calling OrdersApi->getOrders: [400]

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER');
$created_after = "2021-12-01T00:00:00Z";
$created_before = null;
$last_updated_after = null;
$last_updated_before = null;
$order_statuses = array(null);
$fulfillment_channels = array("FBA");
$payment_methods = array(null);
$buyer_email = null;
$seller_order_id = null;
$max_results_per_page = 65;
$easy_ship_shipment_statuses = array(null);
$amazon_order_ids = array(null);
$actual_fulfillment_supply_source_id = null;
$is_ispu = True;
$store_chain_store_id = null;
$data_elements = null;

Is there a way to check why I got 400 error?

Thank you.

**Comment by jlevers** [comment]
Please try making the request without passing any parameters that you don't explicitly want to set (see example below). Also, I'm pretty sure that Amazon requires that the timestamps passed to `getOrders` be in format `Y-m-d\TH:i:s`, so your `$created_after` should be `2021-12-01T00:00:00` instead of `2021-12-01T00:00:00Z`.

```php
<?php
require_once(DIR . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
    "lwaClientId" => "",
    "lwaClientSecret" => "",
    "lwaRefreshToken" => "",
    "awsAccessKeyId" => "",
    "awsSecretAccessKey" => "",
    "endpoint" => Endpoint::NA, // or another endpoint from lib/Endpoint.php
    "roleArn" => ""
]);
$config->setDebug(true);
// To redirect debug info to a file:
$config->setDebugFile('./debug.log');

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = ['ATVPDKIKX0DER'];
$created_after = '2021-12-01T00:00:00';
$fulfillment_channels = ['AFN'];
$max_results_per_page = 56;

try {
    $result = $apiInstance->getOrders($marketplace_ids, $created_after, null, null, null, null, $fulfillment_channels, null, null, null, $max_results_per_page);
    print_r($result);
} catch (Exception $e) {
    var_dump($e);
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by dhdhxk** [comment]
Thank you so much! It works now!
