### ISSUE TITLE
getReports returns rawurlencode() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#15]
getReports() method returns rawurlencode() expects parameter 1 to be string, object given.

**Comment by jlevers** [comment]
Did you resolve the issue? If so, what was the solution? Just asking in hopes of documenting what you found for other people who run into the same problem.

**Comment by Nilanth** [comment]
To resolve it I just passed only report_types and marketplace_ids. Got the error if I pass other params
