### ISSUE TITLE
How to get buyer sudo email ? ( Question )

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#150]
In which API do we get buyer Sudo email without RDT token? Can anyone help with this? 
I have raised this question in [SP API discussion](https://github.com/amzn/selling-partner-api-docs/discussions/1785) also but didn't get any updates so far.

**Comment by jlevers** [comment]
Not sure what you mean by sudo email?

**Comment by Nilanth** [comment]
> Not sure what you mean by sudo email?

Masked buyer email something like below

**xydsgshsshsg@marketplace.amazon.com**

**Comment by jlevers** [comment]
I don't think there's any way to get that without an RDT and access to PII.

**Comment by cpiggott** [comment]
Correct me if I'm wrong here @jlevers .

@Nilanth This should be possible via the getOrderBuyerInfo API call in the OrdersAPI: getOrderBuyerInfo](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/OrdersApi.md#getOrderBuyerInfo)

```
<?php
require_once(__DIR__ . '/vendor/autoload.php');

// See README for more information on the Configuration object's options
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "<LWA client ID>",
    "lwaClientSecret" => "<LWA client secret>",
    "lwaRefreshToken" => "<LWA refresh token>",
    "awsAccessKeyId" => "<AWS access key ID>",
    "awsSecretAccessKey" => "<AWS secret access key>",
    "endpoint" => SellingPartnerApi\Endpoint::NA  // or another endpoint from lib/Endpoints.php
]);

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$order_id = 'order_id_example'; // string | An orderId is an Amazon-defined order identifier, in 3-7-7 format.

try {
    $result = $apiInstance->getOrderBuyerInfo($order_id);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrderBuyerInfo: ', $e->getMessage(), PHP_EOL;
}
```

The `$result` should contain these details if you look through the response.

**Comment by Nilanth** [comment]
@cpiggott Thanks for the reply. 
I too checked this API, Seems it is scheduled for **deprecation on January 12, 2022**

<img width="984" alt="Screenshot 2021-12-14 at 10 41 56 AM" src="https://user-images.githubusercontent.com/28811774/145937063-fb9115ce-44ba-412e-a790-7e6f8002467d.png">

**Comment by cpiggott** [comment]
@Nilanth You may want to reference this Guide on the SP-API official documentation. After looking through issues on the SP-API GitHub, this is considered PII which means that it must be requested with a special token and is not available to public app developers.

I tried the `getOrders()` API call and it does return the Object the would contain this information: https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/Orders/BuyerInfo.md

But I do not have the token or approval(Sounds like it's a long approval time) to get this data from the API at the moment.

[https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#authorization-with-the-restricted-data-token](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#authorization-with-the-restricted-data-token)

**Comment by jlevers** [comment]
@Nilanth I'm going to close this, because I think that the question has been answered -- you can't retrieve that data without PII access. Please feel free to reopen it if you feel there's more discussion to be had.
