### ISSUE TITLE
ApiException::getResponseBody() return "" (empty string)

### ISSUE THREAD

**Issue by gnahz** [jlevers/selling-partner-api#156]
In PSR-7 the body is a stream object which needs to be rewinded every time you want to read it. The body stream pointer is already eof after "$this->writeDebug($e->getResponse()->getBody()->getContents());". So that the responseBody attribute in ApiException object is empty string.
Solution: 
Use explicit casting to get content of body
Modify "$e->getResponse() ? (string) $e->getResponse()->getBody()->getContents() : null" to 
$e->getResponse() ? (string) $e->getResponse()->getBody() : null

**Comment by jlevers** [comment]
Thanks for reporting this, that's a pretty big issue. It should be fixed in `v4.2.3`. Let me know if you have any further issues with it!
