### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function SellingPartnerApi\Configuration()

### ISSUE THREAD

**Issue by suofiya** [jlevers/selling-partner-api#157]
4.2.3 error after composer this library
`composer require jlevers/selling-partner-api`

**Comment by jlevers** [comment]
Hey @suofiya, I'm going to need more details to address the problem you're running into. Is the error with your code or from a `composer` command? What's the error?

**Comment by suofiya** [comment]
> Hey @suofiya, I'm going to need more details to address the problem you're running into. Is the error with your code or from a `composer` command? What's the error?

An error occurred while executing the test.php after installed selling-partner-api by composer command.
`
Stack trace:
#0 {main}
  thrown in /var/www/webroot/amazon_spapi_app/test.php on line 9
[16-Dec-2021 14:19:51 PRC] PHP Fatal error:  Uncaught Error: Call to undefined function SellingPartnerApi\Configuration() in /var/www/webroot/amazon_spapi_app/test.php:9
`

**Comment by jlevers** [comment]
Could you please provide your code?

**Comment by suofiya** [comment]
`<?php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
    "lwaClientId" => "amzn1.application-oa2-client.....",
    "lwaClientSecret" => "abcd....",
    "lwaRefreshToken" => "Aztr|IwEBI....",
    "awsAccessKeyId" => "AKIA....",
    "awsSecretAccessKey" => "ABCD....",
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "endpoint" => Endpoint::NA
]);

$api = new Api\SellersApi($config);
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}

?>`

**Comment by jlevers** [comment]
Hmm, I wasn't able to reproduce the issue after following these steps:
* Creating a new Composer project in an empty directory with `composer init`
* Installing this library with `composer require jlevers/selling-partner-api`
* Creating a file named `test.php` and pasting your code in

It ran fine for me. Based on the error you're getting, I would think that you had forgotten the `new` keyword before `Configuration` when you're initializing the `Configuration` object, but that isn't missing in the above code. Are you definitely executing this file from the same folder where your `vendor` directory is?

**Comment by suofiya** [comment]
> Hmm, I wasn't able to reproduce the issue after following these steps:
> 
> * Creating a new Composer project in an empty directory with `composer init`
> * Installing this library with `composer require jlevers/selling-partner-api`
> * Creating a file named `test.php` and pasting your code in
> 
> It ran fine for me. Based on the error you're getting, I would think that you had forgotten the `new` keyword before `Configuration` when you're initializing the `Configuration` object, but that isn't missing in the above code. Are you definitely executing this file from the same folder where your `vendor` directory is?

This issue has been resolved. Thanks you very much!
