### ISSUE TITLE
Push Fulfillment data of an order in Amazon

### ISSUE THREAD

**Issue by moiloal** [jlevers/selling-partner-api#159]
Hi everybody,

Please can you help me about how to upload shipping information of an order?. I mean about carrier name, shipping method, tracking number, items shipped... 

I remember I did it with MWS API and I created a feed in XML with information about all shipping information and submit this feed by API and it works in MWS but I don't know how do this with SP API and this library.

Thank you very much!.

**Comment by jlevers** [comment]
HI @moiloal,

Order feeds work basically exactly the same as they did with MWS. There's a list of report types [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md). Once you know which feed type you're using, this section of the README details how to do it with this library: https://github.com/jlevers/selling-partner-api/blob/main/README.md#uploading-a-feed-document

**Comment by jlevers** [comment]
Hi @moiloal, since I haven't heard from you, I'm going to assume you resolved your problem and close this issue. Please feel free to reopen it if you need more help.
