### ISSUE TITLE
Syntax error on SellersApi.php line 475 (PHP 7.2)

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#16]
In SellersApi.php, at line 472 you have this function call:
```
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'payload'],
                [],
            );
```
The comma after the empty array is producing a syntax error.
While it works with PHP 7.3, the Readme file says the library works with PHP 7.2

**Comment by jlevers** [comment]
Thanks for pointing this out -- should be fixed in the latest release (v2.0.8).
