### ISSUE TITLE
403 Access to requested resource is denied, code": "Unauthorized"

### ISSUE THREAD

**Issue by haruny** [jlevers/selling-partner-api#160]
Hello,
I followed your blog post and all other documentation but can't figure out why I'm getting a 403 from sp-api.

my code:

```
$config = new Configuration([
    "lwaClientId" => "amzn1.application-oa2-client.******",
    "lwaClientSecret" => "b******",
    "lwaRefreshToken" => "Atzr|**********",
    "awsAccessKeyId" => "AKIA*********",
    "awsSecretAccessKey" => "***************",
    "endpoint" => Endpoint::NA,
]);

$api = new \SellingPartnerApi\Api\SellersApi($config);
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (\Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}
```

I have the user in AWS IAM user with permissions inline and the user as well in the group that it is assigned to.

with 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}
```

My dev account in Amazon Seller Central is approved.
I see the Authoriz Application with the correct app id and marketplaces.
Any suggestions?

**Comment by haruny** [comment]
nevermind. I just needed to wait.

**Comment by mujaffars** [comment]
@haruny How did you resolve the issue? I am also facing the same issue. Can you please help?

**Comment by soseki-angfa** [comment]
@haruny 
How long did you wait?
1 day? 2 days?
