### ISSUE TITLE
Pls Add GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#161]
Dear jlevers,
Pls add the report GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT. 
I saw it at : https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#vendor-retail-analytics-reports

Can we get  Geographic Sales Insights Report on Vendor ?

![image](https://user-images.githubusercontent.com/31786668/147060951-b6f40484-9b27-46fb-b39f-844f2421dafb.png)

thank  jlevers

**Comment by jlevers** [comment]
`GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT` is added in `v4.2.4`.

If the geographic sales insights report doesn't appear in the list of report types in the main documentation repo, I don't believe there's any way to fetch it with the SP API.
