### ISSUE TITLE
Support for GET_PROMOTION_PERFORMANCE_REPORT Report Type

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#162]
Add support for Promotions Performance Report in report type

ENUM - **GET_PROMOTION_PERFORMANCE_REPORT**

https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#performance-reports

**Comment by jlevers** [comment]
Should be fixed in `v4.2.4`.

**Comment by Balinvest** [comment]
@jlevers  Trying to get that report returns: _{"reportRequestError":"Please provide report options promotionStartDateFrom and promotionStartDateTo in the standard ISO-8601 zoned date and time format. For example: \"2011-12-03T10:15:30Z\"."}_

How can I provide those parameters?

**Comment by deadmouse** [comment]
@jlevers  Trying to get that report returns: _{"reportRequestError":"Please provide report options promotionStartDateFrom and promotionStartDateTo in the standard ISO-8601 zoned date and time format. For example: \"2011-12-03T10:15:30Z\"."}_

How can I provide those parameters?

**Comment by jlevers** [comment]
You can pass those options in via the `report_options` field on the [CreateReportSpecification object](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/Reports/CreateReportSpecification.md#createreportspecification). I've never actually needed to use those options before, but I think it'll just be something like:

```php
//....
$spec = new CreateReportSpecification([
    'report_options' => [
        'promotionStartDateFrom' => '2011-12-03T10:15:30Z',
        'promotionStartDateTo' => '2021-12-03T10:15:30Z',
    ],
    // ....
)];
