### ISSUE TITLE
InternalFailure when trying to CreateReport

### ISSUE THREAD

**Issue by CLCWebsiteServices** [jlevers/selling-partner-api#164]
I'm trying to create a report via the library, however when sending the request, I'm getting the following error:
```json
{
    "code": "InternalFailure",
    "message": "We encountered an internal error. Please try again.",
    "details": ""
}
```
The request I'm sending is structured like so:
```json
{
    "reportType": [
        "GET_VAT_TRANSACTION_DATA"
    ],
    "dataStartTime": "2021-07-23",
    "dataEndTime": "2021-09-23",
    "marketplaceIds": [
        "A1PA6795UKMFR9",
        "A1RKKUPIHCS9HS",
        "A13V1IB3VIYZZH",
        "APJ6JRA9NG5V4",
        "A1805IZSGTT6HS",
        "A1F83G8C2ARO7P"
    ]
}
```

And the PHP version of what I'm trying to send looks like this:
```php
$awsApi = new ReportsApi($this->config);

$body = new CreateReportSpecification();
$body->setReportType($report_type);
$body->setDataStartTime($start_date);
$body->setDataEndTime($end_date);
$body->setMarketplaceIds($marketplace_ids);

try {
    return $awsApi->createReport($body);
} catch (Exception $exception) {
    dd($exception->getMessage());
}
```

**Comment by thugic** [comment]
`InternalFailure` means it's an issue on Amazon's end. They do have some issues with the API from time to time, so make sure to add some retry/backoff logic in your code. It's not an issue with this library.

**Comment by jlevers** [comment]
In this particular case, I think the problem might be that the start/end datetimes have to be formatted like this: `2021-07-23T00:00:00Z'

Give that change a try -- if it solves your problem, great. If not, I'd create a support case with Amazon -- this isn't a problem related to this problem as far as I can tell.
