### ISSUE TITLE
What is the best way to update item on Seller account?

### ISSUE THREAD

**Issue by pramodwagh** [jlevers/selling-partner-api#166]
Hello @jlevers,
Can you please tell what is the best way to to update product info like price and quantity on seller account. also if you share example related this would be helpfull. 
Thank you

**Comment by jlevers** [comment]
You can update product prices and quantities via the `POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA` feed type. That feed type is documented [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md#listings-feeds). There's an example of how to upload a feed document in the README, [here](https://github.com/jlevers/selling-partner-api/blob/main/README.md#uploading-a-feed-document), and Amazon has a [use case guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/feeds-api-use-case-guide/feeds-api-use-case-guide_2021-06-30.md) for the Feeds API more generally.
