### ISSUE TITLE
Vendor Products List

### ISSUE THREAD

**Issue by jowylim** [jlevers/selling-partner-api#167]
Dear jlevers,
Really like your library it helps me a lot!! Appreciate it.
May I know is there any way that I can get all the products list under vendor account?

**Comment by jlevers** [comment]
Have you tried any of the [inventory reports](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#inventory-reports)? I haven't tried using those reports for vendors specifically, but I think they should wokr.

**Comment by jlevers** [comment]
@jowylim since I haven't heard from you, I'm going to close this issue, but feel free to reopen it if you need more help.
