### ISSUE TITLE
How to get restricted Report ?

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#169]
Dear jlevers,
I use your library to get report on seller , It work well but when I get restricted report it said forbidden
I think the problem comes from my app client so I update my app client  as the picture attached
![image](https://user-images.githubusercontent.com/31786668/147800093-2bc2628f-eaa7-4ece-9ec0-a6c9d84dead1.png)
then I try to get restricted report again, the forbidden still there
I know  this issue does not come from your library
PLS help me how to fix it
Thanks

**Comment by jlevers** [comment]
You need to apply for PII access by resubmitting your developer application with the relevant restricted roles selected. There will be ~20 more questions you have to answer, and then you'll go through Amazon's PII application review process.

PII access delegation basically means that you can send your SP API credentials to another service that _is_ approved to access PII, and then they'll handle it all for you -- you'll never actually get to access the data. This is useful for e.g., if you write a program that you want to use to pass through shipping information to another service.
