### ISSUE TITLE
 getOrders  SP-API  InvalidInput error 400

### ISSUE THREAD

**Issue by shoyshai** [jlevers/selling-partner-api#172]
i a trying to call getorders API passing $fulfillment_channels value as SellerFulfilled and it returns the error 400 1 validation error detected: Value \u0027[SellerFulfilled]\u0027 at \u0027fulfillmentChannel\u0027 failed to satisfy constraint: Member must satisfy constraint: [Member must satisfy enum value set: [AFN, MFN]].. Please update the correct value to be used to fetch seller fullfilled orders

**Comment by jlevers** [comment]
Could you please provide your code?

**Comment by shoyshai** [comment]
ok here is the code for getorders:-
getorders parameter values:- 
$after_date = date('Y-m-d\TH:i:s\Z',strtotime("-1 days"));
$marketplace_ids = ['A21TJRUUN4KGV'];
$created_after = $after_date;
$created_before = ''; 
$last_updated_after = '';
$last_updated_before = '';
$order_statuses = array('Unshipped','Pending','Shipped'); 
$fulfillment_channels = ['SellerFulfilled']; 
$payment_methods = ['CVS','Other'];
$buyer_email = '';
$seller_order_id = '';
$max_results_per_page = 100;
$easy_ship_shipment_statuses = array();
$next_token = ''; 
$amazon_order_ids = [];
$actual_fulfillment_supply_source_id = '';
$is_ispu = false; 
$store_chain_store_id = '';
 // Configuration object's 
try {
 $result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses,$fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id);
 echo "<pre>";
   //print_r($result);
} catch (Exception $e) {
   // echo "<pre>";print_r($e);die;
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}

**Comment by DayGarcia** [comment]
I had a lot of problem with this at once. I am not sure but the valid fullfilment channels are AFN (Amazon Fullfilment Network) and MFN (Merchant Fullfilment Network). Using this values worked for me.

**Comment by jlevers** [comment]
I see that the documentation doesn't match the error on this one -- sorry about that. Per the error you got, only the values `MFN` and `AFN` are allowed in `$fulfillment_channels`.

**Comment by jlevers** [comment]
Sorry, just realized that @DayGarcia was commenting that solution, so @shoyshai, please give it a try and then close the issue if what @DayGarcia said fixes your problem.

**Comment by shoyshai** [comment]
@jlevers @DayGarcia changing values from sellerfulfilled to mfn resolves the problem.

**Comment by yfhub** [comment]
@jlevers 
In sandbox, there seems to be a case where 'SellerFulfilled' is returned for 'FulfillmentChannel'.
Amazon may change the format and content of the response without notice, so it would be nice to be able to counteract this.

https://github.com/amzn/selling-partner-api-models/blob/7127fcf2a1b340e10b0faaaa7ed5c92efb1a26fb/models/orders-api-model/ordersV0.json#L372
