### ISSUE TITLE
FbaInboundApi  last_updated_after is not working

### ISSUE THREAD

**Issue by zamliyconsulting** [jlevers/selling-partner-api#174]
I am trying to get the activity in the last 24 hours for the FBA shipments.  However, the settings below always brings all shipments, whether or not they had activity in the last 24 hours.  Any ideas?

`$apiInstance = new SellingPartnerApi\Api\FbaInboundApi($config);
$query_type = 'LastUpdatedAfter'; 
$marketplace_id = 'ATVPDKIKX0DER';
$shipment_status_list = array('SHIPPED','IN_TRANSIT','DELIVERED','CHECKED_IN','RECEIVING','CLOSED','CANCELLED','DELETED','ERROR');
$shipment_id_list = array(''); 
$last_updated_after = date("c", strtotime("now") - 86400); 
$last_updated_before = '';`

**Comment by jlevers** [comment]
The dates have to be in ISO8601 Zulu format, like so: `2022-01-11T02:26:00Z`. So try something like this:

```php
$apiInstance = new SellingPartnerApi\Api\FbaInboundApi($config);
$query_type = 'LastUpdatedAfter';
$marketplace_id = 'ATVPDKIKX0DER';
$last_updated_after = new DateTime('1 day ago');

$response = $api->getShipments($query_type, $marketplace_id, null, null, $last_updated_after->format('Y-m-d\TH:i:s\Z'));
```

**Comment by zamliyconsulting** [comment]
> 2022-01-11T02:26:00Z

Thanks.  However, I tried almost all formats.  I also tried manually inserting the date like below.  It always brings all the shipments.

`$last_updated_after = '2022-01-10T02:26:00Z';`

**Comment by jlevers** [comment]
Ah, I think the issue may be the `$query_type` value you're using. I forgot that I had worked with this API before -- I dug into an older project where I was fetching shipments, and see that I used this code to do what you're trying to do:

```php
$api = new Api\FbaInboundApi($config);

$tz = new \DateTimeZone('UTC');
$lastUpdatedAfter = new \DateTime('30 days ago', $tz);
$lastUpdatedBefore = new \DateTime('now', $tz);

$res = $api->getShipments(
    'DATE_RANGE',
    'ATVPDKIKX0DER',
    null,
    null,
    $lastUpdatedAfter->format(\DateTimeInterface::ATOM),
    $lastUpdatedBefore->format(\DateTimeInterface::ATOM)
);
```

The enum docs for the `$query_type` parameter are [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-inbound-api/fulfillmentInboundV0.md#querytype).

**Comment by zamliyconsulting** [comment]
Thanks, the issue was indeed the query_type.  I had looked for the reference page but never found it.  I appreciate you including it here.
