### ISSUE TITLE
can't feed when i user POST_ORDER_FULFILLMENT_DATA

### ISSUE THREAD

**Issue by clxit** [jlevers/selling-partner-api#175]
I write like example:

```php
$feedType = FeedType::POST_PRODUCT_PRICING_DATA;
$feedsApi = new FeedsApi($config);
$createFeedDocSpec = new CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
$feedDocumentId = $feedDocumentInfo->getFeedDocumentId();
$feedContents = file_get_contents('<your/feed/file.xml>');
$docToUpload = new Document($feedDocumentInfo, $feedType);
$docToUpload->upload($feedContents);
```

This right and i can get response.But the follow is error. 

```php
$body = new CreateFeedSpecification();
$body->setInputFeedDocumentId($feedDocumentId);
$body->setFeedType($feedType['name']);
$body->setMarketplaceIds(['ATVPDKIKX0DER']);
try {
    $result = $feedsApi ->createFeed($body);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling FeedsApi->createFeed: ', $e->getMessage(), PHP_EOL;
}
```

The response is :
```
[400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]
}
```

**Comment by jlevers** [comment]
I was able to reproduce your issue -- I ran into this same problem months ago, and the only fix seemed to be to contact Amazon Seller Support by opening a new case and explaining your issue. I don't believe this is a problem related to this library.

(see https://github.com/amzn/selling-partner-api-docs/issues/867)

**Comment by jsanthoshaws** [comment]
HI Jlevers & Team,

can you please help me correcting the draft  

`

<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
--
  |  
  | <Header>
  |  
  | <DocumentVersion>1.02</DocumentVersion>
  |  
  | <MerchantIdentifier>XYZ</MerchantIdentifier>
  |  
  | </Header>
  |  
  | <MessageType>Price</MessageType><Message>
  |  
  | <MessageID>1</MessageID>
  |  
  | <OperationType>Update</OperationType>
  |  
  | <Price>
  |  
  | <SKU>SKUXYZ</SKU>
  | <StandardPrice>119.99</StandardPrice>
  | </Price>
  |  
  | </Message></AmazonEnvelope>


`


Thanks in Advance

**Comment by jsanthoshaws** [comment]
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
--
  |  
  | <Header>
  |  
  | <DocumentVersion>1.02</DocumentVersion>
  |  
  | <MerchantIdentifier>XYZ</MerchantIdentifier>
  |  
  | </Header>
  |  
  | <MessageType>Price</MessageType><Message>
  |  
  | <MessageID>1</MessageID>
  |  
  | <OperationType>Update</OperationType>
  |  
  | <Price>
  |  
  | <SKU>SKUXYZ</SKU>
  | <StandardPrice>119.99</StandardPrice>
  | </Price>
  |  
  | </Message></AmazonEnvelope>
