### ISSUE TITLE
Why cannot get Vendor Direct Fulfillment Orders?

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#178]
Dear Jlevers,
I use your library to get  Vendor Direct Fulfillment Orders as follow
```
 public function __construct()
    {
        $this->config = new Configuration([
            "lwaClientId" =>  $this->ClientID,
            "lwaClientSecret" => $this->ClientSecret,
            "lwaRefreshToken" => $this->RefreshToken,
            "awsAccessKeyId" => $this->AwsAccessKey,
            "awsSecretAccessKey" => $this->AwsSecretKey,
            "endpoint" =>Endpoint::NA,
            "roleArn" =>$this->RoleArn
        ]);
    }
public function GetVendorDirectFulfillmentOrders()
    {
        $Orders = new   VendorDirectFulfillmentOrdersApi($this->config);
        $created_after = new \DateTime("2021-12-05T19:20:30+01:00"); 
        $created_after = $created_after->format('Y-m-d\TH:i:s\Z');
        $created_before= new \DateTime("2021-12-07T19:20:30+01:00"); 
        $created_before= $created_before->format('Y-m-d\TH:i:s\Z');
        $ship_from_party_id = null;
        $status = null;
        $limit = 2; 
        $sort_order='ASC';
        $next_token=null;
        $include_details = true;
        $Response = $Orders->getOrders($created_after, $created_before, $ship_from_party_id ,
        $status = null, $limit = null, $sort_order = null, $next_token = null, $include_details);
        dd($Response);
    }
```
the message is
![image](https://user-images.githubusercontent.com/31786668/149052346-817321f0-4dea-406d-94da-c98bfdf638cb.png)

Please help me

**Comment by jlevers** [comment]
Could I see your SP API application configuration page in Seller Central?

**Comment by justvc** [comment]
I encountered the same problem. I do have the Direct-to-Consumer Shipping(Restricted) access.
![image](https://user-images.githubusercontent.com/26415635/149643768-3d1c11a7-3d04-4b3e-8d30-958a354836a2.png)

**Comment by justvc** [comment]
And I tried to modify the http request with a RDT token, but no luck.

**Comment by jlevers** [comment]
This issue is pretty hard for me to test at the moment, because I don't have access to a Vendor account. I should be able to get access to one sometime in the next week or two, at which point I'll be able to address this issue properly. Sorry for the delay.

**Comment by justvc** [comment]
@jlevers Thanks for your reply. I contacted Amazon support and they said I need a Vendor account instead of Seller account.
I guess that's my account issue instead of the PHP code issue.
Thanks again for your code.

**Comment by jlevers** [comment]
@justvc ah, didn't think to ask that -- yes, you need to have a Vendor account to make calls to the Vendor APIs (unless you're a developer whose application supports Vendors, and a Vendor authorizes your application, so you're making calls with their credentials).

@dangquanghai do you have a vendor account?

**Comment by dangquanghai** [comment]
Dear jlevers ,
I have, actually my friend has. I requested him  submit amazon to access Restrict Area. If Amazon approve I think I can use your library to get Vendor Direct Fulfillment Orders 
Thank All

**Comment by jlevers** [comment]
Great, in that case I'm going to close this issue. Feel free to reopen if you need more help.
