### ISSUE TITLE
`SellingPartnerApi\Model\Catalog\Item` attribute `rank` need to be renamed

### ISSUE THREAD

**Issue by pashamesh** [jlevers/selling-partner-api#179]
`SellingPartnerApi\Model\Catalog\Item` model has `ranks` attribute but [Docs says](https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#item) it's `salesRanks`.

**Comment by jlevers** [comment]
I made that change because despite Amazon's docs saying that the correct key is `salesRanks`, they actually return it in a key named `ranks`. See #64.
