### ISSUE TITLE
Can you give any example using RDT for Order Reports e.g GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING 

### ISSUE THREAD

**Issue by Waqas770** [jlevers/selling-partner-api#183]
I am facing a problem with getting the Order reports. 
Any idea about this?

**Comment by jlevers** [comment]
Was your developer account approved for the Tax Invoicing SP API role? That particular report is only accessible if you've been granted that role, which is a restricted role since it gives you access to PII.

**Comment by Vitaly-A-Ivanov** [comment]
Waqas770 I have the same problem without PII access:/

**Comment by Waqas770** [comment]
<img width="1125" alt="Screenshot 2022-01-21 at 12 50 07 PM" src="https://user-images.githubusercontent.com/34356234/150487500-4cfe8e2d-4399-46f0-960a-654f26c42c06.png">

Kindly check this I first create the restricted token and then pass in headers while creating Report.
Is this a good way to do this? 


Response 

"""
[500] {
  "errors": [
    {
      "code": "InternalFailure",
      "message": "We encountered an internal error. Please try again.",
      "details": ""
    }
  ]
}
"""

**Comment by Waqas770** [comment]
> Was your developer account approved for the Tax Invoicing SP API role? That particular report is only accessible if you've been granted that role, which is a restricted role since it gives you access to PII.

I am using Self AUthorization procedure. 
I already marked the PII option while App creation and regenerate the refresh token. 

Is this something I am missing here

**Comment by jlevers** [comment]
@Waqas770 if you have PII access, you should be able to just do this:

```php
// ...
$api = SellingPartnerApi\Api\ReportsApi($config);
$body = SellingPatnerApi\Model\Reports\CreateReportSpecification([
    'data_start_time' => Carbon::today()->subDay()->toIso8601ZuluString(),
    'data_end_time' => Carbon::today()->subSecond()->toIso8601ZuluString(),
    'marketplace_ids' => [/* your marketplace ids */],
    'report_type' => SellingPartnerApi\ReportType::GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING['name']
]);
$response = $api->createReport($body);
```

The library will create the RDT for you.

**Comment by Waqas770** [comment]
@jlevers Thanks for everything.
My app state is still in "Draft" can you guide me on how can I apply for the PII access?

Thanks

**Comment by jlevers** [comment]
Your application being in draft state is unrelated to whether or not you have PII access. You get PII access by going into your developer profile, selecting the PII roles that you want, and filling out the additional questions they ask you.

**Comment by jlevers** [comment]
Since I haven't heard from you, and this is a PII access issue, I'm going to close this.
