### ISSUE TITLE
403 error with getReports for GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE 

### ISSUE THREAD

**Issue by nikgilbe** [jlevers/selling-partner-api#185]
I'm able to get pretty much everything working fine so far including fees, inventory reports, catalog and order info (without PII - not requested that yet) but I'm really struggling getting a Settlement report and am wondering if this might be down to permissions rather than an error in my code, as I've basically copy/pasted it all from my other working code. I can't see anywhere that this needs anything more than default permissions...

  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]

**Comment by jlevers** [comment]
Could I see a screenshot of your SP API application config page?

**Comment by nikgilbe** [comment]
Hi - is this what you mean?

![image](https://user-images.githubusercontent.com/25084818/150746642-bac27f07-d98a-4c70-af7c-3a81cdd61656.png)

**Comment by jlevers** [comment]
Yep, that's what I was looking for. Given that you have access to the Finance and Accounting role, you should be able to download that report. It sounds like the issue probably isn't with your code, but could you please provide it just in case?

**Comment by nikgilbe** [comment]
It's not the prettiest so far, but **does** work for GET_FLAT_FILE_OPEN_LISTINGS_DATA. 

<?php

require __DIR__ . '/vendor/autoload.php';
require_once '../utils/sql_func.php';


$apiInstance = connectFeed();
$date = date('Y-m-d H:i:s');
$objDateTime = new DateTime('Yesterday');
$created_until = $objDateTime->format("Y-m-d\TH:i:sP");
$objDateTime = new DateTime('11/01/2021');
$created_since = $objDateTime->format("Y-m-d\TH:i:sP");

$report_type = array('GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE'); // This, along with other "financial" reports always fails with a 403 Forbidden error
$report_type = array('GET_FLAT_FILE_OPEN_LISTINGS_DATA'); // This works fine and returns a list of previously generated reports
$processing_statuses = array('DONE'); // string[] | A list of processing statuses used to filter reports.
$marketplaceIds = array('A1F83G8C2ARO7P');
$page_size = 10; // int | The maximum number of reports to return in a single call.
$next_token = '';

try {
        $result = $apiInstance->getReports($report_type, $processing_statuses, $marketplaceIds, $page_size, $created_since, $created_until, $next_token);
        print_r($result['reports']);
} catch (Exception $e) {
        echo 'Exception when calling ReportsApi->getReports: ', $e->getMessage(), PHP_EOL;
}
exit();

function connectFeed() {
        $myIni = parse_ini_file('../../.ini/myphp.ini', true);
        $lwaClientId = $myIni['aws']['lwaClientId'];
        $lwaClientSecret = $myIni['aws']['lwaClientSecret'];
        $lwaRefreshToken = $myIni['aws']['lwaRefreshToken'];
        $awsAccessKeyId = $myIni['aws']['awsAccessKeyId'];
        $awsSecretAccessKey = $myIni['aws']['awsSecretAccessKey'];
        $config = new SellingPartnerApi\Configuration([
            'lwaClientId' => $lwaClientId,
            'lwaClientSecret' => $lwaClientSecret,
            'lwaRefreshToken' => $lwaRefreshToken,
            'awsAccessKeyId' => $awsAccessKeyId,
            'awsSecretAccessKey' => $awsSecretAccessKey,
            "endpoint" => SellingPartnerApi\Endpoint::EU
        ]);

        $reportsApi = new SellingPartnerApi\Api\ReportsApi($config);
        return $reportsApi;
}

?>

Thanks for helping - Nik

**Comment by nikgilbe** [comment]
Hi again - I have created a new SP app with new credentials, and requested the Finance and Accounting role from the outset, as I've just remembered that was added on subsequently for the other App ID. And it is all working perfectly now, so it seems to be a bug in the Amazon world updating the App role. 

Thanks again for all your work with this - much appreciated.

**Comment by jlevers** [comment]
Whenever you add roles to an application, you have to generate a new refresh token to actually be able to make calls to the resources that the new roles give you access to :)

**Comment by nikgilbe** [comment]
Aha - thank you, I wasn't aware of that :-)
