### ISSUE TITLE
Can we update data promotion by API

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#186]
Dear jlevers,
Can we use the library to update data promotion ?
Thanks

**Comment by jlevers** [comment]
I'm not sure what you're referring to -- is there an endpoint in the older MWS API that allows you to do what you're talking about?

**Comment by dangquanghai** [comment]
Thank  jlevers

**Comment by jlevers** [comment]
It's not clear to me whether or not your issue is resolved -- if you still are looking for more guidance, let me know and I'll reopen this. I'm going to close it for now.
