### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by mgiorgi-github** [jlevers/selling-partner-api#187]
Hi,
i am trying to connect to my shop with this library but i receive event this error:

    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }

I've follow the documentation with no success... the app status i've created into seller central is draft, is a problem?
Thanks

**Comment by jlevers** [comment]
Could you please provide your code and a screenshot of your SP API application config page?

**Comment by mgiorgi-github** [comment]
Hi I’ve solved by fix AWS user permission… now I’ve to update quantity product inventory, I’ve to create feed? Can you give a example?
Thanks

**Comment by jlevers** [comment]
That's documented in the README, here: https://github.com/jlevers/selling-partner-api#uploading-a-feed-document

**Comment by mujaffars** [comment]
@mgiorgi-github What user permissions we need to provide for AWS user? I am facing the same error, Please help.

**Comment by Lollichkeit** [comment]
@mgiorgi-github
I also have the same error.
