### ISSUE TITLE
Order/OrderItem API does not pull some information

### ISSUE THREAD

**Issue by dhdhxk** [jlevers/selling-partner-api#189]
Hi, jlevers.

I've noticed it Order/OrderItem API does not pull some information. For example Shipping Address, it does not pull the name, addresses except city, state, zip code. Please refer to the attached object I've exported. Is it because of the permission? or, data_elements? I put null to data element when I call the API. Thank you.

object(SellingPartnerApi\Model\Orders\Address)#762 (1) {
  ["container":protected]=>
  array(13) {
    ["name"]=>
    NULL
    ["address_line1"]=>
    NULL
    ["address_line2"]=>
    NULL
    ["address_line3"]=>
    NULL
    ["city"]=>
    string(9) "MANHATTAN"
    ["county"]=>
    NULL
    ["district"]=>
    NULL
    ["state_or_region"]=>
    string(2) "IL"
    ["municipality"]=>
    NULL
    ["postal_code"]=>
    string(10) "60442-9418"
    ["country_code"]=>
    string(2) "US"
    ["phone"]=>
    NULL
    ["address_type"]=>
    NULL
  }
}

**Comment by jlevers** [comment]
Yeah, I should make this clearer in the documentation -- the `$data_elements` array corresponds to the `dataElements` values that can be specified when using Restricted Data Tokens (see Amazon docs [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md#tutorial-get-authorization-to-access-pii-for-bulk-orders)). If you don't have PII access, you can't retrieve customer addresses or order details. If you do have PII access, you'll need to pass the relevant values into `$data_elements` to retrieve the restricted data.
