### ISSUE TITLE
How to use proxy to connent to spapi?

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#190]
If i want to use proxy,where to add codes?

**Comment by jlevers** [comment]
I describe how to do that here: https://github.com/jlevers/selling-partner-api/issues/52#issuecomment-962533410

I don't know exactly what you need to do to the Guzzle client to use a proxy, but that should show you how you can pass a modified Guzzle client.

**Comment by lai3221** [comment]
Why it always show this:
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 150001 milliseconds with 0 out of 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.amazon.com/auth/o2/token

**Comment by valigara** [comment]
@lai3221 take look at GuzzleHttp docs related to [proxy](https://docs.guzzlephp.org/en/stable/request-options.html#proxy) it may help you, main idea here its that you need to create  GuzzleHttp\Client object with custom config similar to described in docs and those object use when you create relevant api object as second param.

@jlevers sorry for offtopic we created a new pull request it will alow to use proxy also for RDT generation process, we will be glad if you take a look on [it](https://github.com/jlevers/selling-partner-api/pull/184).

**Comment by jlevers** [comment]
@valigara thanks for assisting here. And yes, I saw your PR, just haven't had time to give it a proper look yet. Sorry for the delay.

**Comment by jlevers** [comment]
@lai3221 since I haven't heard from you, I'm going to assume @valigara's solution fixed your problem. If you need more help with this, feel free to reopen the issue.
