### ISSUE TITLE
Missing information in Financial events api

### ISSUE THREAD

**Issue by ianrussel** [jlevers/selling-partner-api#192]
Hi, I would like to track amazon fees, and one of them is FBARemovalFee. I tried the financialEvents API (listFinancialEvents) and heres the result

      "ServiceFeeEventList": [
                {
                    "AmazonOrderId": "DudXG5Q9KK",
                    "FeeList": [
                          {
                            "FeeType": "FBARemovalFee",
                            "FeeAmount": {
                              "CurrencyCode": "EUR",
                              "CurrencyAmount": -0.25
                            }
                        }
                    ]
                },
                {
                      "AmazonOrderId": "DudXG5Q9KK",
                      "FeeList": [
                          {
                              "FeeType": "FBARemovalFee",
                              "FeeAmount": {
                                  "CurrencyCode": "EUR",
                                  "CurrencyAmount": -0.75
                              }
                          }
                      ]
                },
         
              .........................
           

As you can see, it's not really useful since it doesn't contain some attributes/fields like date_posted and SKUs. Is this an amazon sellingpartner api bug or is there any other endpoints to call with complete information? I already tried the `reports` API, and still not complete and not accurate.

Cheers

**Comment by jlevers** [comment]
Hm, just checked the docs and it looks like different fee event types come with different amounts of information. Here's the list of info that comes with the `ServiceFeeEvent` type: https://github.com/amzn/selling-partner-api-docs/blob/main/references/finances-api/financesV0.md#servicefeeevent

Looks like many of those attributes are optional, so I'm not sure whether they're supposed to be coming through or not. Can you add the line `$config->setDebug(true);` before you pass your `Configuration` object into the `FinancesApi` constructor, and post the output of `listFinancialEvents`? You should get a bunch of extra debugging info.

**Comment by ianrussel** [comment]
confirmed, it's amazon sellingpartner API needs to update their API.
