### ISSUE TITLE
getItemOffersAsync return null in promise response body

### ISSUE THREAD

**Issue by crazybee47** [jlevers/selling-partner-api#193]
When i try getItemOffersAsync and unwrap all promises, null returned as promise response. I think the problem is [0], because $response is not array.

vendor/jlevers/selling-partner-api/lib/Api/ProductPricingApi.php:801

**Comment by jlevers** [comment]
Sorry about that -- should be fixed in `v4.2.8`. Give it a try and let me know if that solves your problem.

**Comment by crazybee47** [comment]
Thanks, it solved my problem
