### ISSUE TITLE
GET_PROMOTION_PERFORMANCE_REPORT but there are some promotions cannot see them

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#197]
Dear Jlevers,
I call GET_PROMOTION_PERFORMANCE_REPORT
  "promotionStartDateFrom" => "2022-01-01T00:00:01Z"
  "promotionStartDateTo" => "2022-05-31T23:59:59Z"
  "marketplaceIds" => [
 "ATVPDKIKX0DER"]
  
The response data return many promotions but there are some promotions which have StartDate and EndDate  in promotionStartDateFrom and promotionStartDateTo did not appear

Pls help me

 Thanks

**Comment by dangquanghai** [comment]
![image](https://user-images.githubusercontent.com/31786668/153179382-fd05f7ea-2087-4433-ab72-14c52b1185b4.png)

![image](https://user-images.githubusercontent.com/31786668/153179642-acf82a4e-e9fd-4b88-ade8-5e23d11cb183.png)

**Comment by jlevers** [comment]
Could you please provide your code?

**Comment by dangquanghai** [comment]
Yes Sir,
Here is my code to call the library
https://docs.google.com/document/d/1tuBajxyQxpx62mBSYc-vhnAR9HDRomXS-NsUjtSkFDU/edit?usp=sharing
Thank [jlevers](https://github.com/jlevers)

**Comment by jlevers** [comment]
Your code looks ok -- I'm guessing this is an issue on Amazon's end. I recommend you open a case with them, and/or create an issue in their documentation repository.

**Comment by dangquanghai** [comment]
yeah, I opened a the case and wait them to response.
Thank  jlevers
