### ISSUE TITLE
Validation exceptions for GET of a STANDARD_COMPARISON_TABLE with fewer than 6 positions

### ISSUE THREAD

**Issue by JohnCarnes** [jlevers/selling-partner-api#198]
Using AplusContentApi:getContentDocument throws validation errors when Amazon returns a STANDARD_COMPARISON_TABLE module that has fewer than 6 product columns.  It looks like Amazon returns all 6 positions with blank text for the image altText, the title, asin, and metrics values in the unused positions

This results in the following exceptions:

In ImageComponent.php line 346:                                                                            
  invalid length for $alt_text when calling ImageComponent., must be bigger than or equal to 1.                                                           

In StandardComparisonProductBlock.php line 377:
 invalid length for $title when calling StandardComparisonProductBlock., must be bigger than or equal to 1.

In StandardComparisonProductBlock.php line 406:                                                                            
  invalid length for $asin when calling StandardComparisonProductBlock., must be bigger than or equal to 10.

In PlainTextItem.php line 320:                                                                       
  invalid length for $value when calling PlainTextItem., must be bigger than or equal to 1. 

From the Amazon API documentation it looks like the only required field is the boolean highlight field. There does not seem to be way to indicate that a position is unused, so I would assume blank values need to pass validation for GET operations.

Thanks for the work on this api. I'm really excited about moving away from my old XML based MWS code!

**Comment by jlevers** [comment]
This should be fixed in `v4.3.0` -- give it a shot and let me know if you have any more issues.

**Comment by jlevers** [comment]
Hey @JohnCarnes -- since I haven't heard from you, I'm going to assume that the fix worked. Please reopen the issue if you run into any more problems.
