### ISSUE TITLE
FulfillmentOutbound  API,there is an another enumeration value for Additionallocationinfo

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#199]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md#additionallocationinfo

About additionallocationinfo,in my actual project operation, there is an another enumeration value - FRONT_DOOR/PORCH, but it 's not in selling-partner-api-docs.

**Comment by jlevers** [comment]
Just to clarify -- `FRONT_DOOR/PORCH` is a single value, not two different ones?

**Comment by jlevers** [comment]
Reread your issue and realized that the answer to my question was yes -- give `v4.3.1` a try and see if that fixes your problem.

**Comment by lai3221** [comment]
> Just to clarify -- `FRONT_DOOR/PORCH` is a single value, not two different ones?
It is a single value.

**Comment by jlevers** [comment]
Did `v4.3.1` fix this for you?

**Comment by lai3221** [comment]
> Did `v4.3.1` fix this for you?

yes
