### ISSUE TITLE
FulfillmentOutbound API,there is an another enumeration single value for CurrentStatus

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#201]
https://github.com/amzn/selling-partner-api-docs/blob/main/references/fulfillment-outbound-api/fulfillmentOutbound_2020-07-01.md#currentstatus

Throw exception:Invalid value for enumsst '\SellingPartnerApi\Model\FbaOutbound\CurrentStatus', must be one of: 'IN_TRANSIT', 'DELIVERED', 'RETURNING', 'RETURNED', 'UNDELIVERABLE', 'DELAYED', 'AVAILABLE_FOR_PICKUP', 'CUSTOMER_ACTION'.

About currentStatus,in my actual project operation, there is an another enumeration single value -  OUT_FOR_DELIVERY, but it 's not in selling-partner-api-docs.

I have added this single value on CurrentStatus.php.And it works normally.

**Comment by jlevers** [comment]
Install `v4.3.2` and let me know if that solves the issue for you.

**Comment by jlevers** [comment]
I'm going to assume this worked since I haven't heard from you on it -- feel free to reopen the issue if that's not the case.
