### ISSUE TITLE
Error on getting orders

### ISSUE THREAD

**Issue by ghaliano2005** [jlevers/selling-partner-api#202]
Hi,
In order to setup an app for the aws seller API, i succefuly passed all of those steps well explained [here](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md)
[Step 1. The selling partner initiates authorization from the Amazon Seller Central Partner Network](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-the-selling-partner-initiates-authorization-from-the-amazon-seller-central-partner-network)

[Step 2. The selling partner consents to authorize your application](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-2-the-selling-partner-consents-to-authorize-your-application)

[Step 3. The selling partner signs into your website](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-3-the-selling-partner-signs-into-your-website)

[Step 4. Amazon sends you the authorization information](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-4-amazon-sends-you-the-authorization-information)

[Step 5. Your application exchanges the LWA authorization code for an LWA refresh token](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-5-your-application-exchanges-the-lwa-authorization-code-for-an-lwa-refresh-token)

However  when i try to call the api for orders i get a strange error
` [ERROR] Server error: `POST https://api.amazon.com/auth/o2/token` resulted in a `500 Internal Server Error` response:  
         {"error_index":"Fcx5knlboMSD4FpIWy28qgAAAAAAAAABrjiZIfZ9PKCaJThSvbkUo5Cfrpm8jtmNGY31BOSGhxvg2j9ly53kTHnnmD-ziGL
         P-APuTTwg (truncated...)       `

This is an insight of the code i used to end up with that error
```
public function import(Store $store)
    {
        // See README for more information on the Configuration object's options
        $config = new \SellingPartnerApi\Configuration([
            "lwaClientId" => $this->params->get('aws_app_client_id'),
            "lwaClientSecret" => $this->params->get('aws_app_client_secret'),
            "lwaRefreshToken" => $store->getExchangedRefreshToken()['access_token'],
            "awsAccessKeyId" => $this->params->get('aws_iam_id'),
            "awsSecretAccessKey" => $this->params->get('aws_iam_key'),
            "endpoint" => \SellingPartnerApi\Endpoint::NA  // or another endpoint from lib/Endpoints.php
        ]);

        $apiInstance = new \SellingPartnerApi\Api\OrdersApi($config);
        $marketplace_ids = array($store->getAwsSellingPartnerId()); // string[] | A list of MarketplaceId values. Used to select orders that were placed in the specified marketplaces. See the [Selling Partner API Developer Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#marketplaceid-values) for a complete list of marketplaceId values.

        try {
            $result = $apiInstance->getOrders($marketplace_ids);
            print_r($result);
        } catch (\Exception $e) {
            echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
        }
    }
```

**Comment by jlevers** [comment]
Hey @ghaliano2005 -- I don't see anything immediately wrong with your code. A 500 error means that it's a problem on Amazon's end, not a problem with this library...I would either open a support case via the API support form [here](https://developer.amazonservices.com/support) (click the "Contact Us" button), and/or by opening a new issue in the [main SP API docs repository](https://github.com/amzn/selling-partner-api-docs/issues).
