### ISSUE TITLE
Enum value for AdditionalLocationInfo and CurrentStatus

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#203]
I got two enum values for AdditionalLocationInfo:BACK_PORCH and IN/AT MAILBOX,
a enum value for CurrentStatus:DELIVERY_ATTEMPTED.

I don't understand why these values don't appear in the amz-spapi-doc.

**Comment by jlevers** [comment]
Should be fixed in `v4.3.3`. Amazon (for whatever reason) didn't actually enumerate all the values they pass in their OpenAPI models, so I have to update the enums in the fork of their models that I maintain.
