### ISSUE TITLE
Invalid value for enum '\SellingPartnerApi\Model\FbaOutbound\EventCode'

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#204]
There is an other enum value  EVENT_310  for \SellingPartnerApi\Model\FbaOutbound\EventCode.

Exception:
Invalid value for enum '\SellingPartnerApi\Model\FbaOutbound\EventCode', must be one of: 'EVENT_101', 'EVENT_102', 'EVENT_201', 'EVENT_202', 'EVENT_203', 'EVENT_204', 'EVENT_205', 'EVENT_206', 'EVENT_301', 'EVENT_302', 'EVENT_304', 'EVENT_306', 'EVENT_307', 'EVENT_308', 'EVENT_309', 'EVENT_401', 'EVENT_402', 'EVENT_403', 'EVENT_404', 'EVENT_405', 'EVENT_406', 'EVENT_407', 'EVENT_408', 'EVENT_409', 'EVENT_411', 'EVENT_412', 'EVENT_413', 'EVENT_414', 'EVENT_415', 'EVENT_416', 'EVENT_417', 'EVENT_418', 'EVENT_419'

**Comment by jlevers** [comment]
Should be fixed in `v4.3.3`. Let me know if you run into any more issues.
