### ISSUE TITLE
How to call report GET_AFN_INVENTORY_DATA

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#207]
Dear jlevers,
Pls show us an exam to call GET_AFN_INVENTORY_DATA. We cannot create this report
my code is
 $CalledDate =  date('Y-m-d H:i:s');
  $ReportType = 'GET_AFN_INVENTORY_DATA';
 public function ExecuteGetFBAInventory($CalledDate,$ReportType)
    {
        $ReportsApi  = new ReportsApi($this->config);
        $ReportType = new \SellingPartnerApi\Model\Reports\CreateReportSpecification();
        
        $StartDateTime = $this->MoveDate($CalledDate,-8);
        $EndDateTime = $this->AddLastTimeToDate( $CalledDate,-2);

        $StartDateTime = $this->AddFirstTimeToDate($StartDateTime);
        $EndDateTime = $this->AddLastTimeToDate( $EndDateTime);

        $StartDateTime = strtotime($StartDateTime);
        $EndDateTime = strtotime($EndDateTime);
        $StartDateTime = date('Y-m-d\TH:i:s\Z',$StartDateTime);
        $EndDateTime =date('Y-m-d\TH:i:s\Z',$EndDateTime);
        
        $ReportType->setDataStartTime($StartDateTime);
        $ReportType->setDataEndTime($EndDateTime);
        $ReportType->setReportType($ReportType);
        $ReportType->setMarketplaceIds(['ATVPDKIKX0DER']);
       
        $response = $ReportsApi->createReport($ReportType);
        dd($response);
 }
The result is white page line a picture attached
![image](https://user-images.githubusercontent.com/31786668/154220594-7784b6ef-0a38-4d3a-8fb9-b29e9df4e660.png)

Pls help me
Thank jlevers

**Comment by jlevers** [comment]
This is an error with your application (in Laravel, I think?), not with the SP API related code.
