### ISSUE TITLE
It is recommended to encapsulate two methods for interface response.

### ISSUE THREAD

**Issue by lai3221** [jlevers/selling-partner-api#208]
1、Function getPayload:to get the response's payload data.
2、Function getErrors:to get the response's error data.

**Comment by jlevers** [comment]
Unfortunately not every API enpdoint response contains a payload and errors (for instance the `createFeed` call). I agree that it would be neater to have it work the way you're describing, but it would require a lot of backend effort to get it to work. Also, this library is mostly generated from OpenAPI models, which further complicates things.
