### ISSUE TITLE
Could not match input arguments

### ISSUE THREAD

**Issue by shaikharbaz2** [jlevers/selling-partner-api#209]
Hello 
we are getting error when get orders . could you please help us

use SellingPartnerApi\Endpoint;
use SellingPartnerApi\Api\OrdersApi;
use SellingPartnerApi\Api\VendorOrdersApi;
include __DIR__ . '/vendor/autoload.php';
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "",
    "lwaClientSecret" => "",
    "lwaRefreshToken" => "",
    "awsAccessKeyId" => "",
    "awsSecretAccessKey" => "",
    "roleArn" => "",
    "endpoint" => Endpoint::EU_SANDBOX,
]);

$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
try {
    $result = $apiInstance->getOrders(['A21TJRUUN4KGV']);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrder: ', $e->getMessage(), PHP_EOL;
}

we got Error **Exception when calling OrdersApi->getOrder: [400] [{"code":"InvalidInput","message":"Could not match input arguments"}]**

**Comment by shaikharbaz2** [comment]
Hi 
i have tried but i got same error 
**Exception when calling OrdersApi->getOrder: [400] [{"code":"InvalidInput","message":"Could not match input arguments"}]**
$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
datetime = new DateTime('17 Feb 2022');

try {
    $result = $apiInstance->getOrders(['A21TJRUUN4KGV'],$datetime->format('c'));
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrder: ', $e->getMessage(), PHP_EOL;
}

**Comment by jlevers** [comment]
Dates should be strings in ISO 8601 Zulu format (like `2022-02-17T12:08:00Z`).

**Comment by jlevers** [comment]
Since I haven't heard from you, I'm going to close this issue. Feel free to reopen it if you still need help.
