### ISSUE TITLE
GET_MERCHANT_LISTINGS_ALL_DATA returns an incomplete report 

### ISSUE THREAD

**Issue by crazybee47** [jlevers/selling-partner-api#210]
Heeeelp please! I have already contacted Amazon technical support (they requested logs and immediately closed the appeal without a response), studied the forums and spent several hours with xDebug.

My problem: I get an access token using the [Get an LWA authorization code](https://developer-docs.amazon.com/sp-api/docs/authorization-api-use-case-guide#step-1-get-an-lwa-authorization-code) method and after that I get a full report on inventory - 3388 rows. After a some time (about 1 hour), something happens and I start getting 115 rows instead of 3388. This is due to a reason unknown to me. I know for sure that refresh token is not to blame here, this problem occurs regardless of whether I have an old token or an already updated one.

Maybe you have encountered such a problem? How to solve it?

**Comment by jlevers** [comment]
Are you generating new access tokens hourly with the refresh token you receive from `getAuthorizationCode`? The refresh token is valid forever, but the access token has to be regenerated every hour.

**Comment by crazybee47** [comment]
@jlevers Yes, of course. Before making a request, I check if the access token has expired and update if it has expired through this URL https://api.amazon.com/auth/o2/token. 

That's the problem, I always get an response, but it is not always correct.

**Comment by crazybee47** [comment]
From observations, I saved the auth data received during the first authorization (via authorization code), with a refresh token by this data, I get correct answers, but after a while - again 115 inventory.

**Comment by jlevers** [comment]
This is an issue on Amazon's end, not an issue with this library -- I recommend opening a support case [here](https://developer.amazonservices.com/support) and/or [creating an issue](https://github.com/amzn/selling-partner-api-docs/issues) in the main docs repo.
