### ISSUE TITLE
Not able to create GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING report 

### ISSUE THREAD

**Issue by pramodwagh** [jlevers/selling-partner-api#211]
Hello, @jlevers, 
I am not able to create GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING report to get Taxes related to the order. I have PII access and am also able to get buyer's Info like addresses and others. but not able to generate a Tax report can you please help me with this.

my code:- 

        $api = new ReportsApi($config);
        $body = new \SellingPartnerApi\Model\Reports\CreateReportSpecification([
            'data_start_time' => Carbon::today()->subDay()->toIso8601ZuluString(),
            'data_end_time' => Carbon::today()->subSecond()->toIso8601ZuluString(),
            'marketplace_ids' => ['A1F83G8C2ARO7P'],
            'report_type' => \SellingPartnerApi\ReportType::GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING['name']
        ]);
        $response = $api->createReport($body);
        
        
![image](https://user-images.githubusercontent.com/10533044/154631187-60f47a68-57ba-42c0-ba93-fde3f7e51434.png)

**Comment by jlevers** [comment]
Could I see a screenshot of your application config in Seller Central? Are you able to create other kinds of reports?

**Comment by pramodwagh** [comment]
![config1](https://user-images.githubusercontent.com/10533044/154886103-854ba534-0585-4d88-9b2f-c7955c3e3cf8.PNG)
![config2](https://user-images.githubusercontent.com/10533044/154886107-fa4a979a-fc46-49ec-a087-f6ebc0506477.PNG)

**Comment by pramodwagh** [comment]
Yes, I am able to create GET_FLAT_FILE_OPEN_LISTINGS_DATA report.

**Comment by jlevers** [comment]
You said you have access to PII, but I don't see any PII-related roles in your first screenshot. What makes you say that you do in fact have PII access? Delegating PII does not automatically give you access to PII -- it just allows you to give another application permission to access PII through your application (without you ever seeing it).

**Comment by pramodwagh** [comment]
@jlevers I got PII confirmation from the Amazon team. can you please tell me what should I need to check. can you please share PII enabled account screenshot? so I can verify with amazon team.

**Comment by jlevers** [comment]
If you have access to PII, you'll have one or more of the Direct-to-Customer Shipping, Tax Invoicing, or Tax Remittance roles available to select on your SP API application config page. Could you please send me a screenshot of the whole config page at once?

**Comment by pramodwagh** [comment]
![amzonapplication](https://user-images.githubusercontent.com/10533044/155275805-a2abb2bb-68ca-4b9e-b014-64758daf90e8.jpg)

**Comment by pramodwagh** [comment]
@jlevers can you please check and let me know if this is okay.
