### ISSUE TITLE
Laravel Debug shows: Return type of SellingPartnerApi\Model\VendorOrders\GetPurchaseOrdersResponse::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists

### ISSUE THREAD

**Issue by CreateWithCoding** [jlevers/selling-partner-api#212]
I'm getting what I think are depreciation warnings.  I think this is due to PHP 8.1.2.  However, it doesn't seem to affect the behavior of my program. There are many such errors. Probably not a big deal right now, but maybe in the future? Thoughts?

> Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\GetPurchaseOrdersResponse::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\GetPurchaseOrdersResponse.php on line 292
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\GetPurchaseOrdersResponse::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\GetPurchaseOrdersResponse.php on line 304
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\GetPurchaseOrdersResponse::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\GetPurchaseOrdersResponse.php on line 317
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\GetPurchaseOrdersResponse::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\GetPurchaseOrdersResponse.php on line 333
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\GetPurchaseOrdersResponse::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\GetPurchaseOrdersResponse.php on line 345
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderList::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderList.php on line 266
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderList::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderList.php on line 278
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderList::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderList.php on line 291
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderList::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderList.php on line 307
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderList::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderList.php on line 319
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Pagination::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Pagination.php on line 237
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Pagination::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Pagination.php on line 249
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Pagination::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Pagination.php on line 262
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Pagination::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Pagination.php on line 278
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Pagination::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Pagination.php on line 290
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Order::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Order.php on line 338
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Order::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Order.php on line 350
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Order::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Order.php on line 363
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Order::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Order.php on line 379
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Order::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Order.php on line 391
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderDetails::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderDetails.php on line 702
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderDetails::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderDetails.php on line 714
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderDetails::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderDetails.php on line 727
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderDetails::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderDetails.php on line 743
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderDetails::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderDetails.php on line 755
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\PartyIdentification::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\PartyIdentification.php on line 298
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\PartyIdentification::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\PartyIdentification.php on line 310
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\PartyIdentification::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\PartyIdentification.php on line 323
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\PartyIdentification::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\PartyIdentification.php on line 339
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\PartyIdentification::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\PartyIdentification.php on line 351
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderItem::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderItem.php on line 420
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderItem::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderItem.php on line 432
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderItem::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderItem.php on line 445
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderItem::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderItem.php on line 461
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\OrderItem::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\OrderItem.php on line 473
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ItemQuantity::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ItemQuantity.php on line 331
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ItemQuantity::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ItemQuantity.php on line 343
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ItemQuantity::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ItemQuantity.php on line 356
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ItemQuantity::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ItemQuantity.php on line 372
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ItemQuantity::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ItemQuantity.php on line 384
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Money::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Money.php on line 275
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Money::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Money.php on line 287
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Money::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Money.php on line 300
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Money::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Money.php on line 316
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\Money::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\Money.php on line 328
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ImportDetails::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ImportDetails.php on line 468
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ImportDetails::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ImportDetails.php on line 480
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ImportDetails::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ImportDetails.php on line 493
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ImportDetails::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ImportDetails.php on line 509
Level
warning
Log
Message
Return type of SellingPartnerApi\Model\VendorOrders\ImportDetails::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in C:\laragon\www\appinstafire\vendor\jlevers\selling-partner-api\lib\Model\VendorOrders\ImportDetails.php on line 521
Level
warning

**Comment by jlevers** [comment]
Thanks @CreateWithCoding -- I just started getting these too. You're correct that it has to do with your PHP version, and you're also correct that it doesn't actually effect the code's execution. I'm going to deal with this at some point soon, but I need to make sure I can update the code in such a way that it's still compatible with this library's earliest supported PHP version (7.3).

**Comment by CreateWithCoding** [comment]
Laravel 9 discuses these PHP Return Types here, if interested: https://laravel.com/docs/9.x/upgrade#php-return-types

I think it won't matter until PHP 9 I'm guessing.

> PHP is beginning to transition to requiring return type definitions on PHP methods such as offsetGet, offsetSet, etc. In light of this, Laravel 9 has implemented these return types in its code base. Typically, this should not affect user written code;

**Comment by jlevers** [comment]
I just released some changes that suppress the deprecation warnings for now...give `v4.3.4` a try.

**Comment by CreateWithCoding** [comment]
I updated to v4.3.4 and that solved for now. Thanks Jesse.
