### ISSUE TITLE
Order customization + upload order Invoice

### ISSUE THREAD

**Issue by balicekt** [jlevers/selling-partner-api#214]
Hello, 

first of all thank you for this API. And I checked the documentation but Im not able to find how to get order customer customization data and how to upload order invoice. 

See attached picture form the seller central order detail: https://imgur.com/a/crEXWBT

Thank you very much for any help. If I can find this I will support this project for sure.

**Comment by jlevers** [comment]
Order customization data is available in the [`ItemBuyerInfo`](https://github.com/amzn/selling-partner-api-docs/blob/main/references/orders-api/ordersV0.md#itembuyerinfo) object on each order item in the `OrdersApi::getOrderItems` response.

I've never needed to upload order invoices before, but I'm guessing you use the Feeds API and the `POST_INVOICE_CONFIRMATION_DATA` [feed type](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feedtype-values.md#order-feeds).

**Comment by jlevers** [comment]
Hey @balicekt -- since I haven't heard from you, I'm going to close this issue. Feel free to reopen it if you need more help.

**Comment by balicekt** [comment]
Hello @jlevers thank you for answer. I was waiting for PII access to SP-API now I got it but I still doesn't see the customzation data :(  Any idea what can be wrong?

**Comment by jlevers** [comment]
You need to pass the `$data_elements` parameter as specified [here](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/OrdersApi.md#getorderitems) -- for that particular call, the only allowed `$data_elements` value is `buyerInfo`, so you would pass `['buyerInfo']` for the `$data_elements` parameter. There's more info on the data elements properties in the [RDT documentation](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#tutorial-get-authorization-to-access-pii-for-bulk-orders).

**Comment by balicekt** [comment]
@jlevers OK thank you for help. Now getting below error: 

"message": "Application does not have access to one or more requested data elements: [buyerInfo]"

**Comment by balicekt** [comment]
It is working now. Thank you for help!!
