### ISSUE TITLE
Getting error while calling getOrders API.

### ISSUE THREAD

**Issue by SShalini** [jlevers/selling-partner-api#215]
While calling "getOrders" we are getting this error 

Warning: count(): Parameter must be an array or an object that implements Countable in C:\xampp\htdocs\amazon-sp-api\vendor\jlevers\selling-partner-api\lib\Api\OrdersApi.php on line 2377
Exception when calling OrdersApi->getOrders: [400] { "errors": [ { "code": "InvalidInput", "message": "Application do not have access to some or all requested resource", "details": "" } ] } 

Could you please let us know what we are missing?

**Comment by jlevers** [comment]
Could you please provide your code, and post a screenshot of your SP API application config on Seller Central?

**Comment by SShalini** [comment]
![image (1)](https://user-images.githubusercontent.com/22955592/156106365-6b580999-1de6-4179-b19f-a1bc0b77beb5.png)


Please check the below code. Let me know if any other details required.

<?php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

 

// See README for more information on the Configuration object's options
$config = new Configuration([
    "lwaClientId" => __DEVELOPER_SPAPI_CLIENT_ID__,
    "lwaClientSecret" => __DEVELOPER_SPAPI_CLIENT_SECERET__,
    "lwaRefreshToken" => __REFRESH_TOKEN__,
    "awsAccessKeyId" => __ACCESS_KEY__,
    "awsSecretAccessKey" => __SECRET_KEY__,
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "roleArn" => __ROLE_ARN__,
    "endpoint" => Endpoint::NA
]);


$apiInstance = new SellingPartnerApi\Api\OrdersApi($config);
$marketplace_ids = array('ATVPDKIKX0DER'); // string[] | A list of MarketplaceId values. Used to select orders that were placed in the specified marketplaces. See the [Selling Partner API Developer Guide](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#marketplaceid-values) for a complete list of marketplaceId values.
$created_after = '2022-02-01 00:00:00'; // string | A date used for selecting orders created after (or at) a specified time. Only orders placed after the specified time are returned. Either the CreatedAfter parameter or the LastUpdatedAfter parameter is required. Both cannot be empty. The date must be in ISO 8601 format.
$created_before = '2022-02-28 00:00:00'; // string | A date used for selecting orders created before (or at) a specified time. Only orders placed before the specified time are returned. The date must be in ISO 8601 format.
$last_updated_after = ''; // string | A date used for selecting orders that were last updated after (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in ISO 8601 format.
$last_updated_before = ''; // string | A date used for selecting orders that were last updated before (or at) a specified time. An update is defined as any change in order status, including the creation of a new order. Includes updates made by Amazon and by the seller. The date must be in ISO 8601 format.
$order_statuses = array(''); // string[] | A list of OrderStatus values used to filter the results. Possible values: PendingAvailability (This status is available for pre-orders only. The order has been placed, payment has not been authorized, and the release date of the item is in the future.); Pending (The order has been placed but payment has not been authorized); Unshipped (Payment has been authorized and the order is ready for shipment, but no items in the order have been shipped); PartiallyShipped (One or more, but not all, items in the order have been shipped); Shipped (All items in the order have been shipped); InvoiceUnconfirmed (All items in the order have been shipped. The seller has not yet given confirmation to Amazon that the invoice has been shipped to the buyer.); Canceled (The order has been canceled); and Unfulfillable (The order cannot be fulfilled. This state applies only to Multi-Channel Fulfillment orders.).
$fulfillment_channels = array(''); // string[] | A list that indicates how an order was fulfilled. Filters the results by fulfillment channel. Possible values: AFN (Fulfillment by Amazon); MFN (Fulfilled by the seller).
$payment_methods = array(''); // string[] | A list of payment method values. Used to select orders paid using the specified payment methods. Possible values: COD (Cash on delivery); CVS (Convenience store payment); Other (Any payment method other than COD or CVS).
$buyer_email = ''; // string | The email address of a buyer. Used to select orders that contain the specified email address.
$seller_order_id = 'sellerorder_id_example'; // string | An order identifier that is specified by the seller. Used to select only the orders that match the order identifier. If SellerOrderId is specified, then FulfillmentChannels, OrderStatuses, PaymentMethod, LastUpdatedAfter, LastUpdatedBefore, and BuyerEmail cannot be specified.
$max_results_per_page = 56; // int | A number that indicates the maximum number of orders that can be returned per page. Value must be 1 - 100. Default 100.
$easy_ship_shipment_statuses = array(''); // string[] | A list of EasyShipShipmentStatus values. Used to select Easy Ship orders with statuses that match the specified  values. If EasyShipShipmentStatus is specified, only Amazon Easy Ship orders are returned.Possible values: PendingPickUp (Amazon has not yet picked up the package from the seller). LabelCanceled (The seller canceled the pickup). PickedUp (Amazon has picked up the package from the seller). AtOriginFC (The packaged is at the origin fulfillment center). AtDestinationFC (The package is at the destination fulfillment center). OutForDelivery (The package is out for delivery). Damaged (The package was damaged by the carrier). Delivered (The package has been delivered to the buyer). RejectedByBuyer (The package has been rejected by the buyer). Undeliverable (The package cannot be delivered). ReturnedToSeller (The package was not delivered to the buyer and was returned to the seller). ReturningToSeller (The package was not delivered to the buyer and is being returned to the seller).
$next_token = ''; // string | A string token returned in the response of your previous request.
$amazon_order_ids = array(''); // string[] | A list of AmazonOrderId values. An AmazonOrderId is an Amazon-defined order identifier, in 3-7-7 format.
$actual_fulfillment_supply_source_id = ''; // string | Denotes the recommended sourceId where the order should be fulfilled from.
$is_ispu = True; // bool | When true, this order is marked to be picked up from a store rather than delivered.
$store_chain_store_id = ''; // string | The store chain store identifier. Linked to a specific store in a store chain.
$data_elements = array(''); // string[] | An array of restricted order data elements to retrieve (valid array elements are \"buyerInfo\" and \"shippingAddress\")

try {
    $result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling OrdersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}

**Comment by jlevers** [comment]
The timestamps you pass to `getOrders` need to be in ISO8601 Zulu format, so `2022-02-01 00:00:00` should be `2022-02-01T00:00:00Z` (and same for the other date). Also, most of the `getOrders` parameters are optional, and if you want to pass an empty value for them, it should be `null`, not an empty string. Try replacing this:

```php
$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
```

with this:

```php
$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before);
```

**Comment by jlevers** [comment]
Since I haven't heard from you, I'm going to assume you resolved your problem. Feel free to reopen the issue if you need more help.
