### ISSUE TITLE
Not getting "Order_url" through GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL

### ISSUE THREAD

**Issue by SShalini** [jlevers/selling-partner-api#220]
We are not getting "order_url" value through the SP-API but we are getting the same through the mws, Could you clease confirm this that why we are not getting this value?  Is there any other process to get this?

**Comment by jlevers** [comment]
I haven't fetched that report via MWS, but when I retrieve it from the SP API I don't see any order URL field, so I don't think you're doing anything wrong, if that's what your asking. No idea if there's some other way to get it, as I don't know what it is. It's a direct link to the order of some kind?
