### ISSUE TITLE
For Amazon SP-API how do you close and re-list a listing by API?

### ISSUE THREAD

**Issue by crazybee47** [jlevers/selling-partner-api#221]
In the sellercentral interface i can close listing and re-list closed listing.
![image](https://user-images.githubusercontent.com/32307323/157919326-f9869a97-6ed4-4cd3-a397-04a1f4ebca95.png)

I didn’t find these methods in the SP-API. I tried to do this through ListingPutRequest, and loading POST_FLAT_FILE_INVLOADER_DATA feed, specifying “d” in the add-delete column. Unsuccessfully.

Please tell me if there is a way to Close and Re-list listing via the SP-API?

**Comment by jlevers** [comment]
The only way I know of is through the methods you mentioned -- I don't have any other suggestions, unfortunately. Did you get errors using those methods, or did they just not work?

**Comment by crazybee47** [comment]
They just not work

**Comment by jlevers** [comment]
I'd open a [new case](https://developer.amazonservices.com/support) with Amazon and/or create an issue in the main documentation repository. I unfortunately don't have any better advice for you, and this isn't an issue related to this library.
