### ISSUE TITLE
Unable to run FbaInboundEligibilityApi

### ISSUE THREAD

**Issue by oshimamasara** [jlevers/selling-partner-api#224]
I'm trying to use FbaInbound Eligibility Api to check if my item is dangerous goods.

I wrote the code as below but I get an error.
Can Jesse get the data?
If so, is this not available in Asia?

I think you are busy, but I would appreciate it if you could tell me.
（Google Translate）

```
    require_once(__DIR__ . '/vendor/autoload.php');

    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->load();
    
    $refresh_token = $_ENV["refresh_token"]; 
    $client_id = $_ENV["client_id"];
    $client_secret = $_ENV["client_secret"];
    $AccessKeyId = $_ENV["AccessKey"];
    $SecretKey = $_ENV["SecretKey"];
    
    $config = new SellingPartnerApi\Configuration([
        "lwaClientId" => $client_id,
        "lwaClientSecret" => $client_secret,
        "lwaRefreshToken" => $refresh_token,
        "awsAccessKeyId" => $AccessKeyId,
        "awsSecretAccessKey" => $SecretKey,
        "endpoint" => SellingPartnerApi\Endpoint::FE
    ]);


    #$apiInstance = new SellingPartnerApi\Api\FbaInboundEligibilityApi();
    $apiInstance = new SellingPartnerApi\Api\FbaInboundEligibilityApi($config);
    $asin = 'B003TDTK0G'; 
    $program = 'INBOUND'; 
    $marketplace_ids = array('A1VC38T7YXB528');

    try {
        $result = $apiInstance->getItemEligibilityPreview($asin, $program, $marketplace_ids);
        print_r($result);
    } catch (Exception $e) {
        echo 'Exception when calling FbaInboundEligibilityApi->getItemEligibilityPreview: ', $e->getMessage(), PHP_EOL;
    }
```

### result
Exception when calling FbaInboundEligibilityApi->getItemEligibilityPreview: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }

**Comment by jlevers** [comment]
Hi @oshimamasara -- your code looks fine....could I get a screenshot of your application config in Seller Central? I'm able to successfully call this endpoint in Australia, which is part of the same Amazon region as Japan...I don't have any seller credentials with access to Japan, so it's still possible that Japan doesn't have access to the endpoint, but I think that's unlikely.

**Comment by oshimamasara** [comment]
Thank you for your reply.

Does the image you see match here?

![IMG](https://xs453577.xsrv.jp/_amazon_seller.png)

I can use CatalogItemsV0Api () etc. with the library you created, so area may be a problem.
If you know any useful information, please let me know.
Thank you.

**Comment by jlevers** [comment]
Could you post an English version of that screenshot? I think there's a language selector in the top right.

**Comment by jlevers** [comment]
@oshimamasara since I haven't heard from you I'm going to assume you resolved your issue. Feel free to reopen this if you need more help.

**Comment by BansiFuletra** [comment]
Hello,
I am calling FBA Inbound item eligibility preview api from postman. but i am getting error 403.`{
    "errors": [
        {
            "code": "Unauthorized",
            "message": "Access to requested resource is denied.",
            "details": ""
        }
    ]
}`
`https://sellingpartnerapi-na.amazon.com/fba/inbound/v1/eligibility/itemPreview?marketplaceIds=ATVPDKIKX0DER&asin=B0C7R9FG1C&program=COMMINGLING`

this is the path which i am calling.

**Comment by BansiFuletra** [comment]
@jlevers Kindly help me for this api.
