### ISSUE TITLE
No orders from today

### ISSUE THREAD

**Issue by zvone00** [jlevers/selling-partner-api#226]
When calling `getOrders` API from `VendorDirectFulfillmentOrdersApi`, there are no orders from today, despite I put `created_before` parameter in the future

**Comment by jlevers** [comment]
Could I please see your full code, and a screenshot of your application config page from Vendor Central?

Also, Vendor Central data is often delayed/laggy, so the issue may just be that up-to-date data isn't available yet.

**Comment by zvone00** [comment]
It seems that I sent too big an interval to the API (1 year). When I send short intervals, like one week, everything works well.
