### ISSUE TITLE
Fatal error instead 403 error exception

### ISSUE THREAD

**Issue by crazybee47** [jlevers/selling-partner-api#227]
I try to get ListingsRestrictions by seller without listings restrictions api access rights and SP-API returns error response:
![image](https://user-images.githubusercontent.com/32307323/159015058-c5fcee57-8845-46cb-8a90-7766a057573e.png)

And when you try deserialize response to `Model\ListingsRestrictions\Error[]` here: `vendor/jlevers/selling-partner-api/lib/Api/ListingsRestrictionsApi.php:294`, fatal error happens:
![image](https://user-images.githubusercontent.com/32307323/159015421-6e5ff28e-8c5f-4aa4-a15e-3ddada49808c.png)

**Comment by crazybee47** [comment]
It happens because $data is \stdClass, not array
![image](https://user-images.githubusercontent.com/32307323/159016523-fc0cfbd7-def2-4e1b-8a62-af6f8bdd55c8.png)

**Comment by jlevers** [comment]
Thanks for reporting -- this should be fixed in `v4.3.6`.
