### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by chanakaDe** [jlevers/selling-partner-api#229]
I'm using Laravel 5.8 and I'm getting the following error.

`[403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }`

The details are empty and cannot decide what is the issue. 

Here is my code:

```

    public function __construct()
    {

        $config = new Configuration([
            "lwaClientId" => "amzn1.application-oa2-client.axxxxxxxxxxxxxxxxxxxx",
            "lwaClientSecret" => "3853b97axxxxxxxxxxx1137adc0cc0cf3f2dxxxxxxxxxxx539",
            "lwaRefreshToken" => "Atzr|IwEBIGCNNvBZdCAGm1cZ3_7NYjU-7xFDZ4eY9GofEqpNZnS2FD5Es1aUyJZt0MLYowbg7JlipJZoKqgTCNk0Ex3WBmuks7QOJt-i40Pm7RXF63RAvHcQRjhgjhgjhgfjhfhjgfnwdISbZC9cdmFjDqmFihuSSJWBtmo5vCQCbX7S-J4gtmtcYE1IQFdZuf0NqNPeVNk63ryCpq_PfGt0_dBQOuBcXjMCKPcocKf9CW8EXeZK3HE74",
            "awsAccessKeyId" => "AKIAWXXXXXXJKIXXXX",
            "awsSecretAccessKey" => "/LdWkUqXXXXXXRREDSDz",
            "endpoint" => Endpoint::EU,
            "roleArn" => "arn:aws:iam::42294999999:role/NEW_ROLE_FOR_AMAZON_SC"
        ]);

        $apiInstance = new OrdersApi($config);
        $order_id = '303-444444-555555';
        $data_elements = array();
        try {
            $result = $apiInstance->getOrder($order_id, $data_elements);
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling OrdersApi->getOrder: ', $e->getMessage(), PHP_EOL;
        }
    }
```

I have changed the credentials for security reasons. 

And I followed this YouTube guide from Amazon and configured everything including a Role for access. (roleArn)

Can you please let me know what can be the issue here?

Thank you in advance.

**Comment by jlevers** [comment]
Could you please post a screenshot of your SP API application config page from Seller Central?

**Comment by chanakaDe** [comment]
<img width="599" alt="Screenshot 2022-03-22 at 16-44-55 Amazon" src="https://user-images.githubusercontent.com/7803591/159643303-72ee09ca-3874-43e5-97d3-152ba1c43653.png">

@jlevers  please check this. Thank you.

**Comment by jlevers** [comment]
Try removing the `$data_elements` parameter from the `getOrder` call.

**Comment by chanakaDe** [comment]
Hi @jlevers 

```
try {
            $result = $apiInstance->getOrder($order_id);
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling OrdersApi->getOrder: ', $e->getMessage(), PHP_EOL;
        }
```

This is the code without `$data_elements` and still the same issue as following: 

`[403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }`

Strange issues...

**Comment by chanakaDe** [comment]
@jlevers  And now I added 2 more new permissions / roles and still the same issue. 
Is there any way that I can see what is the error details? 

<img width="545" alt="Screenshot 2022-03-23 at 08-46-00 Amazon" src="https://user-images.githubusercontent.com/7803591/159649032-0dcc9464-998a-4907-b5ee-39181593c656.png">

**Comment by chanakaDe** [comment]
Hallo again, 

I did some R&D and I even changed the IAM ARN in seller account between USER ARN and also ROLE ARN.
Still the same issues. 

I'm adding my AWS ROLE and USER configuration here. Hope it will help you to see the issue. 

User configuration.
<img width="644" alt="USER" src="https://user-images.githubusercontent.com/7803591/159717519-38053071-b33c-4b9b-8db3-4a7d0d417cac.png">

Role configuration

<img width="919" alt="ROLE" src="https://user-images.githubusercontent.com/7803591/159717570-e36423ad-6ff5-4f36-a7d4-95b8452912af.png">

Thank you in advance.

**Comment by jlevers** [comment]
It's hard for me to do much more debugging of this issue here -- there are a lot of things that could be causing this problem. It's not an issue with this library, so I'm going to close the issue.

I recommend opening up a support case with Amazon, or if you'd like, we can set up a consult call. My email is `<myfirstname>@jesseevers.com`.
