### ISSUE TITLE
How to call getListingsItem

### ISSUE THREAD

**Issue by dangquanghai** [jlevers/selling-partner-api#232]
Dear jlevers,
Thank for you great library!
I call getlistingsItem as follow
 
```
//$included_data ='details';
  $included_data ='summaries';
  $listing  = new ListingsApi($this->config);
  $data = $listing->getListingsItem($seller_id, $sku, $marketplace_ids,null,$included_data);
   dd($data);
```   
The error like this
![image](https://user-images.githubusercontent.com/31786668/159829846-cc86b7e4-f702-4eda-8e81-6f90ce0fde40.png)

Turn on debug. It said
![image](https://user-images.githubusercontent.com/31786668/159829897-052e8bb1-98b4-467e-b899-3d403b61a17e.png)

For sure no problem from your library  Pls point me where I got problem?

Thank so much

**Comment by thugic** [comment]
It's already in the error message: the Seller ID is not valid

**Comment by dangquanghai** [comment]
Thank Thugic
