### ISSUE TITLE
listFinancialEvents pagination parameter:nextToken is invalid

### ISSUE THREAD

**Issue by suofiya** [jlevers/selling-partner-api#239]
I get the correct nextToken in the response data when calling the listFinancialEvents api.
When sending a next page request with the previous nextToken, I get error like this "Token is not valid, token duration is 3 minutes." 

After debug, I found the listFinancialEvents api take a long time before return the response, almost over 200s.
So I think this is the root cause.

Do you have some suggestion about this issue??

```
Exception when calling FinancesApi->listFinancialEvents: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Token is not valid, token duration is 3 minutes.",
      "details": ""
    }
  ]
}
```

**Comment by valigara** [comment]
@suofiya imho. its look like amazon side issue 
and looks like its similar to [issue](https://github.com/amzn/selling-partner-api-docs/issues/550) in amazon api github repository
also you may want to look on [related issues](https://github.com/amzn/selling-partner-api-docs/issues?q=is%3Aissue+listFinancialEvents) in amazon api github repository

p.s. 
>  almost over 200s

wow :)

**Comment by jlevers** [comment]
Yeah wow 200s is really, really long. There's not much to be done about it on my end -- I think this an issue to take up with Amazon. That's a ridiculously long time
