### ISSUE TITLE
Add support for role-based authentication using STS

### ISSUE THREAD

**Issue by jlevers** [jlevers/selling-partner-api#24]
The library only supports SP API apps that are set up with the non-standard (but simpler) IAM user-based authentication method. Lots of people set up their SP API applications with an IAM role, per Amazon's developer guide. This library should support the official authentication strategy, using STS to make an `AssumeRole` call.

**Comment by iLoveSarabear** [comment]
Is there a quick way around this? I'm unable to change the IAM ARN on the Seller Central Developer Console after I got my application approved.

Thanks!

-T

**Comment by xudongding** [comment]
> Is there a quick way around this? I'm unable to change the IAM ARN on the Seller Central Developer Console after I got my application approved.
> 
> Thanks!
> 
> -T

The IAM ARN cannot be modified once submitted. You should create a new application.

**Comment by jlevers** [comment]
As of `v2.20`, you can pass a role ARN to the `ConfigurationOptions` constructor to work with SP API applications created with a role ARN. See the [README](https://github.com/jlevers/selling-partner-api/blob/main/README.md#setup) for more details.
