### ISSUE TITLE
Please add GET_FBA_INVENTORY_PLANNING_DATA

### ISSUE THREAD

**Issue by suofiya** [jlevers/selling-partner-api#243]
Missing the report type:  GET_VENDOR_NET_PURE_PRODUCT_MARGIN_REPORT.
I saw it at : https://developer-docs.amazon.com/sp-api/docs/report-type-values#fulfillment-by-amazon-fba-reports

![image](https://user-images.githubusercontent.com/1456885/162947603-827488f9-6ef2-4558-9d5e-51fee37ab093.png)

**Comment by jlevers** [comment]
Added in `v4.3.9`.
