### ISSUE TITLE
Error with searchContentPublishRecords

### ISSUE THREAD

**Issue by OWLMicha** [jlevers/selling-partner-api#244]
When I try to query a result via [#searchContentPublishRecords](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/AplusContentApi.md#searchContentPublishRecords) I get the following error:

_Exception when calling AplusContentApi->searchContentPublishRecords: invalid length for $content_sub_type when calling PublishRecord., must be bigger than or equal to 1._

However, [$content_sub_type](https://developer-docs.amazon.com/sp-api/docs/selling-partner-api-for-a-content-management#postcontentdocumentapprovalsubmissionresponse**) is not a parameter that needs to be specified.

If I set the debug mode, the result is what I expect but it is not output in $result and only the error is output.

I hope you can help me.

Many thanks and best regards
Micha

**Comment by jlevers** [comment]
Should be fixed in `v4.3.10`.
