### ISSUE TITLE
SellersApi->getMarketplaceParticipations:"Access to requested resource is denied.", "code": "Unauthorized", "details"

### ISSUE THREAD

**Issue by pramodwagh** [jlevers/selling-partner-api#245]
Hello, @jlevers,
I got approval from Amazon for my application.
But when I calling the SellersApi->getMarketplaceParticipations, I am getting the below error.
[403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }
Can you please help me? Also attached is user permission.
![image](https://user-images.githubusercontent.com/10533044/163310969-42b28ee8-015f-4411-bea5-79d5a9cba1a5.png)

code:-

$config = new Configuration([
    "lwaClientId" => "",
    "lwaClientSecret" => "",
    "lwaRefreshToken" => "",
    "awsAccessKeyId" => "",
    "awsSecretAccessKey" => "",
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "endpoint" => Endpoint::EU
]);

$api = new Api\SellersApi($config);
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}

**Comment by jlevers** [comment]
Did you generate your refresh token after all those roles were approved? And did you submit your developer application from a European Seller Central URL? E.g. sellercentral.amazon.co.uk, sellercentral-europe.amazon.com, etc

**Comment by pramodwagh** [comment]
I have submitted it from https://sellercentral.amazon.in and also accessed data for India. Also, I have generated the refresh token. If I need to access all the region data, then should I need to submit from that region? Also, what should be the endpoint for India then? Thank you
![image](https://user-images.githubusercontent.com/10533044/163326620-3895d585-ce31-439c-a1c3-4e6b4cdde613.png)

**Comment by pramodwagh** [comment]
And also interesting thing is now I can get the Marketplace Participations using postman with the access token. 
![image](https://user-images.githubusercontent.com/10533044/163330031-685b0bdc-9992-421e-90d0-f3a14dad835f.png)
but not able to using library configuration, should I need to use access token instead of refresh token in the below config
$config = new Configuration([
"lwaClientId" => "",
"lwaClientSecret" => "",
"lwaRefreshToken" => "",
"awsAccessKeyId" => "",
"awsSecretAccessKey" => "",
"endpoint" => Endpoint::EU
]);

**Comment by pramodwagh** [comment]
Got the issue. It is related to the OAuth authorization URI. Closing the issue. Thanks @jlevers

**Comment by mujaffars** [comment]
@devpammy What OAuth URI needs to change? I am also facing the same issue. Can you give more details?
