### ISSUE TITLE
Parse error in version 4.3.10

### ISSUE THREAD

**Issue by valigara** [jlevers/selling-partner-api#246]
please look on my [comment](https://github.com/jlevers/selling-partner-api/issues/235#issuecomment-1100875482) in past issue,
fix that was applied in version 4.3.10 will cause `Parse error` if used php version will be  lower than 8.0

ive opened this issue cause i can't reopen previous issue, sorry for spam

**Comment by jlevers** [comment]
Thanks for pointing this out, I'm on PHP 8.1 so I failed to check for back compatibility. Give `v4.3.11` a try and let me know if it solves the issue.

**Comment by valigara** [comment]
Thanks, works like charm!

p.s.
8.1 -> envy :)
