### ISSUE TITLE
getOrderItems - You exceeded your quota for the requested resource.

### ISSUE THREAD

**Issue by sunil11475-dev** [jlevers/selling-partner-api#247]
Hi again,

Is there anyway make getOrderItems call in $data_elements because its totally frustrating to get all orders items details.

I putted my code live and then start getting this error -
`Exception when calling OrdersV0Api->getOrderDetail: [429] { "errors": [ { "message": "You exceeded your quota for the requested resource.", "code": "QuotaExceeded" } ] }`

It's only 59 orders. when i run for 2 or 5 orders its works perfectly.
```
		try {
			$itemdetails = $apiInstance->getOrderItems($order_id);
		} catch (Exception $e) {
			echo ' - Exception when calling OrdersV0Api->getOrderItems: ', $e->getMessage(), PHP_EOL;
		}
```

Can i use `sleep(1); ` but it may take long time to complete the one request.

Any suggestion will be great full. feel like came out from one well and fall into another one.

**Comment by jlevers** [comment]
If I set up the library to make the `getOrderItems` call internally, the same rate-limiting issue would come up...this is an issue that Amazon really needs to address, but there isn't much I can do about it. Unfortunately, there's no way around their rate limits. I totally feel you on how frustrating it is.

**Comment by sunil11475-dev** [comment]
@jlevers I understand your answer but if you keep my issue open then other may have some suggestion/comment on this issue they can provide.

Hope you understand.
