### ISSUE TITLE
Remove temporal files created by documents download

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#249]
Not really a bug but a small improvement.

Some linux distros only perform /tmp directory cleanup on server restart (that in a production environment can be months or even years).

When the library download reports with the postProcess flag set to true, a file will be left in /tmp directory if it was a csv or xlsx file, but the file is not used anymore after the initial process.

I will add a small PR to unlink the file after processing. If you are leaving this files with a purpose, please fill free to close this issue and the associated PR.

**Comment by jlevers** [comment]
Resolved in #250.
