### ISSUE TITLE
How to create a "manufacturer" (Maker of the product) item with Listings 

### ISSUE THREAD

**Issue by shirushi-dev** [jlevers/selling-partner-api#252]
I would like to know how to create a "manufacturer" (Maker of the product) item with Listings Api. 
The creation and editing of other items has already been completed.

I couldn't do it below

`
    $data = [    
        "product_type" => "PRODUCT",  
                "requirements" => "LISTING_OFFER_ONLY",  
                "attributes" => [  
                    "manufacturer" => [  
                        [  
                            "language_tag" => "ja_JP",  
                            "value" => "test_manufacturer",  
                            "marketplace_id" => "A1VC38T7YXB528",  
                        ],  
                    ],  
]
`

Responce
`
{
    "sku": "testsku",
    "status": "INVALID",
    "submissionId": "6d14ff886bf34f45bae820db37e3dd2a",
    "issues": [
        {
            "message": "The attributes are invalid.",
            "severity": "ERROR",
            "attributeNames": [
                "manufacturer"
            ]
        }
    ]
}
`

**Comment by jlevers** [comment]
Please take a closer look at the comment I linked to in the other issue you replied to: https://github.com/jlevers/selling-partner-api/issues/240#issuecomment-1100667172

**Comment by shirushi-dev** [comment]
@jlevers 

It turns out that it can't be updated with Listings Api.

It can be updated with FeedApi. Cannot update with Listings Api.
That's very inconvenient.

Thank you.
