### ISSUE TITLE
When requesting an inventory report, the quantity for FBA inventory is missing

### ISSUE THREAD

**Issue by fizzyduck** [jlevers/selling-partner-api#253]
When downloading a report using the document helper with the report type:

`ReportType::GET_MERCHANT_LISTINGS_DATA;`

any SKUs which are FBA have an unset quantity. SKUS which are fulfiled by merchant have quantities (including 0 where relevant).

I also note that when attempting to retrieve inventory data using:

`ReportType::GET_AFN_INVENTORY_DATA;`

the response is:

```
[403] {
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}
```

so is this simply a permissions issue?

The application was registered with "Inventory and Order Tracking" ticked but not "Amazon Fulfilment". "Amazon Fulfilment" was subsequently ticked by editing the application registration.

**Comment by jlevers** [comment]
Ah I see that you added the Amazon Fulfillment after you created the app. Did you generate a new refresh token after adding the new role?

**Comment by fizzyduck** [comment]
@jlevers Thanks for getting back to me.

I didn't generate a new refresh token - this was the problem.
