### ISSUE TITLE
Orders API - Get Order Items - Invalid Value for deemed_reseller_category 

### ISSUE THREAD

**Issue by alexmillman2394** [jlevers/selling-partner-api#254]
Hello,

I am using version ^4.0 and I receive this error when trying to grab order items by ID

Invalid value 'CA_MPF' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS', 'GB_VOEC'

In Order/OrderItem

```
const DEEMED_RESELLER_CATEGORY_IOSS = 'IOSS';
const DEEMED_RESELLER_CATEGORY_UOSS = 'UOSS';
const DEEMED_RESELLER_CATEGORY_GB_VOEC = 'GB_VOEC';
```

seem to be the only valid ones. Nothing for "CA_MPF". I'm not really familiar with what these specific values mean, but is this able to be added as a valid value?

**Comment by jlevers** [comment]
Hmm, that's strange -- the most recent version of the library allows more valid values than that:

https://github.com/jlevers/selling-partner-api/blob/9956d9c90f0ca495389f409369e6a73c472dbb9b/lib/Model/Orders/OrderItem.php#L336-L345

Can you run `composer update` and see if you still have this problem?

**Comment by jlevers** [comment]
Since I haven't heard from you, I'm going to assume you resolved your problem. Please feel free to reopen this if you're still having issues!
