### ISSUE TITLE
Help: How to create a new product with no ASIN through the api

### ISSUE THREAD

**Issue by mustaphatg** [jlevers/selling-partner-api#256]
Thanks for the amazing client library.

I carefully implemented all the steps :
1. Create feed document 
2. Upload feed data
3. Create feed

This is sample of my xml:
`<?xml version="1.0" encoding="iso-8859-1"?>
<AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
	<Header>
		<DocumentVersion>1.01</DocumentVersion>
		<MerchantIdentifier>A1Y6E4N414T8K1</MerchantIdentifier>
	</Header>
	<MessageType>Product</MessageType>
	<PurgeAndReplace>false</PurgeAndReplace>
	<Message>
		<MessageID>1</MessageID>
		<OperationType>Update</OperationType>
		<Product>
			<SKU>655255983068</SKU>
			<ProductTaxCode>A_GEN_NOTAX</ProductTaxCode>
			<DescriptionData>
				<Title>Example Product Title</Title>
				<Brand>Example Product Brand</Brand>
				<Description>This is an example product description.</Description>
				<BulletPoint>Example Bullet Point 1</BulletPoint>
				<BulletPoint>Example Bullet Point 2</BulletPoint>
				<MSRP currency="USD">25.19</MSRP>
				<Manufacturer>Example Product Manufacturer</Manufacturer>
				<ItemType>example-item-type</ItemType>
			</DescriptionData>
			<ProductData>
				<Computers>
					<ProductType>
						<Motherboard></Motherboard>
					</ProductType>
				</Computers>
			</ProductData>
		</Product>
	</Message>
</AmazonEnvelope>`

It all went successfully without error. 
But I got an error in the result documents.

> SKU Xxx Xxx, Missing Attributes product_type. SKU XXXXXX does not match any ASINs. Make sure that all 
standard product ids (such as UPC, ISBN, EAN, or JAN codes) are correct. To create a new ASIN, include the following attributes: 
product_type. Feed ID: 0. For more troubleshooting help, see http://sellercentral.amazon.co.uk/gp/errorcode/200692370

I have searched various forum but could not get it to work.

Thanks in advance @jlevers , @0xSekar

**Comment by jlevers** [comment]
To create a new ASIN using a feed, I believe you need to use the `POST_PRODUCT_DATA` feed type. The XSD for that feed type is here: https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Product.xsd

**Comment by jlevers** [comment]
Since I haven't heard back from you on this, I'm going to assume you figured out the issue. If not, feel free to reopen it.
