### ISSUE TITLE
Failure of SKUs containing special characters

### ISSUE THREAD

**Issue by shirushi-dev** [jlevers/selling-partner-api#257]
I am using ListingsApi to retrieve product information. 
However, it fails to retrieve the information for SKUs that contain special characters. 
How can I deal with these?

Of course, other SKUs return "success".

Example )

sku : 'test-M＆L';

```
   SellingPartnerApi\ApiException 

  [404] {
  "errors": [
    {
      "code": "NOT_FOUND",
      "message": "SKU \u0027test-M%EF%BC%86L\u0027 not found in marketplace A1VC38T7YXB528"
    }
  ]
```

**Comment by shirushi-dev** [comment]
This seems to be an error because it contains a capital "&". 
Is there any way to resolve this?

**Comment by jlevers** [comment]
This appears to be resolved according to https://github.com/amzn/selling-partner-api-docs/issues/2224, as of a few days ago -- are you still running into this issue?

**Comment by jlevers** [comment]
Since I haven't heard from you, I'm going to close this. Please reopen it if you still need help.
