### ISSUE TITLE
PII data retrieval

### ISSUE THREAD

**Issue by discover59** [jlevers/selling-partner-api#260]
Recently SP API announced [this](https://developer-docs.amazon.com/sp-api/changelog/important-notice-discontinued-support-lwa-tokens-can-no-longer-retrieve-pii-in-selling-partner-api).

Does latest version handle it?

@jlevers Please let me know if it's already developed or in progress.

**Comment by jlevers** [comment]
Yes, this library automatically generates restricted data tokens for calls that require them. See [this section](https://github.com/jlevers/selling-partner-api#restricted-operations) of the README.
