### ISSUE TITLE
receiving Invalid Input when using createReport

### ISSUE THREAD

**Issue by hashhesh** [jlevers/selling-partner-api#263]
Hi all

I am trying to create a report but I always get Invalid Input below is my code 

```php
   $config = new Configuration([
        "lwaClientId" => $account_data['lwa_client_id'],
        "lwaClientSecret" => $account_data['lwa_client_secret'],
        "lwaRefreshToken" => $account_data['lwa_refresh_token'],
        "awsAccessKeyId" => $account_data['aws_access_key'],
        "awsSecretAccessKey" => $account_data['aws_secret_key'],
        "endpoint" => SellingPartnerApi\Endpoint::NA ,
    ]);

    $apiInstance = new SellingPartnerApi\Api\ReportsApi($config);

    $body = new SellingPartnerApi\Model\Reports\CreateReportSpecification([
                'marketplace_ids' => [$merchant_data['marketplace_ids']], 
                'report_type' => ReportType::GET_MERCHANT_LISTINGS_ALL_DATA['name'],
    ]);

    try{
        $report_id = $apiInstance->createReport($body);
       }catch(Exception $e){
        return array("message"=>$e->getMessage(),'success'=>false);
    }
```

and this is the response:
```json
{
    "notifications": [],
    "text": "{\"message\":\"[400] [{\\\"code\\\":\\\"InvalidInput\\\",\\\"message\\\":\\\"Could not match input arguments\\\"}]\",\"success\":false}"
}
```

Could you please advise what's went wrong? because i got confused because everything seems ok for me but I believe there is something beyond my insight. 

Thanks in advance

**Comment by jlevers** [comment]
If you check out the documentation [here](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/Reports/CreateReportSpecification.md), you'll see that there are more parameters. You need to pass the `data_start_time` parameter in ISO 8601 format.

**Comment by hashhesh** [comment]
Hi @jlevers 
Appreciated your reply and thanks for your time.

Yes, but as i understood data_start_time & data_end_time & report_options are all optional params. Anyway, I have passed them 
```php
    $apiInstance = new SellingPartnerApi\Api\ReportsApi($config);

    $body = new SellingPartnerApi\Model\Reports\CreateReportSpecification([
                'marketplace_ids' => (array) $merchant_data['marketplace_ids'],
                'report_type' =>  ReportType::GET_MERCHANT_LISTINGS_DATA['name'],
                'data_start_time' => date_create('17 Oct 2021')->format( 'c'),
                'data_end_time' => date_create('5 May 2022')->format('c'),
                'report_options' => (object)"custom:true"
    ]);

    try{
        $report_id = $apiInstance->createReport($body);
          // something todo with report_id below
           //......
        }catch(Exception $e){
        return array("message"=>$e->getMessage(),'success'=>false);
    }
```
even with above code I am still receiving the same error 
```
{"message":"[400] [{\"code\":\"InvalidInput\",\"message\":\"Could not match input arguments\"}]","success":false}
```
Does my steps are clear and correct for generating a report?
Could you please help me?
Thanks in advance

**Comment by hashhesh** [comment]
> Hi @jlevers Appreciated your reply and thanks for your time.
> 
> Yes, but as i understood data_start_time & data_end_time & report_options are all optional params. Anyway, I have passed them
> 
> ```
>     $apiInstance = new SellingPartnerApi\Api\ReportsApi($config);
> 
>     $body = new SellingPartnerApi\Model\Reports\CreateReportSpecification([
>                 'marketplace_ids' => (array) $merchant_data['marketplace_ids'],
>                 'report_type' =>  ReportType::GET_MERCHANT_LISTINGS_DATA['name'],
>                 'data_start_time' => date_create('17 Oct 2021')->format( 'c'),
>                 'data_end_time' => date_create('5 May 2022')->format('c'),
>                 'report_options' => (object)"custom:true"
>     ]);
> 
>     try{
>         $report_id = $apiInstance->createReport($body);
>           // something todo with report_id below
>            //......
>         }catch(Exception $e){
>         return array("message"=>$e->getMessage(),'success'=>false);
>     }
> ```
> 
> even with above code I am still receiving the same error
> 
> ```
> {"message":"[400] [{\"code\":\"InvalidInput\",\"message\":\"Could not match input arguments\"}]","success":false}
> ```
> 
> Does my steps are clear and correct for generating a report? Could you please help me? Thanks in advance

Hi @jlevers 
I have found the reason that cause this error, it's because i was using amazon sandbox endpoint once I change to Live endpoint it works fine.

Thanks dear

**Comment by hypogealgaol** [comment]
Should the sandbox really return Invalid Input here? This is an issue with a couple different sandbox endpoints. Are they unimplemented ?
