### ISSUE TITLE
Error on FeesAPI->getMyFeesEstimateForASIN(): "Missing objects [PriceToEstimateFees] in body parameters." 

### ISSUE THREAD

**Issue by hyperothen** [jlevers/selling-partner-api#264]
Hey there,

maybe it is my fault as I am not quite experienced with using an API using PHP but using the function SellingPartnerApi\Api\FeesApi->getMyFeesEstimateForASIN() I get following error message:

Exception when calling FeesApi->getMyFeesEstimateForASIN: [400] { "errors": [ { "code": "InvalidInput", "message": "This is an invalid input", "details": "Missing objects [PriceToEstimateFees] in body parameters." } ] }

Since I tried simply everything and worked myself through the whole FeesAPI documentation, I'd like to share my code:

```php
$apiInstance = new SellingPartnerApi\Api\FeesApi($config);
$asin = '[...]';

$listingPrice = new \SellingPartnerApi\Model\Fees\MoneyType(array(
   'currency_code' => 'EUR',
   'amount' => 5.96)
);

$price = new \SellingPartnerApi\Model\Fees\PriceToEstimateFees(array(
      'listing_price' => $listingPrice
   )
);

$body = new \SellingPartnerApi\Model\Fees\GetMyFeesEstimateRequest(
   array('A1PA6795UKMFR9'),
   true,
   $price,
   '[...]'
);

try {
    $result = $apiInstance->getMyFeesEstimateForASIN($asin, $body);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling FeesApi->getMyFeesEstimateForASIN: ', $e->getMessage(), PHP_EOL;
}
```

The $config is alright as I used it with another example which is working.

I'm looking forward to hearing from you guys!

**Comment by hyperothen** [comment]
maybe additionally interesting:

$price->__toString returns:
{ "ListingPrice": { "CurrencyCode": "EUR", "Amount": 5.96 } }

$price->valid() returns:
1

**Comment by jlevers** [comment]
The array passed to the `GetMyFeesEstimateRequest` constructor (and every other model constructor) needs to be a list of key-value pairs, not a numerically indexed array.

Based on the docs [here](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/Fees/GetMyFeesEstimateRequest.md), `GetMyFeesEstimateRequest` has a single attribute `fees_estimate_request`, which should be set to an instance of `SellingPartnerApi\Model\Fees\FeesEstimateRequest`, whose attributes are documented [here](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/Fees/FeesEstimateRequest.md).

**Comment by hyperothen** [comment]
Hello there, thank you Jesse, this helped.

Having edited the code, now I use:

`$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "amzn1.applicati[...]",
    "lwaClientSecret" => "63f03b7[...]",
    "lwaRefreshToken" => "Atzr|IwEBIDMLYyp[...]",
    "awsAccessKeyId" => "[...]",
    "awsSecretAccessKey" => "[...]",
    "endpoint" => SellingPartnerApi\Endpoint::EU,
]);
$config->setDebug(true);
// To redirect debug info to a file:
$config->setDebugFile('debug.log');

$apiInstance = new SellingPartnerApi\Api\FeesApi($config);
$asin = '[...]'; // string | The Amazon Standard Identification Number (ASIN) of the item.

$listingPrice = new \SellingPartnerApi\Model\Fees\MoneyType(array(
   'currency_code' => 'EUR',
   'amount' => 5.96)
);

$price = new \SellingPartnerApi\Model\Fees\PriceToEstimateFees(array(
      'listing_price' => $listingPrice
   )
);

$feesEstimateRequest = new \SellingPartnerApi\Model\Fees\FeesEstimateRequest(array(
   'marketplace_id' => array('A1PA6795UKMFR9'), // Germany
   'is_amazon_fulfilled' => true,
   'price_to_estimate_fees' => $price,
   'identifier' => '[...]'
));

$body = new \SellingPartnerApi\Model\Fees\GetMyFeesEstimateRequest(array('fees_estimate_request' => $feesEstimateRequest));


try {
    $result = $apiInstance->getMyFeesEstimateForASIN($asin, $body);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling FeesApi->getMyFeesEstimateForASIN: ', $e->getMessage(), PHP_EOL;
}`


Which leads to following error message:

Exception when calling FeesApi->getMyFeesEstimateForASIN: [500] { "errors": [ { "code": "InternalFailure", "message": "We encountered an internal error. Please try again.", "details": "" } ] }

Am I missing something else?

**Comment by jlevers** [comment]
I don't see any immediate issues there. Since you're getting a 500 error back, that's an Amazon issue, not something having to do with your request -- I recommend you open a support case with them.

**Comment by saurabhk-gupta** [comment]
Above code is working for me. I just pass the marketplace id as string instead of array:

`
$feesEstimateRequest = new \SellingPartnerApi\Model\Fees\FeesEstimateRequest(array(
   'marketplace_id' => 'A1PA6795UKMFR9', // Germany
   'is_amazon_fulfilled' => true,
   'price_to_estimate_fees' => $price,
   'identifier' => '[...]'
));
`
