### ISSUE TITLE
Update fixed price and Quantity of the product

### ISSUE THREAD

**Issue by vijaykhollam** [jlevers/selling-partner-api#266]
Can we update fixed price and Quantity of the product using this library? If yes how?

Which SP API We can use for the same?

**Comment by jlevers** [comment]
You can do that by either creating and uploading a [`POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA`](https://developer-docs.amazon.com/sp-api/docs/feed-type-values#listings-feeds) feed, or calling the `patchListingsItem` endpoint (use case guide [here](https://developer-docs.amazon.com/sp-api/docs/listings-items-api-v2021-08-01-use-case-guide#step-1-submit-listings-item-patch-request), example of use with this library [here](https://github.com/jlevers/selling-partner-api/issues/240#issuecomment-1100667172)).
