### ISSUE TITLE
AFN orders are not available via getOrders()

### ISSUE THREAD

**Issue by chanakaDe** [jlevers/selling-partner-api#267]
Hi, 

I'm only getting 'MFN' orders via the '/orders/v0/orders' endpoint. 
But I'm sending parameters for both. 
`$fulfillment_channels = array('AFN','MFN');`

And here is my permissions list. And also I got a new refresh token and everything seems to be fine. 

![Screenshot 2022-05-03 at 10-06-53 Amazon](https://user-images.githubusercontent.com/7803591/166422512-69f7fe1d-774d-4df3-b4f2-8ac4783bd6e0.png)

What can be the issue here?

**Comment by jlevers** [comment]
What happens if you only pass `'AFN'`?

**Comment by chanakaDe** [comment]
Hi @jlevers 
Now I can see them. 
But shipping address, buyer information are NULL. 

<img width="325" alt="Screenshot 2022-05-17 at 10-19-28 Screenshot" src="https://user-images.githubusercontent.com/7803591/168764928-d45e8b85-f449-4788-ad4b-f84ca6f3b3b1.png">

**Comment by chanakaDe** [comment]
@jlevers 
I checked more.
I used `/orders/v0/orders/{orderId}/address` and `/orders/v0/orders/{orderId}/buyerInfo` and still the values are null. 
Can this be an issue with the API?

**Comment by jlevers** [comment]
Are you passing the `$data_elements` parameter as described in the README, [here](https://github.com/jlevers/selling-partner-api/blob/main/README.md#restricted-operations) (and in the Amazon docs [here](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#tutorial-get-authorization-to-access-pii-for-bulk-orders))?

**Comment by jlevers** [comment]
Also, I wouldn't expect you to see addresses for AFN orders, since Amazon's handling the fulfillment for you.

**Comment by kpconnell** [comment]
Just a couple of additional comments, you definitely do not get full address details with FBA orders, and you will not get full address even for merchant fulfilled unless you are approved for PII access, even if you get an RDT successfully.  Amazon philosophically does not believe sellers should be using customer address for *anything* except printing a shipping label, and if you're not approved for PII as a developer, the only way to get the merch fulfilled address is through seller central.

**Comment by chanakaDe** [comment]
@kpconnell  
Thanks for the information. i got the approval for PII access for both seller and vendor portals. And I get PII in MFN orders. 
And in the Aamazon FBA documentation, it says we are getting full data object. 

@jlevers 
Thanks for the update too. 
Yeah I'm passing the '$data_elements' as mentioned in the documentation and I did everything possible. 
And I think Restricted Data Token (RDT)  is also automatically generated by this library for restricted methods. 
And in the Aamazon FBA documentation, it says we are getting full data object.  This is why I need to find a real solution for this. In Germany, due to some tax and legal cases, it's better to have customer address and information. 

And also you closed my other issue, so I will add some update here for the case no https://github.com/jlevers/selling-partner-api/issues/276. 

![Screenshot 2022-05-31 at 08-17-53 RE CASE 7774237362 API Services Cannot see all information in purchaseOrders - c desilva@starmobile de - starmobile de Mail](https://user-images.githubusercontent.com/7803591/171106313-5fea6463-d771-45fa-8795-36818c44bd49.png)

https://developer-docs.amazon.com/sp-api/docs/vendor-retail-procurement-apis-v1-use-case-guide#country-specific-business-requirements

Amazon support says we are supposed to get all information too. That's little confusing.
