### ISSUE TITLE
Redefinition of constant causing runtime error

### ISSUE THREAD

**Issue by fizzyduck** [jlevers/selling-partner-api#270]
https://github.com/jlevers/selling-partner-api/blob/9956d9c90f0ca495389f409369e6a73c472dbb9b/lib/Model/FbaOutbound/CurrentStatus.php#L46

https://github.com/jlevers/selling-partner-api/blob/9956d9c90f0ca495389f409369e6a73c472dbb9b/lib/Model/FbaOutbound/CurrentStatus.php#L56

Please see constant `OUT_FOR_DELIVERY` which is defined twice.

**Comment by fizzyduck** [comment]
The same goes for `DELIVERY_ATTEMPTED`.

**Comment by jlevers** [comment]
This should be fixed in `v5.0.0`. Give it a try and let me know if you're still having issues!
