### ISSUE TITLE
Get Report request delaying in processing time using While loop, is that ok to use?

### ISSUE THREAD

**Issue by sunil11475-dev** [jlevers/selling-partner-api#271]
I am doing report request for get order GET_ORDER_REPORT_DATA_SHIPPING. Its some time take 10sec or 20 sec. I am using `WHILE LOOP` to wait to complete the process. 

Is that ok or if anyone have anther solution rather then making call `getReport` every 10sec to check process `status`?

```
			//CREATE AND GET REPORT ID--------------------------------------------
				$reportId = $this->createreport($apiInstance, $fetch_time, $reportType['name'], $returnResult);
				if($reportId){
					$getreport = $this->getReport($apiInstance, $reportId);
				}else{
					echo "\n createreport function not have report id\n";
				}
			//IF REPORT ID GET DOCUMENT ID--------------------------------------
				while (in_array($getreport['processing_status'], ['IN_PROGRESS', 'IN_QUEUE'])) {
					sleep(10);
					$getreport = $this->getReport($apiInstance, $reportId);
				}
			//GET REPORT DOCUMENT----------------------------------------------------
				if ($getreport['processing_status'] !== 'DONE') {
					echo "\n getreport status is ".$getreport['processing_status']."\n";
					return false;
				}else{
					$documentid = $getreport['report_document_id'];
					if($documentid){
						$ReportArray = $this->getReportDocument($apiInstance, $documentid, $reportType);
					}
				}
```
For testing with 1 or 2 orders works fine but if i put live which it will get 100 - 200 orders, may be it will take longer time in processing status.

**Comment by jlevers** [comment]
You can use the [Notifications API](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-reference) (use case guide [here](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide)) to get notified when a report finishes generating.

Other than that, polling is the best option.
