### ISSUE TITLE
How can I request full invoice and shipment details?

### ISSUE THREAD

**Issue by Johnny99211** [jlevers/selling-partner-api#273]
I need some help! I've requested all roles within the developer registration and created a new app. After setting everything up, I've used getOrders to get all available orders. Somehow the shipping address and buyer info is a strange Amazon email and not the email or even the name of the buyer.

Am I doing something wrong? :(

**Comment by misterakko** [comment]
You did perfectly and the answer you received is par for the course. Amazon will not let you fetch customers' data, though, in a misguided attempt to stay on the safe side of GDPR and other legislation protecting consumers' data.

**Comment by Johnny99211** [comment]
But I've received all roles, also the extended one! Therefore I expect that I can receive the data?
