### ISSUE TITLE
How to call restricted (PII) data with RDT tokens?

### ISSUE THREAD

**Issue by Johnny99211** [jlevers/selling-partner-api#275]
Within the last days I was able to find out, that I need to do 3 things to request PII restricted data from Amazon:

- Request extended developer rights (done)
- Add extended rights to my application (done)
- Request RDT token within the API (done)

I wrote myself a small abstract PHP class to init a new client:

```
/**
 * Init the Amazon orders gateway
 *
 * @param string $restricted_resource
 */
public function init_client( string $restricted_resource = '' ): void {
	$lwaClientId        = Constants::get_constant( 'COLLMAZON_LWA_CLIENT_ID' );
	$lwaClientSecret    = Constants::get_constant( 'COLLMAZON_LWA_CLIENT_SECRET' );
	$lwaRefreshToken    = Constants::get_constant( 'COLLMAZON_LWA_REFRESH_TOKEN' );
	$awsAccessKeyId     = Constants::get_constant( 'COLLMAZON_AWS_ACCESS_KEY_ID' );
	$awsSecretAccessKey = Constants::get_constant( 'COLLMAZON_AWS_SECRET_ACCESS_KEY' );
	if ( ! empty( $this->marketplace_id ) && ! empty( $lwaClientId ) && ! empty( $lwaClientSecret ) && ! empty( $lwaRefreshToken ) && ! empty( $awsAccessKeyId ) && ! empty( $awsSecretAccessKey ) ) {
		try {
			$api_config = new Configuration( [
				'lwaClientId'        => $lwaClientId,
				'lwaClientSecret'    => $lwaClientSecret,
				'lwaRefreshToken'    => $lwaRefreshToken,
				'awsAccessKeyId'     => $awsAccessKeyId,
				'awsSecretAccessKey' => $awsSecretAccessKey,
				'endpoint'           => Endpoint::EU
			] );
			if ( ! empty( $restricted_resource ) ) {
				$tokens_api                    = new TokensApi( $api_config );
				$restricted_data_token_request = new CreateRestrictedDataTokenRequest( [
					'target_application'   => 'CollmAzon',
					'restricted_resources' => [ $restricted_resource ]
				] );
				$response = $tokens_api->createRestrictedDataToken( $restricted_data_token_request );
				$api_config->setLwaRefreshToken( $response->getRestrictedDataToken() );
			}
			$this->orders_api = new OrdersApi( $api_config );
		} catch ( Exception $e ) {
			/** @noinspection ForgottenDebugOutputInspection */
			error_log( 'CollmAzon Amazon orders gateway configuration error: ' . $e->getMessage() );
		}
	}
}
```

Now I've requested all orders without the RDA. After receiving all the orders, I'm looping over them to get the Amazon order id. With this ID I've requested the buyer infos by using the RDA as token:

```
/**
 * Returns the order buyer info from an order
 *
 * @param string $amazon_order_id
 *
 * @return OrderBuyerInfo|false
 */
public function get_order_buyer_info( string $amazon_order_id ) {
	try {
		$this->init_client( 'buyerInfo' );
		$result = $this->orders_api->getOrderBuyerInfo( $amazon_order_id );
		if ( empty( $result->getErrors() ) && $result->getPayload() !== null ) {
			return $result->getPayload();
		}
		return false;
	} catch ( Exception $e ) {
		/** @noinspection ForgottenDebugOutputInspection */
		error_log( 'CollmAzon can not request order buyer info: ' . $e->getMessage() );
		return false;
	}
}
```

Sadly, the response is completely empfy:

```
[16-May-2022 08:05:22 UTC] SellingPartnerApi\Model\Orders\OrderBuyerInfo Object
(
    [container:protected] => Array
        (
            [amazon_order_id] => 304-9090305-7962734
            [buyer_email] => 
            [buyer_name] => 
            [buyer_county] => 
            [buyer_tax_info] => 
            [purchase_order_number] => 
        )

)
```

I also can not find any useful documentation here describing this process.

**Comment by jlevers** [comment]
Hi Johnny,

Did you try passing in the `$data_elements` parameter to `getOrders`, per the documentation in the [README](https://github.com/jlevers/selling-partner-api#restricted-operations)? That should prevent you from needing to call the Tokens API manually. Also, did you generate a new refresh token after getting PII access?

**Comment by HeBuguM** [comment]
I've been using this and it returns both the address and buyer's info without extra requests.
getOrders([
      'last_updated_after' => ...
      "data_elements" => ['shippingAddress','buyerInfo']
  ])

**Comment by Johnny99211** [comment]
Hi! 

thanks for your help! This works. I did it way to complicated. But one thing: I still don't get any invoice / billing address data within the buyerInfo model?

**Comment by HeBuguM** [comment]
Hm, why is that? Amazon generates an invoice for each order, your customer can download it from the order page.

**Comment by Johnny99211** [comment]
Our products require special invoicing, including some important information :/ But if it's not possible, we may need to use the shipping address as invoice address.

**Comment by jlevers** [comment]
I'm going to close this, as it seems this is not an issue with the library. Feel free to continue discussing here if you want.
