### ISSUE TITLE
Vendor Account, cannot get full address in getPurchaseOrder

### ISSUE THREAD

**Issue by chanakaDe** [jlevers/selling-partner-api#276]
Hi, 

I have a Vendor account and I can use getPurchaseOrder() and also getPurchaseOrders().
But in both cases, I cannot get full addresses. 

![Screenshot 2022-05-16 at 12-44-40 Screenshot](https://user-images.githubusercontent.com/7803591/168576576-de04f5f1-6e91-4bd5-b11f-f5ee0ad73ccf.png)

This is all I can see. 

I'm sending $include_details = true also. 

What is the issue here?

**Comment by jlevers** [comment]
Are you approved for access to the `Direct-to-Consumer Shipping` role on your developer profile in Vendor Central?

**Comment by chanakaDe** [comment]
@jlevers 
I think we don't need `Direct-to-Consumer Delivery (Restricted)` permission because I'm trying to get Amazon Vendor Purchase Orders and we only send these to Amazon warehouses. For example WRO5 is Okmiany, Poland Amazon warehouse. So I think we do not need `Direct-to-Consumer Delivery` permission for this. 

![Screenshot 2022-05-17 at 08-31-08 Amazon](https://user-images.githubusercontent.com/7803591/168744665-a2f523b1-1d96-4616-b46e-9e80cf468bf0.png)

But I will check more about this. I think we need `Direct-to-Consumer Delivery` permission for `SellingPartnerApi\VendorDirectFulfillmentOrdersV1Api` this endpoint. 

Thank you.

**Comment by chanakaDe** [comment]
@jlevers 
And also I noticed that we don't have order item names too. 
Is that normal to have only amazon_product_identifier, vendor_product_identifier without item name? 

![Screenshot 2022-05-17 at 08-19-29 Screenshot](https://user-images.githubusercontent.com/7803591/168745704-18451624-a41e-4b9d-b75f-c26a5a67438f.png)

**Comment by jlevers** [comment]
I'm not sure -- I haven't worked with the Vendor side APIs enough to say. I'm trying to figure out if the `dataElements` stuff that I mentioned in your other issue (https://github.com/jlevers/selling-partner-api/issues/267#issuecomment-1141438900) is relevant with the Vendors calls. I haven't seen that documented anywhere, but it's definitely possible.

**Comment by jlevers** [comment]
According to Amazon's docs [here](https://developer-docs.amazon.com/sp-api/docs/vendor-orders-api-v1-reference#orderitem), there aren't any additional order details you should be getting other than the ones you're seeing.

Looks like the lack of address/tax info information is a bug, according to this issue in the main docs repository: https://github.com/amzn/selling-partner-api-docs/issues/709

I'm going to close this, since neither of those problems are things I can solve. Sorry you're running into this!

**Comment by CreateWithCoding** [comment]
@chanakaDe @jlevers  What you do is cross reference the Ship To Party CODES (IDs) to Amazon's fulfillment center addresses like I'm doing below in the screenshot ...

let me know if you require the link to download that. 

![image](https://user-images.githubusercontent.com/4888901/172370560-5d93f87c-f3d2-4cca-b5b3-8638e9b6a238.png)

**Comment by MktpStar** [comment]
@CreateWithCoding 
Hi Jeff,
would you mind giving me that link also?
thank you!


I'm having the same issue - can anyone share how did you overcome this?
Thanks
