### ISSUE TITLE
'SellingPartnerApi\Api\TokensApi' not found in ***/lib/Authentication.php

### ISSUE THREAD

**Issue by HeBuguM** [jlevers/selling-partner-api#277]
Thanks for releasing 5.0.0!

This is the only issue I've been getting since the update:
lib/Authentication.php is looking for the old name of the API -> **TokensAPI** instead of **TokensV20210301Api**

I fixed it in my project but you might want to fix it as it's required for getting orders.

**Comment by jlevers** [comment]
Thanks for the catch -- should be fixed in `v5.0.1`.
