### ISSUE TITLE
How to get order wise Shipping information

### ISSUE THREAD

**Issue by pramodwagh** [jlevers/selling-partner-api#279]
Hello, @jlevers, 
Is there any API to get Shipment Information( like Shipment Id, and status) using order_id?

**Comment by pramodwagh** [comment]
Hi, I checked this API but only able retrieved shipping charges and shipping tax. @jlevers how can i get shipping id in order details or any other API where i need to pass order id, it returns ne shipment id. So I can use this shipment id to call getshipment API. 
Also thanks for quick response.

**Comment by jlevers** [comment]
Not sure, I've never tried to retrieve the shipping id. You'll need to do your own research on that one.
