### ISSUE TITLE
Feature Request: Add Iterator and __get/__set support

### ISSUE THREAD

**Issue by hiryuu42** [jlevers/selling-partner-api#280]
Hello,

This is a great implementation of the SP-API, so thank you for your hard work. The next time you generate the Model files, could you add a couple access methods we had in the old XML library?

     class ModelArray implements \IteratorAggregate {

    // This allows you to foreach() over all of the attributes as Amazon names them
    public function getIterator() {
        return (function () {
            foreach($this->container as $key => $value) {
                yield $this::$attributeMap[$key] => $value;
            }
        }) ();
    }

    // This allows you to get an attribute as $object->AttributeName
    public function __get($propertyName)
    {
       $getter = "get$propertyName";
       return $this->$getter();
    }

    // This allows you to set an attribute as $object->AttributeName
    public function __set($propertyName, $propertyValue)
    {
       $setter = "set$propertyName";
       $this->$setter($propertyValue);
       return $this;
    }
    }

Thank you!

**Comment by jlevers** [comment]
Good call -- added in `v5.2.0`.
