### ISSUE TITLE
The security token is invalid

### ISSUE THREAD

**Issue by misterakko** [jlevers/selling-partner-api#282]
I had not touched my code based on jlevers/selling-partner-api for months, as most of our customers are still using the old MWS codebase — due do Amazon's boneheadedness in handling PIIs — so I was a bit surprised when, on trying it, I noticed that practically every call I make is now answered with
{ "errors": [ { "message": "The security token included in the request is invalid.", "code": "InvalidInput" } ] } 
It used to work fine, recently.

I thought that it might depend on the recent switch to v4 of the library, so I upgraded and refreshed my code to use v5.0.1, but I still get the same result.

My authorisations as a developer must be in order, since the MWS calls work as always... I'm really stumped, if anyone has any suggestion I'll be very grateful

Sample code
```
<?php
    	include_once 'sar-el_core.inc.php';
    	$db = new DB_Sarel;
		use SellingPartnerApi\Api\SellersV1Api as SellersApi;
		// Load config from DB
    	include_once 'SPAPI/amazon.inc.php';
    	$a = new SaratAmazon($db);

		$api = new SellersApi($a->myConfig);
		$result = $api->getMarketplaceParticipations()->getPayload();
```

Code in testing environment: https://dev.accomazzi.net/sarat/akko.php

**Comment by jlevers** [comment]
What does your config object look like?

**Comment by jlevers** [comment]
I updated your comment to redact your actual credentials -- please do not post those publicly, as they make it possible for anyone to make calls to your application.

Are you using a IAM user ARN or an IAM role ARN in your SP API application? Also, have you tried generating a new refresh tokeN?

**Comment by misterakko** [comment]
User, and, yes, you're right, I had to renew the token. I didn't remember it had an expiration date. Thanks! I swear that if I'll ever be able to put this code into production I'll contribute.

**Comment by jlevers** [comment]
It shouldn't expire, but if you change ARNs or add/remove roles, you'll have to regenerate a new token for those changes to go into effect.
