### ISSUE TITLE
New version of Catalog Items API

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#284]
In the **May 2022 SP-API Release Announcement**, Amazon has given support for batch requests in catalogue search API

https://github.com/amzn/selling-partner-api-docs/discussions/2289

**Comment by jlevers** [comment]
Yep, will be adding this relatively soon. Thanks for flaggin.

**Comment by kpconnell** [comment]
bump on this one, relatively critical for our use cases.

**Comment by jlevers** [comment]
The new version of the Catalog Items API is available in `v5.1.0` (in the `CatalogItemsV20220401` class). Let me know if you run into any issues with it :)
