### ISSUE TITLE
Fatal error on report data download

### ISSUE THREAD

**Issue by Uff182** [jlevers/selling-partner-api#285]
When trying to download a report file for FeedType::POST_FLAT_FILE_INVLOADER_DATA (but I suspect the feed type is not relevant), the application is generating the following error:

Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpOffice\\PhpSpreadsheet\\IOFactory::identify() must be of the type string, null given, called in /vendor/jlevers/selling-partner-api/lib/Document.php on line 122 and defined in /vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/IOFactory.php:108

Following the "Downloading a feed result document" example, the error is generated on the

$contents = $docToDownload->download();  // The raw report data

line. SellingPartnerApi\Document class contains the $tmpFilename property which never gets initialized. Creating a csv file (for example) within the application and associating the variable to that file path seems to solve the issue.

**Comment by jlevers** [comment]
Sorry about that -- should be fixed in `v5.0.2`.
