### ISSUE TITLE
EVENT_212 is missing from constants

### ISSUE THREAD

**Issue by fizzyduck** [jlevers/selling-partner-api#286]
https://github.com/jlevers/selling-partner-api/blob/96dc5c5d80ac984b4beb3952f568296eb93f9563/lib/Model/FbaOutboundV20200701/EventCode.php#L53

When I am using the FBA Outbound API, I can receive the error:

``
Invalid value for enum '\SellingPartnerApi\Model\FbaOutboundV20200701\EventCode', must be one of: 'EVENT_101', 'EVENT_102', 'EVENT_201', 'EVENT_202', 'EVENT_203', 'EVENT_204', 'EVENT_205', 'EVENT_206', 'EVENT_301', 'EVENT_302', 'EVENT_304', 'EVENT_306', 'EVENT_307', 'EVENT_308', 'EVENT_309', 'EVENT_310', 'EVENT_401', 'EVENT_402', 'EVENT_403', 'EVENT_404', 'EVENT_405', 'EVENT_406', 'EVENT_407', 'EVENT_408', 'EVENT_409', 'EVENT_411', 'EVENT_412', 'EVENT_413', 'EVENT_414', 'EVENT_415', 'EVENT_416', 'EVENT_417', 'EVENT_418', 'EVENT_419'
``

It turns out it's looking for `EVENT_212` which I can't find referenced in the Amazon data docs.

**Comment by fizzyduck** [comment]
I've also discovered that ``EVENT_636`` is sometimes returned too.

**Comment by fizzyduck** [comment]
Looks like even swiship.co.uk (who report on Amazon shipments) aren't even aware of this status code but it is handled more gracefully:

![image](https://user-images.githubusercontent.com/46020783/169344425-94b4bde2-7b74-4545-9407-0b463285498f.png)

**Comment by jlevers** [comment]
Should be fixed in `v5.1.0`.

**Comment by fizzyduck** [comment]
Thanks @jlevers, this is indeed fixed.
