### ISSUE TITLE
Using $next_token with listAllFulfillmentOrders results in an InvalidInput error from Amazon

### ISSUE THREAD

**Issue by fizzyduck** [jlevers/selling-partner-api#287]
I am trying to retrieve a list of fullfilment orders which is greater than once page using code like the following:

```
$next_token = "";
do {
    $result = $apiInstance->listAllFulfillmentOrders($fromdate, $next_token);

    $orders[] = $result->getPayload()->getFulfillmentOrders();

    $next_token = $result->getPayload()->getNextToken();

} while ($next_token !== NULL);
```

However, on the second call to ``listAllFulfillmentOrders`` when ``$next_token`` is set, I get an error:

```
Exception when calling FbaOutboundApi->listAllFulfillmentOrders: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "InvalidRequestException[CodigoBaseException[message\u003d\"Could not parse bad batch key <complete contents of token that was sent>\"]]",
      "details": ""
    }
  ]
}

```

Note that the entire token is echoed back.

Do you have any thoughts on how I can debug this further?

**Comment by jlevers** [comment]
I haven't used that specific endpoint myself, but that seems like some sort of internal error to me since they're sending back the `CodigoBaseException` error. You could try passing `null` for the date parameter when you pass a non-null `$next_token`, but other than that I'm not sure what else could be going wrong.

If that doesn't resolve the problem, I would open up a support case on Seller Central.

**Comment by fizzyduck** [comment]
Sorry, I should have said, I did try passing ``null`` for the date parameter as I know some of the other calls are sensitive to this but it didn't solve the issue.

For now I am looping by using the updated datestamp from the last order retrieved.

Thank you for the fedback.

**Comment by jlevers** [comment]
Ok, closing since I'm pretty sure this isn't related to the library. Feel free to ping me again here if you want more help.

**Comment by aev-mambro2** [comment]
I just experienced the same issue. Turns out that the nextToken in the ListAllFulfillmentOrdersResult response was url-quoted / encoded, and needed to be unquoted / decoded. I do not know whether the quoting happens by the API or by the way my process reports it back.

**Comment by nhupham-commonservices** [comment]
Thanks @aev-mambro2 , I used urldecode function in PHP to decode next_token. It worked fine

**Comment by windstreet** [comment]
from urllib.parse import unquote
nextToken = response.json().get('payload').get('nextToken')
nextToken = unquote(nextToken)

It worked fine, Python
