### ISSUE TITLE
A basic application with Amazon’s Selling Partner API (Gradle install)

### ISSUE THREAD

**Issue by Lexyy112** [jlevers/selling-partner-api#289]
Thanks Jesse for all your amazing work. I tried your above example using PHP which was very good, just trying it out using Java and am having problems install the gradle using this part of the code.
$ gradle install
# The SP API Gradle wrapper file has an old Gradle version, so we're updating it
$ gradle --version  # Note your Gradle version here
$ gradle wrapper --gradle-version=<your_gradle_version>  # Update the Gradle wrapper (./gradlew) version
$ ./gradlew build

The error I am getting could be found using this link, https://scans.gradle.com/s/ftmz4kec3uvfw/failure#1

Thanks.

**Comment by jlevers** [comment]
hey @Lexyy112 -- i haven't been updating that blog post, because i'm not really working with java anymore. sorry about that!
