### ISSUE TITLE
Required parameter IdType not found

### ISSUE THREAD

**Issue by mba8487143** [jlevers/selling-partner-api#290]
Hi I am getting a list of products by calling `listCatalogItems()` function of class `SellingPartnerApi\Api\CatalogItemsV0Api` but I am getting following error `InvalidInput , Required parameter IdType not found`.
There is no parameter named IdType in `listCatalogItems()`  function. Where to pass this param, guide me.

**Comment by jlevers** [comment]
Could you please provide your code?

**Comment by jlevers** [comment]
Closing as inactive.

**Comment by Gertiozuni** [comment]
Based on docs https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/CatalogItemsV0Api.md#listCatalogItems

MarketplaceId is always required. **At least one of Query, SellerSKU, UPC, EAN, ISBN, JAN is also required**.

I faced this as i filled only **MarketplaceId**
