### ISSUE TITLE
How to get order_status_change notification?

### ISSUE THREAD

**Issue by pramodwagh** [jlevers/selling-partner-api#291]
Hello, @jlevers, 
Thank you for your great library.  
Can you please help me to get a notification if the order_status_change is in Amazon?

I tried your example given here https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/NotificationsV1Api.md but no luck.!

error:- Exception when calling NotificationsV1Api->createDestination: [500] { "errors": [ { "code": "InternalFailure", "message": "We encountered an internal error. Please try again.", "details": "" } ] }
null

Can you please provide me a proper example for notification setup?
Thank you

**Comment by jlevers** [comment]
Have you tried following Amazon's Notifications use case guide [here](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide)?

**Comment by kpconnell** [comment]
```
$data = array(
    "name" => $name,
    "resource_specification" =>  new \SellingPartnerApi\Model\Notifications\DestinationResourceSpecification(
        array(
            "sqs"=>new \SellingPartnerApi\Model\Notifications\SqsResource( array(
                    "arn"=>$sqsarn
            ))))
        

    );

    $createDestReq = new \SellingPartnerApi\Model\Notifications\CreateDestinationRequest($data); // \SellingPartnerApi\Model\Notifications\CreateDestinationRequest
    $dest= $apiInstance->createDestination($createDestReq);


...


    $apiInstance = $apiInstance = new SellingPartnerApi\Api\NotificationsApi(getSPAPIConfig($x));
 
    $data = array(
    
        "payload_version"=>"1.0",
        "destination_id" =>  $dest->getPayload()->getDestinationId()

        );

    
        $createSubReq = new \SellingPartnerApi\Model\Notifications\CreateSubscriptionRequest($data); // \SellingPartnerApi\Model\Notifications\CreateDestinationRequest

$notification_type = $type; // string | The type of notification to which you want to subscribe.

$body = new \SellingPartnerApi\Model\Notifications\CreateSubscriptionRequest($data); // \SellingPartnerApi\Model\Notifications\CreateSubscriptionRequest


    $result = $apiInstance->createSubscription($notification_type, $body);
    print_r($result);
    return $result;
```

**Comment by pramodwagh** [comment]
> Have you tried following Amazon's Notifications use case guide [here](https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide)?

Yes, I tried this but got an error on the first step.

**Comment by pramodwagh** [comment]
> ```
> $data = array(
>     "name" => $name,
>     "resource_specification" =>  new \SellingPartnerApi\Model\Notifications\DestinationResourceSpecification(
>         array(
>             "sqs"=>new \SellingPartnerApi\Model\Notifications\SqsResource( array(
>                     "arn"=>$sqsarn
>             ))))
>         
> 
>     );
> 
>     $createDestReq = new \SellingPartnerApi\Model\Notifications\CreateDestinationRequest($data); // \SellingPartnerApi\Model\Notifications\CreateDestinationRequest
>     $dest= $apiInstance->createDestination($createDestReq);
> 
> 
> ...
> 
> 
>     $data = array(
>     
>         "payload_version"=>"1.0",
>         "destination_id" =>  $dest->getPayload()->getDestinationId()
> 
>         );
> 
>     
>         $createSubReq = new \SellingPartnerApi\Model\Notifications\CreateSubscriptionRequest($data); // \SellingPartnerApi\Model\Notifications\CreateDestinationRequest
> 
> $notification_type = $type; // string | The type of notification to which you want to subscribe.
> 
> $body = new \SellingPartnerApi\Model\Notifications\CreateSubscriptionRequest($data); // \SellingPartnerApi\Model\Notifications\CreateSubscriptionRequest
> 
> 
>     $result = $apiInstance->createSubscription($notification_type, $body);
>     print_r($result);
>     return $result;
> ```

Thanks, let me try this code.

**Comment by jlevers** [comment]
Closing as inactive.
