### ISSUE TITLE
400 on getPricing API for SKU with space

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#292]
I am getting the below error when requesting [getPricing](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/ProductPricingV0Api.md#getpricing) API, when SKU has spaces (SKU - `1876776 sample SKU`)

`{ "errors": [ { "code": "InvalidInput", "message": "Invalid Input", "details": "" } ] }
`

Does any one help on this?

**Comment by jlevers** [comment]
Looks like someone else is having a similar issue here: https://github.com/amzn/selling-partner-api-docs/issues/2261

This isn't something I can fix in this library, though, so I'm going to close this issue.

**Comment by damianelder** [comment]
having the same problems. we replaced space with + and that seemed to work for a while. now we see.

request id 8074d7e4-bf69-49af-8ec0-c4e95564351d - in this example we replace spaces with + and response is ClientError 
{
"payload": [
    {
  "status": "ClientError"
        ,"SellerSKU": "486+0011+5905"
              }
      ]
}

Tweaking the encoding we get signature errors and response is similar to

The Canonical String for this request should have been
'GET
/products/pricing/v0/price
ItemType=Sku&MarketplaceId=A1PA6795UKMFR9&Skus=123%20123%20123

debugging to check the Canonical String and matches what API responded saying we should be using!!!

seems like maybe some double encoding going on between the request query string and/or  Canonical String maybe.

other SKUs without spaces are fine.
