### ISSUE TITLE
Help - Referral fee 

### ISSUE THREAD

**Issue by nikgilbe** [jlevers/selling-partner-api#294]
Hi - this isn't an issue, just after some help if anyone has any thoughts. 

When getting order information from the API, I can't find any way of getting the referral fee charged by Amazon. We are checking estimated fees using the fees API, but that doesn't always return a fee, sometimes the fee changes (no idea why) so it would be nice to see what fee Amazon have definitely charged. We do get order emails which includes the fee, but if we get an Invoice by Amazon order, that doesn't show a fee, until we receive a settlement report. It seems ridiculous all the other information is there via API, apart from fee. Has anyone else come across this ? Am I missing something?

Thanks, Nik

**Comment by misterakko** [comment]
I'm not exactly an expert on this, but have you tried the financials APIs? They return back all kind of info about what was billed to you, when and why. Start here

`	use SellingPartnerApi\Api\FinancesApi;
	$api = new FinancesApi($amazon->myConfig);
	try {
		$date = new DateTime('last month');
		$date->setTimezone(new DateTimeZone('UTC'));
		
		$result = $api->listFinancialEvents(10, $date->format('Y-m-d\TH:i:s.u\Z'));
		print_r($result);
		}
	catch (Exception $e) {

		print_r ($e->getMessage());
		}
`

**Comment by nikgilbe** [comment]
Thank you so much - that was exactly what I needed - you have saved me hours of pain

**Comment by jlevers** [comment]
I'm going to close this as I don't think it's something that can be solved by this library, but please feel free to continue discussing here.
