### ISSUE TITLE
Feature Request - Handle Throttling/Rate Limits

### ISSUE THREAD

**Issue by kpconnell** [jlevers/selling-partner-api#295]
If would be great to have the underlying http classes optionally handle 429s in a reasonable way (incremental back off and retry), otherwise we are presently putting in  lots of boilerplate looking at $exception->code==429.

**Comment by Bariskau** [comment]
You should create your own queuing system. You can use redis or rabbitmq. Redis has built in rate limit supports(redis throttle). All transactions must be async. In other words, the queue runs and records the incoming data to the your database.

**Comment by jlevers** [comment]
While I agree that this would be nice in some ways, different people will want to deal with rate limiting differently, and supporting rate limiting in the code would add a lot of complexity. For that reason, I'm going to close this as wontfix.
