### ISSUE TITLE
getMyFeesEstimates() response

### ISSUE THREAD

**Issue by dont-panic-42** [jlevers/selling-partner-api#297]
Thank you for this library.

I am having trouble getting a response for the new [getMyFeesEstimates()](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/FeesV0Api.md#getMyFeesEstimates) operation added to the Product Fees API in a recent version.  Simplified code looks like:

    $api = new \SellingPartnerApi\Api\FeesV0Api($config);

    $body = new \SellingPartnerApi\Model\FeesV0\FeesEstimateByIdRequest([
        'fees_estimate_request' => new \SellingPartnerApi\Model\FeesV0\FeesEstimateRequest([...]),
        'id_type'               => 'ASIN',
        'id_value'              => $asin
    ]);

    $result = $api->getMyFeesEstimates([$body]);

    print_r($result);

This always gives me an empty result:

    // Array
    // (
    //     [0] => SellingPartnerApi\Model\FeesV0\FeesEstimateResult Object
    //         (
    //             [container:protected] => Array
    //                 (
    //                     [status] => 
    //                     [fees_estimate_identifier] => 
    //                     [fees_estimate] => 
    //                     [error] => 
    //                 )
    // 
    //         )
    // 
    // )

But if I turn debug logging on (`$config->setDebug(true);`), I can see what looks like a complete response logged by [line 943 of \SellingPartnerApi\Api\FeesV0Api.php](https://github.com/jlevers/selling-partner-api/blob/185d89765b6913b5e02623d049312d0e0b5479af/lib/Api/FeesV0Api.php#L943):

    $this->writeDebug((string) $response->getBody());

Shows (for the same request that gives me the empty `$result` above, trimmed for brevity):

    [
       {
          "Status":"Success",
          "FeesEstimateIdentifier":{
             "MarketplaceId":"ATVPDKIKX0DER",
             "IdType":"ASIN",
             ...
             "IdValue":"B007...",
             "PriceToEstimateFees":{
             ...
             }
          },
          "FeesEstimate":{
             "TimeOfFeesEstimation":"2022-06-02T11:06:26.000Z",
             "TotalFeesEstimate":{
                "CurrencyCode":"USD",
                "Amount":15.3
             },
             "FeeDetailList":[
                {
                   "FeeType":"ReferralFee",
                   "FeeAmount":{
                      "CurrencyCode":"USD",
                      "Amount":10.8
                   },
                   "FinalFee":{
                      "CurrencyCode":"USD",
                      "Amount":10.8
                   },
                   "FeePromotion":{
                      "CurrencyCode":"USD",
                      "Amount":0.0
                   }
                },
                {
                   "FeeType":"VariableClosingFee",
                   "FeeAmount":{
                      "CurrencyCode":"USD",
                      "Amount":0.0
                      ...
                },

                // ... etc ...

Is it possible the serializing of the response on [line 981](https://github.com/jlevers/selling-partner-api/blob/185d89765b6913b5e02623d049312d0e0b5479af/lib/Api/FeesV0Api.php#L981) isn't working as expected?

    return ObjectSerializer::deserialize($content, '\SellingPartnerApi\Model\FeesV0\FeesEstimateResult[]', $response->getHeaders());

Or am I doing something wrong?

Thank you.

**Comment by jlevers** [comment]
This should be fixed in `v5.1.1`.

**Comment by myendorphin** [comment]
A quick fix in the ObjectSerializer.php line 365 fixed my error
`if(is_array($data)) $data = (Object)$data;`

just in case if can help @jlevers
