### ISSUE TITLE
Rug Category XML problem

### ISSUE THREAD

**Issue by utkuyilgin** [jlevers/selling-partner-api#298]
## Problem description:
I am trying to create products under rug category and I am trying to variant these products in color and size. I added the sizename-colorname and colorsize parts of the 'documentation to my variation theme, but I couldn't find where to put the product's color attribute in the XML data in the XSD documentation.
## Error:

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
//<Message>
                        <MessageID>' . $product['product_id'] . '</MessageID>
                        <OperationType>Update</OperationType>
                        <Product>
                            <SKU>' . $product['mpn'].'-'.$product['product_id'] . '</SKU>
                            <StandardProductID>
                                <Type>EAN</Type>
                                <Value>' . (strlen($product['ean']) > 13 ? substr($product['ean'], strlen($product['ean']) - 13) : $product['ean']) . '</Value>
		                    </StandardProductID>
                            <DescriptionData>
                                <Title>' . $product['descriptions'][$descriptionEN]['name'] . '</Title>
                                <Brand>brand</Brand>
                                <Description></Description>
                                <MSRP currency="USD">' . number_format(($discount ? $discount : $product['price']) / 16, 0, ".", false) . '</MSRP>
                                <Manufacturer>brand</Manufacturer>
                                <ItemType>area-rugs</ItemType>
                                <SizeName>'. $product['attributes'][$sizeIndex]['text'] .'</SizeName>
                            </DescriptionData>
                            <ProductData>
                                <Home>
                                    <ProductType>
                                        <Rug>
                                            <ColorMap>' . $product['attributes'][$colorIndex]['text'] . '</ColorMap>
                                            <VariationData>
                                                <VariationTheme>colorsize</VariationTheme>
                                                <Parentage>child</Parentage>
                                            </VariationData>
                                            <LengthLongerEdge unitOfMeasure="inches">' . number_format($h / 12, 1) . '</LengthLongerEdge>
                                            <WidthShorterEdge unitOfMeasure="inches">' . number_format($w / 12, 1) . '</WidthShorterEdge>
                                        </Rug>
                                   </ProductType>                                                                       
                                </Home>
                            </ProductData>
                        </Product>
                    </Message>
```

## Seller Central SP API config page screenshot

![Screenshot_1](https://user-images.githubusercontent.com/94164261/172194193-4683cb6f-bc28-40c3-99fa-38710f9f7501.png)

I tried add Color and ColorName in every block but there is always an error. Where should I have to add Color Tags or should I ? I only can add ColorMap but I can't find Color tag, so I cant make relation between them. Thank you.

Rug Category :
https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/Home.xsd

**Comment by jlevers** [comment]
I'm honestly not sure -- I took a look at the XSD and wasn't able to figure it out either. Sorry I can't be of more help here. I recommend asking on the Seller forums.

I'm closing this as it's not directly related to the library.

**Comment by hashhesh** [comment]
Hi @jlevers please let me help with this issue if you don't mind :)

@utkuyilgin this answer might be late.
You need to provide condition, ProductTaxCode, LaunchDate tags after `StandardProductID`

for valid examples please check this repo https://gist.github.com/kitwalker12/87a6939540a948cac7041459aa718189#file-products-xml 

One more thing, there are required attributes for rug many marketplaces ask for like:
CareInstructions,
Color,
SpecialFeatures,
MaterialType,
RoomType,
ItemShape,
WeaveType,

I don't know what marketplace you are in but for AE, SA and EG they asked for these attributes once we provide them it's successfully submitted. Please note that Color should be within <VariationData> tag.

hope it helps you
