### ISSUE TITLE
Can't Upload Feed Data

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#299]
Hello,
When i try ro create feedDocumentId, it works and i create. But i can not upload data.
I am receiving access denied error 403 forbidden

https://developer-docs.amazon.com/sp-api/docs/feeds-api-v2021-06-30-use-case-guide

Here i should pass step 2 but i cant. How can we upload data? 
Any sample code will be great!...

**Comment by jlevers** [comment]
There's instructions on uploading a document here: https://github.com/jlevers/selling-partner-api#uploading-a-feed-document

**Comment by jlevers** [comment]
Closing as inactive.
