### ISSUE TITLE
Vendor api

### ISSUE THREAD

**Issue by fbosman** [jlevers/selling-partner-api#3]
Amazon enabled this api also for vendors. I do have the json files for this api.
Can these be added to your repository?

**Comment by jlevers** [comment]
How does the Vendor API differ from the existing version? Are all the endpoints different?

**Comment by fbosman** [comment]
Yes, it is also open api and uses the same authorization as the sp api, it is a set of seperate json’s.
When these are implemented I can also serve the vendor customers of Amazon.
I use your library to integrate the orderprocessing in the Dolibarr Erp.
Can I pm you with the spec’s?


Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 16 mrt. 2021 om 04:45 heeft Jesse Evers ***@***.***> het volgende geschreven:

﻿
How does the Vendor API differ from the existing version? Are all the endpoints different?

**Comment by jlevers** [comment]
If I'm understanding correctly, it sounds to me like the vendor API should be its own package. I don't want to make this package unnecessarily large, and it sounds like this would be a somewhat separate chunk of functionality from the existing library.

I'm happy to discuss how you could create your own library with the Vendor API JSON models, though -- feel free to respond here, or email me at jesse [at] jesseevers.com.

**Comment by fbosman** [comment]
Hi Jesse,

That is correct, it should be a seperate library. I know how generate with swagger or operapi but I do not know what is needed to implement the authorization stuff.
This is the same for vendor and sellers
Can you give me a hand?
Regards,

Frans

**Comment by jlevers** [comment]
Hey Frans -- I'm realizing that this discussion is outside the scope of this repository. Shoot me an email and we can continue there.
