### ISSUE TITLE
Fatal error Call to undefined method ...setHeaders(...

### ISSUE THREAD

**Issue by kpconnell** [jlevers/selling-partner-api#300]
## Problem description:
latest update seems to have broken some stuff

## Error:
Fatal error: Uncaught Error: Call to undefined method SellingPartnerApi\Model\AplusContent\SearchContentDocumentsResponse::setHeaders() in M:\xampp\htdocs\xxxx\vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php:389 Stack trace: #0 M:\xampp\htdocs\xxxx\vendor\jlevers\selling-partner-api\lib\Api\AplusContentApi.php(2973): SellingPartnerApi\ObjectSerializer::deserialize(Object(stdClass), '\\SellingPartner...', Array) #1 M:\xampp\htdocs\xxxx\vendor\jlevers\selling-partner-api\lib\Api\AplusContentApi.php(2914): SellingPartnerApi\Api\AplusContentApi->searchContentDocumentsWithHttpInfo('ATVPDKIKX0DER', NULL) #2 M:\xampp\htdocs\xxxx\apluscontent\common.php(44): SellingPartnerApi\Api\AplusContentApi->searchContentDocuments('ATVPDKIKX0DER', NULL) #3 M:\xampp\htdocs\xxxx\apluscontent\aplus-rest.php(11): refreshDocs('HRLY') #4 {main} thrown in M:\xampp\htdocs\xxxx\vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php on line 389

# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
 $apiInstance = new SellingPartnerApi\Api\AplusContentApi($config);
..
 $result = $apiInstance->searchContentDocuments($marketplace_id, $page_token);

// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
@kpconnell sorry for the delay here. In what way do you think the design is flawed? A lot of the code in this library is autogenerated and therefore never actually looked at, so I'm open to suggestions.

**Comment by jlevers** [comment]
i'm going to close this due to inactivity, but feel free to reopen if you want to discuss further.
