### ISSUE TITLE
cURL error 28: Failed to connect to api.amazon.com port 443: Connection timed out

### ISSUE THREAD

**Issue by osmanmakhtoom** [jlevers/selling-partner-api#301]
Hi!
when i sending request to get orders & get order items and get order the response is:

cURL error 28: Failed to connect to api.amazon.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.amazon.com/auth/o2/token
 
how can i solve that?

**Comment by jlevers** [comment]
That sounds like a network connection issue -- I've run into that error before when I was connecting through a VPN, or something like that. Have you messed around with your network settings at all?

**Comment by osmanmakhtoom** [comment]
> That sounds like a network connection issue -- I've run into that error before when I was connecting through a VPN, or something like that. Have you messed around with your network settings at all?

I'm using your jlevers sp pai library in laravel project on ubuntu 20.04 server with nginx, all other functions working properly, but the orders api returned that error.
I'm checked it from different systems but the result is that!

**Comment by jlevers** [comment]
i'm not sure what would be causing this, but i'm quite confident it's not an issue with this library. if you have specific reasons to believe that this is a problem with the library, feel free to reopen the issue.
