### ISSUE TITLE
How to send Carton Content information (dimensions, weights) feed for FBA Inbound shipments？

### ISSUE THREAD

**Issue by suofiya** [jlevers/selling-partner-api#302]
```
I can't find any api or feed type in the amazon document to send Carton Content information (dimensions, weights)  for FBA Inbound shipments.

Did you have some advice to solve this problem？
```

**Comment by jlevers** [comment]
@suofiya did @Johnny99211's advice above fix your problem? If so, I'm going to close this issue. Otherwise I can do a little research and see if I can help.

**Comment by jlevers** [comment]
i see info on how to send dimensions for [small parcels/packages](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#partneredsmallparcelpackageoutput), but nothing carton specific. i recommend opening a support case with amazon if you still need help with this.
