### ISSUE TITLE
Confirm Shipment and Update Order Status & Tracking Id 

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#303]
Hello All,

I'm downloading all my orders and details. As of Now I want to confirm orders, then want to mark order shipped and insert carrier & tracking id. I use Orders Feed with POST_ORDER_ACKNOWLEDGEMENT_DATA. but return 400 InvalidInput event everything seems fine.

Could you please help what i should use for confirm and other actions?

Best Regards

**Comment by jlevers** [comment]
Could you show your code, and a screenshot of your SP API app config page from Seller Central?

**Comment by Johnny99211** [comment]
@jlevers sadly, it doesn't seem to be relevant anymore. At least I would be very interested to find out how to notify Amazon about a shipment including the tracking number, weight and all that stuff :(
