### ISSUE TITLE
Sandbox call for order submit acknowledgment transaction status remain Processing  

### ISSUE THREAD

**Issue by priyankdevrepublic** [jlevers/selling-partner-api#305]
## Problem description: as describe flow in https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-apis-use-case-guide

The flow chart says need to check transaction id status every 15 min for  submitting acknowledgment request. and same for shipping label request.

But once I recheck the status its remain same response for all the transaction id.

Here example: I pass 
![image](https://user-images.githubusercontent.com/100564208/173555356-796eb00e-c522-4d31-8244-b8bf27f38eb6.png)

and receiving:

![image](https://user-images.githubusercontent.com/100564208/173555761-342cb37e-93d2-4743-be54-ebc4605110a1.png)
 

## Error: Both transaction id are different what I'm passing and receiving.

![image](https://user-images.githubusercontent.com/100564208/173556932-b097201f-2986-4ac0-bb86-c3ea684ffdd6.png)

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code V1 api

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

Please guide!

**Comment by jlevers** [comment]
The sandbox responses are completely static. When you make a request to submit order acknowledgements in the sandbox, no acknowledgement process actually starts. Each SP API model specifies the sandbox's static response value for each call in the model, in the `x-amzn-api-sandbox` key. See the JSON model [here](https://developer-docs.amazon.com/sp-api/docs/vendor-direct-fulfillment-inventory-api-v1-model) for an example.
