### ISSUE TITLE
Error download report using Document API 

### ISSUE THREAD

**Issue by abedham** [jlevers/selling-partner-api#306]
Exception when try convert encoding when using Document helper API for GET_MERCHANT_LISTINGS_ALL_DATA Report

ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding in /var/www/sellenvo/vendor/jlevers/selling-partner-api/lib/Document.php:139

**Comment by jlevers** [comment]
Closed by #307.
