### ISSUE TITLE
Merchant Fulfillment API not working as expected. 

### ISSUE THREAD

**Issue by yourguide** [jlevers/selling-partner-api#309]
## Error:

```
Exception when calling MerchantFulfillmentV0Api->getEligibleShipmentServices: 
[400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "5

validation errors detected: Value \u0027\u0027 at

\u0027shipmentRequestDetails.shipFromAddress.email\u0027 failed to satisfy

constraint: Member must satisfy regular expression pattern: .+@.+; Value

\u0027\u0027 at \u0027shipmentRequestDetails.amazonOrderId\u0027 failed to

satisfy constraint: Member must satisfy regular expression pattern:

[0-9A-Z]{3}-[0-9]{7}-[0-9]{7}; Value \u0027\u0027 at

\u0027shipmentRequestDetails.weight.unit\u0027 failed to satisfy constraint:

Member must satisfy enum value set: [g, ounces, oz, grams]; Value null at

\u0027shipmentRequestDetails.weight.value\u0027 failed to satisfy constraint:

Member must not be null; Value \u0027[]\u0027 at

\u0027shipmentRequestDetails.itemList\u0027 failed to satisfy constraint: Member

must have length greater than or equal to 1",
      "details": ""
    }
  ]
}
```

## Code

```php
// North America Live
$NA = [
    'url' => 'https://sellingpartnerapi-na.amazon.com',
    'region' => 'us-east-1',
];

// North America Sandbox
// $NA = [
//  'url' => 'https://sandbox.sellingpartnerapi-na.amazon.com',
//  'region' => 'us-east-1',
// ];
    
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => $lwaClientId,
    "lwaClientSecret" => $lwaClientSecret,
    "lwaRefreshToken" => $lwaRefreshToken,
    "awsAccessKeyId" => $awsAccessKeyId,
    "awsSecretAccessKey" => $awsSecretAccessKey,
    "endpoint" => $NA  // or another endpoint from lib/Endpoint.php
]); 

$apiInstance = new SellingPartnerApi\Api\MerchantFulfillmentApi($config);

$body = new \SellingPartnerApi\Model\MerchantFulfillment\GetEligibleShipmentServicesRequest(
[
    "shipment_request_details"  =>  
        [
        "amazon_order_id" => "XXX-XXXXXXXX-XXXXXXXX",
        "item_list" => 
            [
            "order_item_id" => "XXXXXXXXXXXXXXX",
            "quantity" => 1,
            ],
        "ship_from_address" => 
            [
            "name" => "XXXXXXX",
            "address_line1" => "XXXXXXXXXX",    
            "email" => "XXXXX@XXXXX.COM",
            "city" => "XXXXXXXXX",
            "postal_code" => "XXXXXX",
            "country_code" => "US",
            "phone" => "XXXXXXXXXXXX",  
            ],
        "weight" => 
            [
            "value" => 7,
            "unit" => "oz",  
            ],
        "shipping_service_options" => 
            [
            "delivery_experience" => "DeliveryConfirmationWithSignature",  
            "carrier_will_pick_up" => true,  
            ]
        ]   
]
);
try {
    $result = $apiInstance->getEligibleShipmentServices($body);
    d($result);
} catch (Exception $e) {
    echo "<PRE>";
    echo 'Exception when calling MerchantFulfillmentV0Api->getEligibleShipmentServices: <BR>', wordwrap($e->getMessage(),80,"<br>\n",TRUE), PHP_EOL;
    echo "</PRE>";
}
```

My $config is working great... I am connecting.. but it seems no matter what I try to send in the request, the response comes back like I didn't send anything at all.

Am I doing something wrong in the request?

Thanks!

**Comment by Johnny99211** [comment]
For me, it looks like there is something wrong with the email you submit. Maybe an encoding issue as well. You should try to log the final request going out to Amazon to see what data is submitted by the API.

**Comment by yourguide** [comment]
Thanks for your reply.... I will try to generate a log to examine further.... in the error the "\u0027\u0027" is two apostrophe's.... which means its getting a 'blank' value.... or value of '' for all those required fields.

**Comment by jlevers** [comment]
The subarrays in `$body` should be nested model classes. See [this section](https://github.com/jlevers/selling-partner-api/blob/main/README.md#working-with-model-classes) of the README for details.

**Comment by yourguide** [comment]
Thank you for the pointer!   I was pulled into another project for awhile and just got back to this today... I am getting much further now with the following code:

```
$item_list = new \SellingPartnerApi\Model\MerchantFulfillment\FBMItem([
			"order_item_id" => "XXXXXXXX",
			"quantity" => 1,
					]);

$ship_from_address = new \SellingPartnerApi\Model\MerchantFulfillment\Address([
			"name" => "XXXX",
			"address_line1" => "XXXX",	
			"email" => "XXXX",
			"city" => "XXXX",
			"state_or_province_code" => "XX",
			"postal_code" => "XXXX",
			"country_code" => "XXXX",
			"phone" => "XXXX",
					]);

$package_dimensions = new \SellingPartnerApi\Model\MerchantFulfillment\PackageDimensions([
			"length" => 5,
			"width" => 5,	
			"height" => 5,
					]);

$weight = new \SellingPartnerApi\Model\MerchantFulfillment\Weight([
			"value" => 7,
			"unit" => "oz",  // oz or g
					]);

$shipping_service_options = new \SellingPartnerApi\Model\MerchantFulfillment\ShippingServiceOptions([
			"delivery_experience" => "DeliveryConfirmationWithSignature",
			"carrier_will_pick_up" => true,  
					]);

$ShipmentRequestDetails = new \SellingPartnerApi\Model\MerchantFulfillment\ShipmentRequestDetails([
    // ...
    "amazon_order_id" => "XXX-XXXXXX-XXXXXXXX",
		"item_list" => $item_list,
		"ship_from_address" => $ship_from_address,
		"package_dimensions" => $package_dimensions,
		"weight" => $weight,
		"shipping_service_options" => $shipping_service_options,
    // ...
]);


$body = new \SellingPartnerApi\Model\MerchantFulfillment\GetEligibleShipmentServicesRequest([
	"shipment_request_details" 	=> $ShipmentRequestDetails,
		]	
);

```
But I am getting an error saying:
Exception when calling MerchantFulfillmentV0Api->getEligibleShipmentServices: 
[400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "4

validation errors detected: Value \u00270\u0027 at

\u0027shipmentRequestDetails.itemList.1.member.quantity\u0027 failed to satisfy

constraint: Member must have value greater than or equal to 1; Value

\u0027\u0027 at \u0027shipmentRequestDetails.itemList.1.member.orderItemId\u0027

failed to satisfy constraint: Member must have length greater than or equal to

1; Value \u00270\u0027 at

\u0027shipmentRequestDetails.itemList.2.member.quantity\u0027 failed to satisfy

constraint: Member must have value greater than or equal to 1; Value

\u0027\u0027 at \u0027shipmentRequestDetails.itemList.2.member.orderItemId\u0027

failed to satisfy constraint: Member must have length greater than or equal to

1",
      "details": ""
    }
  ]
}

Ill update this if I figure it out... but I don't understand why its complaining about the OrderItemID and Quantity... as if i run $item_list->getOrderItemID() it returns my number correctly.

**Comment by yourguide** [comment]
***Update***
Ok its working now....    the setting for "CarrierWillPickUp" is not explained very well. Carriers do pick up our packages... but setting this to true returns no acceptable shipping methods.... as I believe it to be a reference to SCHEDULING the carrier to pick up the package.... not the fact that the carrier will pick up the package at their accustomed schedule. 
So setting it to false and I now get my available shipping methods.
Maybe this will help my future self. :) 

Its just nice to have a place to document stuff like this. Thanks for this library again Jesse!
