### ISSUE TITLE
Product Pricing batch operations (getItemOffersBatch) sample

### ISSUE THREAD

**Issue by gokigoks** [jlevers/selling-partner-api#310]
Sorry for bothering but I've scoured the documentation on this endpoint but haven't found a sample structure of the request body. The ones specified on the documentation don't have the ASIN. Not even the sandbox models contain any example requests. 

Can anyone who successfully used this operation please post their sample code?

**Comment by gokigoks** [comment]
I was finally able to get a successful response by passing array values in the getMyFeesEstimates() operation and stopped using the helper models (GetMyFeesEstimateRequest, and FeesEstimateRequest) using both resulted in an invalid body format. 

That said, after getting a successful raw response, I ran into another issue with the deserialization. Success status and data look good but the FeesEstimateResult Object comes up with empty values. 

Let me know if you need me to post the getBody() contents.. Any help is greatly appreciated.

**Comment by jlevers** [comment]
Seems like you're talking about two different issues here. One is the `getItemOffersBatch` call, and the other is the `getMyFeesEstimates` call. I've fixed the issues with `getMyFeesEstimates` in `v5.1.1`.

This is the code I've successfully used to use to call `getItemOffersBatch`:

```php
use SellingPartnerApi\Api\ProductPricingV0Api as ProductPricingApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Model\ProductPricingV0 as ProductPricing;

$config = new Configuration([ /******/ ]);
$api = new ProductPricingApi($config);

$body = new ProductPricing\GetItemOffersBatchRequest([
    'requests' => [
        new ProductPricing\ItemOffersRequest([
            'uri' => '/products/pricing/v0/items/B08MFDT65P/offers',
            'method' => 'GET',
            'item_condition' => 'New',
            'marketplace_id' => 'ATVPDKIKX0DER',
        ]),
        new ProductPricing\ItemOffersRequest([
            'uri' => '/products/pricing/v0/items/B000P6Q7MY/offers',
            'method' => 'GET',
            'item_condition' => 'New',
            'marketplace_id' => 'ATVPDKIKX0DER',
        ]),
    ],
]);
$res = $api->getItemOffersBatch($body);
```

**Comment by gokigoks** [comment]
Thank you very much. You are right, I was focusing on the GetMyFeesEstimates issue and completely forgot I had trouble with the new item offers batch request as well. My bad. 😄
