### ISSUE TITLE
Wrong parameter types

### ISSUE THREAD

**Issue by sergeykalenyuk** [jlevers/selling-partner-api#314]
@jlevers, great SDK! It works great, but there are a few places with incorrect parameter definitions.
Example:
`\SellingPartnerApi\Model\MerchantFulfillmentV0\PackageDimensions::setUnit()`
`\SellingPartnerApi\Model\MerchantFulfillmentV0\Weight::setUnit()`
`\SellingPartnerApi\Model\MerchantFulfillmentV0\ShippingServiceOptions::setDeliveryExperience()`
`\SellingPartnerApi\Model\MerchantFulfillmentV0\ShippingServiceOptions::setCarrierWillPickUpOption()`
`\SellingPartnerApi\Model\MerchantFulfillmentV0\ShippingServiceOptions::setLabelFormat()`

`setUnit()` expectes `\SellingPartnerApi\Model\MerchantFulfillmentV0\UnitOfLength|null` but the correct value is a string value:
`$packageDimensions = new \SellingPartnerApi\Model\MerchantFulfillmentV0\PackageDimensions;`
`$packageDimensions->setUnit(UnitOfLength::INCHES);`
Also
`$weight = new \SellingPartnerApi\Model\MerchantFulfillmentV0\Weight;`
`$weight->setUnit(UnitOfWeight::OZ);`
etc.
The problem is that, for example, `SellingPartnerApi\Model\MerchantFulfillmentV0::UnitOfLength()` does not have the `__construct($value)` method and there is no corresponding, for example, `__toString()` method in `\SellingPartnerApi\ObjectSerializer::sanitizeForSerialization()`:

https://github.com/jlevers/selling-partner-api/blob/e59531553589e470b051d973a4cace4a326433e5/lib/Model/MerchantFulfillmentV0/UnitOfWeight.php#L40

Please look at as an example here:

https://github.com/amazon-php/sp-api-sdk/blob/56d51dfcb49d2be2d74003dc8954e7f23f18a23b/src/AmazonPHP/SellingPartner/Model/MerchantFulfillment/UnitOfWeight.php#L47

https://github.com/amazon-php/sp-api-sdk/blob/56d51dfcb49d2be2d74003dc8954e7f23f18a23b/src/AmazonPHP/SellingPartner/ObjectSerializer.php#L67

Thanks!

**Comment by jlevers** [comment]
Fixed in `v5.2.0`.

**Comment by sergeykalenyuk** [comment]
Please upload `v5.2.0` to https://packagist.org/packages/jlevers/selling-partner-api. Thanks!

**Comment by jlevers** [comment]
Sorry about that -- please pull `v5.2.1`.

**Comment by sergeykalenyuk** [comment]
Thanks!
