### ISSUE TITLE
Confirming shipment using POST_PRODUCT_PRICING_DATA

### ISSUE THREAD

**Issue by Johnny99211** [jlevers/selling-partner-api#319]
Is there anyone who can share an example using `POST_PRODUCT_PRICING_DATA` to confirm the shipment and transfer the tracking number?

I'm unable to find any example out there and since Amazon don't allows test accounts, I need to blind-develop everything...

Also at the very beginning I'm totally unsure which document should be used for upload. Uploading an invoice file makes totally sense but what about a shipment notification as a vendor??

I really need fast help since I'm urgently running out of time with this topic. This needs to be done until this week, otherwise I'll be in a big trouble! 

As always, I'll post my fully working example here in case I find a way before I get any help.

**Comment by jlevers** [comment]
@Johnny99211 were you able to figure this out? if not, [here's a link](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/Price._TTH_.xsd) to the XSD for the Pricing feed, which describes the format of the data you should provide inside the standard XML feed envelope. there is more info on all XSDs at this link: https://sellercentral.amazon.com/help/hub/reference/1611
