### ISSUE TITLE
Getting Signature expired

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#32]
What might be the cause for this error ?
`Signature expired: 20210527T091025Z is now earlier than 20210527T093851Z (20210527T094351Z - 5 min.)`

Got this error on getCatalogItem();

**Comment by jlevers** [comment]
Is it possible that the time on your computer or server is set incorrectly? That's when I've gotten that error -- it means that the date used to sign the SP API request is too old (the request has to be signed within 5 minutes the last five minutes of when it's actually sent to Amazon).
