### ISSUE TITLE
postContentDocumentApprovalSubmission - invalid length for $details

### ISSUE THREAD

**Issue by ptakptakptak** [jlevers/selling-partner-api#320]
Hello

I am having problems with submiting the A+ content 

I use the following sample code that comes in this project.
and get following error:
"Exception when calling AplusContentV20201101Api->postContentDocumentApprovalSubmission: invalid length for $details when calling Error., must be bigger than or equal to 1.
"

The code i am using
```

$apiInstance = new SellingPartnerApi\Api\AplusContentV20201101Api($config);
$content_reference_key = "58a***-**********"; 
$marketplace_id = "A1PA********R9"; 

try {
    $result = $apiInstance->postContentDocumentApprovalSubmission($content_reference_key, $marketplace_id);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling AplusContentV20201101Api->postContentDocumentApprovalSubmission: ', $e->getMessage(), PHP_EOL;
}
```

Can anyone give me a hint?
Thank you for your help

**Comment by jlevers** [comment]
Fixed in `v5.2.0`.
