### ISSUE TITLE
How to update order status ?

### ISSUE THREAD

**Issue by maheshkumarkbs12** [jlevers/selling-partner-api#321]

**Comment by maheshkumarkbs12** [comment]
Here is my code
   
        $payload = new \SellingPartnerApi\Model\OrdersV0\UpdateShipmentStatusRequest();
        
        $payload->marketplace_id = $marketplace_ids;

        $payload->shipment_status = "ReadyForPickup"; // how to pass this value ?
        
        $result = $apiInstance->updateShipmentStatus($order_id, $payload); // getting exception at this  point
        
        
        SellingPartnerApi \ ApiException (400)
[400] { "errors": [ { "code": "InvalidInput", "message": "2 validation errors detected: Value \u0027\u0027 at \u0027marketplaceId\u0027 failed to satisfy constraint: Member must have length greater than or equal to 1; Value \u0027\u0027 at \u0027shipmentStatus\u0027 failed to satisfy constraint: Member must satisfy enum value set: [ReadyForPickup, RefusedPickup, PickedUp]", "details": "" } ] }

**Comment by maheshkumarkbs12** [comment]
@jlevers Please let me know how to fix this issue.

**Comment by jlevers** [comment]
i'm guessing based on the variable name that `$marketplace_ids` is an array but is supposed to be a single string, but your code doesn't include enough context for me to figure it out.

**Comment by jmperea80** [comment]
Hi, I´m try this code  with error 500.

require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersV1Api as SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

// See README for more information on the Configuration object's options
$config = new Configuration([
    "lwaClientId" => "amznXXXXXXXXXX8",
    "lwaClientSecret" => "299XXXXXXXX94",
    "lwaRefreshToken" => "Atzr|XXXXXXXXXXXXhKAI",
    "awsAccessKeyId" => "AKXXXXXOM7",
    "awsSecretAccessKey" => "nDtxXXXXXXXXXXICq",
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "endpoint" => Endpoint::EU,
	"roleArn" => "arn:aws:iam::XXXXXXXXXX:role/RXXXXXXXXXXn1"
]);

$apiInstance = new SellingPartnerApi\Api\OrdersV0Api($config);

$order_id = 'XXXXXXXXXXXXX'; // string | An Amazon-defined order identifier, in 3-7-7 format.
$payload = new \SellingPartnerApi\Model\OrdersV0\UpdateShipmentStatusRequest(); // \SellingPartnerApi\Model\OrdersV0\UpdateShipmentStatusRequest | The request body for the updateShipmentStatus operation.

 $shipment_status = \SellingPartnerApi\Model\OrdersV0\ShipmentStatus::READY_FOR_PICKUP;
    $data = [
        'marketplace_id'=>array('XXXXXXXXXX'),
        'shipment_status'=> $shipment_status
    ];

$payload = new \SellingPartnerApi\Model\OrdersV0\UpdateShipmentStatusRequest($data);


try {
    $apiInstance->updateShipmentStatus($order_id, $payload);
} catch (Exception $e) {
    echo 'Exception when calling OrdersV0Api->updateShipmentStatus: ', $e->getMessage(), PHP_EOL;
}

[500] { "errors": [ { "code": "InternalFailure", "message": "We encountered an internal error. Please try again.", "details": "" } ] }
