### ISSUE TITLE
Get error after calling createFeed

### ISSUE THREAD

**Issue by armmeltonyan** [jlevers/selling-partner-api#322]
## Problem description:
I successfully create a feedDocument, and also upload the contents, but when I call CreatFeed I got an error without details
## Error:
We encountered an internal error. Please try again.
```
# Your error here. PLEASE make sure to redact secrets from your error log!
```
[500] {
"errors": [
{
"code": "InternalFailure",
"message": "We encountered an internal error. Please try again.",
"details": ""
}
]
}
## Code

$marketplace_ids = array('A1PA6795UKMFR9');

        $feedType = FeedType::POST_INVENTORY_AVAILABILITY_DATA;
        $feedsApi = new FeedsApi($config);
// Create feed document
        $createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
        $feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
        $feedDocumentId = $feedDocumentInfo->getFeedDocumentId();

// Upload feed contents to document
        $feedContents = file_get_contents('../text.xml');
// The Document constructor accepts a custom \GuzzleHttp\Client object as an optional 3rd parameter. If that
// parameter is passed, your custom Guzzle client will be used when uploading the feed document contents to Amazon.
        $docToUpload = new \SellingPartnerApi\Document($feedDocumentInfo, $feedType);
        $docToUpload->upload($feedContents);

        $body = new \SellingPartnerApi\Model\FeedsV20210630\CreateFeedSpecification();
        $body->setFeedType($feedType);
        $body->setMarketplaceIds($marketplace_ids);
        $body->setInputFeedDocumentId($feedDocumentId);
        try {
            $result = $feedsApi->createFeed($body);
            print_r($result);
            die;
        } catch (Exception $e) {
            echo 'Exception when calling FeedsV20210630Api->createFeed: ', $e->getMessage(), PHP_EOL;
        }

**Comment by armmeltonyan** [comment]
@pc-stummer Hi, I already fix my issues, thanks a lot for response, if I can help you, just let me know.

**Comment by pc-stummer** [comment]
yes, please.
What fixed the issue?
We tried with POST_ORDER_FULFILLMENT_DATA

**Comment by armmeltonyan** [comment]
@pc-stummer Could you please put here the code?

**Comment by pc-stummer** [comment]
Thank you very, very much, for your help
```
use SellingPartnerApi\Api\FeedsV20210630Api as FeedsApi;
use SellingPartnerApi\FeedType;
use SellingPartnerApi\Model\FeedsV20210630 as Feeds;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Document;
use SellingPartnerApi\Endpoint;
...
$this->amazon_config = new Configuration([
            "lwaClientId" => $this->shop->sp_lwaClientId,
            "lwaClientSecret" => $this->shop->sp_lwaClientSecret,
            "lwaRefreshToken" => $this->shop->sp_lwaRefreshToken,
            "awsAccessKeyId" => $this->shop->sp_awsAccessKeyId,
            "awsSecretAccessKey" => $this->shop->sp_awsSecretAccessKey,
            "endpoint" => Endpoint::EU,
            // "roleArn" => "SellingPartnerAPIRole",
        ]);
...
$feedType = FeedType::POST_ORDER_FULFILLMENT_DATA;
        $feedsApi = new FeedsApi($this->amazon_config);
        $createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
        $feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
        $feedDocumentId = $feedDocumentInfo->getFeedDocumentId();
        $this->log->info($feedDocumentId, [$this->shop->name, $file]);

        // Upload feed contents to document
        $docToUpload = new Document($feedDocumentInfo, $feedType);
        $docToUpload->upload($feedBody);

        // Create Feed 
        $body = new Feeds\CreateFeedSpecification(['feed_type' => $feedType, 'marketplace_ids' => $this->shop['marketplace']->marketplace_id , 'input_feed_document_id' => $feedDocumentId]);

        try {
            $result = $feedsApi->createFeed($body);
            dump($result);
```

**Comment by armmeltonyan** [comment]
Check this part <$this->shop['marketplace']->marketplace_id>, it must be in array, another part is looks good)

**Comment by pc-stummer** [comment]
Thanks for your reply.

it has already been an array.
in the meantime, we changed it to:
```
 $body = new Feeds\CreateFeedSpecification();
        $body->setFeedType($feedType);
        $body->setMarketplaceIds([$this->shop['marketplace']->marketplace_id]);
        $body->setInputFeedDocumentId($feedDocumentId);
```

may be something within the xml?
```
<?xml version="1.0" encoding="UTF-8"?>
<AmazonEnvelope>
  <Header>
    <DocumentVersion>1.01</DocumentVersion>
    <MerchantIdentifier>AG16AGWXXXXX</MerchantIdentifier>
  </Header>
  <MessageType>OrderFulfillment</MessageType>
  <Message>
    <MessageID>1</MessageID>
    <OperationType>PartialUpdate</OperationType>
    <OrderFulfillment>
      <AmazonOrderID>302-0009154-329XXXX</AmazonOrderID>
      <FulfillmentDate>2022-07-06T06:00:00Z</FulfillmentDate>
      <FulfillmentData>
        <CarrierCode>DHL</CarrierCode>
        <ShippingMethod>Paket</ShippingMethod>
        <ShipperTrackingNumber>0034043465106XXXXX</ShipperTrackingNumber>
      </FulfillmentData>
      <Item>
        <AmazonOrderItemCode>031982867XXXXX</AmazonOrderItemCode>
        <Quantity>1</Quantity>
      </Item>
    </OrderFulfillment>
  </Message>
</AmazonEnvelope>
```


The amazon support mentioned that the grantless operation version of this LWA call has to be called first.
Could this be the case?

**Comment by armmeltonyan** [comment]
The xml looks good, I am not sure about LWA call, but I use roleArn from my side and it works good, maybe the issue in the configs.

**Comment by pc-stummer** [comment]
we also created a role, but as soon as we send them with the configs, we get "Access to requested resource is denied."
As we are already creating Prime Labels for one of our merchants, we think it should work without roleArn with every API.

by the way: how has the parameter to be filled? 
"arn:aws:iam::001562XXXXX:role/SellingPartnerApiRole",
or 
"SellingPartnerApiRole"

**Comment by pc-stummer** [comment]
it works :)
Thank you very much
