### ISSUE TITLE
Usage of accessToken? 

### ISSUE THREAD

**Issue by ShaneOH** [jlevers/selling-partner-api#324]
Hey @jlevers!

What's the best way to handle the storage of `accessToken` relative to the SDK _as it is refreshed during normal usage_? There isn't much documentation on this field other than it being noted as an optional key to pass into the Configuration object. 

For example, working on our app, we have a flow that looks like:

1. generate grantless token via `(new AuthorizationV1Api($config))->getAuthorizationCode( ... )`
2. get `accessToken` + `refreshToken` via non-SDK call to `/auth/o2/token` (see https://github.com/jlevers/selling-partner-api/issues/313)
3. store tokens in DB, provide `accessToken` and `accessTokenExpiration` in subsequent instantiations of the SDK's `Configuration` object

From there, it looks like the SDK internally handles checking on the expiration and handles calling for a new `accessToken` when needed.  Digging through the code, it looks like there's this:

```
        if ($this->needNewCredentials($this->awsCredentials)) {
            $this->newToken();
        }
```

And `newToken` looks like it calls `requestLWAToken`.

That all looks good, but since the `accessToken` stays good for 1 hour, are there any examples of the best way to store that token as needed (basically as in Step 3 of the above flow when we _initially_ authorize a user)? 

It seems inconvenient to have to write in a hook to every API call by the SDK to check if it refreshed to pull a new token, etc. -- and we also don't want to have to spam calls to `newToken => requestLWAToken` for _every_ call if we only have to do it once an hour. I'm hoping there is an easy way to cache the accessToken or expose it such that we can store it and use the accessToken for it's entire lifetime every hour. 

For example, in our own app, we could check the `needNewCredentials` SDK function in the __constructor and refresh ourselves before making the first call, but that's a private function in the SDK. I'm imagining something where we could call a public `tokenRefreshed()` function and could put in the __destructor `if $sdk->tokenRefreshed() { storeNewTokens($sdk->creds) }`

Hopefully that makes sense -- some guidance on this would be appreciated!

**Comment by dont-panic-42** [comment]
I'm just a user of this SDK, but are you looking for the `onUpdateCredentials` configuration option?  It is described, briefly,  in [the list of configuration options](https://github.com/jlevers/selling-partner-api#configuration-options). You can provide a callback that will receive the credentials when they are refreshed, and eg save them to your DB.

**Comment by ShaneOH** [comment]
@dont-panic-42 Hey that's exactly what I'm looking for! I missed that when going through the configs. Thanks so much for pointing that out to me! Totally resolves this
