### ISSUE TITLE
ShippingSpeedCategory missing properties? 

### ISSUE THREAD

**Issue by ShaneOH** [jlevers/selling-partner-api#327]
Hey @jlevers , I'm trying to use the [CreateFulfillmentRequest](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/FbaOutboundV20200701/CreateFulfillmentOrderRequest.md) method. It seems to require the [ShippingSpeedCategory](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/FbaOutboundV20200701/ShippingSpeedCategory.md) model but as you can see, the properties are empty here. In the code https://github.com/jlevers/selling-partner-api/blob/main/lib/Model/FbaOutboundV20200701/ShippingSpeedCategory.php it's just a static class and you can only access its constants. So:

- Does the model code need to be fixed?
- At minimum doesn't the CreateFulfillmentOrderRequest signature need to accept a `string` rather than a `ShippingSpeedCategory` object?

**Comment by ShaneOH** [comment]
Same with https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/FbaOutboundV20200701/FulfillmentAction.md

**Comment by jlevers** [comment]
thanks for flagging this. this is the same issue as #314, so i'm going to track it there. should be fixed soon.
