### ISSUE TITLE
x-amzn-RateLimit-Limit response header

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#33]
Is possible to get this **x-amzn-RateLimit-Limit** response header from the response?

**Comment by jlevers** [comment]
Not at the moment, but that would be a good addition. I've been wanting to add a way to get the request timestamp (`x-amzn-date`) and request ID (`x-amzn-requestId`) headers from the response as well, so maybe all three of those things should be added together.

**Comment by barryjt** [comment]
Hey, thanks for the great library! I second this request, in case this will help push it to the top of the to do list! :)

**Comment by ivaaaan** [comment]
Hey, @jlevers. If you have something in your mind on how to implement this, I can work on it. Because we already need this :) 
I was thinking about just adding appropriate fields into the responses classes.

**Comment by jlevers** [comment]
Response headers are now available via the `getHeaders()` method in `v4.0.0`. Give it a shot and let me know if you run into any issues :)
