### ISSUE TITLE
How to declare $marketplace_ids for CatalogItemsV20220401Api

### ISSUE THREAD

**Issue by s-r-io** [jlevers/selling-partner-api#330]
## Problem description:
I am unsure how to set the $marketplace_ids variable. With the V2020 version of searchCatalogItems, 

`$marketplace_ids = "ATVPDKIKX0DER";`

is working great. I have tried every iteration I can think of, and dug through the issues searching for a working example

## Error:
count(): Argument #1 ($value) must be of type Countable|array, string given

```
   TypeError 

  count(): Argument #1 ($value) must be of type Countable|array, string given

  at vendor/jlevers/selling-partner-api/lib/Api/CatalogItemsV20220401Api.php:928
    924▕             throw new \InvalidArgumentException(
    925▕                 'Missing the required parameter $marketplace_ids when calling searchCatalogItems'
    926▕             );
    927▕         }
  ➜ 928▕         if (count($marketplace_ids) > 1) {
    929▕             throw new \InvalidArgumentException('invalid value for "$marketplace_ids" when calling CatalogItemsV20220401Api.searchCatalogItems, number of items must be less than or equal to 1.');
    930▕         }
    931▕ 
```
## Code
```
        $config = new Configuration([
            "lwaClientId" => env("AMAZON_LWA_CLIENT_ID"),
            "lwaClientSecret" => env("AMAZON_LWA_CLIENT_SECRET"),
            "lwaRefreshToken" => env("AMAZON_LWA_REFRESH_TOKEN"),
            "awsAccessKeyId" => env("AWS_ACCESS_KEY_ID"),
            "awsSecretAccessKey" => env("AWS_SECRET_ACCESS_KEY"),
            "endpoint" => Endpoint::NA,
            "roleArn" => env("AWS_ROLE_ARN"),
        ]);

        $apiInstance = new CatalogItemsV20220401Api($config);
        $keywords = "spatula";
        $marketplace_ids = array("ATVPDKIKX0DER");
        $included_data = "summaries, images, salesRanks, productTypes, identifiers, variations";

        try {
            $result = $apiInstance->searchCatalogItems($keywords, $marketplace_ids, $included_data);
            print_r($result);
        } catch (Exception $e) {
            echo 'Exception when calling CatalogItemsV20220401Api->searchCatalogItems: ', $e->getMessage(), PHP_EOL;
        }
```
![Screen Shot 2022-07-18 at 9 53 48 PM](https://user-images.githubusercontent.com/109572381/179667661-84194cd2-a3d2-44ef-8ccf-202619d5337d.png)

**Comment by dont-panic-42** [comment]
I'm just a user of this SDK, but I think you simply have the parameter order wrong.  [The documentation](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/CatalogItemsV20220401Api.md#searchCatalogItems) shows:

    searchCatalogItems($marketplace_ids, $identifiers, $identifiers_type, $included_data, $locale, $seller_id, $keywords, $brand_names, $classification_ids, $page_size, $page_token, $keywords_locale)

You can confirm this by browsing the code.

The parameter order you have (`$keywords, $marketplace_ids, $included_data`) does. not match this.

**Comment by jlevers** [comment]
thanks @dont-panic-42 -- you are correct. @s-r-io, the method signatures of the different versions of the Catalog Items API are different, even if the method names are the same.
