### ISSUE TITLE
UpdateVerificationStatusRequestBody

### ISSUE THREAD

**Issue by maheshkumarkbs12** [jlevers/selling-partner-api#331]
@jlevers How can I get this external_reviewer_id?

![image](https://user-images.githubusercontent.com/88480536/179694486-4abd7e80-6a21-45ac-b32b-4a1262fb09e8.png)

**Comment by jlevers** [comment]
i honestly have no idea -- i'd create a support case with amazon. i don't know what that value is, or when you'd use it.
