### ISSUE TITLE
Document download bug

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#337]
When downloading a tab delimited file, the code sets a reader at https://github.com/jlevers/selling-partner-api/blob/92a9d037d4c55c5e3c91dc8246fe5db3222f0ba6/lib/Document.php#L144-L150 and then sets the special enclosure at https://github.com/jlevers/selling-partner-api/blob/92a9d037d4c55c5e3c91dc8246fe5db3222f0ba6/lib/Document.php#L158.

The problem is that later at line 161, instead of using the reader to load the file, it uses IOFactory::load($this->tmpFilename); instead of $reader->load($this->tmpFilename);

This introduces the issue with tab delimited files again.

**Comment by jlevers** [comment]
PR merged in `v5.2.0`.
