### ISSUE TITLE
Need Support for Tokens API

### ISSUE THREAD

**Issue by kpconnell** [jlevers/selling-partner-api#34]
It does not look like there is support for using the restricted data tokens, which starting in September will be required for quite a few API Calls.

https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/use-case-guides/tokens-api-use-case-guide/tokens-API-use-case-guide-2021-03-01.md

**Comment by jlevers** [comment]
Yep, you're correct -- no support yet. The newer sections of the Selling Partner API (including the Tokens API) will be supported in v3.0 of this library, which will be released well in advance of the September 30th deadline. I'll update this issue as I make progress on adding RDT support to the library.

**Comment by kpconnell** [comment]
Thank you, understood, and thanks for this library!

**Comment by jlevers** [comment]
Support for this is available in [v3.0.0](https://github.com/jlevers/selling-partner-api/releases/tag/v3.0.0). The library will generate RDTs for you automatically when you make calls to endpoints that require them, so you shouldn't need to change anything about what you're doing other than updating the library!

**Comment by Mercadoeiea** [comment]
Hi, 
When I call getOrderAddress Or getOrderBuyerInfo, RDT is generated OK in OrdersApi/config/auth/restrictedDataTokens/credentials BUT I can't get ALL Buyer or Shipping Address correctly. Only city, state_or_region, postal_code & country. NO name NO address_line1.
¿How can I get this info?
Thanks

**Comment by jlevers** [comment]
Do you have access to PII?

**Comment by Mercadoeiea** [comment]
> Do you have access to PII?

Do I need additional permission for my AWS Role User?

**Comment by jlevers** [comment]
No, but as part of your SP API developer application, you have to select which SP API roles you want access to. If you didn't select any of the PII roles (e.g., Direct-to-Consumer Fulfillment) and fill out the additional PII-related application questions, you won't be able to access any PII.

**Comment by Mercadoeiea** [comment]
It's this.
I need the 3 restricted permissions.
https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/roles/Roles-in-the-Selling-Partner-API.md
Thanks,

**Comment by adarmanto** [comment]
Hi, 

I am still facing the issue with missing PII data when call getOrderBuyerInfo (missing the buyer_name), even my app was granted to access PII. I have reached to Amazon support too, but the response is not helpful at all and keeps referring to offcial docs :/ 

I am using IAM user to request the API call and make the requests successfully on any endpoints. Is there any part that I missed?

**Comment by jordan26** [comment]
@adarmanto - Can you paste your code so we can review + I'll run it on my SP-API credentials and see if I get results then compare if permissions are different.

**Comment by jlevers** [comment]
Thanks for helping @jordan26! Have you been able to make `getOrderBuyerInfo` calls successfully with your own credentials in the past? Just want to make sure that I'm not the only person this is working for.

**Comment by jordan26** [comment]
@jlevers - Not having much luck myself.

`Exception when calling OrdersApi->getOrderAddress: [400] { "errors": [ { "code": "InvalidInput", "message": "Application do not have access to some or all requested resource", "details": "" } ] }`

![image](https://user-images.githubusercontent.com/1609366/128485470-46838e13-f1fc-4d0b-842e-1a85fc43f50d.png)

**Comment by jlevers** [comment]
My understanding is that you need access to the `Direct-to-Consumer Fulfillment` role in order to make `getOrderBuyerInfo` calls. I'm able to make that call successfully with a set of credentials that have access to that role, using this code:

```php
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Api\OrdersApi;

$config = new Configuration([ /* ... */ ]);

$orderId = 'XXX-XXXXXXX-XXXXXXX';

$api = new OrdersApi($config);

$response = $api->getOrderBuyerInfo($orderId);
print_r($response->getPayload());
```

**Comment by adarmanto** [comment]
Hello guys, just want to clarify that it was our mistake when creating the APP. We did approve to get the PII access on the Developer Profile already (as my screenshot above), but we were not aware that we need to also give that access on the APP. Here was the helpful response from Amazon support:

> "_When you create your Selling Partner API application on the application client creation page, **you can choose roles from among those that were requested and approved in your developer profile**. If the role you need is missing, you must update the roles in your developer profile to include it, and resubmit your profile for evaluation by Amazon. Once approved, the added role will be available to select for your application. **Once the role is added, re-authorize your application i.e. Generate a new LWA Refresh token to make valid API calls.**_"

We were missing the 'Tax Invoicing' in our app, the important thing is don't forget to generate a new LWA refresh token whenever update the APP roles.

BTW, thanks for a great SP-API lib @jlevers!

**Comment by jlevers** [comment]
> ...the important thing is don't forget to generate a new LWA refresh token whenever update the APP roles.
Thanks for noting this, excellent point.

> BTW, thanks for a great SP-API lib @jlevers!
You're very welcome :)

**Comment by emelaz** [comment]
HI,
did you successfully got buyer info ans address with an auto approved application?
