### ISSUE TITLE
Encoding parameter for Document class (2 issues)

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#340]
In this block, 
https://github.com/jlevers/selling-partner-api/blob/8b5cdc6739242bc87b2445070cc8165569381765/lib/Document.php#L126-L137
if encoding is passed and is valid, the if at line 126 is false so the else is executed, overriding the encoding parameter with the encoding in the response header. I think that if the parameter is passed and valid, it must override the one from the response.

Second problem is the Content-type response from Amazon for some reports in Europe. Instead of ISO-8859-1, amazon is sending Cp1252 that is not in the list of supported php encodings, rendering the auto-detect feature useless for some EU reports.

**Comment by quazardous** [comment]
Is it related to #336 ?

**Comment by 0xSekar** [comment]
> Is it related to #336 ?

I Don't think it is directly related. Similar issues, but one is for downloads while the other is for upload

**Comment by jlevers** [comment]
fixed in `v5.2.1`.
