### ISSUE TITLE
Restricted Data Token and getOrders

### ISSUE THREAD

**Issue by luckdragon** [jlevers/selling-partner-api#342]
so, I'm trying to find out/figure out how to "attach" my restricted data token (retrieved with createRestrictedDataToken), to my request for getOrders so that it returns the buyerInfo and the shipping_addresses so far, no success

unless I missed something on the request

**Comment by jlevers** [comment]
you pass in the [data elements](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide) you'd like to retrieve as the last parameter to the `getOrders` call, per the docs here: https://github.com/jlevers/selling-partner-api/#restricted-operations

**Comment by luckdragon** [comment]
i have done that,  and it returns no orders,  but without it returns
everything except address data

**Comment by jlevers** [comment]
Do you have PII access?

**Comment by luckdragon** [comment]
i think so, but how do i know?

**Comment by jlevers** [comment]
Did you apply for PII access by selecting one of the restricted roles in the developer application? If so, were you granted access to that role? Did you select it in your SP API app config on Seller Central?

If the answer to any of those questions is no, you and/or your SP API application does not have access to PII.

**Comment by luckdragon** [comment]
i will have to find out,  in actually developing for the intranet of a
company,  thank you for pointing me in the right direction

**Comment by kristinemaemateo** [comment]
I'm experiencing a similar issue. Despite having PII access, I'm unable to retrieve the buyerInfo and shippingAddress values. Strangely, I can successfully retrieve the values when making requests through Postman. 

This is how I call the getOrders method :
![image](https://github.com/jlevers/selling-partner-api/assets/86992383/cd1a92b1-4e0d-428c-8149-7a4ac8d50cc5)

The configuration I send:
![image](https://github.com/jlevers/selling-partner-api/assets/86992383/b716b869-99f8-4698-98cf-7f5d788ef688)

This is the result I get 
![image](https://github.com/jlevers/selling-partner-api/assets/86992383/bef0024e-9b60-46b7-a97b-9b32443ab9b2)

What else I'm missing ?

**Comment by jlevers** [comment]
Two things:

1. You have an extra `null` parameter in your `getOrders` call, so the `$data_elements` parameter is being set to `null`. If you're on PHP 8.1 or later, you can used named parameters to make the params less confusing, like so:
    ```php
    $result = $apiInstance->getOrders(
        marketplace_ids: $marketplace_ids,
        created_after: $create_after,
        order_statuses: $order_statuses,
        fulfillment_channels: self::FULFILLMENT_CHANNEL,
        data_elements: ['shippingAddress', 'buyerInfo']
    );
    ```
3. You don't need to pass a `tokensApi` param to the `Configuration object, and if you want to pass one it should be an instance of the `TokensV20210301Api`, not the result of calling `createRestrictedDataToken`.

**Comment by kristinemaemateo** [comment]
Thank you for your help! Your solution resolved my problem, and I can now retrieve the data I needed. I appreciate your assistance!

**Comment by DiegoWtf** [comment]
@kristinemaemateo Hi man. Can you share your $body structure?
![253511755-b716b869-99f8-4698-98cf-7f5d788ef688](https://github.com/jlevers/selling-partner-api/assets/8034654/0392c6ab-ef18-4bd8-841e-9cd78b4bd6f4)
