### ISSUE TITLE
Seller Order Id - How to update?

### ISSUE THREAD

**Issue by luckdragon** [jlevers/selling-partner-api#346]
can't really find any information about how to update the seller order id via the SP-API  google says that someone was trying to do it via the feeds api, but I don't know if that's right, or not.

**Comment by m-linss** [comment]
You need the feed type "POST_ORDER_ACKNOWLEDGEMENT_DATA" (see https://developer-docs.amazon.com/sp-api/docs/feed-type-values#order-feeds). If you browse the [OrderAcknowledgement.xsd](https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_4_1/OrderAcknowledgement.xsd), the tag "MerchantOrderID" equals the "SellerOrderId".

**Comment by jlevers** [comment]
@luckdragon, sorry that I never got to this. @m-linss comment above is correct (thanks @m-linss :)
