### ISSUE TITLE
Not able to update the inventory stock with patch/put listing API.

### ISSUE THREAD

**Issue by mzbk** [jlevers/selling-partner-api#349]
I need your help, I tried all the above suggestions but am still not able to update the inventory quantity with Amazon SP API.
Below body, I am sending to update the quantity with Put Request.

Need your help @doverradio @BashaBill @hashhesh @Om3n31 
Thanks in advance.

````
SellingPartnerApi\Model\ListingsV20210801\ListingsItemPutRequest Object
(
    [container:protected] => Array
        (
            [product_type] => FALSE_EYELASH
            [requirements] => 
            [attributes] => Array
                (
                    [fulfillment_availability] => Array
                        (
                            [fulfillment_channel_code] => AMAZON_JP
                            [quantity] => 5
                        )
                )
        )
)
````

When I use sandbox get a response **ACCEPTED** but without getting an error.

````
........
            [sku] => 2629-48KGT-2347 // TEST
            [status] => INVALID
            [submission_id] => 602b84b73b964e24b174a80d3a7870a3
            [issues] => Array
                (
                    [0] => SellingPartnerApi\Model\ListingsV20210801\Issue Object
                        (
                            [container:protected] => Array
                                (
                                    [code] => 4000003
                                    [message] => ������������Amazon������������������������������������������������������������������������������
                                    [severity] => ERROR
                                    [attribute_names] => 
                                )
                        )
                )
........
````

=======================

To patch the request I am trying the below body.

````
SellingPartnerApi\Model\ListingsV20210801\ListingsItemPatchRequest Object
(
    [container:protected] => Array
        (
            [product_type] => FALSE_EYELASH
            [patches] => Array
                (
                    [op] => replace
                    [operation_type] => UPDATE    // Already try with or without this parameter
                    [path] => /attributes/fulfillment_availability
                    [value] => Array
                        (
                            [fulfillment_channel_code] => AMAZON_JP
                            [quantity] => 5
                        )
                )
        )
)
````
Get the below response.

````
Exception when calling: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Request has missing or invalid parameters and cannot be parsed.",
      "details": ""
    }
  ]
}
````

**Comment by hashhesh** [comment]
Sorry for late revert but for me it was Sandbox mode once change to live it works well till some point I kept getting the same error `InvalidInput` so I have used old way for updating price xml feed and inventory xml feed it's way way faster than new REST apis.

**Comment by mzbk** [comment]
> Hi @mzbk , Sorry for late revert but for me it was Sandbox mode once change to live it works well till some point I kept getting the same error `InvalidInput` so I have used old way for updating price xml feed and inventory xml feed it's way way faster than new REST apis.

Can you show me how? I am really stuck on this point and I get no help so far. I appreciate your effort Thank you.

**Comment by hashhesh** [comment]
hi @mzbk sorry for late revert, I have used `POST_INVENTORY_AVAILABILITY_DATA` (Pricing Feed) you can check this example of xml feed https://gist.github.com/kitwalker12/87a6939540a948cac7041459aa718189#file-prices-xml 
I know this is almost deprecated way but I will migrate to SP_API once it's stable because now i am stuck a little bit some times it works well with Sandbox environment and not working in live environment. 

hope this helps you

**Comment by mzbk** [comment]
> hi @mzbk sorry for late revert, I have used `POST_INVENTORY_AVAILABILITY_DATA` (Pricing Feed) you can check this example of xml feed https://gist.github.com/kitwalker12/87a6939540a948cac7041459aa718189#file-prices-xml I know this is almost deprecated way but I will migrate to SP_API once it's stable because now i am stuck a little bit some times it works well with Sandbox environment and not working in live environment.
> 
> hope this helps you

Thank you very much I found the correct body to update the inventory with the new method.

I found the solution the main issue is in the **body** there are many different methods which are provided by amazon feed base or listing put/patch base.

In my question, I was using the Listing base approach.

The endpoint URL is below.

    {{fe_url}}/listings/2021-08-01/items/{{seller_id}}/8001025974?marketplaceIds={{jp_market_id}}

The body should be like the below. If there is an error in product type even if you pass the current product type just use **"PRODUCT"** instead.

**Note:** But if you are using a feed document then it might be changed [see here][1]

I got success with the below body.

    {
        "productType": "PRODUCT",
        "patches": [
            {
                "op": "replace",
                "operation_type": "PARTIAL_UPDATE",
                "path": "/attributes/fulfillment_availability",
                "value": [
                    {
                        "fulfillment_channel_code": "DEFAULT",
                        "quantity": 0
                    }
                ]
            }
        ]
    }


  [1]: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2-example

**Comment by hashhesh** [comment]
hi @mzbk much appreciated for your swift reply. I think you are right  i am missing `operation_type` I am using the same body as yours but i think there is something going wrong in other place I need to investigate.
