### ISSUE TITLE
URGENT: Enums need to serialize as scalars, not objects

### ISSUE THREAD

**Issue by ShaneOH** [jlevers/selling-partner-api#353]
Hey @jlevers !

I believe this may be related to https://github.com/jlevers/selling-partner-api/issues/350. 

When trying to create a `ShipmentRequestDetails` object, we can now, for example do this:

```
$packageDimensions->setUnit(new UnitOfLength('inches'));
```

But when that is eventually serialized into the JSON request, it is serialized to this:

```
{"ShipmentRequestDetails": ... {"PackageDimensions":{"Length":1,"Width":1,"Height":1,"Unit":{"value":"inches"}}}
```

That's breaking the API call, since it should be:

```
{"ShipmentRequestDetails": ... {"PackageDimensions":{"Length":1,"Width":1,"Height":1,"Unit":"inches"}}}
```

So the enums should be evaluating to `$string` instead of `{"value": $string}`

So the response from Amazon is:

```
Value '{value=inches}' at 'shipmentRequestDetails.packageDimensions.unit' failed to satisfy constraint: Member must satisfy enum value set: [centimeters, inches];
```

I went to take a stab at fixing this in the `ObjectSerializer` class but I notice the comment 

```
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
 ```
 
 
Don't have experience with OpenAPI Generator, but happy to be directed to where this could be fixed. As it stands now, this is breaking most/all API calls that rely on these enums

**Comment by jlevers** [comment]
hey @ShaneOH, thank you for flagging this! that was a dumb one on my end. try `v5.2.2` and let me know if that fixes it for you.

**Comment by ShaneOH** [comment]
@jlevers No worries, thanks for the quick response and continued support! I tested this last night, looks to be fixed, so can close now! Thanks again!
