### ISSUE TITLE
Is there really no way to request orders including billing address?

### ISSUE THREAD

**Issue by Johnny99211** [jlevers/selling-partner-api#355]
4 Months ago I've got a very disappointing answer from Amazon that it's not possible anymore to receive the invoice address for an order. If I request the orders I can still confirm that I only see the shipping address but no billing address. Is there any update or hacky way to receive the billing address? I really can't work with the shipping address as address for invoices, deliveries and at least bookings at my financial booking tool...

**Comment by jlevers** [comment]
I believe it's possible to retrieve billing information if you have access to the `Tax Invoicing` and or `Tax Remittance` roles (more info on roles [here](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api)). Those are both restricted roles, so you'll need to apply for PII access in order to be approved for them.

**Comment by Johnny99211** [comment]
I have both roles but can not see any billing data... I've PII as well!

**Comment by jlevers** [comment]
Have you tried the `GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING` report? I just checked, and that one definitely has billing addresses.

**Comment by Johnny99211** [comment]
Nope, I always used the orders API. Do you have an example how I can request the report for an order? That would be so helpful!!

**Comment by jlevers** [comment]
When you generate a report, you do it for a particular time period, so the report will contain data for all the orders made during that period. There's a use case guide on how to generate reports [here](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-use-case-guide#tutorial-request-and-retrieve-a-report), and some library-specific info [here](https://github.com/jlevers/selling-partner-api#uploading-and-downloading-documents). The library should make you an RDT automatically when you go to retrieve the report document, so you don't need to worry about generating a token yourself.

Just to confirm, you're not seeing anything in the `buyer_tax_info` key of the `buyer_info` object when you call `getOrders`? (I'm not seeing anything there either, but I don't have access to any US-based credentials with those roles approved.)

**Comment by Johnny99211** [comment]
I was able to request a report by using:

```
$result = $this->reports_api->getReports( [ 'GET_AMAZON_FULFILLED_SHIPMENTS_DATA_INVOICING' ] );

foreach ( $result->getReports() as $report ) {
	$a = $this->reports_api->getReportDocument($report->getReportDocumentId();
	error_log( print_r( $this->reports_api->getReportDocument($report->getReportDocumentId()), true ) );
}
```

I'm getting back a URL which leads me to a file containing some orders and billing address as well. Is there any built-in functionality to receive the content as an array? Or do I need to download the file by myself and read it into an array?

**Comment by Johnny99211** [comment]
I've tried using `GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING` but I get no reports at all. I'm so confused about the Amazon API...

**Comment by Johnny99211** [comment]
@jlevers can you may contact me via email: info@enwikuna.de

I'm totally admitted, paying you for your help! I would like to show you how I do the current implementation and what I need to request for FBA & FBM orders. This Amazon staff is so nasty and I would be very glad for any help I can get!

**Comment by jlevers** [comment]
@Johnny99211 as we've communicated via email since you last commented, and I provided some possible solutions above, I'm going to close this issue.
