### ISSUE TITLE
Missing Report type in `ReportType`

### ISSUE THREAD

**Issue by lashaLobjanidzeXentral** [jlevers/selling-partner-api#356]
1. Recording to [SP-API documentation](https://developer-docs.amazon.com/sp-api/docs/report-type-values) the report type `GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT` is present
2. But in `SellingPartnerApi\ReportType` ([Link](https://github.com/jlevers/selling-partner-api/blob/1f733d3b185712dbd7d373ecd0398f4b2348e9aa/lib/ReportType.php#L10)) is this report type absent.

See:
<img width="847" alt="Bildschirmfoto 2022-08-03 um 11 50 44" src="https://user-images.githubusercontent.com/81755255/182579401-fb749cee-96ec-4647-b356-acc21d39281d.png">

**Comment by jlevers** [comment]
Fixed in `v5.2.4`.
