### ISSUE TITLE
How can i post new asins to inventory for multiple Merchants

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#358]
Hello,
I use POST_PRODUCT_DATA when creating asin and I can add as many products as I want for a store. But I can only use 1 merchantId in Header and I have to send xml repeatedly for each store and this process takes too long. How can I send the products of more than one store in the same XML for different merchants in the same region? Is this possible, if possible how can we do it?

i sent this xml while creating ASIN in one store.

<?xml version="1.0" encoding="iso-8859-1"?>
                                <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                    xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
                                  <Header>
                                    <DocumentVersion>1.01</DocumentVersion>
                                    <MerchantIdentifier>MY_MERCHANT_ID</MerchantIdentifier>
                                  </Header>
                                <MessageType>Product </MessageType>
                                ' . $messages . '
                                </AmazonEnvelope>

$messages .= "<Message>
                <MessageID>" . $message_id . "</MessageID>
                <OperationType>Update</OperationType>
                <Product>
                    <SKU>" . $product["sku"] . "</SKU>
                    <StandardProductID>
                        <Type>ASIN</Type>
                        <Value>" . $product["asin"] . "</Value>
                    </StandardProductID>
                    <Condition>
                        <ConditionType>New</ConditionType>
                    </Condition>
                </Product>
            </Message>"

**Comment by isarzhan** [comment]
> Hello, I use POST_PRODUCT_DATA when creating asin and I can add as many products as I want for a store. But I can only use 1 merchantId in Header and I have to send xml repeatedly for each store and this process takes too long. How can I send the products of more than one store in the same XML for different merchants in the same region? Is this possible, if possible how can we do it?
> 
> i sent this xml while creating ASIN in one store.
> 
> ```
>                             <AmazonEnvelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>                                 xsi:noNamespaceSchemaLocation="amzn-envelope.xsd">
>                               <Header>
>                                 <DocumentVersion>1.01</DocumentVersion>
>                                 <MerchantIdentifier>MY_MERCHANT_ID</MerchantIdentifier>
>                               </Header>
>                             <MessageType>Product </MessageType>
>                             ' . $messages . '
>                             </AmazonEnvelope>
> ```
> 
> $messages .= " " . $message_id . " Update " . $product["sku"] . " ASIN " . $product["asin"] . " New "

Did you figure out of this process? If you found decision please share.

**Comment by Oriontechamz** [comment]
Still searching...

**Comment by Kernel1453** [comment]
I'm still searching...

**Comment by jlevers** [comment]
It should be possible by specifying multiple marketplace IDs in the `createFeed` call. The thing to be careful with here is that any prices you provide will be the same in every listing in every country, in that country's currency...so if you upload a feed that applies to both the UK and Poland and specify a price of 10 for a certain product, that will be £10 in the UK and zł10 in Poland.
