### ISSUE TITLE
XML Orders By Order Date Report， could not parse the order information of the Japanese site

### ISSUE THREAD

**Issue by MingTX0854** [jlevers/selling-partner-api#359]
## Problem description:
When using the order report API, an error was found that the XML could not be parsed
## Error:
Warning: simplexml_load_string(): input conversion failed due to input error, bytes 0x97 0x34 0x20 0x34

**Comment by jlevers** [comment]
Could you please provide the actual contents of the report that's causing you the issues so that I can test with it? If it contains information you'd rather not make public, feel free to email me a link privately -- my email is in my profile.

**Comment by MingTX0854** [comment]
Thank you for your reply. I have sent the file to your mailbox

**Comment by jlevers** [comment]
Hey @MingTX0854 -- sorry for the long wait time here.

After looking into this a bit more, I recommend you try specifying the encoding of the incoming report document like so:

```php
// ...
$reportContents = $document->download(false, 'UTF-8');
```

The error you're having appears to be an encoding error. If UTF-8 doesn't work, try playing around with other common encodings in your locale and see if that helps.

**Comment by MingTX0854** [comment]
Thank you very much. This method enables me to solve problems in a customized way
