### ISSUE TITLE
I am trying to view address of the Order done but it is retuning Application do not have access to some or all requested resource

### ISSUE THREAD

**Issue by jayant301975** [jlevers/selling-partner-api#362]
$apiInstance = new SellingPartnerApi\Api\OrdersV0Api($config); $order_id = '402-3081095-7840333';

try { $result = $apiInstance->getOrderAddress($order_id); print_r($result); } catch (Exception $e) { echo 'Exception when calling OrdersV0Api->getOrderAddress: ', $e->getMessage(), PHP_EOL; }
when i am taking respone of it it is returning

Exception when calling OrdersV0Api->getOrderAddress: [400] { "errors": [ { "code": "InvalidInput", "message": "Application do not have access to some or all requested resource", "details": "" } ] }

**Comment by MktpStar** [comment]
@jayant301975 

please see https://github.com/jlevers/selling-partner-api/issues/355

**Comment by jlevers** [comment]
@jayant301975, if you don't have PII access you won't be able to make that call. See some related info in #189.
