### ISSUE TITLE
Undefined array key "restricted" for ReportType::GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2

### ISSUE THREAD

**Issue by m-linss** [jlevers/selling-partner-api#367]
## Problem description:
the constant SellingPartnerApi\ReportType::GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 hasn't set the attribute "restricted". This causes a 500 exception "Undefined array key \"restricted\"" in class SellingPartnerApi\Authentication in method signRequest when accessing this attribute.

## Suggested solution 1:
checking existens of attribute when accessing in class SellingPartnerApi\Authentication in method signRequest 

```php
/* change line */
if ($constantPath === null || !defined($constantPath) || !constant($constantPath)['restricted']) {

/* to line */
if ($constantPath === null || !defined($constantPath) || !array_key_exists('restricted', constant($constantPath)) || !constant($constantPath)['restricted']) {
```

## Suggested solution 2:
adding attribute to constant SellingPartnerApi\ReportType::GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 

```php
public const GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2 = [
    'contentType' => ContentType::TAB,
    'name' => 'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2',
    'restricted' => false, /* this line is missing*/
    'requested' => false,
    'scheduled' => false,
];
```

Thank You!

**Comment by jlevers** [comment]
Thanks for reporting -- used solution 2. Should be fixed in `v5.2.5`
