### ISSUE TITLE
 How can I use Shipping API V2 - amazon error not deserialize properly showing PHP error

### ISSUE THREAD

**Issue by Jaimin-Devhero** [jlevers/selling-partner-api#368]
## Problem description:
In my system, we have a requirement of the seller API shipping API V2.

I am not able to call shipping API version 2 using this package.

Shipping API version 2: https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference

Please guide me. if is there any other way to call the shipping API version 2?

**Comment by jlevers** [comment]
Without the info I request in the template, I'm not able to help you. Please fill it in if you want assistance.

**Comment by Jaimin-Devhero** [comment]
This package is developed for version 1 of the shipping API. but now I want to call Version 2 of the shipping API. Is there any way I can use version2 of the shipping API in this package?

**Comment by jlevers** [comment]
I wasn't aware that the ShippingV2 API existed until you created this issue, because the model for that API isn't included in the main SP API models repo. I'll integrate it into the library in the near future and notify you here in this issue once the update is released.

**Comment by jlevers** [comment]
Should be fixed in `v5.3.0`. Feel free to reopen if you run into issues.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

Thanks for the quick replay of the issue and for integrating the new shipping API v2. 

I am getting the below error whenever there is an error from amazon response:

![image](https://user-images.githubusercontent.com/48583433/185871708-b88e95bb-d82e-42a4-af48-2a9144d5e9cd.png)

Can you check and guide me?

**Comment by jlevers** [comment]
Please make the request with the Configuration object's `debug` attr [set to true](https://github.com/jlevers/selling-partner-api/blob/main/README.md#debug-mode), and then post the output that you get when you make the request.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

Below is the output after debugging is set to true in Configuration obj.

[error.txt](https://github.com/jlevers/selling-partner-api/files/9413523/error.txt)

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers Is there any update?

I am stuck in handling the errors that came from amazon side and logging it, as it always shows this code side error.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

Can you provide me with any guidance on how to handle the above issue?

**Comment by Jaimin-Devhero** [comment]
**I am expecting this error:** 

{
"errors": [
  {
    "message": "Invalid request body: [object has missing required properties ([\"packages\"])]",
    "code": "InvalidInput"
  }
]
}

**Instead of this error:**
InvalidArgumentException {#2957
  #message: "Invalid array '\SellingPartnerApi\Model\ShippingV2\Error[]'"
  #code: 0
  #file: "D:\laragon\www\bloompost\vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php"
  #line: 268

**Comment by Jaimin-Devhero** [comment]
I have made the below changes in file **ObjectSerializer.php**  function "deserialize"

if (strcasecmp(substr($class, -2), '[]') === 0) {
    $data = is_string($data) ? json_decode($data, **true**) : $data;

but the issue is that the file is in the **vendor** folder.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

Please answer the issue I am facing.

**Comment by gokigoks** [comment]
@Jaimin-Devhero You can actually just fork a copy of this library and autoload that one in your project.

**Comment by jlevers** [comment]
@Jaimin-Devhero does the rest of the library still work fine with the solution that you provided in your PR?

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

I have only tested for the shipping API V2. ad it was working fine. 

Can you please check for the other APIs?

**Comment by jlevers** [comment]
Update to `v5.4.3` and let me know if that solves your issue.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

Thanks for the update. it worked.
