### ISSUE TITLE
Create ASIN from scratch

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#369]
Hello All,
I'm trying to create a new product for amazon. But i couldn't find which API i should use and any example xml file. Could you please help?
Best Regards

**Comment by ali-cedcoss** [comment]
This code would get you started with listing products using the new SP-API on Amazon.

```php

use SellingPartnerApi\Api\SellersV1Api as SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;
use SellingPartnerApi\Model\ListingsV20210801 as Listings;
use SellingPartnerApi\Api\ListingsV20210801Api as ListingsApi;

$config = new Configuration([
    "lwaClientId" => "xxxx",
    "lwaClientSecret" => "xxxx",
    "lwaRefreshToken" => $token,
    "awsAccessKeyId" => "xxxx",
    "awsSecretAccessKey" => "xxxx",
    "endpoint" => Endpoint::EU,
    "roleArn" => "xxxxx"
  ]);

  $data = [
    'product_type' => $product_type,
    'requirements' => 'LISTING_OFFER_ONLY',
    "attributes" => [
        "condition_type" => [
           [
              "value" => "new_new", 
              "marketplace_id" => $marketplace_id 
           ] 
        ], 
        "merchant_shipping_group" => [
                 [
                    "value" => "legacy-template-id", 
                    "marketplace_id" => $marketplace_id 
                 ] 
              ], 
        "merchant_suggested_asin" => [
                       [
                          "value" => "B08YRD1CNN", 
                          "marketplace_id" => $marketplace_id 
                       ] 
                    ], 
        "purchasable_offer" => [
                             [
                                "currency" => "INR", 
                                "our_price" => [
                                      [
                                         "schedule" => [
                                            [
                                               "value_with_tax" => 30 
                                            ] 
                                         ] 
                                      ] 
                                   ], 
                                "marketplace_id" => $marketplace_id 
                             ] 
                          ], 
        "fulfillment_availability" => [
                                                  [
                                                     "fulfillment_channel_code" => "DEFAULT", 
                                                     "quantity" => 1, 
                                                     "marketplace_id" => $marketplace_id 
                                                  ] 
                                               ], 
        "main_product_image_locator" => [
                                                        [
                                                           "media_location" => "https://media-origin-na-ssl.integ.amazon.com/images/I/xxxx1.jpg", 
                                                           "marketplace_id" => $marketplace_id 
                                                        ] 
                                                     ], 
        "other_product_image_locator_1" => [
                                                              [
                                                                 "media_location" => "https://media-origin-na-ssl.integ.amazon.com/images/I/xxxxx2.jpg", 
                                                                 "marketplace_id" => $marketplace_id 
                                                              ] 
                                                           ], 
        "other_product_image_locator_2" => [
                                                                    [
                                                                       "media_location" => "https://media-origin-na-ssl.integ.amazon.com/images/I/xxxxx3.jpg", 
                                                                       "marketplace_id" => $marketplace_id 
                                                                    ] 
                                                                 ] 
     ],
];


 $api = new ListingsApi($config);
$result = $api->putListingsItem(
    $seller_id,
    $sku,
    $marketplace_id_arr,
    new Listings\ListingsItemPutRequest($data),
    ''
);

````

**Comment by hesham331** [comment]
hi @ali-cedcoss 
What about `list_price` i am getting error Required value is missing `list_price` ???
do you have any idea?

**Comment by jlevers** [comment]
@Kernel1453 since you haven't replied to this in quite a while, I'm going to assume you got what you needed and close the issue. Let me know if you need more help.

**Comment by Kernel1453** [comment]
> This code would get you started with listing products using the new SP-API on Amazon.
> 
> ```
> use SellingPartnerApi\Api\SellersV1Api as SellersApi;
> use SellingPartnerApi\Configuration;
> use SellingPartnerApi\Endpoint;
> use SellingPartnerApi\Model\ListingsV20210801 as Listings;
> use SellingPartnerApi\Api\ListingsV20210801Api as ListingsApi;
> 
> $config = new Configuration([
>     "lwaClientId" => "xxxx",
>     "lwaClientSecret" => "xxxx",
>     "lwaRefreshToken" => $token,
>     "awsAccessKeyId" => "xxxx",
>     "awsSecretAccessKey" => "xxxx",
>     "endpoint" => Endpoint::EU,
>     "roleArn" => "xxxxx"
>   ]);
> 
>   $data = [
>     'product_type' => $product_type,
>     'requirements' => 'LISTING_OFFER_ONLY',
>     "attributes" => [
>         "condition_type" => [
>            [
>               "value" => "new_new", 
>               "marketplace_id" => $marketplace_id 
>            ] 
>         ], 
>         "merchant_shipping_group" => [
>                  [
>                     "value" => "legacy-template-id", 
>                     "marketplace_id" => $marketplace_id 
>                  ] 
>               ], 
>         "merchant_suggested_asin" => [
>                        [
>                           "value" => "B08YRD1CNN", 
>                           "marketplace_id" => $marketplace_id 
>                        ] 
>                     ], 
>         "purchasable_offer" => [
>                              [
>                                 "currency" => "INR", 
>                                 "our_price" => [
>                                       [
>                                          "schedule" => [
>                                             [
>                                                "value_with_tax" => 30 
>                                             ] 
>                                          ] 
>                                       ] 
>                                    ], 
>                                 "marketplace_id" => $marketplace_id 
>                              ] 
>                           ], 
>         "fulfillment_availability" => [
>                                                   [
>                                                      "fulfillment_channel_code" => "DEFAULT", 
>                                                      "quantity" => 1, 
>                                                      "marketplace_id" => $marketplace_id 
>                                                   ] 
>                                                ], 
>         "main_product_image_locator" => [
>                                                         [
>                                                            "media_location" => "https://media-origin-na-ssl.integ.amazon.com/images/I/xxxx1.jpg", 
>                                                            "marketplace_id" => $marketplace_id 
>                                                         ] 
>                                                      ], 
>         "other_product_image_locator_1" => [
>                                                               [
>                                                                  "media_location" => "https://media-origin-na-ssl.integ.amazon.com/images/I/xxxxx2.jpg", 
>                                                                  "marketplace_id" => $marketplace_id 
>                                                               ] 
>                                                            ], 
>         "other_product_image_locator_2" => [
>                                                                     [
>                                                                        "media_location" => "https://media-origin-na-ssl.integ.amazon.com/images/I/xxxxx3.jpg", 
>                                                                        "marketplace_id" => $marketplace_id 
>                                                                     ] 
>                                                                  ] 
>      ],
> ];
> 
> 
>  $api = new ListingsApi($config);
> $result = $api->putListingsItem(
>     $seller_id,
>     $sku,
>     $marketplace_id_arr,
>     new Listings\ListingsItemPutRequest($data),
>     ''
> );
> ```

Hi Ali,
Could you please give more details and field example which you tried and accepted for create asin from scratch? Should we keep images on amazon or is it enough to give some url for images1-2-3?
