### ISSUE TITLE
InvalidInput Error on createFeed

### ISSUE THREAD

**Issue by KhorneHoly** [jlevers/selling-partner-api#37]
I'm trying to upload a POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA file with "createFeed", but the Response is HTTP 400 InvalidInput everytime. 

Here's my code that creates the document and uploads the file.
```
// Options are set via a Factory
$feedsApi = new FeedsApi(SellingPartnerApiConfigurationFactory::createSellingPartnerApiConfiguration($seller));

// Creating Feed Document - See my pull request for the charset addition.
$createFeedDocSpec = new CreateFeedDocumentSpecification(["content_type" => "text/tab-separated-values; charset=UTF-8"]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);

// Getting file data
$documentContents = file_get_contents($this->projectDir . '/var/files/test_add_delete.txt');

// Sending file data to SP-API
$docToUpload = new Document($feedDocumentInfo->getPayload(), "text/tab-separated-values; charset=UTF-8");
$docToUpload->upload($documentContents);

$body = new CreateFeedSpecification([
    'feed_type' => "POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA",
    'marketplace_ids' => ["A1PA6795UKMFR9"],
    'input_feed_document_id' => $feedDocumentInfo->getPayload()->getFeedDocumentId(),
    'feed_options' => null
]);
$result = $feedsApi->createFeed($body);
dump($result);
```

The JSON, that is send to the endpoint is this:
`{"feedType":"POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA","marketplaceIds":["A1PA6795UKMFR9"],"inputFeedDocumentId":"*VALUE FROM RESPONSE HERE*"}`

The response is following:
```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]
}
```
The options are correctly set in the FeedApi, I was able to generate reports with the same Factory and the ReportsApi. Other feedTypes create the same issue.

Checking the request with the API documentation doesn't reveal any errors or missing information. Any clues what the issue could be?

**Comment by jlevers** [comment]
While I would expect you to get a 403 (not a 400) if this was a permissions issue, could you send me a screenshot of the SP API roles you have access to?

**Comment by KhorneHoly** [comment]
Hi, thanks for the reply. This issue seems to be something different, because I can download reports, get orders whatsoever. I'm closing this issue therefor, I'm already in contact with the developer support from Amazon via a support case.

**Comment by jlevers** [comment]
Ok, great -- thanks for following up. I'm going to close your related PR as well.

**Comment by KhorneHoly** [comment]
Hi, no problem! 

The PR wasn't related to this issue though - without the changes in the PR the request was denied on the `createFeedDocument` call because of an invalid content_type.

Only with the change and the therefore added charset the `createFeedDocument` call worked for me.

**Comment by jlevers** [comment]
Ah -- sorry for the misunderstanding, I assumed they were related.

That's interesting, because I haven't had that content type issue myself when uploading feeds. I'll look into that some more. Thanks for clarifying!
