### ISSUE TITLE
How can use with another seller?

### ISSUE THREAD

**Issue by sopyo** [jlevers/selling-partner-api#370]
Hi,

Firstly thanks for amazing repo!

I can make success api call with own seller but, how can we use with another sellers?

I have approved app in appstore, sellers can auth use and i have a spapi_oauth_code code and selling_partner_id but i cant see use this tokens in this repo.

Thanks for help.

**Comment by Kernel1453** [comment]
Here you can see the example config you need to send to amazon. When other seller authorize your application, amazon returns other sellers stores refresh_token which you specify a callback url in developer account.


<?php
require_once(__DIR__ . '/vendor/autoload.php');

// See README for more information on the Configuration object's options
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "<LWA client ID>",
    "lwaClientSecret" => "<LWA client secret>",
    "lwaRefreshToken" => "<LWA refresh token>",
    "awsAccessKeyId" => "<AWS access key ID>",
    "awsSecretAccessKey" => "<AWS secret access key>",
    "endpoint" => SellingPartnerApi\Endpoint::NA  // or another endpoint from lib/Endpoints.php
]);

**Comment by sopyo** [comment]
@Kernel1453 thanks for help.

If someone looking answer like me @jlevers  have a awesome article about this. 

Check it out : https://jesseevers.com/spapi-oauth/
