### ISSUE TITLE
403 Unauthorized

### ISSUE THREAD

**Issue by jrmaia** [jlevers/selling-partner-api#373]
I'm receiving: 

Exception when calling SellersApi->getMarketplaceParticipations: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }

My app on seller central is with status Draft, maybe this is the problem?

**Comment by ali-cedcoss** [comment]
> My app on seller central is with status Draft, maybe this is the problem?

Yes, this the issue.

**Comment by jrmaia** [comment]
> > My app on seller central is with status Draft, maybe this is the problem?
> 
> Yes, this the issue.

Do you know how I change the status do approved?

**Comment by jrmaia** [comment]
Problem solved.
I'm using IAM role, so I need configure on $config, like this:

$config = new Configuration([
    "lwaClientId"           => "amzn1.application...",
    "lwaClientSecret"       => "e0...",
    "lwaRefreshToken"       => "Atzr|...",
    "awsAccessKeyId"        => "AK...",
    "awsSecretAccessKey"    => "...",
    "roleArn"               => "arn:aws:iam::...", //here
    "endpoint"              => Endpoint::NA  
]);
