### ISSUE TITLE
Request Report API for other sellers

### ISSUE THREAD

**Issue by Capital-SetMawHtay** [jlevers/selling-partner-api#376]
My application is changing from MWS api to SP API . 

I have one problem on using ReportAPI with selling-partner-api.

I can get Report for owner seller but can't get report for other sellers. How to proper get other seller's report?

In mws , I can get other seller's report by passing "Merchant" and "MWSAuthToken" as parameters. 
For SPApi , how can I request for other sellers . ( I can request for owner seller).

**Comment by jlevers** [comment]
You have to set up [OAuth](https://developer-docs.amazon.com/sp-api/docs/authorizing-selling-partner-api-applications) to make requests as another seller. I've written a guide on how to do so [here](https://jesseevers.com/spapi-oauth/).
