### ISSUE TITLE
getOrders  

### ISSUE THREAD

**Issue by fangdashng** [jlevers/selling-partner-api#378]
## Problem description:
throw exception,  config params corrent,   what`s the reason of the error?

## Error:
[403] {
"errors": [
{
"message": "Access to requested resource is denied.",
"code": "Unauthorized",
"details": ""
}
]
}
```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*
![图片](https://user-images.githubusercontent.com/12724269/186389788-98d2356c-a998-402b-9c27-1a4a9bbfb1be.png)

**Comment by sopyo** [comment]
Usually this problem related with config. Add roleArn option the config. 

Like this ;

$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "<LWA client ID>",
    "lwaClientSecret" => "<LWA client secret>",
    "lwaRefreshToken" => "<LWA refresh token>",
    "awsAccessKeyId" => "<AWS access key ID>",
    "awsSecretAccessKey" => "<AWS secret access key>",
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "endpoint" => SellingPartnerApi\Endpoint::NA,
    "roleArn" => "<Role ARN>",
]);

**Comment by fangdashng** [comment]
The problem has been found， thanks
