### ISSUE TITLE
Need support for updating inventory quantities

### ISSUE THREAD

**Issue by iLoveSarabear** [jlevers/selling-partner-api#38]
Endpoint: 
https://sellingpartnerapi-na.amazon.com/vendor/directFulfillment/inventory/v1/warehouses/{warehouseId}/items

Docs:
https://github.com/amzn/selling-partner-api-docs/blob/main/references/vendor-direct-fulfillment-inventory-api/vendorDirectFulfillmentInventoryV1.md

**Comment by jlevers** [comment]
Support for this is coming in version 3.0 -- you can track progress on that version by checking out the [v3](https://github.com/jlevers/selling-partner-api/tree/v3) branch.

**Comment by jlevers** [comment]
Support for this is available in [v3.0.0](https://github.com/jlevers/selling-partner-api/releases/tag/v3.0.0).
