### ISSUE TITLE
Invalid value 'AU_VOEC' for 'deemed_reseller_category'

### ISSUE THREAD

**Issue by StefanGlaesser** [jlevers/selling-partner-api#382]
Hi,

there is an issue in the OrderItem-Model.

lib/Model/OrdersV0/OrderItem.php
LINE 422
$allowedValues = $this->getDeemedResellerCategoryAllowableValues();

Invalid value 'AU_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS', 'GB_VOEC', 'NO_VOEC', 'CA_MPF'. 

Best regards,
Stefan

**Comment by 0xSekar** [comment]
Getting the same error here. The patch solved the issue

**Comment by jlevers** [comment]
Merged the PR, thanks :)

**Comment by jlevers** [comment]
This should be fixed in v5.4.0 -- let me know if you keep encountering this issue.

**Comment by luckdragon** [comment]
it's broken again in 5.6, additionally, I get it for SG_VOEC

fix:  in lib/Model/OrdersV0/OrderItem.php 

search for: 
const DEEMED_RESELLER_CATEGORY_UOSS = 'UOSS';

add after:  
    const DEEMED_RESELLER_CATEGORY_SG_VOEC = 'SG_VOEC';
    const DEEMED_RESELLER_CATEGORY_GB_VOEC = 'GB_VOEC';
    const DEEMED_RESELLER_CATEGORY_NO_VOEC = 'NO_VOEC';
    const DEEMED_RESELLER_CATEGORY_CA_MPF = 'CA_MPF';
    const DEEMED_RESELLER_CATEGORY_AU_VOEC = 'AU_VOEC';
    const DEEMED_RESELLER_CATEGORY_NZ_VOEC = 'NZ_VOEC';


then search for: 
            self::DEEMED_RESELLER_CATEGORY_UOSS,
 
add after:
            self::DEEMED_RESELLER_CATEGORY_SG_VOEC,
            self::DEEMED_RESELLER_CATEGORY_GB_VOEC,
            self::DEEMED_RESELLER_CATEGORY_NO_VOEC,
            self::DEEMED_RESELLER_CATEGORY_CA_MPF,   
            self::DEEMED_RESELLER_CATEGORY_AU_VOEC,
            self::DEEMED_RESELLER_CATEGORY_NZ_VOEC,

**Comment by NoxArt** [comment]
Can confirm the preceding reply, we ran into the same issue (GB_VOEC), this has fixed it
