### ISSUE TITLE
2 issues with reports download

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#387]
Hi @jlevers ,

We are having some issues downloading reports:

1. Fields on GET_LEDGER_DETAIL_VIEW_DATA are being quoted by amazon, so unless I manually change the report type to `ContentType::CSV`, all the data get with double quotes included
2. For any TAB delimited report with a field content starting with = (equal sign), we get the following error:
`code: 0 - content: string(58) "Worksheet!Y16074 -> Formula Error: Unexpected operator '='"`
The code is interpreting it as a formula and trying to process it which I think is incorrect.

I solved second issue updating
`$sheet = $spreadsheet->getSheet(0)->toArray();`
to
`$sheet = $spreadsheet->getSheet(0)->toArray(null, false);`

in Document.php

For first issue, I updated my own code to force the report type to by CSV

Let me know if you agree with those changes (or at least the solution for the second issue) and I can create a PR

**Comment by jlevers** [comment]
Hey @0xSekar, thanks for reporting and sorry I've been AWOL the last few weeks -- life has been nuts.

Definitely down with the solution to part 2, and I think the simplest solution to part 1 is just to have a special case in `Document.php` for that report. If you add that to your PR, I'd be happy to merge it.
