### ISSUE TITLE
"Complete Shipment" FBAInbound

### ISSUE THREAD

**Issue by luckdragon** [jlevers/selling-partner-api#391]
what is the API equivalent to clicking the "Complete Shipment" button in seller central for Inbound FBA Shipments?

**Comment by jlevers** [comment]
I'm not sure, but my best guess would be the [confirmTransport](https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-reference#confirmtransport) endpoint. I haven't had to deal with this personally, so it's hard for me to say.

**Comment by jlevers** [comment]
i'm going to close this because it's not an actual problem with the library, but feel free to continue asking questions here if you want :)
