### ISSUE TITLE
Product pricing error in HttpResponseHeaders listInvalidProperties

### ISSUE THREAD

**Issue by myendorphin** [jlevers/selling-partner-api#392]
The subject method causing error due to the line below
`$invalidProperties = parent::listInvalidProperties();`

There is no parent on the class. might be a quick fix?
*use by the ProductPricingV0Api getItemOffersBatch

**Comment by jlevers** [comment]
What version of the library are you using? I think someone else ran into this error a while back and I fixed it, and I don't see that line of code anywhere in the current codebase

**Comment by myendorphin** [comment]
@jlevers 5.1
