### ISSUE TITLE
Upload and create feeds for POST_FLAT_FILE_FULFILLMENT_DATA type

### ISSUE THREAD

**Issue by priyankpatel-dev** [jlevers/selling-partner-api#394]
## Problem description:
Hello,
I want to do shipping confirmation by API and I have integrated all the steps of uploading and creating feeds but I am facing issue with the file, I am using a .txt file with tab-delimited-value content type and it always gives an error in feed document response.

Does anyone have integration feeds to confirm shipment and the data prepared from an array? 

I have tried multiple ways, text/xml, text/csv, text/plain but every time i got the same error.

Here's the file that i am using to upload data:
[Flat.txt](https://github.com/jlevers/selling-partner-api/files/9526004/Flat.txt)

## Error:

```
Warning	The order-id\torder-item-id\tquantity\tship-date\tcarrier-code\tcarrier-name\ttracking-number\tship-method\ttransparency_code\tship_from_address_name\tship_from_address_line1\tship_from_address_line2\tship_from_address_line3\tship_from_address_city\tship_from_address_county\tship_from_address_state_or_region\tship_from_address_postalcode\tship_from_address_countrycode\t\r\n123456789\t333333\t10\t10-02-30\tFEDEX\tFedEx\t852852828\tGround\t\t\t\t\t\t\t\t\t\t\t\r\n123456789\t333333\t10\t10-02-30\tFEDEX\tFedEx\t852852828\tGround\t\t\t\t\t\t\t\t\t\t\t\r\n field heading is invalid, so values in this field were ignored. To correct this error, download the template again and use the new copy, or fix the field heading in your existing file.
```

## Seller Central SP API config page screenshot

![image](https://user-images.githubusercontent.com/112478826/189098648-bfe97d59-2668-4978-b533-c52ccd2cdb82.png)

**Comment by priyankpatel-dev** [comment]
Fixed by myself!

**Comment by jmperea80** [comment]
Hi,

It´s posible to see you code, i need a example.

thank you

Regards
