### ISSUE TITLE
GetMyFeesEstimates array structure

### ISSUE THREAD

**Issue by nikgilbe** [jlevers/selling-partner-api#395]
Hi again. Since Amazon appear to have reduced the rate limit on getMyFeesEstimateForSKU, I'm looking to start using getMyFeesEstimates to get fees in batch for 20 at a time. The code I have is working fine for a single SKU, but I'm at a complete loss what the structure needs to be for calling it in batch. I've gone through the Amazon docs, the docs here, and the issues, and just can't get my head around how it should look. 

The first step in the Amazon docs say "you must create an array with up to 20 FeesEstimateByIdRequest objects." I started with a single item, but can't even get that to work. I was getting an error about a missing IdType when my array looked like this, and can't get beyond that:

        $feeArray = [
                'fees_estimate_request' => [
                        'MarketplaceId' => 'A1F83G8C2ARO7P',
                        'IsAmazonFulfilled' => false,
                        'PriceToEstimateFees' => [
                                'ListingPrice' => [
                                        'CurrencyCode' => 'GBP',
                                        'Amount' => 200
                                ]
                        ],
                        'Identifier' => $row['sku']
                        ],
                        'IdType' => 'SellerSKU',
                        'IdValue' => $row['sku']
                ];
and then even if I could, I can't get my head wrapped around how to turn that into an array of 20 elements as it says it needs to be key value pairs, not a numbered array - any help gratefully received :-(

**Comment by nikgilbe** [comment]
I've tried copying the structure from the Amazon seller docs and got an array that looks like this:
Array
(
    [FeesEstimateRequest] => Array
        (
            [MarketplaceId] => A1F83G8C2ARO7P
            [IsAmazonFulfilled] =>
            [PriceToEstimateFees] => Array
                (
                    [ListingPrice] => Array
                        (
                            [CurrencyCode] => GBP
                            [Amount] => 200
                        )

                )

            [Identifier] => UmaS1
        )

    [IdType] => SellerSku
    [IdValue] => ABC95369XYZ
)

$feesEstimateRequest = new \SellingPartnerApi\Model\FeesV0\FeesEstimateRequest($myArray);
$body = new \SellingPartnerApi\Model\FeesV0\GetMyFeesEstimateRequest(array('fees_estimate_request' => $feesEstimateRequest));
$result = $apiInstance->getMyFeesEstimates($body);

and end up with this error:

PHP Fatal error:  Uncaught SellingPartnerApi\ApiException: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "This is an invalid input",
      "details": "Missing objects [PriceToEstimateFees] in body parameters."
    }
  ]

**Comment by gokigoks** [comment]
instead of having the priceToEstimateFees as an array, try using the class SellingPartnerApi\Model\FeesV0\PriceToEstimateFees

**Comment by nikgilbe** [comment]
I've tried this:

$listingPrice = new \SellingPartnerApi\Model\FeesV0\MoneyType(array(
   'currency_code' => 'GBP',
   'amount' => 200)
);

$price = new \SellingPartnerApi\Model\FeesV0\PriceToEstimateFees(array(
      'listing_price' => $listingPrice
   )
);
$feesEstimateRequest = new \SellingPartnerApi\Model\FeesV0\FeesEstimateRequest(array(
   'marketplace_id' => array('A1F83G8C2ARO7P'),
   'is_amazon_fulfilled' => false,
   'price_to_estimate_fees' => $price,
   'identifier' => $skus
));

followed by this

$body = new \SellingPartnerApi\Model\FeesV0\GetMyFeesEstimateRequest(array('fees_estimate_request' => $feesEstimateRequest));

and this

$result =$apiInstance->getMyFeesEstimates($body);

and the same outcome

**Comment by gokigoks** [comment]
I remember having trouble with this request too. But try these things I'm doing differently. 
1. Add a shipping price key value in PriceToEstimateFees, even if having a value of 0. 
2. The body I'm sending to $apiInstance->getMyFeesEstimates() is an **FLAT** array instead of the class GetMyFeesEstimateRequest

My body looks something like this:

```
[
    [
        'FeesEstimateRequest' => [
            'MarketplaceId'       => $this->marketPlace,
            'IsAmazonFulfilled'   => true,
            'PriceToEstimateFees' => new PriceToEstimateFees([
                'listing_price' => new MoneyType([
                    'currency_code' => $currencyCode,
                    'amount'        => $price,
                ]),
                'shipping'      => new MoneyType([
                    'currency_code' => $currencyCode,
                    'amount'        => $shippingPrice,
                ]),
            ]),
            'Identifier'          => $asin,
        ],
        'IdType'              => "ASIN",
        'IdValue'             => $asin,
    ]
]
```
Also convert the keys under feesEstimateRequest to camel-case.

hope this helps.

**Comment by nikgilbe** [comment]
Thank you SO much - I've been banging my head against this for days, all working now - you're a star @gokigoks
