### ISSUE TITLE
Help needed with Feeds API and default usage plan

### ISSUE THREAD

**Issue by Johnny99211** [jlevers/selling-partner-api#397]
Hello,

I need some help with the Feeds API usage plan. Currently, I'm uploading invoices within a loop by sleeping 6 seconds after each request/upload to Amazon. This seems to be not enough because after a while I'm still getting QuotaExceeded errors.

I've tried looking around for the limit of the feeds API and found this link: https://spapi.cyou/en/references/feeds_2021-06-30.html#createfeed

Within this link there is a section describing some burst and usages: 

<img width="435" alt="image" src="https://user-images.githubusercontent.com/43766368/190699905-c82463cf-713b-4d80-9482-366e09ec0a10.png">

I'm not really understanding how to use this within an implementation. For me, it sounds like I can do 15 requests every second until I'm getting blocked. But how long should I wait now? I can not find anything about this topic. All in all, this kind of limitations are strange because I've customers with way over 100 invoices for example every day.

I've tried looking around in this library and tried to find an existing logic handling this, but found nothing.

Thanks for any help!

**Comment by gokigoks** [comment]
0.0083 requests per second refers to the regeneration rate of the limit. That translates to 1 request per 120 seconds with an allowed burst of 15 requests (token bucket algorithm). Hope this helps. But you might be able to get better help in https://github.com/amzn/selling-partner-api-docs/issues/

**Comment by jlevers** [comment]
This library doesn't provide any rate limiting functionality, because different people have different requirements for how they need to handle rate limits.

Amazon documents how the rate limits work here: https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api
