### ISSUE TITLE
To use selling partner catalog api , Do I need to check "Product Listing" in developer profile

### ISSUE THREAD

**Issue by Capital-SetMawHtay** [jlevers/selling-partner-api#398]
Last day ago , I asked a question with [authorization problem ](https://github.com/jlevers/selling-partner-api/issues/376) and the problem was solved . Thanks a lot. Now , I can make successfully api called with Report API .

Now , I have problem with using catalog api . My question is "do I need to check "Product Listing" in developer profile . I have attached my current developer profile setting in seller-central. 

Thanks for your time.

![developer profile setting](https://user-images.githubusercontent.com/60599388/190976025-8811418f-1b59-4823-8da9-557285ecff00.png)

**Comment by jlevers** [comment]
Yes, you do. Please consult Amazon's [role descriptions](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api) to figure out which roles are required for which API methods.
