### ISSUE TITLE
Image Variant Error

### ISSUE THREAD

**Issue by gokigoks** [jlevers/selling-partner-api#399]
## Problem description:
There seems to be an error if Amazon returns a non-capitalized image variant. 
## Error:
Invalid value 'Main' for 'variant', must be one of 'MAIN', 'PT01', 'PT02', 'PT03', 'PT04', 'PT05', 'PT06', 'PT07', 'PT08', 'SWCH' at vendor/jlevers/selling-partner-api/lib/Model/CatalogItemsV20220401/ItemImage.php:300)

This search is on the marketplace 'A1RKKUPIHCS9HS' using the following ASINs:

```
$identifiers = [
        "B07SGMJS6F",
        "B07SHC3LPD",
        "B07SL295L9",
        "B07SR5FBL6",
        "B07SSDQS6K",
        "B07SXD8GTS",
        "B07T8BKZSR",
        "B07T8HY28S",
        "B07TBYYGTP",
        "B07TMRS3CR",
        "B07TTDJ2HW",
        "B07TTSF8ZQ",
        "B07TVHKHSG",
        "B07TVVGG2L",
        "B07TW29LB5",
        "B07TXHV47D",
        "B07V1N8VYB",
        "B07V2JQQTB",
        "B07V2N4SJY",
        "B07V5GYW1H",
    ];
```

**Comment by gokigoks** [comment]
This is the line causing the error for the 

https://github.com/jlevers/selling-partner-api/blob/06187a932358a393e12f79ea9ea04eb27354e6ca/lib/Model/CatalogItemsV20220401/ItemImage.php#L300

I propose we could just convert the variant from Amazon's response to uppercase. @jlevers please let me know what you think.

**Comment by gokigoks** [comment]
#400

**Comment by gokigoks** [comment]
Hey, @jlevers thank you very much for making the fix for the issue. Just wondering if it's possible for us to get the 3.5.0+ version anytime soon? :)

**Comment by jlevers** [comment]
Probably will be released in the next couple days.

**Comment by jlevers** [comment]
This should be fixed in v5.4.0 -- let me know if you keep encountering this issue.

**Comment by gokigoks** [comment]
I tried the fix but unfortunately, it did not work for us. The issue was being thrown from the deserialization process. Our workaround was to just put the propertySetter inside a try-catch statement.

**Comment by cal-tec** [comment]
Commit bd890b90ff047ec5fd85052f04a698aa41103df7 raises a bug please see #404
