### ISSUE TITLE
Create a new item from putListingItem

### ISSUE THREAD

**Issue by Daniel-01-10** [jlevers/selling-partner-api#401]
How about good day colleagues.!!!
I hope you can help me. :)
My problem is that I am trying to create a new document using putListingsItem giving it the productType and Required Attributes.
The response I get is Accepted but when I try to see if my Item was published in the Amazon Seller Central listing it doesn't show up.
What would I be missing or what am I doing wrong?
I hope you can help me, I would really appreciate it
![captura](https://user-images.githubusercontent.com/34693043/191760476-e0d91e83-f7a1-492a-afc6-e6764168941a.png)

**Comment by jlevers** [comment]
I would open a case with Amazon -- based on the response you're getting it does look like the listing should have been created. I haven't encountered this issue before, and it doesn't appear to be an issue with this library, so I'm going to close this. Good luck!

**Comment by Daniel-01-10** [comment]
@jlevers  good morning
I have continued to investigate and the problem is that I am not passing an ASIN to the required attribute mercantil_suggested_asin, but the question is how am I going to generate an ASIN if I have not published it yet, since it is supposed to be generated by Amazon when making a publication
Can you help me on that please!
