### ISSUE TITLE
updateShipmentStatus

### ISSUE THREAD

**Issue by jmperea80** [jlevers/selling-partner-api#402]
## Problem description:
Hi everyone,
hi ,
when i try to update the order status i get this error. Please see my code if anybody detect some errors.

I will accept any advice as I am tired of this.

## Error:

```
Exception when calling OrdersV0Api->updateShipmentStatus: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid Request Parameters",
      "details": ""
    }
  ]
}
```

## Code

```php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersV1Api as SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

// See README for more information on the Configuration object's options
$config = new Configuration([
    "lwaClientId" => "amzxxxxxxxxx8",
    "lwaClientSecret" => "2xxxxxxxxxxxxxxxxxxxxxxxx94",
    "lwaRefreshToken" => "AxxxxxxxxxxxxxxxxxxxxxxxxAI",
    "awsAccessKeyId" => "AxOM7",
    "awsSecretAccessKey" => "nDtxxxxxxxxxxxxxxxxxxxxxxxxCq",
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "endpoint" => Endpoint::EU,
	"roleArn" => "arn:aws:iam::xxxxxxx2:role/Roxxxxxxxxxx1"
]);



$apiInstance = new SellingPartnerApi\Api\OrdersV0Api($config);

$order_id = '1xx-2xxxx0-3xxxxx8'; 

 $shipment_status = \SellingPartnerApi\Model\OrdersV0\ShipmentStatus::READY_FOR_PICKUP;
 

    $data = [
        'marketplace_id'=>'AxxxxxxxxxS',
        'shipment_status'=> $shipment_status
    ];

$payload = new \SellingPartnerApi\Model\OrdersV0\UpdateShipmentStatusRequest($data);


try {
    $apiInstance->updateShipmentStatus($order_id, $payload);
} catch (Exception $e) {
    echo 'Exception when calling OrdersV0Api->updateShipmentStatus: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by jlevers** [comment]
I don't see anything immediately wrong with this. Which marketplace ID are you using?

**Comment by jmperea80** [comment]
Hi,

this is marketplace ID: A1RKKUPIHCS9HS.

do you need the file debug.log??

**Comment by jmperea80** [comment]
I have opened a ticket with amazon and they have answered me this:


I would like to inform you that the operation is only applicable for ISPU orders (InStorePickUp orders).

From what I can see, order Id 4xx-6xxxxx6-0xxxxxx8 is not ISPU.

If you receive a 400 exception for unshipped orders, please note that this is working as designed and our teams are working for the API payload to give a more meaningful error message.

Should you receive a 400 exception for an ISPU order as well, please feel free to reach out with the request and response for that order.
