### ISSUE TITLE
[BUG-FIXING] Error on method "Shipping V2"

### ISSUE THREAD

**Issue by gmauro99** [jlevers/selling-partner-api#405]
Hello,

Documentation need to be updated for method getRates in ShippingV2 - https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/ShippingV2/Item.md

Weight - isn't optional but required (see Amazon documentation there: https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference#item)
item_identifier - it depends (if  is an Amazon order, it should be passed the right one just calling getOrderItems. Otherwise can be left blank for external orders)

Regards,

**Comment by jlevers** [comment]
If you want to make a PR for this, I'd welcome that -- otherwise I'm probably going to leave it as is, because docs are autogenerated and I don't have a good enough understanding of the Business Shipping API to make decent documentation improvements.

**Comment by jlevers** [comment]
Fixed in `v5.10.0`.
