### ISSUE TITLE
Stock update (Vendor only)

### ISSUE THREAD

**Issue by MktpStar** [jlevers/selling-partner-api#406]
Hi guys,
I'm using this library with great success to connect to Vendor API's : orders and invoices work perfectly.
Now I want to update the product stock/availability for Vendor products, too.
Tried the Listings API and getListingsItem does not return anything on the fulfillmentAvailability section, while patchListingsItem complains that fulfillment_availability is an invalid attribute.
(followed the steps outlined here : https://github.com/jlevers/selling-partner-api/issues/240#issuecomment-1100667172 )
Is the stock update via patchListingsItem  not available for Vendor?
Is Feeds -> POST_INVENTORY_AVAILABILITY_DATA  the only way ?
Are feeds like this soon to be deprecated?
Thank you  for your time.

**Comment by jlevers** [comment]
hey @MktpStar -- i haven't tried to use the Listings API with a vendor account personally, but it looks like people have been able to do so successfully based on the issues in the main SP API docs repository. There's an issue with some detailed discussion here: https://github.com/amzn/selling-partner-api-docs/issues/2167. I would also try passing `procurement` in `includedData` on your `getListingsItem` requests and see if that gets you the data you need.

i believe the only product-related feed supported for vendors is the `JSON_LISTINGS_FEED`, which uses the same format as the Listings API. The schema for this report is here: https://developer-docs.amazon.com/sp-api/docs/listings-feed-schema-v2

**Comment by jlevers** [comment]
@MktpStar since I haven't heard from you, I'm going to close this. Let me know if you still need assistance here.
