### ISSUE TITLE
SellingPartnerApi\ShippingV2Api-get error when convert GetTrackingResponse to string using __toString()

### ISSUE THREAD

**Issue by Jaimin-Devhero** [jlevers/selling-partner-api#408]
## Problem description:
I am getting the success response from the amazon side but when I try to convert the response to string using the __toSting() function it throws the error.

below is the amazon response I am getting from the API call.

`{
  "payload": {"eventHistory":[{"eventTime":"2019-03-12T14:04:50Z","eventCode":"ReadyForReceive","location":null},{"eventTime":"2019-04-12T05:23:29Z","eventCode":"PickupDone","location":{"stateOrRegion":"Leicestershire","countryCode":"GB","city":"Bardon","postalCode":"LE67 1LD"}},{"eventTime":"2019-04-12T12:23:29Z","eventCode":"Departed","location":{"stateOrRegion":"Northamptonshire","countryCode":"GB","city":"Peterborough","postalCode":"PE2 6YG"}},{"eventTime":"2019-04-13T16:23:29Z","eventCode":"DeliveryAttempted","location":{"stateOrRegion":"Leicestershire","countryCode":"GB","city":"Bardon","postalCode":"LE67 1LD"}},{"eventTime":"2019-04-14T16:23:29Z","eventCode":"Delivered","location":{"stateOrRegion":"Leicestershire","countryCode":"GB","city":"Bardon","postalCode":"LE67 1LD"}}],"summary":{"status":"Delivered"},"trackingId":"XXX","promisedDeliveryDate":"2019-03-13T20:00:00Z"}
}`

## Error:

The error I am getting:

`[2022-09-28 12:01:41] local.ERROR: InvalidArgumentException: Invalid value for enum '\SellingPartnerApi\Model\ShippingV2\EventCode', must be one of: 'ReadyForReceive', 'PickupDone', 'Delivered', 'Departed', 'DeliveryAttempted', 'Lost', 'OutForDelivery', 'ArrivedAtCarrierFacility', 'Rejected', 'Undeliverable', 'PickupCancelled' in \vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php:85
Stack trace:
#0 \vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php(76): SellingPartnerApi\ObjectSerializer::sanitizeForSerialization(Object(SellingPartnerApi\Model\ShippingV2\EventCode), '\\SellingPartner...', NULL)
#1 \vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php(63): SellingPartnerApi\ObjectSerializer::sanitizeForSerialization(Object(SellingPartnerApi\Model\ShippingV2\Event))
#2 \vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php(76): SellingPartnerApi\ObjectSerializer::sanitizeForSerialization(Array, '\\SellingPartner...', NULL)
#3 \vendor\jlevers\selling-partner-api\lib\ObjectSerializer.php(76): SellingPartnerApi\ObjectSerializer::sanitizeForSerialization(Object(SellingPartnerApi\Model\ShippingV2\GetTrackingResult), '\\SellingPartner...', NULL)
#4 \vendor\jlevers\selling-partner-api\lib\Model\ShippingV2\GetTrackingResponse.php(333): SellingPartnerApi\ObjectSerializer::sanitizeForSerialization(Object(SellingPartnerApi\Model\ShippingV2\GetTrackingResponse))
#5 \app\Actions\AmazonShipping\GetTrackingRequestAction.php(70): SellingPartnerApi\Model\ShippingV2\GetTrackingResponse->__toString()
#6 \app\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder.php(148): App\Actions\AmazonShipping\GetTrackingRequestAction->handle()
#7 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder->handle()
#8 \vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#10 \vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 \vendor\laravel\framework\src\Illuminate\Container\Container.php(651): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#13 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#14 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#15 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 \vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(124): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder), false)
#17 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#18 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#19 \vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(126): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 \vendor\laravel\framework\src\Illuminate\Queue\CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\SyncJob), Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#21 \vendor\laravel\framework\src\Illuminate\Queue\Jobs\Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#22 \vendor\laravel\framework\src\Illuminate\Queue\SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#23 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(253): Illuminate\Queue\SyncQueue->push(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#24 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(229): Illuminate\Bus\Dispatcher->pushCommandToQueue(Object(Illuminate\Queue\SyncQueue), Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#25 \vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(95): Illuminate\Bus\Dispatcher->dispatchToQueue(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#26 \vendor\laravel\framework\src\Illuminate\Foundation\Bus\Dispatchable.php(74): Illuminate\Bus\Dispatcher->dispatchSync(Object(App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder))
#27 \app\Listeners\OrderShipmentListener.php(120): App\Jobs\PostalServices\AmazonShipping\SendToAmazonShippingOrder::dispatchSync(Object(App\Models\Order), Object(App\Models\ShippingCompany), Object(App\Models\User))
#28 \vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(441): App\Listeners\OrderShipmentListener->handle(Object(App\Events\OrderShipmentEvent))
#29 \vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('App\\Events\\Orde...', Array)
#30 \vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(450): Illuminate\Events\Dispatcher->dispatch('App\\Events\\Orde...')
#31 \app\Http\Controllers\Superadmin\FullfillmentController.php(705): event(Object(App\Events\OrderShipmentEvent))
#32 \vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): App\Http\Controllers\Superadmin\FullfillmentController->AddOrdersToShipments(Object(Illuminate\Http\Request))
#33 \vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('AddOrdersToShip...', Array)
#34 \vendor\laravel\framework\src\Illuminate\Routing\Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Superadmin\FullfillmentController), 'AddOrdersToShip...')
#35 \vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\Route->runController()
#36 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(725): Illuminate\Routing\Route->run()
#37 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 \app\Http\Middleware\Admin.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\Admin->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 \app\Http\Middleware\PreventBackHistory.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\PreventBackHistory->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 \app\Http\Middleware\CheckPassWordExpired.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\CheckPassWordExpired->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 \app\Http\Middleware\LanguageMiddleware.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\LanguageMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 \vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 \vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 \app\Http\Middleware\VerifyCsrfToken.php(36): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 \vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 \vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 \app\Http\Middleware\LoginSecurityMiddleware.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): App\Http\Middleware\LoginSecurityMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(703): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(667): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#63 \vendor\laravel\framework\src\Illuminate\Routing\Router.php(656): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#64 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#65 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#66 \vendor\livewire\livewire\src\DisableBrowserCache.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Livewire\DisableBrowserCache->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 \vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 \vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 \vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#72 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#81 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 \vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 \vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#86 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#87 \vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#88 \public\index.php(61): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#89 {main}  `

## Code

```php

```
Same code as given in documentaion.

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
This should be fixed in `v5.4.1` -- give it a try and let me know if you're still having issues.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

It has solved the first issue of __toString for getTracing API response but the second issue is still open.

I am still facing the below error after adding "v5.4.1".

The second issue comment on this issue:
https://github.com/jlevers/selling-partner-api/issues/408#issuecomment-1269701197

**Comment by jlevers** [comment]
I would need your code to be able to help you with the second issue.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

We have a class action for each API call. 

Below is the code for my API:

`
$credentials = "<OUR CREDENTIALS>[]";
$isTestEnvironment = $shippingCompany->isTestEnvironment();

$config = new Configuration([
    "lwaClientId" => $credentials['client_id'],
    "lwaClientSecret" => $credentials['client_secret'],
    "lwaRefreshToken" => $credentials['refresh_token'],
    "awsAccessKeyId" => $credentials['access_key_id'],
    "awsSecretAccessKey" => $credentials['secret_access_key'],
    "endpoint" => $credentials["endpoint"]
]);
$apiInstance = new ShippingV2Api($config);
$businessId = 'AmazonShipping_UK';

try {
    $this->apiResponse = $apiInstance->getTracking($this->trackingId, $this->carrierId, $businessId);
    $responseData = $this->apiResponse->__toString();

    Log::success($responseData);
} catch (ApiException $e) {
    Log::error($e);
    $this->error = $e;
    $responseData = $e->getResponseBody();
} catch (Exception $e) {
    Log::error($e);
}

?>`

**Comment by jlevers** [comment]
Try `v5.4.3` and let me know if that solves this problem.

**Comment by Jaimin-Devhero** [comment]
Hello @jlevers 

Thanks for the update. it worked.
