### ISSUE TITLE
Amazon Api Gateway And Increase Rate-Limits

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#409]
Dear All,
I am trying to develop my own application with an external hosting using your package. My friend read an article yesterday and said that i should use Amazon Api Gateway. Do i have such an obligation? And assume that maybe around 1K users will use this application, When we send requests to APIs with xml, we can only send request for 1 marketplaceId and due to the rate-limit problems. Therefore, the waiting time for other users will be very very long. Again let's assume that in this application where there will be about 1K users, what should we do for very fast requests and responses and also i would like to have information for the api gateway.

Best Regards

**Comment by jlevers** [comment]
Could you please provide the article you're referring to? I don't think the Amazon API Gateway solution actually increases the rate limits, although I could be wrong.

**Comment by Kernel1453** [comment]
> Could you please provide the article you're referring to? I don't think the Amazon API Gateway solution actually increases the rate limits, although I could be wrong.

No, no. There are 2 different questions in my message. 1st. Should we use Amazon Api Gateway While using your package? Or why should we use?
2nd. How can we increase our rate limits? Assume that 1k users will use applucation and we need to check all stores for inventory update,orders,customer messages etc for each 30min. What must we do?

**Comment by jlevers** [comment]
"No, no" is a somewhat patronizing way to reply to someone who's helping you for free.

That aside:
1. I never have, so I don't see why you would need to -- it might make your life easier in some ways, but it's certainly not required.
2. Rate limits are per set of credentials, so if you have 1000 authorized users, the rate limits apply to each of their refresh tokens individually. So the number of sellers you have shouldn't affect your rate limiting issues at all.

**Comment by Kernel1453** [comment]
Sorry for misunderstanding what I mean. i've been misunderstood because i wrote in the logic of my own language.
And you have helped me so much with this explanation that I cannot explain. Thank you veryvery much. With this logic, I can also update repricer with feed api. In the end, everyone will spend their own rate limit and amazon allows up to 10MB for xml files.
