### ISSUE TITLE
ist products via api

### ISSUE THREAD

**Issue by totem80** [jlevers/selling-partner-api#410]
should i list products via api, is there an example please?

**Comment by Kernel1453** [comment]
You can use Feed API, type Post_Product_Data
First, You need to send ASIN, then quantity and last price when you completed your product will be active and listed in inventory

**Comment by totem80** [comment]
> You can use Feed API, type Post_Product_Data First, You need to send ASIN, then quantity and last price when you completed your product will be active and listed in inventory


i used this code, which gives me no errors. however it doesn't charge me anything:

`use SellingPartnerApi\Api\FeedsV20210630Api as FeedsApi;
use SellingPartnerApi\FeedType;
use SellingPartnerApi\Model\FeedsV20210630 as Feeds;



$feedType = FeedType::POST_PRODUCT_DATA;
$feedsApi = new FeedsApi($config);

// Create feed document
$createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
echo '<pre>';
print_r(json_encode($feedDocumentInfo->jsonSerialize()));
echo '</pre>';
$feedDocumentId = $feedDocumentInfo->getFeedDocumentId();


// Upload feed contents to document
$feedContents = file_get_contents('prodotti.xml');
// The Document constructor accepts a custom \GuzzleHttp\Client object as an optional 3rd parameter. If that
// parameter is passed, your custom Guzzle client will be used when uploading the feed document contents to Amazon.
$docToUpload = new SellingPartnerApi\Document($feedDocumentInfo, $feedType);
$docToUpload->upload($feedContents);


// ... call FeedsApi::createFeed() with $feedDocumentId

$feedsApi->createFeed($feedDocumentId);
`

**Comment by totem80** [comment]
> 
I don't have any products listed on amazon yet, I wanted to do it via api. How do I assign an ASIN?

**Comment by jlevers** [comment]
Check out [this discussion](https://github.com/amzn/selling-partner-api-docs/discussions/2644) that @Kernel1453 made on the main SP API docs repo for details on how to do this.
