### ISSUE TITLE
InboundShipmentPlanRequestItem not handling Quantity object correctly

### ISSUE THREAD

**Issue by mberding** [jlevers/selling-partner-api#413]
## Problem description:

SellingPartnerApi\Model\FbaInboundV0\InboundShipmentPlanRequestItem is not properly handling the condition object when using the getters or setters and as a result the serialization code runs into errors (because the value is not being passed correctly).

## Error:

`Exception when calling FbaInboundV0Api->createInboundShipmentPlan: Invalid value for enum '\SellingPartnerApi\Model\FbaInboundV0\Condition', must be one of: 'NewItem', 'NewWithWarranty', 'NewOEM', 'NewOpenBox', 'UsedLikeNew', 'UsedVeryGood', 'UsedGood', 'UsedAcceptable', 'UsedPoor', 'UsedRefurbished', 'CollectibleLikeNew', 'CollectibleVeryGood', 'CollectibleGood', 'CollectibleAcceptable', 'CollectiblePoor', 'RefurbishedWithWarranty', 'Refurbished', 'Club'`

## Code
```php
$conditionObj = new \SellingPartnerApi\Model\FbaInboundV0\Condition('NewItem');
$ispriObj = new \SellingPartnerApi\Model\FbaInboundV0\InboundShipmentPlanRequestItem([
    'seller_sku'=>$poItemObj->getSellerSku(),
    'asin'=>$mwsiObj->getAsin(),
    'condition'=>$conditionObj,
    'quantity'=>$poItemObj->getQuantity(),
]);
/*
add the $ispriObj to an array, and that array to a CreateInboundShipmentPlanRequest, and that to a FbaInboundV0Api
*/
```

## Here's a fix that worked for me that seems like it would be easy to implement:

<img width="1346" alt="Screen Shot 2022-10-01 at 12 16 57 PM" src="https://user-images.githubusercontent.com/5495231/193418580-58c7e928-86dd-4e7b-ae5c-441f29003a64.png">

**Comment by jlevers** [comment]
Just to make sure, are you running the latest version of the library (`v5.4.1`)? We were running into similar issues to this one a while back, but I haven't seen one in a while so I'm wondering if you're running an older version of the library.

**Comment by mberding** [comment]
Thanks for the reply -- turns out I was running 5.4.0.  I didn't think to try an update because I had just installed the library a few days before finding this issue.

I've updated to 5.4.2 and the bug appears to be resolved.
