### ISSUE TITLE
Orders inside reports marked for cancellation at Amazon

### ISSUE THREAD

**Issue by Johnny99211** [jlevers/selling-partner-api#414]
I'm currently using the `GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING` to receive new FBM orders from Amazon. Today, I've found out that it looks like the reports includes orders the customer wants to cancel. This is a problem because I automatically import the orders to my local fulfillment program, which thinks the order is still valid and should be shipped to the customer.

Do you have any idea how I can check against cancellation requests? The order report does not include a status model I think.

**Comment by Kernel1453** [comment]
why don't you try to use getorders,items??? Then you can check if there are cancellation requests or not.

**Comment by Kernel1453** [comment]
> Because it's shit. The burst and request time is really bad...
right, but for some reasons, i am using this too.

**Comment by CreateWithCoding** [comment]
why not simply filter out what you don't want with some logic?

**Comment by CreateWithCoding** [comment]
I saw you mentioned that just after I posted. 

Perhaps this below from Amazon changelog on Buyer Order Cancellations? 

What action is required?
If you have an application that is affected by these changes, update your application workflow to accommodate the buyer requested cancellation status and buyer cancel reason in the following ways:

• Run the ListOrders operation periodically to receive updated orders for any Buyer requested cancellations.

• Import the IsBuyerRequestedCancel and BuyerCancelReason fields with each order item to give sellers visibility for orders with cancellation requests.

https://developer-docs.amazon.com/sp-api/changelog/changes-to-orders-api-and-reports-api-for-buyer-cancellation-requests

Good luck on this. looks a bit frustrating. I have my own challenges programming into Amazon Vendor Central.

**Comment by CreateWithCoding** [comment]
one more from Amazon. See image below and link here:
https://sellercentral.amazon.com/help/hub/reference/GPNRJVBQMJRS942V#mnd_2jc_jcb__section_g1n_sg2_rsb

![image](https://user-images.githubusercontent.com/4888901/194233139-ecdb7347-dad0-4964-90f4-57220908239b.png)

**Comment by Johnny99211** [comment]
So do I need to make a parallel call to receive the orders list to only check for the flag? If this is true, Amazon definitely needs to change something because this is absolutely baaaad

**Comment by CreateWithCoding** [comment]
can I see a sample or the sandbox response of the GET_FLAT_FILE_ORDER_REPORT_DATA_INVOICING  ?

and the link to the docs on this?  the response is XML ?

is there a setting to include all details of the response payload?

**Comment by jlevers** [comment]
@Johnny99211 it's possible from within Seller Central to add a `is-buyer-requested-cancelation` field to order reports. More info here: https://sellercentral.amazon.com/help/hub/reference/GPNRJVBQMJRS942V#mnd_2jc_jcb__section_tq4_b22_rsb
