### ISSUE TITLE
Vendor Central Retail: Transaction Status shows Processing on Live even though completed on Amazon Vendor

### ISSUE THREAD

**Issue by CreateWithCoding** [jlevers/selling-partner-api#415]
Via the **Transaction Status API:**

**Response status from Amazon only shows Processing** after submitting Acknowledged or submitting Shipments. **Even days later even though it shows PO accepted within Amazon Vendor Central.**

**Screenshots below show result & code.** 

**Thoughts?  What am I missing?  Thanks.**

Laravel 9

![image](https://user-images.githubusercontent.com/4888901/194224203-deb8fabd-afa0-4688-ad45-986e3f130a14.png)
![image](https://user-images.githubusercontent.com/4888901/194224491-56ffbd8a-4de2-4c9e-a6bd-56185eea41a5.png)

**Comment by jlevers** [comment]
I don't see anything wrong with your code, and I'm not sure how the library could be causing this issue -- I recommend opening a support case with Amazon. Sorry to not be of more help!

**Comment by MktpStar** [comment]
see the last reply here: 
https://github.com/amzn/selling-partner-api-docs/issues/1653
