### ISSUE TITLE
Update Prices

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#416]
Hello All,
I can update prices with feed api but there are rate-limits you know. I set up my sqs for repricer on aws and getting updates between 5 and 20 mins. Now, when i get new updates for asins,  immediately i need to send price. What should i do? Which service, which api, which configuration i must do. How do other softwares update prices immediately for users marketplaces without have issues about limits?

Best Regards

**Comment by jlevers** [comment]
Presumably they're using pricing feeds, although there's no real way to know for sure how anyone else is doing it. There are also some endpoints where the rate limits get less strict the more you use them, although that behavior is poorly documented (and last I knew was only true of the Orders API).

**Comment by jlevers** [comment]
Presumably they're using pricing feeds, although there's no real way to know for sure how anyone else is doing it. There are also some endpoints where the rate limits get less strict the more you use them, although that behavior is poorly documented (and last I knew was only true of the Orders API).

**Comment by RestOp** [comment]
> Hello All, I can update prices with feed api but there are rate-limits you know. I set up my sqs for repricer on aws and getting updates between 5 and 20 mins. Now, when i get new updates for asins, immediately i need to send price. What should i do? Which service, which api, which configuration i must do. How do other softwares update prices immediately for users marketplaces without have issues about limits?
> 
> Best Regards

HI, have you found a way to update quickly?
