### ISSUE TITLE
Suppressed and Duplicate Listings

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#419]
Hi All,
İs there any api or way to get the list for suppressed and duplicate listings in inventory?

Thank you.

**Comment by jlevers** [comment]
Check out the inventory reports: https://developer-docs.amazon.com/sp-api/docs/report-type-values#inventory-reports

The suppressed listings report (`GET_MERCHANTS_LISTINGS_FYP_REPORT `) should get you some of what you're looking for

**Comment by Kernel1453** [comment]
> Check out the inventory reports: https://developer-docs.amazon.com/sp-api/docs/report-type-values#inventory-reports
> 
> The suppressed listings report (`GET_MERCHANTS_LISTINGS_FYP_REPORT `) should get you some of what you're looking for

Hi Jlevers,

Greetings to you, we are very happy to meet you.
