### ISSUE TITLE
AWS User Issues

### ISSUE THREAD

**Issue by susotrek** [jlevers/selling-partner-api#42]
I am trying to connect via Selling Partner API application using an IAM role ARN instead of a user ARN but it returns error.

When logging in as root:
AccessDenied (client): Roles may not be assumed by root accounts. - Sender Access Denied Roles may not be assumed by root accounts.

Or when accessing with user with permissions:

AccessDenied (client): User: arn: aws: iam :: 1234567890123: user / EXAMPLE is not authorized to perform: sts: AssumeRole on resource: arn: aws: iam :: 1234567890123: user / EXAMPLE - Sender AccessDenied User: arn: aws: iam :: 1234567890123: user / EXAMPLE is not authorized to perform: sts: AssumeRole on resource: arn: aws: iam :: 1234567890123: user / EXAMPLE c1c9f242-13c5-4025-8ff0-

There is no way for Amazon to assist me. Can you think of where the error is?

**Comment by jlevers** [comment]
To my knowledge, you can't use a root IAM user with the Selling Partner API.

If you created your SP API app in Seller Central with an IAM Role ARN, you need to add an `AssumeRole` policy on the IAM user whose access key ID and secret access key you're using to authenticate with the SP API, so that that IAM user can assume the permissions of the IAM role with `ExecuteAPI` permissions. The `AssumeRole` policy should look something like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "<your role ARN>"
        }
    ]
}
```

**Comment by susotrek** [comment]
Sorry, I did the IAM user permission policies but it keeps giving me the same error. I also added this permission policy, as indicated in the SP-API manual

{
     "Version": "2012-10-17",
     "Statement": [
         {
             "Effect": "Allow",
             "Action": "execute-api: Invoke",
             "Resource": "arn: aws: execute-api: *: *: *"
         }
     ]
}

I don't know where to continue at the moment.

Thank you!

**Comment by jlevers** [comment]
Did you add the `execute-api` policy to your IAM user or your IAM role?

**Comment by susotrek** [comment]
I have added the policy to the user arn: aws: iam :: 123456789012: user / XXXXXXXX and also to the role arn: aws: iam :: 123456789012: role / XXXXXXXX 

Thank you!

**Comment by jlevers** [comment]
Ok, you should only need that policy on your IAM role, since you're using the `AssumeRole` policy on your IAM user to assume the permissions granted to that role.

With this setup, are you still getting the `not authorized to perform: sts: AssumeRole` error?

**Comment by sbcjr** [comment]
This resolved the same error on my end, although (obviously) it won't validate with all those spaces- it needs to look just like the example in the docs:
`    {
      "Effect": "Allow",
      "Action": "execute-api:Invoke",
      "Resource": "arn:aws:execute-api:*:*:*"
    }`

**Comment by jlevers** [comment]
@sbcjr did you add that to an IAM user or an IAM role? Either way, interesting that it still worked without the rest of the JSON structure that I thought was required.

**Comment by sbcjr** [comment]
Sorry @jlevers, what I wrote was pretty misleading.  I added it to the IAM user, but it definitely did require the rest of the JSON- I only posted the part that I had added.  You were correct all along- this is what it looked like in its entirety:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "<my role ARN>"
        },
        {
            "Effect": "Allow",
            "Action": "execute-api:Invoke",
            "Resource": "arn:aws:execute-api:*:*:*"
        }
    ]
}
```

**Comment by jlevers** [comment]
The fact that that fixed your issue makes me think that you're using an SP API application that was created using an IAM user ARN -- is that true?

**Comment by sbcjr** [comment]
Ah...you're right.  Not what I meant to do- I had both in a text file and grabbed the wrong one.  Now the errors I was getting make a whole lot more sense- sorry to have butted in!  :)

**Comment by jlevers** [comment]
No problem -- I'm going to hide this part of the conversation just to make things clearer for other people :)

**Comment by jlevers** [comment]
@susotrek since I haven't heard from you in a while, I'm going to close this. Feel free to reopen it if necessary.

**Comment by VigneshQikink** [comment]
> Sorry @jlevers, what I wrote was pretty misleading. I added it to the IAM user, but it definitely did require the rest of the JSON- I only posted the part that I had added. You were correct all along- this is what it looked like in its entirety:
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "VisualEditor0",
>             "Effect": "Allow",
>             "Action": "sts:AssumeRole",
>             "Resource": "<my role ARN>"
>         },
>         {
>             "Effect": "Allow",
>             "Action": "execute-api:Invoke",
>             "Resource": "arn:aws:execute-api:*:*:*"
>         }
>     ]
> }
> ```

as mentioned in this, i changed the policy but still the error is coming.
