### ISSUE TITLE
Category and SubCategory List

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#420]
Hello All,

I'm trying to create an asin from scratch. So, User need to select products Category and subcategory for its parent. How can i get category and its subcategories by using sp api? Or, is there any category list as per marketplace?

Thank you too much.

**Comment by sopyo** [comment]
Hi,
You can use Reports API for get all category and subcat list with GET_XML_BROWSE_TREE_DATA report type.

**Comment by jlevers** [comment]
You can also use the [Product Type Definitions `getDefinitionsProductType`](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/ProductTypeDefinitionsV20200901Api.md#getDefinitionsProductType) call to retrieve product category information.
