### ISSUE TITLE
Class not found (following example)

### ISSUE THREAD

**Issue by misterakko** [jlevers/selling-partner-api#421]
I am following instructions from 
https://github.com/jlevers/selling-partner-api#downloading-a-report-document
But I get

```
Uncaught Error: Class 'ReportType' not found
```

## Code

```php
use SellingPartnerApi\Api\ReportsV20210630Api as ReportsApi;
use SellingPartnerApi\ReportType;
$documentId = 'amzn1.spdoc.1.4.eu.9b0e01d7-e842-45cb-b46b-2e9fa57125df.T3O4LH84696CMH.303';
$reportType = ReportType::GET_MERCHANT_LISTINGS_DATA_LITER;
```

**Comment by jlevers** [comment]
Are you importing the library from Composer by adding this to the top of your file?

```php
require_once __DIR__ . '/vendor/autoload.php';
```

**Comment by jlevers** [comment]
Closing since due to inactivity. Please feel free to reopen if you still need help with this.
