### ISSUE TITLE
Not able to create Fulfillment Order when SKU has double quotes in it

### ISSUE THREAD

**Issue by pawan1793** [jlevers/selling-partner-api#427]
SKU with double quote in it is failing
eg sellerSKU : PH 7" HVL-1

Getting response as invalid SKU ... as SKU is getting escaped when creating json object ,
when creating JSON object sku becomes PH 7\\" HVL-1

 "items": [
        {
            "quantity": "1",
            "sellerFulfillmentOrderItemId": "123456789",
            "sellerSku": "PH 7\\" HVL-1",
            "displayableComment": "Hope you love the product"
        }
    ]

**Comment by CreateWithCoding** [comment]
This?   https://stackoverflow.com/questions/15637429/how-to-escape-double-quotes-in-json

**Comment by pawan1793** [comment]
@CreateWithCoding not exactly 

//till here sku is not escaped 
$body = new \SellingPartnerApi\Model\FbaOutboundV20200701\CreateFulfillmentOrderRequest($requestdata);

but in $body I get sku with escaped double quote so not able to create fulfilment 
$response = $apiInstance->createFulfillmentOrder($body);

**Comment by jlevers** [comment]
I've seen this issue several times before, and as far as I know it's an issue with Amazon's encoding/decoding system, not with this library: https://github.com/amzn/selling-partner-api-docs/issues/2715 (there are other related issues)
