### ISSUE TITLE
Exception when calling SellersApi->getOrders: cURL error 7 for https://api.amazon.com/auth/o2/token

### ISSUE THREAD

**Issue by statsmarketing** [jlevers/selling-partner-api#428]
Keep getting this error when running the getOrders:

`Exception when calling SellersApi->getOrders: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.amazon.com/auth/o2/token`

I have run the exact same code for getOrders on 2x different servers before and it currently works fine...nothing changed with code.

Problem must be with server but not sure what would be causing this error.

The only difference on this particular server is it is an AWS server without an SSL (Non-Secure).  Perhaps that is the issue?

**Comment by jlevers** [comment]
I've run into this issue when I have a sketchy network connection, or occasionally when Amazon's OAuth service is down. Are you getting this error consistently, every time you make a call?

**Comment by statsmarketing** [comment]
So the issue was with the Apache Server.  

I changed the SELinux Modes to **disabled** mode.

As it appears, the cURL operation ran successfully when setting it to disabled.

The problem was with cURL settings on the server.

Thanks.
