### ISSUE TITLE
Get Transaction Status

### ISSUE THREAD

**Issue by jonkur909** [jlevers/selling-partner-api#429]
Hi,  I have used your API many times - many thanks.   When using the Vendor Transaction Status API V1 to check on the status of transactions, I am getting "errors": [ { "code": "ResourceNotFound", "message": "Cannot find resource by the given URI" } ]
Previously, I wrote an App using the VendorDirectFulfillment APIs and the corresponding functionality worked fine to check on transactions submitted with that part of the API.
Please could you check the above API and advise if it is working as expected for you?  
Thanks very much, Jon
(jon@goshipr.com)

**Comment by jlevers** [comment]
Unfortunately I don't have access to a vendor account that I can use to test this. If you're willing to share your API creds with via email, I can try to diagnose this, but otherwise I can't really test it. My email is jesse [at] jesse evers [dot] com.
