### ISSUE TITLE
GET /catalog/2020-12-01/items

### ISSUE THREAD

**Issue by mishasaz** [jlevers/selling-partner-api#43]
Hello!
I need to search asins of brand...
In amazon docs is path GET /catalog/2020-12-01/items (https://github.com/amzn/selling-partner-api-docs/blob/main/references/catalog-items-api/catalogItems_2020-12-01.md#searchcatalogitems)

Can I do this search using your library?
Thank you.

**Comment by jlevers** [comment]
Support for this is coming in version 3.0 -- you can track progress on that version by checking out the [v3](https://github.com/jlevers/selling-partner-api/tree/v3) branch.

**Comment by mishasaz** [comment]
Thank you for your work!
