### ISSUE TITLE
What happens if I don't remove "version=beta" when my application has been published?

### ISSUE THREAD

**Issue by Senpai10** [jlevers/selling-partner-api#430]
Hello guys,

This is a very dumb question but what happens if I let the "version=beta" parameter from the OAuth authorization URI(s) on production when my app has been approved and published by amazon ?

**Comment by jlevers** [comment]
As far as I know, nothing except that the authorization you perform with `version=beta` contributes to your 25 allowed unlisted-status OAuth authorizations. More details [here](https://developer-docs.amazon.com/sp-api/docs/application-authorization-limits).

**Comment by Senpai10** [comment]
Thanks for your answer @jlevers !

I'm asking because recently my clients have encountered an error: "invalid_grant", "The authorization grant or refresh token is invalid, expired, revoked, does not match the Device Token Request, or was issued to another client."

And I just noticed that I left "version=beta". Do you think this error could be caused by "version=beta" ?
