### ISSUE TITLE
Updating Inventory / Stocks doesn't work

### ISSUE THREAD

**Issue by PrimaryFlorian** [jlevers/selling-partner-api#433]
## Problem description:

Hi, 

the Feeds-Endpoint doesn't work for me. I'm not able to create a Feed Document.

## Error:

```
Exception when calling FeedsV20210630Api: [400] {"errors":[{"code":"400","message":"Invalid input","details":"Invalid input"}]} 
```

## Code

$this->Feeds is builded in constructor with FeedsV20210630Api containg the Configuration-Object. 

```php
        $body = new \SellingPartnerApi\Model\FeedsV20210630\CreateFeedDocumentSpecification(['content_type' => 'POST_INVENTORY_AVAILABILITY_DATA']);


        try {
            $result = $this->Feeds->createFeedDocument($body);
            echo "<pre>";
            print_r($result);
            echo "</pre>";
        } catch (\Exception $e) {
            echo 'Exception when calling FeedsV20210630Api: ', $e->getMessage(), PHP_EOL;
        }
```

How can I fix it? I just want to update the stocks

**Comment by PrimaryFlorian** [comment]
Fixed my two mistakes. 

Mistake #1: You can't use Sandbox-Mode I think.
Mistake #2 (definitely): Content_Type is not the Feed Type, it's the content_type in header, e.g. `'text/xml; charset=UTF-8'`

`        $body = new \SellingPartnerApi\Model\FeedsV20210630\CreateFeedDocumentSpecification(['content_type' => 'text/xml; charset=UTF-8']);


        try {
            $result = $this->Feeds->createFeedDocument($body);

            $FeedId = $result->getFeedDocumentId();

            echo "</pre>";
        } catch (\Exception $e) {
            echo 'Exception when calling FeedsV20210630Api: ', $e->getMessage(), PHP_EOL;
        }`


So this works finde but the Docs for createFeedDocument aren't good at all. :)

**Comment by jlevers** [comment]
There's a section [in the README](https://github.com/jlevers/selling-partner-api#uploading-a-feed-document) that I think does a pretty good job of describing how to use `createFeedDocument`, but if you'd like to improve it, I'm definitely open to PRs :)
