### ISSUE TITLE
API Calls not Working on Laravel Queue with Supervisor

### ISSUE THREAD

**Issue by saketkrb2b** [jlevers/selling-partner-api#439]
Hi, 
So, I am facing this strange issue. I have created laravel jobs that are triggered every six hours through the Laravel scheduler. The job is supposed to fetch the Amazon performance report using the reports api. It creates the report and then dispatches another job with report id to be triggered after 2 mins (by when the report will be in DONE status). The job gets successfully dispatched and processed when it is being run on localhost. However, when the exact same job is transferred to the production server with supervisor, the queue worker gets killed. I am not really sure what could be causing the issue. 
The supervisor workers work perfectly fine for other jobs. The job logs suggest that the termination happens the moment it start executing the following line: 

$reportResponse = $apiInstance->createReport($reportRequestBody);

Please note that all configurations are correct, have been checked very carefully multiple times and the job works perfectly fine on localhost. 

Is there a known issue with the API calls being made in jobs? Anyone faced a similar issue. 

Please let me know if more information is required to understand this further. Has been banging my head with this issue for more than 3 days now.

**Comment by steverobison** [comment]
I've not used laravel supervisor but i would guess the api is throwing an amazon api error which kills the worker.  Try putting that createReport inside of try/catch if you aren't already to see what the amazon error is.  Then also try running it on live but not through supervisor, just as through cli or a web function.  Just ideas to help you find it.

**Comment by jlevers** [comment]
This sounds more like a queue issue than an issue with the library to me, so I'm going to close it. If you find clues to the contrary, feel free to reopen the issue :)
