### ISSUE TITLE
I am getting [Access to requested resource is denied]

### ISSUE THREAD

**Issue by soseki-angfa** [jlevers/selling-partner-api#440]
## Problem description:
I am trying to call \SellingPartnerApi\Api\ProductPricingV0Api.
However, I can not call because of Access to requested resource is denied.

Could you please take a look at followings?

## Error:

```
  [403] 
{
"errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
```

## Code
```php
$config = new Configuration([
    "lwaClientId" => "amzn1.application-oa2-client.asdfdsfds",
    "lwaClientSecret" => "sadfsadfsad",
    "lwaRefreshToken" => "Atzr|IwsdasdfasdfjvAT9ttrxTBxxg9ANAG2SDCC2r-",
    "awsAccessKeyId" => "sdfasdfas",
    "awsSecretAccessKey" => "sdfa/sfdads+sdf/+rmo05aGP1",
    "endpoint" => Endpoint::NA,
]);

$api = new \SellingPartnerApi\Api\ProductPricingV0Api($config);
$marketplace_id = 'A1VC38T7YXB528';
$item_type = 'sku';
$result = $api->getCompetitivePricing($marketplace_id, $item_type);
```

## Seller Central SP API config page screenshot

![image](https://user-images.githubusercontent.com/106799197/206099490-5fb2e138-94ec-4276-81ca-f0f2c54391ae.png)

IAM User Policy is as following
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "execute-api:*",
                "sts:GetSessionToken",
                "sts:DecodeAuthorizationMessage",
                "sts:GetAccessKeyInfo",
                "sts:GetCallerIdentity",
                "sts:GetServiceBearerToken"
            ],
            "Resource": "*"
        }
    ]
}
```

I have been changing the above User Policy today.
But, it dose not work at all.
It seems like there is some problem with my User Policy, but, it dose not like me.
Do you have any suggestion for this?
Regards,

**Comment by soseki-angfa** [comment]
UPDATE: It seems I could get access token.
But, I cat not get the data because of above error message.

**Comment by sventhebarbarian** [comment]
I am receiving the same error although I believe I have entered all configuration params correctly, any way to debug?

I am attempting to connect to a UK Amazon seller account.

A note for @soseki-angfa have you set the correct endpoint? Your screenshot looks like it is Amazon's Japan site which would use Far East (Endpoint::FE) but your debug shows connecting to North America (sellingpartnerapi-na.amazon.com)

**Comment by soseki-angfa** [comment]
@sventhebarbarian 
Thank you very much for comment.
I want to use "Product Pricing API v0 ".
So, I set the endpoint to https://sellingpartnerapi-na.amazon.com,namely Endpoint::NA.

If I am wrong, please let me know.

Then, I will check if configuration for IAM user and seller central is okay.
But, I guess it should be okay since I can get refresh token from the API.

**Comment by soseki-angfa** [comment]
@soseki-angfa 
Here is my IAM policy.
![image](https://user-images.githubusercontent.com/106799197/208586679-f3fce834-108b-4782-86de-ed1cee9ef5d8.png)

**Comment by scabudlan** [comment]
I am also stuck with this problem, please help us!

**Comment by sventhebarbarian** [comment]
I was able to get past it but cannot say exactly how, I was juggling going through the process a couple of times and one worked so I stuck with it.

Try re-doing it with new IAM accounts, try different instructions on the net, some advise using IAM roles, some advise applying access directly to IAM users without roles, I also redid the authorization on Amazon seller account when playing around..

**Comment by soseki-angfa** [comment]
@sventhebarbarian 
Okay, thanks.
One bad thing is it dose not say what is wrong with it...

**Comment by soseki-angfa** [comment]
@scabudlan 
I found doc for this.
Hopefully, this may help us.
https://developer-docs.amazon.com/sp-api/docs/tutorial-create-a-private-selling-partner-api-application

By the way, you can use any of the method USER Based Authentication or Role Based Autentication

**Comment by steverobison** [comment]
I would also recommend getting the sp-api setup in postman too.  https://developer-docs.amazon.com/sp-api/docs/using-postman-for-selling-partner-api-models  - Has helped me a bunch r&d and debugging the api.

**Comment by jlevers** [comment]
@soseki-angfa I can see that you're using the Japan marketplace ID (`A1VC38T7YXB528`) in your API call, but specifying the North American endpoint in your configuration (`Endpoint::NA`). There may be other configuration issues, but the marketplace ID you're using needs to be for a marketplace in the region that you're making requests to.

**Comment by soseki-angfa** [comment]
@jlevers 
Thank you very much for this comment.
As you suggeusted, I changed Endpoint to Endpoint::FE.

Now I am getting NotFound error.
The suorce code is as following.
Am I missing parameters?
```
     $config->setDebug(true);
      $config->setDebugFile('./debug.log');
  
      $api = new \SellingPartnerApi\Api\ProductPricingV0Api($config);
      $marketplace_id = 'A1VC38T7YXB528';
      $item_type = 'SKU';
      $result = $api->getCompetitivePricing($marketplace_id, $item_type);                                     
      print_r($result);
```
The error message.
```
[404] {
  "errors": [
    {
      "code": "NotFound",
      "message": "The requested resource doesn\u0027t exist."
    }
  ]
}
```

**Comment by soseki-angfa** [comment]
By the way, I can call OrdersV0Api\getOrders().

**Comment by soseki-angfa** [comment]
@jlevers 
I just thought.....
404 means there is no data to be found on the request?

**Comment by jlevers** [comment]
You aren't passing any SKUs. Please read the documentation for the call [here](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/ProductPricingV0Api.md#getCompetitivePricing).

**Comment by soseki-angfa** [comment]
@jlevers 
Thank you very much for your help.
I thought it could ignored...
By the way, I guess SP-API dose not have the api that gives me all product sku..
Am I right?

**Comment by soseki-angfa** [comment]
@jlevers 
I am successfully could call the sp-api.
Thanks for your big help.
Here, what I was wrong.

1. item type is wrong.
This should be "Sku" or "Asin", otherwise, it gives me NotFound error.
2. The endpoint is wrong, not Endpoint::NA.
In my case, I have to specify Endpoint::FE
3. I did not pass correct number of parameter.
If we want to use Sku for calling the CompetitivePricing, I need to specify an array of sku.
 
Sample code
```
$item_type = 'Asin';
$asin = ["BSDF343SDFDS"];
$api = new \SellingPartnerApi\Api\ProductPricingV0Api($config);
$result = $api->getCompetitivePricing($marketplace_id, $item_type, $skus);
```
