### ISSUE TITLE
Can't use NextToken to get Order

### ISSUE THREAD

**Issue by clxit** [jlevers/selling-partner-api#441]
when i get more Orders,i receive NextToken like "...cWr+Y=".
if i use that to get order.i get error message 'the value of a query string parameter may not contain a '=' delimiter'.
i try use urlencode() ,but also error.
how to use it?
thanks

**Comment by MuhammadDanyal** [comment]
I was also facing the same issue try following the below link and it will work:
https://github.com/jlevers/selling-partner-api/issues/459

**Comment by gugglegum** [comment]
Yes, this issue is the same as #459. And I found solution. It's due to the changed arguments order in `getOrder()` method. Check out my answer in #459.

**Comment by clxit** [comment]
thank you。i have get orders by next token。thank you
