### ISSUE TITLE
Dealing with throttling

### ISSUE THREAD

**Issue by franclin** [jlevers/selling-partner-api#442]
Hi,

 I was wondering how you deal with throttling in your code please.

 For instance, the creation of reports (https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#createreport) is subject to a request per second rate of 0.0167 

 Are you making use of the value of x-amzn-RateLimit-Limit response header?

 Thanks

**Comment by steverobison** [comment]
Not the developer, but this app doesn't do anything about throttling other then throw the error using the try/catch stuff.  Its a good design plan for this api as it shouldn't as that would be overstepping what this app should do.  Its up to the main application that is using this api to handle the response header and implement back-off functionality.  

Amazon has some documentation about it.  https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api

**Comment by Kernel1453** [comment]
Hello,
Try to write two functions. 1st get report id, 2nd send reportId and get docId. Schedule 2nd 10 seconds after 1st function. While waiting you can show Please Wait while preparing..... or try to get reportt link to your users.

**Comment by franclin** [comment]
> Hello, Try to write two functions. 1st get report id, 2nd send reportId and get docId. Schedule 2nd 10 seconds after 1st function. While waiting you can show Please Wait while preparing..... or try to get reportt link to your users.

I was looking more into an algorithm that will leverage the x-amzn-RateLimit-Limit header

**Comment by Kernel1453** [comment]
> 

You can create a case for increasing limits to your developer Profile. But answer will be like " When your requests increase, we'll automatically increase your limits too".

**Comment by jlevers** [comment]
@franclin unfortunately the `x-amzn-RateLimit-Limit` header only tells you what the limit for the endpoint is, and doesn't tell you how many calls you have left and/or how long you have to wait before your next call, so designing a retry mechanism around it can be unreliable. I have no plans to add throttling handling to the library, so I'm going to close this issue.
