### ISSUE TITLE
Uncaught Error: Class 'SellingPartnerApi\Endpoint' not found

### ISSUE THREAD

**Issue by JeffMash** [jlevers/selling-partner-api#453]
I apologize for the simple question (I'm really new to implementing all this stuff).

When running your example (index.php), I am getting the following error and I don't know why:

Fatal error: Uncaught Error: Class 'SellingPartnerApi\Endpoint' not found in /home/username/public_html/store/backorder/AWS_SPAPI/index.php:14 Stack trace: #0 {main} thrown in /home/username/public_html/store/backorder/AWS_SPAPI/index.php on line 14

It's okay to talk to me like a complete dummy, because I probably am!

1.  On my server, I have a directory I called "AWS_SPAPI"
2.  I ran composer install and put your library (so now there's a "vendor" subfolder in that directory)
3. I created the index.php file in the main "AWS_SPAPI" directory and filled in all the configuration data
4. My Application Role does have the "Selling Partner Insights" checked.
5. I followed all the steps to create the IAM User and Roles, etc.

What am I missing?  Is it something in the install I did, or perhaps a permissions issue with the folders/files on my server?   Thanks for any help you can provide!

**Comment by Kernel1453** [comment]
Please hide Keys and paste your index.php here for review.

**Comment by soseki-angfa** [comment]
@JeffMash 
There is a fix 2 days ago. So, please update itself.

**Comment by JeffMash** [comment]
> Please hide Keys and paste your index.php here for review.

This is the contents of my index.php file:

```
<?php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersV1Api as SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
    "lwaClientId" => "amzn1.application-oa2-client.3e90bd9a569XXXXXXXXXXXXXXXXXXXXX",
    "lwaClientSecret" => "f64a8c4e0c804c73b4726944b58de43881fb1dXXXXXXXXXXXXXXXXXXXXX",
    "lwaRefreshToken" => "Atzr|IwEBIOXEAhPV8L8TOLnryQ5DqmkYidP3epC-XXXXXXXXXXXXXXXXXXXXX",
    "awsAccessKeyId" => "AKIASEWNN4XXXXXXXXXXXXXXXXXXXXX",
    "awsSecretAccessKey" => "rpE9y2KoIwS0Ywa7vU9WX51K0wXXXXXXXXXXXXXXXXXXXXX",
	"roleArn" => "arn:aws:iam::147533XXXXXXXXXXXXXXXXX:role/ExecuteSPAPI",
    "endpoint" => Endpoint::NA  // or another endpoint from lib/Endpoint.php
]);

$api = new SellersApi($config);
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ',
        $e->getMessage(),
        PHP_EOL;
}
```

As you can see, I have the "roleARN" in there because my App is using the role as the ARN.

I just did a "composer update" in my seller-partner-api folder, but that didn't seem to fix the error.   I still am getting:

`Fatal error: Uncaught Error: Class 'SellingPartnerApi\Endpoint' not found in /home/username/public_html/store/backorder/AWS_SPAPI/index.php:15 Stack trace: #0 {main} thrown in /home/username/public_html/store/backorder/AWS_SPAPI/index.php on line 15`

(Line 15 is the  "endpoint" => Endpoint::NA)

Still looking for any help, and I appreciate all your efforts!  <3

**Comment by JeffMash** [comment]
Looks like this issue was resolved with the latest update.   Thank you @soseki-angfa for pointing me in that direction!

**Comment by toby11** [comment]
any reason why this update is not installed when installing composer?

**Comment by soseki-angfa** [comment]
@toby11 
This isssue has been fixed and I have no problem with it.
I guess you should check composer.json.
