### ISSUE TITLE
5.2.2:VM/HGQ\u003d\u003d is not valid; the value of a query string parameter may not contain a \u0027\u003d\u0027 delimiter

### ISSUE THREAD

**Issue by star-081** [jlevers/selling-partner-api#454]
## Problem description:
jlevers/selling-partner-api  5.5.2,    the api "getOrders" sudden the problem:

"message": "\u0026Action\u003dListOrders\u0026Version\u003d2013-09-01\u0026SellerId\u003dA1WAFYMZ5Z80OH\u0026CreatedAfter\u003d2022-01-08T00:00:00Z\u0026CreatedBefore\u003d2022-01-09T00:00:00Z\u0026MarketplaceId.Id.1\u003dATVPDKIKX0DER\u0026MarketplaceId.Id.2\u003dA2EUQ1WTGCTBG2\u0026MarketplaceId.Id.3\u003dA1AM78C64UM0Y8\u0026MarketplaceId.Id.4\u003dA2Q3Y263D00KWC\u0026MaxResultsPerPage\u003d50\u0026ElectronicInvoiceStatus.Status.1\u003dYtqQ7t//9huaJqJYLDm0ZAmQazDrhw3Cr8qlDXzgmb1UojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy+2E9Hb5tLZvPajN6uGFcoSvQc2GE4VT2tOtYnIyYlzpiInTAy+XKVmRZBY+oaVuycwQFure81U/ClAaAVwbxHLa7Ab1L9KJVvIDmpd1calcFf2GLmUGyr9UGnxD0RJmrryegoU0IPZxXXD37mnKQgpHG8ON0YhrNiMN0ZSqIPwMTMBO/reDY2s/v6DywD2BmVI0KxWlk275HcwL20LTtrzX4RdX8TYd2vY/hmEkfuviGuLwLoCuIp4RS2HgrtrpPNwLv81ok7XMvb5p4oOdihWAT+lSSkl9LyGgVGOZd77LM7YYXwRo+g8JfownguvYNQduZ3sLNMwtc3eXHfp1pupKBww9GX7PZY2F0A7oTEFUvdoKsRYeW9B3OkrSp3YyTE22EuLn1sywvEsqGJJJsu8+Pnp7zXB4uNYQPHuINDRJ2MPMIfg4CK8jPZjTnVM/HGQ\u003d\u003d is not valid; the value of a query string parameter may not contain a \u0027\u003d\u0027 delimiter"

arguments: {
        $marketplace_ids: array:4 [ …4]
        $created_after: "2022-01-08T00:00:00Z"
        $created_before: "2022-01-09T00:00:00Z"
        $last_updated_after: null
        $last_updated_before: null
        $order_statuses: null
        $fulfillment_channels: null
        $payment_methods: null
        $buyer_email: null
        $seller_order_id: null
        $max_results_per_page: 50
        $easy_ship_shipment_statuses: null
        $electronic_invoice_statuses: "YtqQ7t//9huaJqJYLDm0ZAmQazDrhw3Cr8qlDXzgmb1UojdU4H46tsNI3HOI22PIxqXyQLkGMBs8VhF73Xgy+2E9Hb5tLZvPajN6uGFcoSvQc2GE4VT2tOtYnIyYlzpiInTAy+XKVmRZBY+oaVuycwQFure81U/ClAaAVwbxHLa7Ab1L9KJVvIDmpd1calcFf2GLmUGyr9UGnxD0RJmrryegoU0IPZxXXD37mnKQgpHG8ON0YhrNiMN0ZSqIPwMTMBO/reDY2s/v6DywD2BmVI0KxWlk275HcwL20LTtrzX4RdX8TYd2vY/hmEkfuviGuLwLoCuIp4RS2HgrtrpPNwLv81ok7XMvb5p4oOdihWAT+lSSkl9LyGgVGOZd77LM7YYXwRo+g8JfownguvYNQduZ3sLNMwtc3eXHfp1pupKBww9GX7PZY2F0A7oTEFUvdoKsRYeW9B3OkrSp3YyTE22EuLn1sywvEsqGJJJsu8+Pnp7zXB4uNYQPHuINDRJ2MPMIfg4CK8jPZjTnVM/HGQ=="
        $next_token: null
        $amazon_order_ids: null
        $actual_fulfillment_supply_source_id: null
        $is_ispu: null
        $store_chain_store_id: null
      }
    }

5.1.1 don't have this problem.

## Error:

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by gugglegum** [comment]
Have same problem on the latest 5.5.3. Appears on the second call of getOrders.

**Comment by star-081** [comment]
你的邮件已收到了~~~

**Comment by gugglegum** [comment]
I found the problem. For me the last working version was 5.2.5. Since 5.3.0 it returns the subject error. When I compared `OrdersV0Api.php` file in 5.2.5 and 5.3.0 I noticed that the signature of `getOrders()` method has been changed. Since 5.3.0 there was added a new argument `$electronic_invoice_statuses` between `$easy_ship_shipment_statuses` and `$next_token`. My code was written before 5.3.0 and was using old arguments order. Due to this change in 5.3.0 my $next_token argument was passed as `$electronic_invoice_statuses` and seems it was incorrect value. I just added a `null` argument before `$next_token` and problem was solved. So the problem was in my code. Here's how I retrieve orders portion now:

```
            return $this->ordersApi->getOrders([$this->amazonMarketplaceId],
                $this->createdAfterDate?->toIso8601ZuluString(),
                $this->createdBeforeDate?->toIso8601ZuluString(),
                $this->updatedAfterDate?->toIso8601ZuluString(),
                $this->updatedBeforeDate?->toIso8601ZuluString(),
                $this->statuses ?? null,
                $this->fulfillmentChannels ?? null,
                null,
                null,
                null,
                100,
                null,
                null,                     // <--- this argument I added to fix this problem
                $this->nextToken,
                $this->amazonOrderIds ?? null,
                null,
                null,
                null,
                null // ['buyerInfo', 'shippingAddress'] // commented due to no access to restricted data
            );
```

**Comment by star-081** [comment]
你的邮件已收到了~~~
