### ISSUE TITLE
CatalogItemsV20220401 update

### ISSUE THREAD

**Issue by KhorneHoly** [jlevers/selling-partner-api#456]
The returned attributes of the Catalog Items v2022-04-01 API got updated. The library should be extended to match the update.

You can find the full changelog here: https://developer-docs.amazon.com/sp-api/changelog/catalog-items-v2022-04-01-updated-to-include-additional-attributes

**Comment by jlevers** [comment]
This should be fixed in `v5.5.3`. Let me know if you continue to run into issues.
