### ISSUE TITLE
Unable to fetch orders using next token

### ISSUE THREAD

**Issue by MuhammadDanyal** [jlevers/selling-partner-api#459]
## Problem description: 
We are able to get the first hundred orders from orders API successfully, while for getting orders on next page we are passing mandatory parametrs MarketPlace and NextToken as a parameter to getOrders function but it is not working. Even we pass $lastUpdatedAfter='';
 $lastUpdatedBefore='';
 $order_status = array('Shipped');
 $fulfillment_channels = array('AFN', 'MFN');
 $payment_methods = array('CVS', 'Other','COD');
 $max_results_per_page = 56; but it's not working.

## Error:

```
# 
Exception when calling OrdersV0Api->getOrders: [400] { "errors": [ { "code": "InvalidInput", "message": "This is an invalid input", "details": "Invalid Date-Time field(s) [createdAfter]." } ] }
```

## Code

```php
$result = $apiInstance->getOrders($marketplace_ids, $next_token);
  print_r($result); 
``` 

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by KhorneHoly** [comment]
From my understanding, you must send the exact same request again and add the `NextToken` additionally. I'm using it like this and I haven't had any trouble getting the next pages that way.

So, as example from my system, the first request:

```
$result = $this->ordersApi->getOrders(
    marketplace_ids: $marketplaceIds,
    last_updated_after: $lastFeedAmaShipmentReport->format('Y-m-d\TH:i:s'),
    last_updated_before: $dateBefore?->format('Y-m-d\TH:i:s'),
    fulfillment_channels: 'MFN',
    data_elements: ['buyerInfo', 'shippingAddress']
);
```

If a `NextToken` is provided in the result, my next request looks like this:

```
$result = $this->ordersApi->getOrders(
    marketplace_ids: $marketplaceIds,
    last_updated_after: $lastFeedAmaShipmentReport->format('Y-m-d\TH:i:s'),
    last_updated_before: $dateBefore?->format('Y-m-d\TH:i:s'),
    fulfillment_channels: 'MFN',
    next_token: $nextToken
    data_elements: ['buyerInfo', 'shippingAddress']
);
```
Keep in mind, that the second result might contain a new `NextToken` for the third page and so forth, so you always need to use the new `NextToken` until none is returned.

**Comment by MuhammadDanyal** [comment]
using the example that you have provided in your code i was able to get it done. Thanks

**Comment by gugglegum** [comment]
You cannot call `getOrder` like that `$apiInstance->getOrders($marketplace_ids, $next_token);`. This method has 19 arguments. And each argument should be on its place. The `$next_token` should be on 14th place. If you don't need anything other, you have to insert 12 `null` arguments between `$marketplace_ids` and `$next_token`.

**Comment by mtarique** [comment]
I am getting NextToken emty or null error getShipments

Any idea how to do that
