### ISSUE TITLE
Migration to catalogItems_2020-12-01.md API

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#46]
Amazon MWS Products section and Selling Partner Catalog Items v0 operations to be deprecated on March 31, 2022

https://github.com/amzn/selling-partner-api-docs/issues/904 

Do we have this in our roadmap?

**Comment by jlevers** [comment]
Yes -- the new version of the Catalog and Products APIs will be released in v3. I'm planning to release v3 in early July, once the new Feeds and Reports APIs have been released and I've had a chance to test with them.
