### ISSUE TITLE
getCompetitivePricing returns "Offers" as NULL

### ISSUE THREAD

**Issue by yourguide** [jlevers/selling-partner-api#462]
I am able to use the getCompetitivePricing to return data using a list of ASINS... but it appears that "Offer" data is not included as it is NULL.

I have used the other API pricing function GetListingOffers... but it is limited to one product at a time.  I am working on getting the GetListingOffersBatch working... but I really like all the information coming from the getCompetitivePricing  call and would prefer to have it if it included the Offers for each ASIN.

Is this possible? 
Thanks!

**Comment by jlevers** [comment]
This appears to be an issue on Amazon's end, because in the raw JSON response from the API, the `offers` array is empty or missing in every test request I've made. I recommend opening a support request with them.
