### ISSUE TITLE
Vendor Direct Fulfillment Inventory API v1 reference

### ISSUE THREAD

**Issue by Tradetechnique** [jlevers/selling-partner-api#468]
Hi,
Someone know how to use Vendor Direct Fulfillment Inventory API v1 reference on : 
https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/VendorDirectFulfillmentInventoryV1Api.md

I need to update quantity of my product on my account vendor?

Thanks

**Comment by jlevers** [comment]
You can't update vendor quantities via the SP API – unfortunately, you have to integrate with their EDI system using the `COSTINV` message type for inventory quantity and cost prices updates.
