### ISSUE TITLE
createInboundShipmentPlanRequest creates wrong body

### ISSUE THREAD

**Issue by M-Mommsen** [jlevers/selling-partner-api#469]
regarding the function createInboundShipmentPlanRequest in FbaInboundV0Api.php

In my tests $httpBody gets build to:
{
  "InboundShipmentHeader": {
    "ShipFromAddress": {
      "Name": "TheName",
      "AddressLine1": "Strasse 1",
      "City": "Hamburg",
      "StateOrProvinceCode": "HH",
      "CountryCode": "DE",
      "PostalCode": "22000"
    },
    "LabelPrepPreference": "SELLER_LABEL"
  },
  "InboundShipmentItems": [
    {
      "SellerSKU": "ITEMNO1",
      "Quantity": "1"
    }
  ],
  "MarketplaceId": "A1PA6795UKMFR9"
}

This results in "Reason: Country field is missing, Name field is missing, AddressLine1 field is missing."
Also later, when correcting the ShipFromAddress address structure manually,I got "InboundShipmentPlanRequestItem can not be empty"

So, what actually works is:
{
  "**ShipFromAddress**": {
    "Name": "TheName",
    "AddressLine1": "Strasse 1",
    "City": "Hamburg",
    "StateOrProvinceCode": "HH",
    "CountryCode": "DE",
    "PostalCode": "22000"
  },
  "LabelPrepPreference": "SELLER_LABEL",
  "**InboundShipmentPlanRequestItems**": [
    {
      "SellerSKU": "ITEMNO1",
      "Quantity": "1"
    }
  ],
  "MarketplaceId": "A1PA6795UKMFR9"
}

So the address parent "InboundShipmentHeader" should be removed, and "InboundShipmentItems" renamed to "InboundShipmentPlanRequestItems"

Also there is an example in https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v0-use-case-guide#request-example-9

**Comment by M-Mommsen** [comment]
Found the problem. I passed the wrong request to the function.  There seems to be no checking. It got serialzed and sent...

Just in case someone else is missing an example.
This works:

$inbound_api=new \SellingPartnerApi\Api\FbaInboundV0Api($sp_api_config);
$shipFromAddress=new \SellingPartnerApi\Model\FbaInboundV0\Address();
$shipFromAddress->setName('My Company');
$shipFromAddress->setAddressLine1('My Street');
$shipFromAddress->setCity('My City');
$shipFromAddress->setCountryCode('DE');
$shipFromAddress->setPostalCode('12345');
$shipFromAddress->setStateOrProvinceCode('##');
$inboundShipmentPlanItemList=[];
foreach($articles as $article) {
	$inboundShipmentPlanRequestItem = new \SellingPartnerApi\Model\FbaInboundV0\InboundShipmentPlanRequestItem();
	$inboundShipmentPlanRequestItem->setSellerSku($article['Sku']);
	$inboundShipmentPlanRequestItem->setQuantity($article['Quantity']);
    $inboundShipmentPlanItemList[]=$inboundShipmentPlanRequestItem;
}

$createInboundShipmentPlanRequest = new \SellingPartnerApi\Model\FbaInboundV0\CreateInboundShipmentPlanRequest();
$createInboundShipmentPlanRequest->setLabelPrepPreference('SELLER_LABEL');
$createInboundShipmentPlanRequest->setShipFromAddress($shipFromAddress);
$createInboundShipmentPlanRequest->setInboundShipmentPlanRequestItems($inboundShipmentPlanItemList);

$createInboundShipmentPlanResponse=$inbound_api->createInboundShipmentPlan($createInboundShipmentPlanRequest);

**Comment by mo86** [comment]
@M-Mommsen Thank you so much for your example. It helped me a lot. How do you proceed with the createInboundShipmentPlanResponse ? What are the next steps to make the shipment complete?

Thank you

**Comment by M-Mommsen** [comment]
I don't remember the whole process.
After parsing the shipmentplan it needs to be shipped.  Which is another script in my environment.
I am using something like this:
`	$inbound_api=new \SellingPartnerApi\Api\FbaInboundV0Api($sp_api_config);

	$shipFromAddress=new \SellingPartnerApi\Model\FbaInboundV0\Address();
	$shipFromAddress->setName('Company Name);
	$shipFromAddress->setAddressLine1('Street');
	$shipFromAddress->setCity('City');
	$shipFromAddress->setCountryCode('DE');
	$shipFromAddress->setPostalCode('12345');
	$shipFromAddress->setStateOrProvinceCode('SH');

	$inboundShipmentHeader = new \SellingPartnerApi\Model\FbaInboundV0\InboundShipmentHeader();
	$inboundShipmentHeader->setShipFromAddress($shipFromAddress);
	$inboundShipmentHeader->setShipmentName($shipmentName);
	$inboundShipmentHeader->setLabelPrepPreference(\SellingPartnerApi\Model\FbaInboundV0\LabelPrepType::SELLER_LABEL);
	$inboundShipmentHeader->setShipmentStatus(SellingPartnerApi\Model\FbaInboundV0\ShipmentStatus::SHIPPED);


	foreach($shipments as $shipment) {
		$inboundShipmentHeader->setDestinationFulfillmentCenterId($shipment['FulfillmentCenterId']);

		$articles = array();
		foreach($shipment['Boxes'] ?? $shipment as $box) {
			foreach($box['Articles'] as $article) {
				if(array_key_exists($article['Sku'], $articles)) {
					$articles[$article['Sku']] += $article['Quantity'];
				} else {
					$articles[$article['Sku']] = $article['Quantity'];
				}
			}
		}

		$inboundShipmentItemList= [];
		foreach($articles as $sku => $quantity) {
			$inboundShipmentItem = new \SellingPartnerApi\Model\FbaInboundV0\InboundShipmentItem();
			$inboundShipmentItem->setSellerSKU($sku);
			$inboundShipmentItem->setQuantityShipped($quantity);
	//        $inboundShipmentItem->setQuantityInCase($quantity);
			$inboundShipmentItemList[]=$inboundShipmentItem;
		}

		$createInboundShipmentRequest = new \SellingPartnerApi\Model\FbaInboundV0\InboundShipmentRequest();
		$createInboundShipmentRequest->setInboundShipmentHeader($inboundShipmentHeader);
		$createInboundShipmentRequest->setInboundShipmentItems($inboundShipmentItemList);
		$createInboundShipmentRequest->setMarketplaceId($marketplace_id);

		$throttleSleep = 1;
		do {
			$isThrottled = false;
			try {
				$createInboundShipmentResponse = $inbound_api->updateInboundShipment($shipment['Id'],$createInboundShipmentRequest);
			} catch(Exception $exception) {
				if($exception->getCode()==503 || $exception->getCode()==429) {
					sleep($throttleSleep);
					if(64 > $throttleSleep) {
						$throttleSleep *= 2;
					}
					$isThrottled = true;
				} else {
					echo "Header:<br/><pre>".htmlentities(print_r($createInboundShipmentRequest->toHeaderValue(),true))."</pre><br/>";
					echo "Exception:<br/><pre>".htmlentities(print_r($exception,true))."</pre><br/>";
					die();
				}
			}
		} while($isThrottled);
	}
`
