### ISSUE TITLE
Docs should state PHP 7.3 requirement

### ISSUE THREAD

**Issue by andyknas** [jlevers/selling-partner-api#47]
But you have trailing commas - 7.2 throws a parse error for these in Configuration.php.  Should update to reflect that 7.3 is needed.

`PHP Parse error:  syntax error, unexpected ')' in /var/www/html/integration/amazon_sp/lib/Configuration.php on line 124`

Host is PHP Version 7.2.34-21+ubuntu16.04.1+deb.sury.org+1

**Comment by jlevers** [comment]
Thanks for reporting -- this version of the library should be compatible with PHP 7.2. The trailing comma issue is fixed in v2.3.2.
