### ISSUE TITLE
Application do not have access to some or all requested resource

### ISSUE THREAD

**Issue by muglali20** [jlevers/selling-partner-api#476]
## Problem description:
Application do not have access to some or all requested resource I get an error
## Error:

```
[400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application do not have access to some or all requested resource",
      "details": ""
    }
  ]
}
```

The same error returns when I buy a new token.
Can You Support On This Issue?
## Code

```php
$data_elements = array('buyerInfo'); 
$result = $apiInstance->getOrder($order_id,$data_elements);


```

## Seller Central SP API config page screenshot
https://i.hizliresim.com/k2jjuyf.png
https://i.hizliresim.com/3xrk746.png

**Comment by statsmarketing** [comment]
Same issue here after updating the SDK from older version and utilizing the getOrder API.

**Comment by muglali20** [comment]
I wonder what we need to do, does everyone have this problem, how can we overcome it?

**Comment by muglali20** [comment]
@schellj
Hello;
  Can you support for this Issue?

**Comment by schellj** [comment]
It's a bit hard to tell since your screen shots aren't in english, but your app seems to have all of the access scopes. Has Amazon approved your app?

**Comment by muglali20** [comment]
yes, can you see it here?

https://sellercentral.amazon.com.tr/selling-partner-appstore/dp/amzn1.sp.solution.3fcbece7-7767-43a8-9df6-1c7fe32befb9

**Comment by schellj** [comment]
Yes, I see your app.

I'm not familiar with this repo, so it's a little hard to help debug. However, I do know that in order to get the buyer info from an order you need a restricted data token (RDT); is your code requesting and using one?

**Comment by muglali20** [comment]
Which library do you use, can you get customer cargo information? necessary information for the cargo I need

**Comment by schellj** [comment]
Sorry, but I can't really get into that, but your code and/or whatever library you use is going to need to use an RDT to get that data.

**Comment by muglali20** [comment]
#

> Sorry, but I can't really get into that, but your code and/or whatever library you use is going to need to use an RDT to get that data.

can you support this

@jlevers

**Comment by jlevers** [comment]
@muglali20 this library automatically requests an RDT for you if you have PII access. Do you have access to one or both of the Tax Invoicing or Tax Remittance roles? I can't tell from your screenshots as I don't speak Turkish.

What version of the library are you using, and did you recently upgrade from an older version?

**Comment by muglali20** [comment]
> @muglali20 this library automatically requests an RDT for you if you have PII access. Do you have access to one or both of the Tax Invoicing or Tax Remittance roles? I can't tell from your screenshots as I don't speak Turkish.
> 
> What version of the library are you using, and did you recently upgrade from an older version?

@jlevers 
thanks for your answer. I downloaded and installed the library up to date. Can you check the application images attached?
Could you please help me as to why I am getting this error?
https://i.hizliresim.com/jaqx9t5.png
https://i.hizliresim.com/1holpbi.png

**Comment by jlevers** [comment]
Delegating access to PII (as you've done for your SP API application) does not allow you yourself to access it. If you want to directly access PII, you need to apply for access to whichever restricted roles you need (one or more of Direct-to-Consumer Shipping, Tax Remittance, and Tax Invoicing, depending what you need – details [here](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api)). The two restricted tax-related roles will both get you access to buyer info.

Until you get approved for restricted roles, you will not be able to make requests to the SP API requesting PII.
