### ISSUE TITLE
getOrders -> You exceeded your quota for the requested resource. code: QuotaExceeded

### ISSUE THREAD

**Issue by statsmarketing** [jlevers/selling-partner-api#477]
## Problem description:
Been using this for past year or so no problems.

Took it offline for about 3 mos and now it will not work.

When looping through the getOrderItems Api.

## Error:
```
SellingPartnerApi\ApiException Object
(
    [message:protected] => [429] {
  "errors": [
    {
      "message": "You exceeded your quota for the requested resource.",
     "code": "QuotaExceeded"
    }
  ]
}
```

Any information on what to do to rectify this error?

**Comment by muglali20** [comment]
Hello; I have this week too, how did you overcome this error? can you help me?

https://github.com/jlevers/selling-partner-api/issues/476

**Comment by statsmarketing** [comment]
I have resolved the issue with the old SDK, but still have the access issue with the new SDK.

I believe that Amazon updated their rate limits, therefore my `foreach` inside my `try` messes it up. 

I also put `null` for all blank parameters.

I removed creating the array of order items inside the `try`:

`try {
	$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses,$fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements);
	
	$order_array['order_data'] = $result->getPayload();
	
	// Create Array of Order Items
        //begin removal here
	foreach($result->getPayload()->getOrders() as $list_orders){
		$order_id = $list_orders->getAmazonOrderId();
		$order_result = $apiInstance->getOrderItems($order_id);
		
		$order_result_array['order_items'][] = $order_result->getPayload();

	}
	$the_orders[]=$order_array;
	$the_orders[]=$order_result_array;
        //end removal
	print_r(json_encode($the_orders));
	

} catch (Exception $e) {
	echo '<pre>';
print_r($e);
echo '</pre>';
    echo 'Exception when calling SellersApi->getOrders: ', $e->getMessage(), PHP_EOL;
}`

**Comment by muglali20** [comment]
Yes, I can get the Order List without any problem, but for the shipping address and customer information.
`$result = $apiInstance->getOrder($order_id,$data_elements);`

> Application do not have access to some or all requested resource I get an error

Error Returns I Can't Get Information for Cargo

**Comment by statsmarketing** [comment]
> Yes, I can get the Order List without any problem, but for the shipping address and customer information. `$data_elements = array('buyerInfo'); $result = $apiInstance->getOrder($order_id,$data_elements);`
> 
> > Application do not have access to some or all requested resource I get an error
> 
> Error Returns I Can't Get Information for Cargo

Did you try to use `getOrders()` instead of `getOrder()` ?

`$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses,$fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements);`

**Comment by muglali20** [comment]
In the get Orders method, I take a list and request for order detail information about the get Order method.
How do you process the order detail?
`
$order_id='xxx';
$data_elements = array('buyerInfo'); 
$result = $apiInstance->getOrders($order_id,$data_elements);
`
But I do it this way

> Application do not have access to some or all requested resource"

it gives error

**Comment by statsmarketing** [comment]
The way I have always done it was to pull all orders with `getOrders()` from a `created_after` date, loop through them and call `getOrderItems($order_id)` on each of them.  But I am running into new rate limits.

```
try {
	$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before, $last_updated_after, $last_updated_before, $order_statuses,$fulfillment_channels, $payment_methods, $buyer_email, $seller_order_id, $max_results_per_page, $easy_ship_shipment_statuses, $next_token, $amazon_order_ids, $actual_fulfillment_supply_source_id, $is_ispu, $store_chain_store_id, $data_elements);
	$order_array['order_data'] = $result->getPayload();
	
	foreach($result->getPayload()->getOrders() as $list_orders){
		$order_id = $list_orders->getAmazonOrderId();
		$order_result = $apiInstance->getOrderItems($order_id);
		
		$order_result_array['order_items'][] = $order_result->getPayload();

	}
	$the_orders[]=$order_array;
	$the_orders[]=$order_result_array;
	print_r(json_encode($the_orders));

}
```

**Comment by muglali20** [comment]
> $order_array['order_data'] = $result->getPayload();

`[container:protected] => Array
                                                                (
                                                                    [name] => null
                                                                    [address_line1] => null
                                                                    [address_line2] => null
                                                                    [address_line3] => 
                                                                    [city] => İstanbul
                                                                    [county] => 
                                                                    [district] => 
                                                                    [state_or_region] => Fatih
                                                                    [municipality] => 
                                                                    [postal_code] => 34134
                                                                    [country_code] => TR
                                                                    [phone] => null
                                                                    [address_type] => 
                                                                )

                                                        )`

Customer Cargo and Invoice information does not come, how do you request them?

**Comment by statsmarketing** [comment]
In the `getOrders` operation I ensure the following parameters:

`$data_elements = array('shippingAddress','buyerInfo'); `
`$order_statuses = array('Unshipped','PartiallyShipped');`

Make sure the others are `null`.

Now I could NOT get this working with this new SDK as I was getting the same message as you were about access issues.

**Comment by muglali20** [comment]
$data_elements = array('shippingAddress','buyerInfo'); 
Returned Reply
`
    [container:protected] => Array
        (
            [payload] => SellingPartnerApi\Model\OrdersV0\OrdersList Object
                (
                    [container:protected] => Array
                        (
                            [orders] => Array
                                (
                                )

                            [next_token] => 
                            [last_updated_before] => 
                            [created_before] => 2023-02-08T00:00:00Z
                        )

                )
`

$data_elements = array(); 
Returned Reply
`orders] => Array
                                (
                                    [0] => SellingPartnerApi\Model\OrdersV0\Order Object
                                        (
                                            [container:protected] => Array
                                                (
                                                    [amazon_order_id] => 404-6346577-xxx
                                                    [seller_order_id] => 
                                                    [purchase_date] => 2023-02-07T10:28:38Z
                                                    [last_update_date] => 2023-02-08T11:52:26Z
                                                    [order_status] => Shipped
                                                    [fulfillment_channel] => MFN
                                                    [sales_channel] => Amazon.com.tr
                                                    [order_channel] => 
                                                    [ship_service_level] => std-ez-tr
                                                    [order_total] => SellingPartnerApi\Model\OrdersV0\Money Object
                                                        (
                                                            [container:protected] => Array
                                                                (
                                                                    [currency_code] => TRY
                                                                    [amount] => 60.49
`...
When "buyer Info" Requests, List Returns Empty. Do you have any information?

**Comment by jlevers** [comment]
You need access to one or more of the [restricted roles](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api) in order to retrieve PII (the `buyerInfo` and `shippingAddress` `$data_elements` values both indicate that you're requesting PII from the SP API). The buyer info and shipping address will come back empty if you haven't been approved for PII on your Developer Profile in Seller Central.
