### ISSUE TITLE
getReports API returns 403 for restricted reports

### ISSUE THREAD

**Issue by ansgarbecker** [jlevers/selling-partner-api#478]
## Problem description:
Similar to what you already solved for `getReportDocument` in #262 , I get a 403/Unauthorized response when retrieving a list of ready-to-download reports.
I guess the `getReports` operation does not yet get an RDT token?
The developer profile in Seller Central has PII access. At least the "data access" option is set like [documented](https://developer-docs.amazon.com/sp-api/docs/registering-as-a-developer#to-register-as-a-private-developer-for-private-seller-applications) :
> Private Developer: I build application(s) that integrate my own company with Amazon Services APIs.

## Error:

```
SellingPartnerApi\ApiException: [403] {
  "errors": [
    {
      "code": "Unauthorized",
      "message": "Access to the resource is forbidden",
      "details": ""
    }
  ]
}
```

## Code

```php
$reportsApi = new ReportsV20210630Api($this->configuration);
$response = $reportsApi->getReports(['GET_ORDER_REPORT_DATA_INVOICING']);
```

**Comment by ansgarbecker** [comment]
Here's a patch for Authentication.php, which should fix this.
I'm just not sure if there is a `reportTypes` array in the `$params`, and if they need to be removed in the end, like `reportType` above.

```
 .../jlevers/selling-partner-api/lib/Authentication.php  | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)

diff --git a/jlevers/selling-partner-api/lib/Authentication.php b/jlevers/selling-partner-api/lib/Authentication.php
index fd26012c5..7ec97534b 100644
--- a/jlevers/selling-partner-api/lib/Authentication.php
+++ b/jlevers/selling-partner-api/lib/Authentication.php
@@ -189,6 +189,23 @@ class Authentication implements RequestSignerContract
                 // Remove the extra 'reportType' query parameter
                 $newUri = Psr7\Uri::withoutQueryValue($request->getUri(), 'reportType');
                 $request = $request->withUri($newUri);
+            } else if ($operation === 'getReports') {
+                // getReports calls need an RDT if one or more of the report types are restricted
+                $needRdt = false;
+
+                if(!empty($params['reportTypes'])) {
+                    foreach($params['reportTypes'] as $reportType) {
+                        $constantPath = 'SellingPartnerApi\ReportType::' . $reportType;
+                        if(defined($constantPath) && constant($constantPath)['restricted']) {
+                            $needRdt = true;
+                            break;
+                        }
+                    }
+                }
+
+                if(!$needRdt) {
+                    $relevantCreds = $this->getAwsCredentials();
+                }
             } else if (isset($params['dataElements'])) {
                 // Remove the extra 'dataElements' query parameter
                 $newUri = Psr7\Uri::withoutQueryValue($request->getUri(), 'dataElements');
```

**Comment by ansgarbecker** [comment]
My patch above is incomplete. To force generating an RDT I added the operation "getReports" to  `ReportsV20210630Api->getReportsWithHttpInfo`:
```php
$signedRequest = $this->config->signRequest($request, null, $request->getUri()->getPath(), "getReports");
```
But then the API returns a 400/ApiException: InvalidInput, "_Invalid or unsupported document ID found_". I guess the `getReports` operation does not work with an RDT.

@jlevers do you have any clue why we get an 403/Unauthorized when calling `$reportsApi->getReports(['GET_ORDER_REPORT_DATA_INVOICING']);` ?

**Comment by Julian3004** [comment]
I cant find the Tax Invoicing (restricted). U mean the authorization in my Role?
