### ISSUE TITLE
getOrderAddress Problem for NA Region

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#479]
Hello Everyone,

I have problems about my new users. When we are trying to download past orders, we cant get Addresses. You can see my response below. in this site https://sellercentral.amazon.com/sp-api-status, i see some problems for na region. is there any other way to get orders from sellercentral? 

SellingPartnerApi\Model\OrdersV0\Address {#4766 ▼
  #container: array:13 [▼
    "name" => ""
    "address_line1" => null
    "address_line2" => null
    "address_line3" => null
    "city" => "Calgary"
    "county" => null
    "district" => null
    "state_or_region" => "Alberta"
    "municipality" => null
    "postal_code" => "T2* 1**"
    "country_code" => "CA"
    "phone" => null
    "address_type" => null
  ]
}

Thank you very much.

**Comment by jlevers** [comment]
Were you approved for PII access using the Selling Partner API? To retrieve shipping addresses, you need to have been approved for the restricted [Direct-to-Consumer Shipping role](https://developer-docs.amazon.com/sp-api/docs/direct-to-consumer-shipping-restricted-role), and then pass the `shippingAddress` `$data_elements` value to your `getOrders` call. The `getOrderAddress` call is deprecated. More information [in the README](https://github.com/jlevers/selling-partner-api#restricted-operations).
