### ISSUE TITLE
When can I officially use V3?

### ISSUE THREAD

**Issue by allen1706** [jlevers/selling-partner-api#48]
When can I officially use V3?

**Comment by jlevers** [comment]
I'm shooting for sometime next week -- one thing blocking its release is Amazon enabling the new versions of the Reports and Feeds APIs. They were supposed to be enabled yesterday (6/30), but I tried them out today and I'm getting a 403 on every endpoint. You can track progress on that in this issue: https://github.com/amzn/selling-partner-api-docs/issues/925

**Comment by jlevers** [comment]
Since Amazon said they're not releasing the new Reports/Feeds APIs for another couple weeks, I decided to released v3 sooner than planned. It's now published :)
