### ISSUE TITLE
getReportDocument Error

### ISSUE THREAD

**Issue by balicekt** [jlevers/selling-partner-api#487]
## Problem description:
Hi, Im able to generate new report and I will get Report ID: 

               $reportType = ReportType::GET_MERCHANT_LISTINGS_ALL_DATA;

		$body = new CreateReportSpecification([
			'marketplace_ids' => self::MARKETPLACE_IDS,
			'report_type' => $reportType['name'],
		]);
		$reportsApi = new ReportsApi($this->getConfig());
		$res = $reportsApi->createReport($body);

		$reportId = $res->getReportId();

I can also see the report was generated in amazon seller central. The report ID is: 50311019412

In another method I want to donwload the file:

		$reportType = ReportType::GET_MERCHANT_LISTINGS_ALL_DATA;
		$reportsApi = new ReportsApi($this->getConfig());

		$reportDocumentInfo = $reportsApi->getReportDocument($reportId, $reportType['name']);
		$docToDownload = new Document($reportDocumentInfo, $reportType);

		$contents = $docToDownload->download();  // The raw report text
		$data = $docToDownload->getData();

but the function getReportDocument doesnt work. Im getting following error: 

SellingPartnerApi\ApiException #400

[400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid reportDocumentId 50311019412",
      "details": ""
    }
  ]
}

So I think the report ID should not be a number but should be i link? But Im not able to get the link. Can you help me where to get please? 

Thank you

**Comment by balicekt** [comment]
Hi @jlevers can anyone help me with this please? I think it will be very easy and stupid mistake. But I spend lot of time on it and searching but couldn't find anything helpful.  

Thank you for any answer

**Comment by ansgarbecker** [comment]
There's a longer alphanumeric `reportDocumentId` and a shorter numeric `reportId` for each report. `getReportDocument()` expects the `reportDocumentId`, and you are using the shorter `reportId` which is wrong.

**Comment by ansgarbecker** [comment]
I think you need to call `getReport($reportId)` before:
```php
$rp = $reportsApi->getReport('50311019412');
$document = $reportsApi->getReportDocument($rp->getReportDocumentId());
```

**Comment by balicekt** [comment]
@ansgarbecker Thank you very much you are a legend!

**Comment by Julian3004** [comment]
I tried exactly that but  the Exception is:
 Exception when calling ReportsV20210630Api->getReportDocument: [400] { "errors": [ { "code": "InvalidInput", "message": "Invalid or unsupported document ID found", "details": "" } ] }  

The report_document_id looks like that: amzn1.spdoc.1.4.eu.04096...

`$result = $apiInstance->getReport($iReportId);
 $report_document_id = $result->getReportDocumentId();

try {
    $reportDocumentInfo = $apiInstance->getReportDocument($report_document_id, $reportType['name']);

    $docToDownload = new SellingPartnerApi\Document($reportDocumentInfo, $reportType);
    $contents = $docToDownload->download();  // The raw report text
    $sPfad = '/Users/Shared/temp_daten/'.$partner_id.'/Amazon/';
    file_put_contents($sPfad.'2239_aws_invoice_'.$reportType['name'].'.txt', $contents);

} catch (Exception $e) {
  echo 'Exception when calling ReportsV20210630Api->getReportDocument: ', $e->getMessage(), PHP_EOL;
}`
