### ISSUE TITLE
Orders v0 Models are updated; invalid value error 

### ISSUE THREAD

**Issue by KhorneHoly** [jlevers/selling-partner-api#490]
Hi,

the orders v0 models got updated. Currently I'm getting this error:

`"Invalid value 'SG_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS'"`

I fixed it dirty in a fork, but generating the models from the OpenAPI json created a lot of changes because I used different settings in my generator.
Maybe you could share the configuration of your OpenAPI generator so that we could try the generation with the same settings as you for pull requests.

Thanks.

**Comment by jlevers** [comment]
I have a bunch of custom scripts written to make this work – it's not pretty, and it's full of secrets. I'd like to clean it up so I can make it public but just don't have the time at the moment.

This is fixed in `v5.7.0`.
