### ISSUE TITLE
Fees API v0 - getMyFeesEstimates() for multiple products.

### ISSUE THREAD

**Issue by mtazam1985** [jlevers/selling-partner-api#491]
## Problem description:
Hi,
I am trying to get Estimation fees for the list of skus using getMyFeesEstimates(). It is working for single SKU. 
but when I try with the multiple SKUs it is giving error. 

## Error:
![image](https://user-images.githubusercontent.com/14324980/222055019-0c5ae126-6d17-4cce-a696-2500a388a49c.png)

## Code

        $feesApi = new FeesV0Api($this->config);
        $body = array(new \SellingPartnerApi\Model\FeesV0\FeesEstimateByIdRequest($od));

        $getMyFeesRequest = $feesApi->getMyFeesEstimates($body);
        print_r($getMyFeesRequest);

**Comment by jlevers** [comment]
Without seeing what the variable `$od` is, it's hard to diagnose the problem. This code is working fine for me:

```php
use SellingPartnerApi\Api\FeesV0Api as FeesApi;
use SellingPartnerApi\Model\FeesV0 as Fees;

$api = new FeesApi($config);
$body = [
    new Fees\FeesEstimateByIdRequest([
        'id_type' => 'SellerSKU',
        'id_value' => 'SKU1234',
        'fees_estimate_request' => new Fees\FeesEstimateRequest([
            'marketplace_id' => 'ATVPDKIKX0DER',
            'identifier' => '1',
            'price_to_estimate_fees' => new Fees\PriceToEstimateFees([
                'listing_price' => new Fees\MoneyType([
                    'amount' => 1.00,
                    'currency_code' => 'USD',
                ])
            ]),
        ]),
    ]),
    new Fees\FeesEstimateByIdRequest([
        'id_type' => 'SellerSKU',
        'id_value' => 'SKU5678',
        'fees_estimate_request' => new Fees\FeesEstimateRequest([
            'marketplace_id' => 'ATVPDKIKX0DER',
            'identifier' => '2',
            'price_to_estimate_fees' => new Fees\PriceToEstimateFees([
                'listing_price' => new Fees\MoneyType([
                    'amount' => 1.00,
                    'currency_code' => 'USD',
                ])
            ]),
        ]),
    ])   
];

$res = $api->getMyFeesEstimates($body);
var_dump($res);
```

**Comment by jlevers** [comment]
@mtazam1985 since I haven't heard from you again, I'm going to close this issue. Feel free to reopen if you still need help.
