### ISSUE TITLE
Other values for OrderItem.deemed_reseller_category: GB_VOEC, SG_VOEC, CA_MPF

### ISSUE THREAD

**Issue by gravitiq-cm** [jlevers/selling-partner-api#492]
At the moment `OrderItem::getDeemedResellerCategoryAllowableValues()` only allows IOSS or UOSS.

In our data we've also seen GB_VOEC, SG_VOEC and CA_MPF.

Can these be added?

Is it just a matter of creating new `DEEMED_RESELLER_CATEGORY_XYZ` class constants and updating `getDeemedResellerCategoryAllowableValues()`? If so I'll see if I can create a PR.

**Comment by KhorneHoly** [comment]
I've fixed it that way in a local fork for my own use. But it's more or less a dirty hack, because the models have changed, see https://github.com/jlevers/selling-partner-api/issues/490 for that.

**Comment by luckdragon** [comment]
it's broken again in 5.6, additionally, I get it for SG_VOEC

fix: in lib/Model/OrdersV0/OrderItem.php

search for:
const DEEMED_RESELLER_CATEGORY_UOSS = 'UOSS';

add after:
const DEEMED_RESELLER_CATEGORY_SG_VOEC = 'SG_VOEC';
const DEEMED_RESELLER_CATEGORY_GB_VOEC = 'GB_VOEC';
const DEEMED_RESELLER_CATEGORY_NO_VOEC = 'NO_VOEC';
const DEEMED_RESELLER_CATEGORY_CA_MPF = 'CA_MPF';
const DEEMED_RESELLER_CATEGORY_AU_VOEC = 'AU_VOEC';
const DEEMED_RESELLER_CATEGORY_NZ_VOEC = 'NZ_VOEC';

then search for:
self::DEEMED_RESELLER_CATEGORY_UOSS,

add after:
self::DEEMED_RESELLER_CATEGORY_SG_VOEC,
self::DEEMED_RESELLER_CATEGORY_GB_VOEC,
self::DEEMED_RESELLER_CATEGORY_NO_VOEC,
self::DEEMED_RESELLER_CATEGORY_CA_MPF,
self::DEEMED_RESELLER_CATEGORY_AU_VOEC,
self::DEEMED_RESELLER_CATEGORY_NZ_VOEC,


of course, once you update, it's going to break again, unless it gets added to the core code

**Comment by gravitiq-cm** [comment]
Thanks for the comprehensive list

**Comment by luckdragon** [comment]
don't know if it's complete, but it covers a lot of the ones I noticed.

**Comment by jlevers** [comment]
Sorry about that, the values I'd added to this enum got overwritten in the last JSON model update. Fixed in `v5.7.0`.
