### ISSUE TITLE
missing enum value "CREATING" of \SellingPartnerApi\Model\FbaInbound\ShipmentStatus

### ISSUE THREAD

**Issue by suofiya** [jlevers/selling-partner-api#495]
There is status "CREATING" that is missing from Amazon's documentation and I get an error if there is a shipment with this status returned by SellingPartnerApi\Api\FbaInboundApi->getShipments();

I submitted the same issue on Apr 25, 2022.  Can you add a constant in \SellingPartnerApi\Model\FbaInbound\ShipmentStatus to fix the issue.

https://github.com/jlevers/selling-partner-api/issues/258

**Comment by jlevers** [comment]
Sorry about that, it got overwritten in the last model update. Fixed in `v5.7.0`.
