### ISSUE TITLE
Fatal error: Uncaught Error: Class "SellingPartnerApi\Configuration" not found in /var/www/vhosts/xxx/yyy/index.php:8 Stack trace: #0 {main} thrown in /var/www/vhosts/xxx/yyy/index.php on line 8

### ISSUE THREAD

**Issue by RestOp** [jlevers/selling-partner-api#496]
## Problem description:
Hello,

I have followed all the steps of this https://jesseevers.com/selling-partner-api-access/ and linked socuments to register and creat a user.
But now i get a "Fatal Error".
I think the problem ist stupid and hope that it is not a bug, but i am sitting 2 days with it and can not solve it. 
Please help!
Thanks!

PS
If it matters i use PHP 8.1.16

And if it matters i used this composer.json https://github.com/jlevers/selling-partner-api/blob/main/composer.json

## Error:

```
**Fatal error: Uncaught Error: Class "SellingPartnerApi\Configuration" not found in /var/www/vhosts/xxx/yyy/index.php:8 Stack trace: #0 {main} thrown in /var/www/vhosts/xxx/yyy/index.php on line 8**
```

## Code

The code is directly from this https://github.com/jlevers/selling-partner-api#examples example, just changed the endpoit to EU
```php
require_once(__DIR__ . '/vendor/autoload.php');

use SellingPartnerApi\Api\SellersV1Api as SellersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
    "lwaClientId" => "xxx",
    "lwaClientSecret" => "xxx",
    "lwaRefreshToken" => "xxx",
    "awsAccessKeyId" => "xxx",
    "awsSecretAccessKey" => "xxx",
    // If you're not working in the North American marketplace, change
    // this to another endpoint from lib/Endpoint.php
    "endpoint" => Endpoint::EU
]);

$api = new SellersApi($config);
try {
    $result = $api->getMarketplaceParticipations();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by VigneshQikink** [comment]
this is because , you installed the library through composer. update the latest files in github and try, this error will be solved

**Comment by jlevers** [comment]
You want to create your own Composer project with `composer init` and install the library into that project with `composer install jlevers/selling-partner-api`, rather than using the `composer.json` from this library. Read up on how to use Composer [here](https://getcomposer.org/doc/00-intro.md) :)
