### ISSUE TITLE
> Sorry @jlevers, what I wrote was pretty misleading. I added it to the IAM user, but it definitely did require the rest of the JSON- I only posted the part that I had added. You were correct all along- this is what it looked like in its entirety:

### ISSUE THREAD

**Issue by VigneshQikink** [jlevers/selling-partner-api#498]
> Sorry @jlevers, what I wrote was pretty misleading. I added it to the IAM user, but it definitely did require the rest of the JSON- I only posted the part that I had added. You were correct all along- this is what it looked like in its entirety:
> 
> ```
> {
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "VisualEditor0",
>             "Effect": "Allow",
>             "Action": "sts:AssumeRole",
>             "Resource": "<my role ARN>"
>         },
>         {
>             "Effect": "Allow",
>             "Action": "execute-api:Invoke",
>             "Resource": "arn:aws:execute-api:*:*:*"
>         }
>     ]
> }
> ```

as mentioned in this, i changed the policy but still the error is coming.

_Originally posted by @VigneshQikink in https://github.com/jlevers/selling-partner-api/issues/42#issuecomment-1456029455_

**Comment by jlevers** [comment]
Please read [this blog post](https://www.highsidelabs.co/blog/selling-partner-api-access) and follow the setup instructions exactly, and let me know if you continue to have issues.

**Comment by VigneshQikink** [comment]
`Exception when calling ListingsV20210801Api->getListingsItem: Error executing "AssumeRole" on "https://sts.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: POST https://sts.eu-west-1.amazonaws.com resulted in a 403 Forbidden response: Sender AccessDeni (truncated...) AccessDenied (client): User: arn:aws:iam::672**4798257:user/Qikink is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::672**4798257:user/Qikink - Sender AccessDenied User: arn:aws:iam::672**4798257:user/Qikink is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::672**4798257:user/Qikink 8bdef71a-48c8ea2-d7b74953beef`

Still this error is coming. please help regarding this

**Comment by KhorneHoly** [comment]
> Thanks for your post link. I did exactly what was in that post. but still facing error
> 
> `Exception when calling ListingsV20210801Api->getListingsItem: Error executing "AssumeRole" on "https://sts.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: POST https://sts.eu-west-1.amazonaws.com resulted in a 403 Forbidden response: Sender AccessDeni (truncated...) AccessDenied (client): User: arn:aws:iam::672**4798257:user/Qikink is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::672**4798257:user/Qikink - Sender AccessDenied User: arn:aws:iam::672**4798257:user/Qikink is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::672**4798257:user/Qikink 8bdef71a-48c8ea2-d7b74953beef`
> 
> Still this error is coming. please help regarding this

You haven't set up your IAM role correctly, thus the respective error. Check the blogpost again or the documentation from Amazon: https://developer-docs.amazon.com/sp-api/docs/creating-and-configuring-iam-policies-and-entities

**Comment by jlevers** [comment]
@VigneshQikink since you haven't responded to this issue, I'm assuming you were able to fix your IAM problem.
