### ISSUE TITLE
Do you know why requests are always wrong

### ISSUE THREAD

**Issue by allen1706** [jlevers/selling-partner-api#51]
![image](https://user-images.githubusercontent.com/34757825/124582068-40d9d880-de84-11eb-8196-f9acf84664ce.png)
v3.0.1 ProductPricingApi

**Comment by jlevers** [comment]
Could you provide the code you're running, and the contents of your `composer.json`? I'm able to make calls to the `getPricing` endpoint without a problem, so I'll need a little more info to diagnose what's going on here.

**Comment by allen1706** [comment]
> Could you provide the code you're running, and the contents of your `composer.json`? I'm able to make calls to the `getPricing` endpoint without a problem, so I'll need a little more info to diagnose what's going on here.
![image](https://user-images.githubusercontent.com/34757825/124683181-05302480-deff-11eb-95d9-d6041e106fee.png)
this is my code, other api are ok.

**Comment by jlevers** [comment]
@allen1706 I just deleted your comment because it made your LWA/AWS secrets public. Could you please repost your code (preferably as text, not images) with that data obfuscated?

**Comment by allen1706** [comment]
> @allen1706 I just deleted your comment because it made your LWA/AWS secrets public. Could you please repost your code (preferably as text, not images) with that data obfuscated?

ok, thinks.

$config = new Configuration([
        'lwaClientId' => 'mylwaClientId',
        'lwaClientSecret' => 'mylwaClientSecret',
        'lwaRefreshToken' => $oauth['refresh_token'],
        'awsAccessKeyId' => 'myawsAccessKeyId',
        'awsSecretAccessKey' => 'myawsSecretAccessKey',
        'endpoint' => Endpoint::NA,
        'accessToken' => $oauth['access_token'],
        'accessTokenExpiration' => strtotime($oauth['expire_time'])
  ]);
  $apiInstance = new ProductPricingApi($config);
  $asin = 'B093WSPGGY';
  $marketplace_ids = 'ATVPDKIKX0DER';
  $result = $apiInstance->getPricing($marketplace_ids, 'ASIN', [$asin]);

**Comment by jlevers** [comment]
The problem is that `ASIN` needs to be written `Asin`. The fact that a) that causes an error at all, and b) that the error it doesn produce is a 404 seems wrong to me, so I'll open an issue with them...but for now, changing `ASIN` to `Asin` should fix the problem.

The enumeration of the valid `item_type`s is in the official docs [here](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#itemtype-subgroup-1).

**Comment by jlevers** [comment]
Tracking this here: https://github.com/amzn/selling-partner-api-docs/issues/995

**Comment by allen1706** [comment]
> 问题是`ASIN`需要写`Asin`。a) 完全导致错误，以及 b) 它不会产生的错误是 404 的事实对我来说似乎是错误的，所以我将向他们打开一个问题......但现在，更改`ASIN`为`Asin`应该修复问题。
> 
> 有效`item_type`s的枚举在[此处](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#itemtype-subgroup-1)的官方文档中。
ok, thank you.

**Comment by allen1706** [comment]
> Tracking this here: [amzn/selling-partner-api-docs#995](https://github.com/amzn/selling-partner-api-docs/issues/995)

ok, thank you.
