### ISSUE TITLE
Searching by product types or keywords using the searchCatalogItems feature

### ISSUE THREAD

**Issue by BeranAday** [jlevers/selling-partner-api#513]
We want to search by product types or keywords using the searchCatalogItems feature. We can make an empty search using the code below. And we get as a result, millions of results . For example, we want to search by the word "television" or search for products in the "television" category. We think that the problem we are experiencing is related to the function or parameters we use.  How can we do this? (Being able to search by keywords can help us a lot.)

        $api = new SellersApi($config);

        try {

            $result = $api->searchCatalogItems($marketplace_ids, $identifiers = null, $identifiers_type = null, $included_data=null, $locale = null, $seller_id = null, $page_size = 20, $page_token = null);

            print_r(json_encode($result));

            }

**Comment by jlevers** [comment]
You need to use the keywords parameter:

```php
use SellingPartnerApi\Api\CatalogItemsV20220401Api as CatalogItemsApi;
use SellingPartnerApi\Configuration;

$config = new Configuration([ /****/ ]);
$api = new CatalogItemsV20220401Api($config);
$response = $api->searchCatalogItems(
    $marketplace_ids,
    keywords: ['book']
);
```

If you aren't using PHP 8 or greater, you won't be able to use named keywords, so you'll need to pass all the parameters up to the `keywords` parameter:

```php
use SellingPartnerApi\Api\CatalogItemsV20220401Api as CatalogItemsApi;
use SellingPartnerApi\Configuration;

$config = new Configuration([ /****/ ]);
$api = new CatalogItemsV20220401Api($config);
$response = $api->searchCatalogItems(
    $marketplace_ids,
    null,
    null,
    null,
    null,
    null,
    ['book']
);
```
