### ISSUE TITLE
Try to use VendorShippingV1Api getShipmentDetails method,but get 404 ResourceNotFound.

### ISSUE THREAD

**Issue by niesheng** [jlevers/selling-partner-api#516]
## Problem description:
Try to use VendorShippingV1Api getShipmentDetails method.
## Error:
But get 404 ResourceNotFound.
```
# Your error here. PLEASE make sure to redact secrets from your error log!
```
[404] {
"errors": [
{
"code": "ResourceNotFound",
"message": "Cannot find resource by the given URI"
}
]
}
## Code

```php
$config = new \SellingPartnerApi\Configuration([
            "lwaClientId" => "XXX",
            "lwaClientSecret" => "XXX",
            "lwaRefreshToken" => "XXX",
            "awsAccessKeyId" => "XXX",
            "awsSecretAccessKey" => "XXX",
            "endpoint" => \SellingPartnerApi\Endpoint::EU,  
            "roleArn" => "XXX",
        ]);
        
        $apiInstance = new \SellingPartnerApi\Api\VendorShippingV1Api($config);
        $limit = 1; 
        sort_order = 'DESC';
        $created_after = '2023-01-01T00:00:00Z'; 
        $next_token = null;
        $result =  $apiInstance->getShipmentDetails($limit , $sort_order , $next_token , $created_after);
        print_r($result->getPayload());
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
I would take this up with Amazon Support – their models indicate that the path for this call is `/vendor/shipping/v1/shipments`, so if you're getting a 404, either their models are wrong or there's something misconfigured with your account. It's also possible that that call isn't supported in the EU. Sorry I can't be of more help.
