### ISSUE TITLE
invalid value for "$item_approval_types" when calling OrdersV0Api.getOrders, number of items must be less than or equal to 1.

### ISSUE THREAD

**Issue by dv336699** [jlevers/selling-partner-api#522]
## Problem description:
After updating from 5.5.4 to 5.7.0 this message has started to appear.

## Error:

```
invalid value for "$item_approval_types" when calling OrdersV0Api.getOrders, number of items must be less than or equal to 1.
```

I use this parameter to request more information when pulling orders, `['buyerInfo', 'shippingAddress']` and it seems that this has been restricted to only 1 item.

## Code

```php
$request = $api->getOrders(
                [$MarketplaceID],
                date('Y-m-d'),
                null,
                null,
                null,
                ['Unshipped', 'Pending'],
                null,
                null,
                null,
                null,
                100,
                null,
                null,
                $apiNextToken,
                null,
                null,
                null,
                null,
                ['buyerInfo', 'shippingAddress']
            );
```

**Comment by dartheditous** [comment]
That method has more parameters than it did before. You need to add two more `null`s to make sure the array is assigned to the right parameter, or (PHP 8) you can instead put `data_elements: ['buyerInfo', 'shippingAddress']`. You can use the same format for all the other parameters, then you can get rid of the `null`s and you won't have to worry about this in future (unless a parameter name changes).

**Comment by dv336699** [comment]
@dartheditous many thanks

**Comment by dv336699** [comment]
@jlevers thanks, that's much appreciated - worked like a charm :)
