### ISSUE TITLE
Question: what sp-api function to call to RETRIEVE messages from subscription?

### ISSUE THREAD

**Issue by JeffMash** [jlevers/selling-partner-api#524]
I already created my SQS destination (using createDestination).   I already created a subscription (for ANY_OFFER_CHANGED).   I can see messages in the Amazon SQS queue when I poll for messages on the AWS website.

I just don't know which function in the SP-API to call to actually get and enumerate through the messages? 

For example, I called createSubscription() to create my subscription, but now what function do we call in order to enumerate through the messages?

I have my subscription id.........and I assume there is some API function I need to call in order to pass this to, and then I can see the queued messages in my program.    Can you point me in the right direction?

_(Everything I see online shows me how to view the messages through the SQS in my browser (polling messages, etc), but I need my php program to access this information.  Now sure how.)_

**Comment by jlevers** [comment]
There's no mechanism in the SP API to retrieve messages – you have to pull them directly from the SQS queue. There's documentation for the SQS APIs [here](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-working-with-apis.html), and [here's the AWS PHP SDK](https://github.com/aws/aws-sdk-php) you can use to access the SQS API without writing a custom wrapper.

**Comment by JeffMash** [comment]
Thank you for that.    It was confusing for me because in the actual SP-API documentation, it talks about the Notification Structure, and says "**Selling Partner notifications** are in JSON format".

It then goes on to show the structure of the object which made me think it was accessible through the Selling Partner API.   

Screenshot: https://i.postimg.cc/PrHy41H9/screenshot-590.png

Source: https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide#what-is-the-notifications-api

So it looks like the SP-API only lets you create the subscriptions, but we will need another separate API to get those messages.  That's a bummer.

**Comment by jlevers** [comment]
Yep, it's a bit confusing – that took me a while to figure out the first time too.

It's outside the scope of this repository, but if you want support pulling messages from SQS, feel free to shoot me an email. I've built applications to do this for clients in the past. My email is [first name] [at] highsidelabs.co.

**Comment by JeffMash** [comment]
> It's outside the scope of this repository, but if you want support pulling messages from SQS, feel free to shoot me an email.

Thanks  Jesse, I appreciate the help!   I will see what I can figure out on my own before bothering you with anything else.   By the way, love what you're doing there at HighSide.   It;'s too bad I'm over here in California!   As an artist myself, it's totally a place I would love to chill at!  (My art channel on IG is @WatchJeffArt: https://www.instagram.com/watchjeffart/reels/).

**Comment by jlevers** [comment]
Thank you, I appreciate it! Let me know if you're ever in NYC :)

Just checked out your page – impressive work! I can't draw for the life of me, so I'm always sorta amazed by people who can.
