### ISSUE TITLE
Auto converting dates to DateTime

### ISSUE THREAD

**Issue by AlexeyKosov** [jlevers/selling-partner-api#526]
## Problem description:

Hello,

Thanks for this library!

Currently, all dates are returned as strings, which requires converting them manually to `DateTime` objects.
And vice versa when submitting data to the API.

Just wanted to ask, maybe there's some option to add a hook to the generated models so that date strings are automatically converted to `DateTime`?

**Comment by jlevers** [comment]
Hey @AlexeyKosov,

Thanks for the idea. I agree that this would be nice, although it would be a breaking change so would have to wait for the next major version. I'll add it to the list of features for v6 of the library.

**Comment by jlevers** [comment]
This is completed in `v6`.
