### ISSUE TITLE
Tested PHP Versions

### ISSUE THREAD

**Issue by UpsyDavy** [jlevers/selling-partner-api#530]
Hi

Has this just not been tested on older PHP versions, or will it definitely not work.

Our current server is running Version 5.6.30

Thank you for your help

Regards

**Comment by jlevers** [comment]
Hi!

The minimum PHP version is 7.3. If you need a version made that will be compatible with older versions of PHP, we can talk about what it would look like for me to build you a custom version, but it's not supported by the main library. If you're interested in that, feel free to get in touch with me privately at [first name] [at] highsidelabs.co.

**Comment by kristianstout** [comment]
Composer dependencies are forcing 8.1 -- is there any way to drop those dependencies and run it on 7.3?
