### ISSUE TITLE
GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT (VIDR) report

### ISSUE THREAD

**Issue by impromani** [jlevers/selling-partner-api#531]
HI,

This report type "GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT" always returns an empty result
does anyone use this report type and got a result?

**Request** 
```
SellingPartnerApi\Model\ReportsV20210630\CreateReportSpecification Object
(
    [container:protected] => Array
        (
            [report_options] => {'ReportOption=All': 'true'}
            [report_type] => GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT
            [data_start_time] => 2023-03-01T00:00:01Z
            [data_end_time] => 2023-03-31T23:59:59Z
            [marketplace_ids] => Array
                (
                    [0] => A1PA6795UKMFR9
                    [1] => A1RKKUPIHCS9HS
                    [2] => A13V1IB3VIYZZH
                    [3] => APJ6JRA9NG5V4
                    [4] => A1F83G8C2ARO7P
                )

        )

)

```

**Comment by jlevers** [comment]
How are you passing `report_options`? The structure of yours look a bit strange, although the documentation for `report_options` for this report is also quite confusing. I think your `CreateReportSpecification` object should look something like this:

```php
new Reports\CreateReportSpecification([
    'report_type' => ReportType::GET_FLAT_FILE_VAT_INVOICE_DATA_REPORT['name'],
    'data_start_time' => '2023-03-01T00:00:00Z',  // Note that this is the very beginning of the day (:00), not :01 as you have it
    'data_end_time' => '2023-03-31T23:59:59Z',
    'marketplace_ids' => [/* your marketplace IDs */],
    'report_options' => [
        'all' => 'true',
    ],
]);
```

If that doesn't work, here are a few other things to try:
* Try retrieving data from a single marketplace at a time
* Try passing this for `report_options`:
    ```php
    [
        'ReportOption=All' => 'true'
    ]
    ```
* Try specifying a report period in `report_options`:
    ```php
    [
        'all' => 'true',  // Also try 'ReportOption=All' => 'true' here
        'reportPeriod' => 'MONTH',
    ]
    ```

**Comment by impromani** [comment]
@jlevers thank you so much, it is working now

**Comment by michelexport** [comment]
Field "invoice-number" is empty when an order is business, so when field "is-business-order" = "true". 
Anyone experiencing the same?

**Comment by diegocvazquez** [comment]
@impromani 
Hi there could you please share what parameters are you passing in the reportOptions to get it working? 
Thanks in advanced

**Comment by diegocvazquez** [comment]
@impromani 
Nevermind, I got working following @jlevers recomendation about passing "'ReportOption=All' => 'true' instead of all' => 'true'.
