### ISSUE TITLE
No Permission to access to "DataElement"

### ISSUE THREAD

**Issue by AntoWkill** [jlevers/selling-partner-api#535]
## Error: 

Exception when calling OrdersV0Api->getOrder: [400] {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "Application does not have access to one or more requested data elements: [shippingAddress]",
      "details": ""
    }
  ]
}

## Code
    $data_elements = array('buyerInfo','shippingAddress'); // string[] | An array of restricted order data elements to retrieve (valid array elements are \"buyerInfo\" and \"shippingAddress\")
        
        try {
            $result = $apiInstance->getOrderItems($order_id, $next_token, $data_elements);
            print_r($result);
            $json_result_decoded = json_decode($result, true);
            //print_r($json_result_decoded);
        } catch (Exception $e) {
            echo 'Exception when calling OrdersV0Api->getOrder: ', $e->getMessage(), PHP_EOL;
        }

## Seller Central SP API config page screenshot

https://ibb.co/HDCMG9C

https://ibb.co/d2pd4NS

**Comment by Blazevoir** [comment]
I'm getting the same problem, have you tried using Postman to test the call?

I receive the data_elements successfully in Postman but the library doesn't seem to do so.
Debugging the code I realized I'm getting an RDT, just like in Postman, but that token doesn't work neither in the code nor in Postman.

I see lots of people having the same issue, let's see if we can get any help.

**Comment by AntoWkill** [comment]
> I'm having the same problem, have you tried using Postman to test the call?
> 
> I receive the data_elements successfully in Postman but the library doesn't seem to do so. Debugging the code I realized I'm getting an RDT, just like in Postman, but that token doesn't work neither in the code nor in Postman.
> 
> I see lots of people having the same issue, let's see if we can get any help.

Yes the same for me.

**Comment by jlevers** [comment]
Have you been approved for PII access on your developer application? If you haven't been granted any of the restricted SP API roles, you won't be able to retrieve PII. More information on SP API roles [here](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api#role-definitions) – you can see which ones you've been granted on your SP API app's page on Seller Central.

**Comment by AntoWkill** [comment]
I have not the Invoicing but only the direct shipping. Is that necessary for the role? Check my screen attached https://ibb.co/d2pd4NS

**Comment by jlevers** [comment]
If you're only passing `shippingAddress` to `$data_elements` that should be fine, but if you want `buyerInfo` too you'll need access to one of the other restricted roles.

**Comment by AntoWkill** [comment]
Unfortunately also if I ask only shipping address I get the error.

**Comment by jlevers** [comment]
I just noticed that in your initial post you're calling `getOrderItems` in your code. Is that actually the call you're making, or are you calling `getOrders? The `getOrderItems` call doesn't ever return PII, and so it doesn't accept a `$data_elements` parameter.

**Comment by AntoWkill** [comment]
> I just noticed that in your initial post you're calling `getOrderItems` in your code. Is that actually the call you're making, or are you calling `getOrders`? The `getOrderItems` call doesn't ever return PII, and so it doesn't accept a `$data_elements` parameter.

Yes I’m calling getOrderItems, but the repo docs I see under the example code the data element array. Please check docs. Do you confirm that is not work for getOrderItems?

**Comment by jlevers** [comment]
Apologies, I was misremembering the details of the endpoint. The only valid element for `$data_elements` on the `getOrderItems` endpoint is `'buyerInfo` – `'shippingAddress'` is not allowed for that endpoint. This is specified in the [docs](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/OrdersV0Api.md#parameters-4) (guess I should read my own docs a little more carefully, too ;)

**Comment by AntoWkill** [comment]
> Apologies, I was misremembering the details of the endpoint. The only valid element for `$data_elements` on the `getOrderItems` endpoint is `'buyerInfo` – `'shippingAddress'` is not allowed for that endpoint. This is specified in the [docs](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/OrdersV0Api.md#parameters-4) (guess I should read my own docs a little more carefully, too ;)
> 
> I believe `getOrderAddress` is deprecated, so I would avoid using it if possible.

The problem is that I have same problem with ‘getshippingaddress’ API .. I really do not understand why.. for Amazon I have the permission to get this data.

**Comment by AntoWkill** [comment]
Solution found, was an Amazon problem they update my permission and now i can i sell all :)!

**Comment by nhupham-commonservices** [comment]
Hi @AntoWkill 
Could you please guide me how to ask Amazon to update permission to have access to "DataElement"?
I am facing the same problem :(
