### ISSUE TITLE
Missing "Shipping Information Note" to API

### ISSUE THREAD

**Issue by AntoWkill** [jlevers/selling-partner-api#536]
## Error: Can't find this information (i tried all the Order API i can't find it) this is the output

Array
(
    [payload] => Array
        (
            [AmazonOrderId] => 405-5364644-9871560
            [ShippingAddress] => Array
                (
                    [Name] => XX
                    [AddressLine1] => XX
                    [City] => xXX
                    [StateOrRegion] => XXX
                    [PostalCode] => XX
                    [CountryCode] => XX
                    [Phone] => XX
                    [AddressType] => XX
                )

        )

)

```

## Seller Central SP API config page screenshot

**Comment by jlevers** [comment]
I don't see any reference in the official SP API docs to a way to retrieve shipping notes, so I'm guessing it just isn't possible at the moment. I'd open a [support case](https://sellercentral.amazon.com/gp/mws/contactus.html?ld=ASXXSPAPIDirect) with Amazon about this issue and see what they have to say.
