### ISSUE TITLE
Access to requested resource is denied.

### ISSUE THREAD

**Issue by dougblackjr** [jlevers/selling-partner-api#539]
## Error:

```
{  "message": "Access to requested resource is denied.",
 "code": "Unauthorized",}
```

When trying to run any of the API calls, I am getting Unauthorized. Have tried this with:
```
SellersV1Api->getMarketplaceParticipations
ReportsV20210630Api->getReports
FbaInventoryV1Api->getInventorySummaries
```

Have also tried role based.

Developer in Seller Central is currently a private developer, and app is in draft mode. There is no option to publish it.

## Code

```php
<?php

namespace App\Services;

use Carbon\Carbon;
use SellingPartnerApi\Configuration as SpConfiguration;
use SellingPartnerApi\Endpoint as SpEndpoint;
use SellingPartnerApi\Api\SellersV1Api as SellersApi;
use SellingPartnerApi\Api\FbaInventoryV1Api;
use SellingPartnerApi\Api\VendorDirectFulfillmentInventoryV1Api;
use SellingPartnerApi\Api\ReportsV20210630Api;

class AmazonSellerService
{
    public $config;

    public function __construct()
    {
        $this->config = new SpConfiguration([
            'lwaClientId' => config('amazon-seller.lwa_client_id'),
            'lwaClientSecret' => config('amazon-seller.lwa_client_secret'),
            'lwaRefreshToken' => config('amazon-seller.lwa_refresh_token'),
            'awsAccessKeyId' => config('amazon-seller.aws_access_key_id'),
            'awsSecretAccessKey' => config('amazon-seller.aws_secret_access_key'),
            // 'roleArn' => config('amazon-seller.aws_role_arn'),
            'endpoint' => SpEndpoint::NA,
        ]);
    }

    public function getProducts($skus = null, $next = null)
    {
        $api = new FbaInventoryV1Api($this->config);
        $granularityType = '';//'granularity_type_example'; // string | The granularity type for the inventory aggregation level.
        $granularityId = '';//'granularity_id_example'; // string | The granularity ID for the inventory aggregation level.
        $marketplaceIds = config('amazon-seller.marketplace_id');
        $details = 'true';
        $startDateTime = now()->subMonth()->toIso8601String();

        try {
            // getInventorySummaries($granularity_type, $granularity_id, $marketplace_ids, $details = 'false', $start_date_time = null, $seller_skus = null, $next_token = null)
            $result = $api->getInventorySummaries(
                $granularityType,
                $granularityId,
                $marketplaceIds,
                $details,
                $startDateTime,
                $skus,
                $next
            );
            return json_decode($result, true);
        } catch (Exception $e) {
            throw new \Exception('Exception when calling FbaInventoryV1Api->getInventorySummaries: ' . $e->getMessage());
        }
    }
}

```

The config function pulls in the environment variables from here:

```
LWA_CLIENT_ID="amzn1.application-oa2-client.HIDDEN"
LWA_CLIENT_SECRET="amzn1.oa2-cs.v1.HIDDEN"
LWA_REFRESH_TOKEN="REALLY LONG STRING"
AWS_ACCESS_KEY_ID=USERKEY
AWS_SECRET_ACCESS_KEY=SECRETKEY
MARKETPLACE_ID="amzn1.merchant.d.HIDDEN"
```

## Seller Central SP API config page screenshot

![Screenshot from 2023-05-12 09-08-01](https://github.com/jlevers/selling-partner-api/assets/6020323/51ed3c43-618c-42a3-ba35-ca3a70e51389)

Appreciate any help you can give, I'm super blocked on this!

**Comment by DomuITteam** [comment]
Hi, what stands out is the **MARKETPLACE_ID** value. You're using NA endpoint, so your marketplaces should be one or more of the following values (as per **getByMarketplaceId** function in lib/Endpoint.php):

- Brazil: A2Q3Y263D00KWC
- Canada: A2EUQ1WTGCTBG2
- Mexico: A1AM78C64UM0Y8
- US: ATVPDKIKX0DER

**Comment by dougblackjr** [comment]
@DomuITteam Thank you, updated that but still getting the same response.

**Comment by dougblackjr** [comment]
@jlevers I have tried both, either the user IAM ARN or the role IAM ARN with the `roleArn` in the config, neither seem to connect.

The only thing I can think of is that either its because the app is in Draft mode (but we're a private developer, so I'm not sure if that's important nor can I change it), or because the user is different than the Seller Central user. Any thoughts on either of these?

**Comment by jlevers** [comment]
As in, you've set up both user and role ARNs in IAM, and then edited your app to use both types?

The app being in draft mode doesn't matter. What do you mean by the user being different than the Seller Central user?

**Comment by dougblackjr** [comment]
@jlevers More that I created multiple apps, one with the user ARN attached, one with the role ARN. Neither are working for me.

RE: The Seller Central user, the app is created under info@thedomain.com, but the AWS user is under person@thedomain.com. Does that matter? Do these need to match?

**Comment by jlevers** [comment]
I'm guessing there's an issue in your IAM setup somewhere. I explained the whole IAM setup process as part of a blog post  [here](https://www.highsidelabs.co/blog/selling-partner-api-access#set-up-aws-iam-configuration). I'd need to log into your AWS to do any further diagnosis of this, but the difference in Seller Central and AWS emails doesn't matter.

**Comment by serianshops** [comment]
I get the error message "403 Access to requested resource is denied" seemingly by chance on exactly the same call. Sometimes it works 2-3 times in a row, then the error 403 comes, sometimes it works again after a few minutes, sometimes only after an hour or more. 
Sometimes it is the other way round - the first call has the error 403, the next attempt then works.
The calls are at least 3 minutes apart. What could be the reason for this?

**Comment by jlevers** [comment]
Just to wrap this up – we got on a call and there was a credentials issue. Good chatting, Doug!
