### ISSUE TITLE
Exception on OrderItems Api (Invalid tax collection model)

### ISSUE THREAD

**Issue by 0xSekar** [jlevers/selling-partner-api#540]
Getting the following errors for a seller in Australia:

`Error not handled, code: 0 - content: string(82) "Invalid value 'LowValueGoods' for 'model', must be one of 'MARKETPLACEFACILITATOR'"`

and 

`Invalid value 'Amazon Commercial Services Pty Ltd' for 'responsible_party', must be one of 'AMAZON SERVICES, INC.'`

This response values are not documented in https://developer-docs.amazon.com/sp-api/docs/orders-api-v0-model. I wonder if you will accept a PR to add those values as constants on https://github.com/jlevers/selling-partner-api/blob/2f6b5520e7f4c1ffbd46a6f9592bccd5996666b3/lib/Model/OrdersV0/TaxCollection.php even if they are undocumented.

**Comment by jlevers** [comment]
Appreciate the offer of a PR – I'm just going to add them to my version of the OpenAPI models, because that's the easiest way to get them into the codebase.

**Comment by jlevers** [comment]
Fixed in `v5.8.3`.

**Comment by 0xSekar** [comment]
I think it should work in 7.x version. Which one are you using?
