### ISSUE TITLE
FbaOutboundV20200701Api: “missing value for timestamp type"

### ISSUE THREAD

**Issue by Ronan04130** [jlevers/selling-partner-api#543]
An attempt to create an order using FbaOutboundV20200701Api returns 
“missing value for timestamp type" 
(We have been able to integrate succesfully the classes “ProductPricingV0Api” and “FeedsV20210630Api”).
I attached the php code and the output showing the payload and the error. 
The function fba_CancelFullfillmentOrder works as expected but the function fba_CreateFullfillmentOrder returns “missing value for timestamp type". The only date in there seems correct:
[displayableOrderDate] => 2023-05-10T14:50:49Z
[error output.txt](https://github.com/jlevers/selling-partner-api/files/11479299/error.output.txt)
[timestamp error.php.txt](https://github.com/jlevers/selling-partner-api/files/11479300/timestamp.error.php.txt)
Thank you

**Comment by jlevers** [comment]
Model properties are specified in `snake_case`, not `camelCase`. If you change this part of your code:

```php
$payload = [
    'marketplaceId' => MARKETPLACE_ID,
    'sellerFulfillmentOrderId' => $Body_OrderId,
    'displayableOrderDate' => date("Y-m-d\TH:i:s\Z"),
    'displayableOrderId' => $Body_OrderId,
    'destinationAddress' => $address,
    'displayableOrderComment' => 'Thank you for your order at SCB Solutions!',
    'items' => $item,
    'shippingSpeedCategory' => fba_get_amazon_shipping_class($order->delivery['shipping_module']),
    'notificationEmails' => $email_list,
];
```

to this:

```php
$payload = [
    'marketplace_id' => MARKETPLACE_ID,
    'seller_fulfillment_order_id' => $Body_OrderId,
    'displayable_order_date' => date("Y-m-d\TH:i:s\Z"),
    'displayable_order_id' => $Body_OrderId,
    'destination_address' => $address,
    'displayable_order_comment' => 'Thank you for your order at SCB Solutions!',
    'items' => $item,
    'shipping_speed_category' => fba_get_amazon_shipping_class($order->delivery['shipping_module']),
    'notification_emails' => $email_list,
];
```

Also, make sure that `items` is an array, not a single item.

If you're creating other models elsewhere that aren't shown in your code, make sure you're using snake case for those models too.

I realize the snake case setup is confusing, because it conflicts with Amazon's documentation. I've explained the reason for it in [another issue](https://github.com/jlevers/selling-partner-api/issues/506#issuecomment-1481484666), and plan to fix it in the next major version release.

**Comment by Ronan04130** [comment]
Thank you very much for your response. The date format does not seem to have an impact on the result.
I changed to snake_case (I should have noticed that the address and the items were formatted differently) But still the same error. Here is the payload:

Array
(
    [marketplace_id] => ATVPDKIKX0DER
    [seller_sulfillment_order_id] => 12088934
    [displayable_order_date] => 2023-05-16T18:25:04Z
    [displayable_order_id] => 12088934
    [destination_address] => SellingPartnerApi\Model\FbaOutboundV20200701\Address Object
        (
            [container:protected] => Array
                (
                    [name] => Ronan Lapie - SCB Solutions
                    [address_line1] => 2732 18TH ST N
                    [address_line2] =>
                    [address_line3] =>
                    [city] => Arlington
                    [district_or_county] =>
                    [state_or_region] => VA
                    [postal_code] => 22201-4028
                    [country_code] => US
                    [phone] => 7034659494
                )

        )

    [displayable_order_comment] => Thank you for your order at SCB Solutions!
    [items] => Array
        (
            [0] => SellingPartnerApi\Model\FbaOutboundV20200701\CreateFulfillmentOrderItem Object
                (
                    [container:protected] => Array
                        (
                            [seller_sku] => 67-TCER-RX4Q-NL
                            [seller_fulfillment_order_item_id] => 12088934-0
                            [quantity] => 1
                            [gift_message] =>
                            [displayable_comment] =>
                            [fulfillment_network_sku] =>
                            [per_unit_declared_value] =>
                            [per_unit_price] =>
                            [per_unit_tax] =>
                        )

                )

        )

    [shipping_speed_category] => Standard
    [notification_emails] => Array
        (
            [0] => ***@***.***
            [1] => ***@***.***
        )

)

Am I missing a step in the following sequence to format the $payload properly before passing it to createFulfillmentOrderRequest?

       $payload = [
            'marketplace_id' => MARKETPLACE_ID,
            'seller_sulfillment_order_id' => $Body_OrderId,
            'displayable_order_date' => date("Y-m-d\TH:i:s\Z"),
            'displayable_order_id' => $Body_OrderId,
            'destination_address' => $address,
            'displayable_order_comment' => 'Thank you for your order at SCB Solutions!',
            'items' => $item,
            'shipping_speed_category' => fba_get_amazon_shipping_class($order->delivery['shipping_module']),
            'notification_emails' => $email_list,
        ];
        echo "<pre>";
        print_r($payload);
        $request = $apiInstanceFBA->createFulfillmentOrderRequest($payload);
        try {

            $response = $apiInstanceFBA->CreateFulfillmentOrder($request);


Thanks again!

Ronan Lapie
SCB Solutions, Inc.
2200 Wilson Boulevard
Arlington, VA 22201
+1 703 465 9491
***@***.******@***.***>
http://www.scbsolutions.com<http://www.scbsolutions.com/>

This e-mail is confidential and may be privileged and/or proprietary.  If you are not the intended recipient, any review, disclosure, copying, or use of this e-mail is prohibited.

**Comment by Ronan04130** [comment]
Hello Jesse:
The problem was in the signature date:
class AuthorizationSigner implements AuthorizationSignerContract
{
    //public const DATETIME_FMT = 'Ymd\THis\Z';
    public const DATETIME_FMT = 'Y-m-d\TH:i:s\Z';

Not quite there though. I am now getting an invalid signature error…
Sincerely,

Ronan Lapie
SCB Solutions, Inc.
2200 Wilson Boulevard
Arlington, VA 22201
+1 703 465 9491
***@***.******@***.***>
http://www.scbsolutions.com<http://www.scbsolutions.com/>

This e-mail is confidential and may be privileged and/or proprietary.  If you are not the intended recipient, any review, disclosure, copying, or use of this e-mail is prohibited.

**Comment by jlevers** [comment]
I don't think the issue is the date format in `AuthorizationSigner`, because that date format shouldn't affect your model serialization at all. What makes you say that's the problem?

The signature-related error you're getting is almost certainly because you changed the date format in `AuthorizationSigner`, since the request signing process has a lot of very specific steps, one of which involves the current datetime formatted in a particular way.

**Comment by Ronan04130** [comment]
You are entirely right. This was not the issue.
I actually just completed the first order.
Surprisingly with the following code:
$payload = [
            'displayableOrderDate' => date("Y-m-d\TH:i:s\Z"),
            'marketplaceId' => MARKETPLACE_ID,
            'sellerFulfillmentOrderId' => $Body_OrderId,
            'displayableOrderId' => $Body_OrderId,
            'destinationAddress' => $address,
            'displayableOrderComment' => 'Thank you for your order at SCB Solutions!',
            'items' => $item,
            'shippingSpeedCategory' => fba_get_amazon_shipping_class($order->delivery['shipping_module']),
            'notificationEmails' => $email_list,
        ];
        echo "<pre>";
        //print_r($payload);
        try {

            $response = $apiInstanceFBA->CreateFulfillmentOrder($payload);


Ronan Lapie
SCB Solutions, Inc.
2200 Wilson Boulevard
Arlington, VA 22201
+1 703 465 9491
***@***.******@***.***>
http://www.scbsolutions.com<http://www.scbsolutions.com/>

This e-mail is confidential and may be privileged and/or proprietary.  If you are not the intended recipient, any review, disclosure, copying, or use of this e-mail is prohibited.

**Comment by jlevers** [comment]
Awesome! Glad you got it figured out.
