### ISSUE TITLE
getMessagingActionsForOrder() - How can I access the messages?

### ISSUE THREAD

**Issue by BeranAday** [jlevers/selling-partner-api#544]
I'm trying to reach messages from customers. When I use the getMessagingActionsForOrder() function, I get the following response. As far as I understand, I need to access the messages using the links here. I'm stuck at this point.

I am open to even the smallest help. :)

```json
{
  "_links": {
    "self": {
      "href": ["/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX?marketplaceIds=A1F83G8C2ARO7P"]
    },
    "actions": [
      {
        "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/legalDisclosure?marketplaceIds=A1F83G8C2ARO7P",
        "name": "legalDisclosure"
      },
      {
        "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/unexpectedProblem?marketplaceIds=A1F83G8C2ARO7P",
        "name": "unexpectedProblem"
      }
    ]
  },
  "_embedded": {
    "actions": [
      {
        "_links": {
          "self": {
            "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/legalDisclosure?marketplaceIds=A1F83G8C2ARO7P",
            "name": "legalDisclosure"
          },
          "schema": {
            "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/legalDisclosure/schema",
            "name": "legalDisclosure"
          }
        },
        "_embedded": {
          "schema": {
            "_links": {
              "self": {
                "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/legalDisclosure/schema",
                "name": "legalDisclosure"
              }
            }
          }
        }
      },
      {
        "_links": {
          "self": {
            "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/unexpectedProblem?marketplaceIds=A1F83G8C2ARO7P",
            "name": "unexpectedProblem"
          },
          "schema": {
            "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/unexpectedProblem/schema",
            "name": "unexpectedProblem"
          }
        },
        "_embedded": {
          "schema": {
            "_links": {
              "self": {
                "href": "/messaging/v1/orders/XXX-XXXXXXX-XXXXXXX/messages/unexpectedProblem/schema",
                "name": "unexpectedProblem"
              }
            }
          }
        }
      }
    ]
  }
}
```

**Comment by jlevers** [comment]
Hi @BeranAday,

Have you looked through the Messaging API's [Use Case Guide](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-use-case-guide)? It gives a step-by-step tutorial on how to send a message to a customer for a particular order.

My understanding is that those links point you to available message types schemas, not links to individual messages. You can then send a message by calling the Messaging API endpoint corresponding to the message type you want to send (for instance, if you wanted to send an `unexpectedProblem` message, you could call the [`createUnexpectedProblem`](https://developer-docs.amazon.com/sp-api/docs/messaging-api-v1-reference#createunexpectedproblem) endpoint.

There are some details to this process that are explained in the use case guide I linked to.

**Comment by BeranAday** [comment]
Hi @jlevers 

Thank you for your answer. I actually took a quick look and started to develop it. I want to be able to read and respond to messages from customers within the API. Like a mini customer service. Although I see a few things about sending messages, I will first start with the section of viewing messages, and then move on to the section of replying to messages after the messages are displayed. There are only 2 get functions in **[MessagingV1Api](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/MessagingV1Api.md)**, **getAttributes()** and **getMessagingActionsForOrder()**. I am trying on how I can display messages with these two functions.

**Comment by jlevers** [comment]
I'm not sure there's any way to retrieve customer messages via the SP API, unfortunately. I just did some digging and couldn't find any way to do that.

**Comment by BeranAday** [comment]
I see, no problem, thank you for your effort. If I can find a way, I'll share it here.
