### ISSUE TITLE
Obtain most interface prompts InvalidInput

### ISSUE THREAD

**Issue by zhiyinsoft** [jlevers/selling-partner-api#546]
## Problem description:
When I test most interfaces, the interface prompts InvalidInput，My application is currently in the testing phase and has not been released
## Error:
```
[400] { "errors": [ { "code": "InvalidInput", "message": "Could not match input arguments", "details": "" } ] }
```

## Code
```php

$config = new Configuration([
            "lwaClientId" => "amzn1.application-oa2-client.hidden",
            "lwaClientSecret" => "amzn1.oa2-cs.v1.hidden",
            "lwaRefreshToken" => "Atzr|hidden",
            "awsAccessKeyId" => "AKIAT2 hidden",
            "awsSecretAccessKey" => "QL1oW7 hidden",
            "endpoint" => Endpoint::EU_SANDBOX,
            "roleArn" => "arn:aws:iam::hidden:role/hidden"            
        ]);
$apiInstance = new OrdersV0Api($config);
$marketplace_ids = array('A1PA6795UKMFR9');
$created_after = date("c", strtotime('2023-05-20'));
$created_before = date("c", strtotime('2023-05-22'));
$result = $apiInstance->getOrders($marketplace_ids, $created_after, $created_before);
echo '<pre>';
print_r($result);
echo '</pre>';
exit;
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
The sandbox endpoints only support very specific static inputs, and thus are not that useful for testing your code. If you want to see the supported sandbox inputs for a given request, you have to look at the responses in the JSON models for the relevant API. For instance, the static inputs and expected static output for the `getOrders` endpoint is [here](https://github.com/amzn/selling-partner-api-models/blob/73b38981ed6abec9c6d92b212a302c32d0a67d9b/models/orders-api-model/ordersV0.json#L252).

I recommend trying your request again with the normal `Endpoint::EU` endpoint and see if it works – I don't see any obvious issues in your code.

**Comment by zhiyinsoft** [comment]
Thank you for your reply. When I add Endpoint:: EU_ After changing SANDBOX to Endpoint:: EU, the following prompt appears：
[400] { "errors": [ { "code": "InvalidInput", "message": "Application do not have access to some or all requested resource", "details": "" } ] }

Does it mean that we need to publish our application before conducting formal store data docking?

Actually, our main goal is to test whether the interface can be called correctly and obtain the corresponding data

**Comment by jlevers** [comment]
You don't need to publish your application, no. Which Selling Partner API roles do you have access to? You can see them in your SP API application config.

**Comment by zhiyinsoft** [comment]
Can you please let us know where to view and set up, as we are new to development and not very familiar with Amazon APIs? Also, could you please let us know:
1. We need to pull orders
2. We need to modify the logistics information of the order and update the status of the order for shipment
Currently, only these functions are needed. Can you tell me which ones need to be authorized?

Thank you very much for your prompt reply！

**Comment by jlevers** [comment]
You can see the roles selected/available for your application in Seller Central on the Develop Apps page by going to the edit page for the relevant app. To make more roles available you will have to resubmit your developer application with the new roles you want selected.

If you're FBM, you will need the restricted Direct-to-Consumer Shipping role and the Inventory and Order Tracking role. If you're FBA, you'll need Amazon Fulfillment and Inventory and Order Tracking.

**Comment by jlevers** [comment]
Since I haven't heard from you, I'm going to assume your issue is resolved. If that's not the case, please feel free to reopen this issue.
