### ISSUE TITLE
getOrderAddress() and getOrderBuyerInfo() interfaces returned the following errors

### ISSUE THREAD

**Issue by zhiyinsoft** [jlevers/selling-partner-api#550]
## Problem description:
The getOrder and getOrderItems () interfaces successfully returned data，but both getOrderAddress() and getOrderBuyerInfo() interfaces returned the following errors:
## Error:

```
[400] { "errors": [ { "code": "InvalidInput", "message": "Application do not have access to some or all requested resource", "details": "" } ] }
```
May I ask what is causing this? Can you tell me where to set it in order for these two interfaces to successfully return data?

I have another question, which interface can return the weight of all products in the order？

**Comment by jlevers** [comment]
Those endpoints are deprecated – try using the `getOrder` endpoint with `$data_elements` passed to get buyer and shipping info (more info [here](https://github.com/jlevers/selling-partner-api#restricted-operations)). Note that you will not be able to get buyer or shipping information unless you have been approved for PII access.
