### ISSUE TITLE
getOrders 400 Invalid Input Could not match input argument

### ISSUE THREAD

**Issue by pgbrown** [jlevers/selling-partner-api#551]
## Problem description:
I expect I'm doing something really stupid here, but after going through the Issues to no avail I thought I'd ask why I may be getting the following error. I'm trying to keep it basic (just want to get some orders coming down) before modifying more variables. Am using the Sandbox.

## Error:

```
{ "code": "InvalidInput", "message": "Could not match input arguments", "details": "" }
```

## Code

```php
 try {
            $orders = $this->api->getOrders(
                ['A39IBJ37TRP1C6'],
                '2022-05-28T00:00:00Z',
                null,
                null,
                null,
                array('PendingAvailability',  'Pending', 'Unshipped', 'PartiallyShipped', 'Shipped', 'InvoiceUnconfirmed', 'Canceled', 'Unfulfillable'),
                array('MFN'),
                null,
                null,
                null,
                100,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null
            );
            return $orders;
        } catch (\Exception $ex) {
            echo 'Exception when calling OrdersApi:->getOrders ', $ex->getMessage(), PHP_EOL;
        }
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
The sandbox only accepts certain static inputs and produces particular static outputs – you can't make arbitrary requests to sandbox endpoints (unfortunately). If you run that request outside the sandbox, it should work, as @DomuITteam said.

**Comment by pgbrown** [comment]
Yes it worked perfectly when I connected to the production environment. Makes it  a bit annoying. But  it's not the first time Amazon have annoyed me :)

**Comment by stephengineer** [comment]
I connected to my APP client and use valid date: `2017-01-20T19:49:35Z`, I still got error:
```json
"errors": [
    {
      "code": "InvalidInput",
      "message": "Could not match input arguments",
      "details": ""
    }
  ]
```
