### ISSUE TITLE
Feeds always getting cancelled.

### ISSUE THREAD

**Issue by tajinderk** [jlevers/selling-partner-api#555]
Feed Submission Result not available. Feed Submission has been canceled for Feed: XXXXXXXXXXXXX

I am getting the Feed ID but those are always getting cancelled.
Can you explain what the issue could be?

**Comment by meertensm** [comment]
@tajinderk
One of my customers had this on Amazon Spain and Italy. The permission to sell actively was pulled due to low performance. The same api credentials were still working for Germany and France.
Maybe check if your account is (fully) active?
Also are you sure the feed has the right format?

**Comment by jlevers** [comment]
@tajinderk take a look at #545. The common reasons for reports being cancelled are discussed there.
