### ISSUE TITLE
Error in getShipments in FbaInboundV0Api. invalid length for $district_or_county when calling Address., must be smaller than or equal to 25.

### ISSUE THREAD

**Issue by Sri0311** [jlevers/selling-partner-api#557]
## Problem description:
Error in getShipments in FbaInboundV0Api while using the marketplaceID "A2VIGQ35RCS4UG"
## Error:

```
# invalid length for $district_or_county when calling Address., must be smaller than or equal to 25.
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
This is fixed in `v5.10.1`, thanks for reporting!
