### ISSUE TITLE
Restricted Access Request

### ISSUE THREAD

**Issue by muglali20** [jlevers/selling-partner-api#558]
Hello,
We have been requesting PII access for more than 6 months.
We provide all the information and documents requested by Amazon, but these requests are denied without any clear reason.
Due to this problem, our software development process and our customers are suffering.
We have to access this information as soon as possible and satisfy our customers.
Can you please support those who received positive feedback on this issue, what should we do? :(
The final answer is as follows:
"Hello,

Thank you for your response.
As previously mentioned, we have determined that you will not be given access to Restricted SP-API roles based on your application. Your SP-API access remains unchanged at this time.

We evaluate all Public Developer applications that request Restricted SP-API access, for a variety of technical and business criteria including, but not limited to, launch readiness, services offered that can be viewed on a public facing website, and supported geographies.

Please note that this decision is final and we may not respond to further inquiries about this.

Thank you for selling with Amazon. 

Amazon.co.uk Seller Support

**Comment by jlevers** [comment]
Hi @muglali20 – this is somewhat outside the scope of this library, but I do help companies apply for PII access. Shoot me an email at [first name] [at] highsidelabs [dot] co and we can work something out.
