### ISSUE TITLE
Update Quantity and/or Price example.

### ISSUE THREAD

**Issue by UpsyDavy** [jlevers/selling-partner-api#561]
Hi

Is example code available for updating inventory quantity and/or price? Preferably for multiple SKUs.

Thank in advance for your help.

Regards

**Comment by DomuITteam** [comment]
To update inventory levels in bulk, you can focus on using Feeds, specifically POST_INVENTORY_AVAILABILITY_DATA.

Our approach is to build a string that contains inventory update information as XML.

The beginning is always the same:

```
<?xml version='1.0' encoding='utf-8' ?>
<AmazonEnvelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='amzn-envelope.xsd'>
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>YOUR MERCHANT ID</MerchantIdentifier>
</Header>
<MessageType>Inventory</MessageType>
```

Then for each seller sku you want to update, concatenate the string with the following information:

```
<Message>
<MessageID>Unique message ID, starting from 1 and incremented by 1 with each product</MessageID>
<OperationType>Update</OperationType>
<Inventory>
<SKU>SELLER SKU</SKU>
<Quantity>123456</Quantity>
</Inventory>
</Message>
```

If you want to provide a restock date, you simply add the date in **\<RestockDate>** tags before closing the **\</Inventory>** tag.

Afterwards, complete the string by closing **\</AmazonEnvelope>** tag. Then you create the feed, and how to do it is explained [here](https://github.com/jlevers/selling-partner-api#uploading-a-feed-document) - we simply provide our string instead of **$feedContents** variable/XML file.

**Comment by UpsyDavy** [comment]
Hi

Thank you so much for your response. This building block looks very similar to the way we are currently using in MWS. Can you please explain where we add the code into the example code below for createFeed() in FeedsV20210630Api.md

https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/FeedsV20210630Api.md#createFeed

Thank you in advance for your help.

Regards

<?php
require_once(__DIR__ . '/vendor/autoload.php');

// See README for more information on the Configuration object's options
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "<LWA client ID>",
    "lwaClientSecret" => "<LWA client secret>",
    "lwaRefreshToken" => "<LWA refresh token>",
    "awsAccessKeyId" => "<AWS access key ID>",
    "awsSecretAccessKey" => "<AWS secret access key>",
    "endpoint" => SellingPartnerApi\Endpoint::NA  // or another endpoint from lib/Endpoints.php
]);

$apiInstance = new SellingPartnerApi\Api\FeedsV20210630Api($config);
$body = new \SellingPartnerApi\Model\FeedsV20210630\CreateFeedSpecification(); // \SellingPartnerApi\Model\FeedsV20210630\CreateFeedSpecification

try {
    $result = $apiInstance->createFeed($body);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling FeedsV20210630Api->createFeed: ', $e->getMessage(), PHP_EOL;
}

**Comment by DomuITteam** [comment]
It all depends on how your code is structured, mine looks more or less like this:

```
use SellingPartnerApi\Document;
use SellingPartnerApi\FeedType;
use SellingPartnerApi\Model\FeedsV20210630 as Feeds;
use SellingPartnerApi\Api\FeedsV20210630Api as FeedsApi;

$feedType = FeedType::POST_INVENTORY_AVAILABILITY_DATA;
$feedsApi = new FeedsApi(YOUR CONFIG VARIABLE);
$createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);

$feedDocumentId = $feedDocumentInfo->getFeedDocumentId();
$feedContents = YOUR XML STRING WITH STOCK UPDATES;
$docToUpload = new Document($feedDocumentInfo, $feedType);

$docToUpload->upload($feedContents);

$createFeedSpec = new Feeds\CreateFeedSpecification();
$createFeedSpec->setMarketplaceIds(YOUR MARKETPLACE IDS);
$createFeedSpec->setInputFeedDocumentId($feedDocumentId);
$createFeedSpec->setFeedType($feedType['name']);

$createFeedResult = $feedsApi->createFeed($createFeedSpec);
$feedId = $createFeedResult->getFeedId();
$feed = $feedsApi->getFeed($feedId);
```

The last two lines are optional but useful if you want to check further down the code if the feed creation process was successful, and what are the results. Hopefully, that helps.

**Comment by UpsyDavy** [comment]
Hi DumulTteam

Thank you for your help again. I think I'm almost there but not quite. The complete code I am trying is below. The response I am getting when echoing $feed is:

{ "feedId": "254192019535", "feedType": "POST_PRODUCT_PRICING_DATA", "marketplaceIds": [ "A1F83G8C2ARO7P" ], "createdTime": "2023-06-27T11:08:03+00:00", "processingStatus": "IN_QUEUE" }

and the quantity does not update.

Anything you can see that I may be missing.

Thank you again in advance for your help.

Regards


<?php
require_once(__DIR__ . '/vendor/autoload.php');

// See README for more information on the Configuration object's options
$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "xx--amzn1--xx",
    "lwaClientSecret" => "xx--48184--xx",
    "lwaRefreshToken" => "xx--Atzr--xx",
    "awsAccessKeyId" => "xx--4CEO--xx",
    "awsSecretAccessKey" => "xx--ZlBZc--xx",
    "endpoint" => SellingPartnerApi\Endpoint::EU  // or another endpoint from lib/Endpoints.php
]);

use SellingPartnerApi\Api\FeedsV20210630Api as FeedsApi;
use SellingPartnerApi\FeedType;
use SellingPartnerApi\Model\FeedsV20210630 as Feeds;

$feedType = FeedType::POST_PRODUCT_PRICING_DATA;
$feedsApi = new FeedsApi($config);

// Create feed document
$createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
$feedDocumentId = $feedDocumentInfo->getFeedDocumentId();

// Upload feed contents to document
$feedContents = "
<?xml version='1.0'encoding='utf-8'?> 
<AmazonEnvelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='amzn-envelope.xsd'>
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>xx--ID--xx</MerchantIdentifier>
</Header>
<MessageType>Inventory</MessageType>

<Message>
<MessageID>1</MessageID>
<OperationType>Update</OperationType>
<Inventory>
<SKU>1234567</SKU>
<Quantity>300</Quantity>
</Inventory>
</Message>

</AmazonEnvelope>"
;
// The Document constructor accepts a custom \GuzzleHttp\Client object as an optional 3rd parameter. If that
// parameter is passed, your custom Guzzle client will be used when uploading the feed document contents to Amazon.
$docToUpload = new SellingPartnerApi\Document($feedDocumentInfo, $feedType);
$docToUpload->upload($feedContents);

$createFeedSpec = new Feeds\CreateFeedSpecification();
$createFeedSpec->setMarketplaceIds(['A1F83G8C2ARO7P']);
$createFeedSpec->setInputFeedDocumentId($feedDocumentId);
$createFeedSpec->setFeedType($feedType['name']);

$createFeedResult = $feedsApi->createFeed($createFeedSpec);
$feedId = $createFeedResult->getFeedId();
$feed = $feedsApi->getFeed($feedId);

echo $feed;

**Comment by jlevers** [comment]
Feeds take some time to finish processing, so the feed status in response to your `createFeed` call will never be `DONE` – it will always be `IN_PROCESS` or `IN_QUEUE`. You need to call `getFeed` periodically to see when the feed is done processing. Once that's done, you can call `getFeedDocument` (as described [in the README](https://github.com/jlevers/selling-partner-api#downloading-a-feed-result-document)) to get the processing report for the feed, which will tell you if there were any issues with it.

**Comment by UpsyDavy** [comment]
Hi JesseThanks for the info. I’m out of the office for a few days now. I’ll check this out when I return. RegardsDavidSent from my iPhoneOn 29 Jun 2023, at 19:24, Jesse Evers ***@***.***> wrote:﻿
Feeds take some time to finish processing, so the feed status in response to your createFeed call will never be DONE – it will always be IN_PROCESS or IN_QUEUE. You need to call getFeed periodically to see when the feed is done processing. Once that's done, you can call getFeedDocument (as described in the README) to get the processing report for the feed, which will tell you if there were any issues with it.

**Comment by jordan26** [comment]
Hi All. I am also using these methods to update my listings stock. I've managed to submit the feed successfully, waited as it eventually switched to `DONE` status, no change to the stock on Seller Central however, I've refreshed plenty of times, has not changed value to match what I sent.

I am now also trying to set up the `getFeedDocument` to download the processing report, the code I think runs (no errors shown on screen) but nothing is downloaded via the browser:

```
$contents = $docToDownload->download();  // The raw report data
$data = $docToDownload->getData();  // Parsed/formatted report data
```

These lines are adding the report contents to the variables, but not sure how to actually trigger it to download for me to open and view.

**Comment by jordan26** [comment]
Hi All, I am setting up a script using the above to update inventory as per the examples above too. I am sending fine and feed eventually switches to DONE. However upon checking the result it's failing:

```
["ResultDescription"]=>
        string(112) "XML Parsing Fatal Error at Line 2, Column 1: Content is not allowed in prolog. Content is not allowed in prolog."
```

I am using the exact same XML set up as per the code provided by @UpsyDavy. In terms of this XML template, where are you finding this from? How did you know what XML elements to use, in what format etc?

I'll continue to update if I find anything, this thread has been helpful and I need to get this up and running by Friday.

**Comment by jordan26** [comment]
Deleted my previous replies as I have now got it all working, here you go @UpsyDavy :

The `FeedType` needed to be: **POST_INVENTORY_AVAILABILITY_DATA**
Modified the XML to be the same as yours but without all the backslashes, not sure if that was just something whilst you posted to GH or something.

**Code for submitting inventory for a SKU and getting back a feed ID:**

```
use SellingPartnerApi\Api\FeedsV20210630Api as FeedsApi;
use SellingPartnerApi\FeedType;
use SellingPartnerApi\Model\FeedsV20210630 as Feeds;

$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "xxxxx",
    "lwaClientSecret" => "xxxxx",
    "lwaRefreshToken" => "xxxxx",
    "awsAccessKeyId" => "xxxxx",
    "awsSecretAccessKey" => "xxxxx",
    "endpoint" => SellingPartnerApi\Endpoint::EU,
]);

$feedType = FeedType::POST_INVENTORY_AVAILABILITY_DATA;
$feedsApi = new FeedsApi($config);

// Create feed document
$createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
$feedDocumentId = $feedDocumentInfo->getFeedDocumentId();

// Upload feed contents to document
$feedContents = "<?xml version='1.0' encoding='utf-8' ?>
<AmazonEnvelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='amzn-envelope.xsd'>
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>XXXXXXXXXXX</MerchantIdentifier>
</Header>
<MessageType>Inventory</MessageType>
<Message>
<MessageID>1</MessageID>
<OperationType>Update</OperationType>
<Inventory>
<SKU>571081GE</SKU>
<Quantity>101</Quantity>
</Inventory>
</Message>
</AmazonEnvelope>";

// The Document constructor accepts a custom \GuzzleHttp\Client object as an optional 3rd parameter. If that
// parameter is passed, your custom Guzzle client will be used when uploading the feed document contents to Amazon.
$docToUpload = new SellingPartnerApi\Document($feedDocumentInfo, $feedType);
$docToUpload->upload($feedContents);

$createFeedSpec = new Feeds\CreateFeedSpecification();
$createFeedSpec->setMarketplaceIds(['A1F83G8C2ARO7P']);
$createFeedSpec->setInputFeedDocumentId($feedDocumentId);
$createFeedSpec->setFeedType($feedType['name']);

$createFeedResult = $feedsApi->createFeed($createFeedSpec);
$feedId = $createFeedResult->getFeedId();
$feed = $feedsApi->getFeed($feedId);

echo $feed;
```

**Code for checking the status of a submitted feed, such as `IN_PROGRESS`, `DONE` etc.**

```
$feedId = 'XXXXXX'; // The feed ID returned from the createFeed call previously ran from the code above.
$feed = $feedsApi->getFeed($feedId);

echo $feed;
```

**Code for checking the result of a submitted feed, if it was successful (or not). If not, it will provide the error. I was simply dumping the data on screen in my tests.**

```
use SellingPartnerApi\Api\FeedsV20210630Api as FeedsApi;
use SellingPartnerApi\FeedType;
use SellingPartnerApi\Model\FeedsV20210630 as Feeds;

$config = new SellingPartnerApi\Configuration([
    "lwaClientId" => "xxxxx",
    "lwaClientSecret" => "xxxxx",
    "lwaRefreshToken" => "xxxxx",
    "awsAccessKeyId" => "xxxxx",
    "awsSecretAccessKey" => "xxxxx",
    "endpoint" => SellingPartnerApi\Endpoint::EU,
]);

$feedType = FeedType::POST_PRODUCT_PRICING_DATA;
$feedsApi = new FeedsApi($config);

$feedId = 'XXXXXXXXX';  // From the createFeed call
$feed = $feedsApi->getFeed($feedId);

$feedResultDocumentId = $feed->resultFeedDocumentId;
$feedResultDocument = $feedsApi->getFeedDocument($feedResultDocumentId);

$docToDownload = new SellingPartnerApi\Document($feedResultDocument, $feedType);
$contents = $docToDownload->download();  // The raw report data
$data = $docToDownload->getData();  // Parsed/formatted report data

echo '<pre>';
var_dump($data);
echo '</pre>';
```

**Comment by jordan26** [comment]
Sorry, to clarify, in my example I only wanted to update Inventory, that's why I used `POST_INVENTORY_AVAILABILITY_DATA` as the feedtype, so I suppose `POST_PRODUCT_PRICING_DATA` is what you want. Be sure to update the XML to declare a `<price>` tag instead of the `<inventory>` item like mine.

**Comment by UpsyDavy** [comment]
@jordan26 Thank you so much, you are a superstar for helping to get this working. I was nearly there but not quite and the response was not giving me enough information to solve the problem.

For anybody else struggling to update price the changes to the inventory update code posted by @jordan26 are:

Change POST_INVENTORY_AVAILABILITY_DATA for POST_PRODUCT_PRICING_DATA

and change

<Inventory>
<SKU>571081GE</SKU>
<Quantity>101</Quantity>
</Inventory>

to

<Price>
<SKU>xxxxxx</SKU>
<StandardPrice currency='GBP'>8.03</StandardPrice>
</Price>

Currency would need to be set to your local currency.

@jlevers Thanks again for your continued support

**Comment by UpsyDavy** [comment]
@jordan26 Thank you so much, you are a superstar for helping to get this working. I was nearly there but not quite and the response was not giving me enough information to solve the problem.

For anybody else struggling to update price the changes to the inventory update code posted by @jordan26 are:

Change POST_INVENTORY_AVAILABILITY_DATA for POST_PRODUCT_PRICING_DATA

and change

`<Inventory>
<SKU>571081GE</SKU>
<Quantity>101</Quantity>
</Inventory>`

to

`<Price>
<SKU>xxxxx</SKU>
<StandardPrice currency='GBP'>8.03</StandardPrice>
</Price>`

Currency would need to be set to your local currency.

@jlevers Thanks again for your continued support

**Comment by jordan26** [comment]
Thanks @UpsyDavy too! I would not have known you have to include currency too, good to know as I may soon be setting up a price script too. Information such as needing to include `currency` where did you find that out from, or was it from an API response when you tested your script?

**Comment by UpsyDavy** [comment]
@jordan26 

I copied the XML code from what we are currently using on AWS API.

[https://developer-docs.amazon.com/sp-api/docs/migrating-listings-management-workflows#submitting-pricing-data](url)

The above link shows some examples of XML code

Hope it helps

**Comment by jlevers** [comment]
@UpsyDavy it looks like your question was answered, so I'm going to close this issue.

**Comment by Fran-Brogiolo** [comment]
Hello, do you know if to update quantities/prices for many items, we need to create a single feed and request for each item, or we can simply concatenate somehow in the XML so we have many messages, one for each item?
Thanks!

**Comment by UpsyDavy** [comment]
Hi

You can have many message (one for each item) in one request. Each must have a unique message id.

Hope this helps

**Comment by UpsyDavy** [comment]
```
<AmazonEnvelope xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='amzn-envelope.xsd'>
<Header>
<DocumentVersion>1.01</DocumentVersion>
<MerchantIdentifier>XXXXXXXXXXX</MerchantIdentifier>
</Header>
<MessageType>Inventory</MessageType>
  <Message>
    <MessageID>1</MessageID>
    <OperationType>Update</OperationType>
    <Inventory>
      <SKU>SKU1</SKU>
      <Quantity>100</Quantity>
    </Inventory>
  </Message>
  <Message>
    <MessageID>2</MessageID>
    <OperationType>Update</OperationType>
    <Inventory>
      <SKU>SKU2</SKU>
      <Quantity>101</Quantity>
    </Inventory>
  </Message>
</AmazonEnvelope>";
```

**Comment by Fran-Brogiolo** [comment]
Thank you very much :)

**Comment by Fran-Brogiolo** [comment]
Do you know if there is a limit of messages to send? I am trying to update around 300k item quantities in the same request, and the request is successfully completed (status DONE and no error messages) but Amazon never gets updated

**Comment by jlevers** [comment]
Yep, the limit is 10,000 items per report...I think I found that number in the `JSON_LISTINGS_FEED` schema doc at some point, although looking back at it I can't find it anymore. That number has worked consistently for me as a cutoff, though.

**Comment by Fran-Brogiolo** [comment]
Thank you ☺️

**Comment by jordan26** [comment]
> Yep, the limit is 10,000 items per report...I think I found that number in the `JSON_LISTINGS_FEED` schema doc at some point, although looking back at it I can't find it anymore. That number has worked consistently for me as a cutoff, though.

Here are the docs detailing the limits. Search "Throttle rates"
https://developer-docs.amazon.com/sp-api/docs/building-listings-management-workflows-guide#creating-and-updating-listings-items-in-bulk

**Comment by limeng92** [comment]
Hello, how can I update the pre-sale inventory + arrival time of pre-sale products in batches? If there is available inventory, I will update the available inventory. If there is pre-sale inventory, I will update the pre-sale inventory + arrival time of pre-sale products. How can I do this? Thank you.
