### ISSUE TITLE
GZDecode Error

### ISSUE THREAD

**Issue by titansoftime** [jlevers/selling-partner-api#563]
Hello,

I just today started getting this error "gzdecode(): data error".

Only seems to happen on this report GET_FLAT_FILE_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL regardless of date range.

I can workaround by editing:

```
        if ($this->compressionAlgo !== null && $this->compressionAlgo === "GZIP"  ) { // && false
            $contents = gzdecode($rawContents);
        } else {
            $contents = $rawContents;
        }
```

If I bypass GZIP it works.

**Comment by mikhaill** [comment]
Same here! I was going crazy because it's happening on some account and not others. It's happening for me on GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA reports.

**Comment by HeBuguM** [comment]
Check out issue #559

**Comment by titansoftime** [comment]
Duplicate of https://github.com/jlevers/selling-partner-api/issues/559
