### ISSUE TITLE
Use variable to access class memebr

### ISSUE THREAD

**Issue by eugenepritsker** [jlevers/selling-partner-api#565]
In the line:

$feedType = FeedType::POST_PRODUCT_PRICING_DATA;

can variable be used in place of POST_PRODUCT_PRICING_DATA?

For example:

$type = 'POST_PRODUCT_PRICING_DATA';

$feedType = FeedType::$type;

I tried different ways and only get errors.

**Comment by jlevers** [comment]
I usually use the `constant` built-in to handle this:

```php
$type = 'POST_PRODUCT_PRICING_DATA';
$feedType = constant("SellingPartnerApi\FeedType::$type");
```

**Comment by eugenepritsker** [comment]
Excellent. It works!

 

Sincerely,

Eugene
