### ISSUE TITLE
createFeed() exception error "Invalid request parameters"

### ISSUE THREAD

**Issue by SARANGHAJA** [jlevers/selling-partner-api#569]
## Problem description:
Dear Sir,

I am multiple markets are generating feeds.
In the US and Canada, createFeedDocument() and createFeed() are working well.
However in Singapore, createFeedDocument() is normal, but an error occurs at createFeed().
Singapore account information (AWS/LWA) information is no problem.
Because, the order information (getOrders(), getReportDocument()) is being imported normally.

## Code
```php
//ellipsis//
createFeedDocument(); //us,ca,sg success
//ellipsis//
upload() //us,ca,sg success

$opts = array(
	"feed_type"              => "POST_ORDER_FULFILLMENT_DATA",
	"marketplace_ids"        => array("[marketplace_ids]"),  /*US: ATVPDKIKX0DER, CA: A2EUQ1WTGCTBG2, SG: A19VAU5U5O7RUS*/
	"input_feed_document_id" => "[input_feed_document_id]",
	"feed_options"           => null
);
$body = new \SellingPartnerApi\Model\Feeds\CreateFeedSpecification($opts); // \SellingPartnerApi\Model\Feeds\CreateFeedSpecification
$api_result = $apiInstance->createFeed($body);  //us,ca success.   sg exception error
```

## Error in Singapore:
```
[400] { "errors": [ { "code": "InvalidInput", "message": "Invalid request parameters", "details": "" } ] }
```

I don't know what the problem.
I need your help.

Thank you.

**Comment by jlevers** [comment]
Are you using the `Endpoint::FE` endpoint (in the `Configuration` constructor) for your Singapore calls?

**Comment by SARANGHAJA** [comment]
thank you sir.


[My Configuration Code]
```
//Get country-specific information from DB and set it to each constants
..ellipsis..

eval("\$endpoint = SellingPartnerApi\Endpoint::".ENDPOINT.";");  //When Singapore, ``SellingPartnerApi\Endpoint::FE``
$_CONFIG = new SellingPartnerApi\Configuration([
	"lwaClientId" => LWA_CLIENT_ID,
	"lwaClientSecret" => LWA_CLIENT_SECRET,
	"lwaRefreshToken" => LWA_REFRESH_TOKEN,
	"awsAccessKeyId" => AWS_ACCESSKEY_ID,
	"awsSecretAccessKey" => AWS_SECRET_ACCESSKEY,
	"endpoint" => $endpoint
]);

$apiInstance = new SellingPartnerApi\Api\FeedsApi($_CONFIG);
```


When Singapore, the endpoint information is as follows
```
Array
(
    [url] => https://sellingpartnerapi-fe.amazon.com
    [region] => us-west-2
)
```

**Comment by jlevers** [comment]
I don't see anything obviously wrong with your code. I recommend you get in touch with Amazon support about this, because it seems like there might be some issue in how they're processing `POST_ORDER_FULFILLMENT_DATA` reports in Singapore.

**Comment by SARANGHAJA** [comment]
Thank you.
I'll ask Amazon about this issue.

"jlevers/selling-partner-api" is such a wonderful project.
I'm using it very well.
Thank you always.
