### ISSUE TITLE
Orders API v0 OrderItem DeemedResellerCategory new value 'JE_VOEC'

### ISSUE THREAD

**Issue by Stuart1066** [jlevers/selling-partner-api#570]
When downloading our order items from the EU endpoint for one order we received an error to say the Orders API v0 OrderItem DeemedResellerCategory value 'JE_VOEC' is not supported.

Please can you add the new DeemedResellerCategory value 'JE_VOEC'. I edited OrderItem.php, extract below, to add the two lines which contain JE_VOEC and the order item was processed without a problem. Thanks for building this project, it's been a great help. 

    const DEEMED_RESELLER_CATEGORY_IOSS = 'IOSS';
    const DEEMED_RESELLER_CATEGORY_UOSS = 'UOSS';
    const DEEMED_RESELLER_CATEGORY_SG_VOEC = 'SG_VOEC';
    const DEEMED_RESELLER_CATEGORY_GB_VOEC = 'GB_VOEC';
    const DEEMED_RESELLER_CATEGORY_NO_VOEC = 'NO_VOEC';
    const DEEMED_RESELLER_CATEGORY_CA_MPF = 'CA_MPF';
    const DEEMED_RESELLER_CATEGORY_AU_VOEC = 'AU_VOEC';
    const DEEMED_RESELLER_CATEGORY_NZ_VOEC = 'NZ_VOEC';
    const DEEMED_RESELLER_CATEGORY_CH_SUPPLIER_IMPORT = 'CH_SUPPLIER_IMPORT';
    const DEEMED_RESELLER_CATEGORY_JE_VOEC = 'JE_VOEC';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeemedResellerCategoryAllowableValues()
    {
        $baseVals = [
            self::DEEMED_RESELLER_CATEGORY_IOSS,
            self::DEEMED_RESELLER_CATEGORY_UOSS,
            self::DEEMED_RESELLER_CATEGORY_SG_VOEC,
            self::DEEMED_RESELLER_CATEGORY_GB_VOEC,
            self::DEEMED_RESELLER_CATEGORY_NO_VOEC,
            self::DEEMED_RESELLER_CATEGORY_CA_MPF,
            self::DEEMED_RESELLER_CATEGORY_AU_VOEC,
            self::DEEMED_RESELLER_CATEGORY_NZ_VOEC,
            self::DEEMED_RESELLER_CATEGORY_CH_SUPPLIER_IMPORT,
            self::DEEMED_RESELLER_CATEGORY_JE_VOEC,
        ];

**Comment by jlevers** [comment]
Thanks for reporting – this should be fixed in `v5.10.0`.

**Comment by mcphelan** [comment]
Are the models going to be updated to include this?

https://github.com/amzn/selling-partner-api-models/blob/main/models/orders-api-model/ordersV0.json
