### ISSUE TITLE
createReport() Error when retrieving GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE report type

### ISSUE THREAD

**Issue by Julian3004** [jlevers/selling-partner-api#573]
I'm encountering difficulties when trying to retrieve the GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE report type. I'm receiving an ApiException with error code InvalidInput and message "Request for report type 1117 is not allowed at this time".

The exact error I receive is as follows:

`Fatal error: Uncaught SellingPartnerApi\ApiException: [400] { "errors": [ { "code": "InvalidInput", "message": "Request for report type 1117 is not allowed at this time", "details": "" } ] } in /Users/Shared/www/inc/vendor/jlevers/selling-partner-api/lib/Api/ReportsV20210630Api.php:674`

And here's the code I'm using to request the report:

```
$reportType = SellingPartnerApi\ReportType::GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE;
$iReportId = '';

if ($iReportId == '') {
  $apiInstance = new SellingPartnerApi\Api\ReportsV20210630Api($config);

  $body = new SellingPartnerApi\Model\ReportsV20210630\CreateReportSpecification();
  $body->setDataStartTime(gmdate ('Y-m-d\TH:i:s\Z', strtotime (date ('Y-m-d', strtotime ('-3days')). ' 00:00:00') - (2 * 60 * 60)));
  $body->setDataEndTime(gmdate ('Y-m-d\TH:i:s\Z', strtotime (date ('Y-m-d', strtotime ('-1day')). ' 23:59:59')));
  $body->setReportType($reportType['name']);
  $body->setMarketplaceIds(['A1PA6795UKMFR9']);
  $body->setReportOptions(['Action' => 'GetReport']);

  $report_id = $apiInstance->createReport($body);
  $iReportId = $report_id->getReportID();
  echo $iReportId.'<br><br>';
}

```
The issue seems specific to the GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE report type. Is this a known issue? Or could there be something I'm overlooking in my code that's causing this error? Any assistance would be greatly appreciated.

**Comment by Akanksha-cedcoss** [comment]
I think you have not gone through the Sp-api documentation use guide.
https://developer-docs.amazon.com/sp-api/docs/report-type-values-settlement

If you go to this page of settlement type report values, you'll notice the very first line wrote by Amazon
 **Settlement reports cannot be requested or scheduled. They are automatically scheduled by Amazon. You can search for these reports using the getReports operation.**

So the error you are receiving **Request for report type 1117 is not allowed at this time** clearly means that you can not create request for any sattelement type of reports.

As it is also mentioned that Amazon automatically generates these reports periodically, what you would want to do i get the report id and download report. You can achieve this in 2 ways:

1. You can call getReports for api with reportTypes parameter which will you all the report_id of these type of reports. You can then get these report by gerReport api providing a report_id and download it.
read this :- [get reports api guide](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-reference#getreports)
Or.
3. If you want these report types regularly, you can subscribe to to REPORT_PROCESSING_FINISHED type of notification which will send you all the reports with their report_id and generated_report_id by which you can directly call downloadReport api.
[report notification guide](https://developer-docs.amazon.com/sp-api/docs/reports-api-v2021-06-30-tutorial-request-a-report)

**Comment by Julian3004** [comment]
You have helped me a lot! I should have read the SP-API documentation more carefully. I was only aware of the option with the getReports function. Thank you very much for the detailed explanation.
