### ISSUE TITLE
FBA shipment Product Labels

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#574]
Hello,
I am creating a new fba shipment plan. Everything is fine. We get package label but we want to get product labels as well. Which method should we use to get product labels?
Any help will be appreciated. Thank you,

Best regards

**Comment by Kernel1453** [comment]
Could you please help me about this problem? We cant print product labels, what must we do? @jlevers 
Thank you.

**Comment by Kernel1453** [comment]
Still not fixed

**Comment by jlevers** [comment]
Not entirely sure, but I think the Shipping V2 API's [getShipmentDocuments](https://developer-docs.amazon.com/amazon-shipping/docs/shipping-api-v2-reference#get-shippingv2shipmentsshipmentiddocuments) call might get you what you're looking for.

**Comment by Kernel1453** [comment]
No, this is not. This api is only for shippings which sold by FBM and purchased shipping over amazon.com.
So, we have to send this apis shipmentId. But we want to print FBA shipment item label.

Thank you for response.

**Comment by MuhammadDanyal** [comment]
Hi.
Were you able to print FBA shipment item label? facing the same issue.

> No, this is not. This api is only for shippings which sold by FBM and purchased shipping over amazon.com. So, we have to send this apis shipmentId. But we want to print FBA shipment item label.
> 
> Thank you for response.
