### ISSUE TITLE
missing address at getOrderItems()

### ISSUE THREAD

**Issue by KemnaMOL** [jlevers/selling-partner-api#582]
Hello,
when I use the getOrderItems() function I get the odered item, but not the shipping address.
When I use 
`$data_elements = array('\"buyerInfo\"');`
I get on error. I thing I must write it in other way?

**Comment by DomuITteam** [comment]
Pass Amazon order ID to **[getOrderAddress()](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/OrdersV0Api.md#getorderaddress)** to retrieve [shipping address information](https://github.com/jlevers/selling-partner-api/blob/main/docs/Model/OrdersV0/Address.md),

**Comment by KemnaMOL** [comment]
Yes, of course I had done this:
```
$apiInstance = new SellingPartnerApi\Api\OrdersV0Api($config);
$order_id = '30x-523xxx7-15xxxx2'; 
```

**Comment by jlevers** [comment]
There are a couple issues here. First, you can't retrieve shipping addresses via the `getOrderItems` endpoint, only buyer info. Shipping addresses are available via the `getOrders` and `getOrder` endpoints, if you pass `'shippingAddress'` in the `$data_elements` array. Second, you don't need to pre-escape `buyerInfo` – just write it like this:

```php
$data_elements = ['buyerInfo'];
```

Also, this won't work if you don't have access to one of the restricted roles that grants you access to buyer info (see info on restricted roles [here](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api#roles-in-the-selling-partner-api), and different roles are required for accessing shipping addresses vs buyer info. Buyer info is the buyer's tax-relevant address data, whereas shipping address is where the package is going...and those can be different values.

**Comment by KemnaMOL** [comment]
Thank you Jesse!
Of course it was my missunderstanding with the address. Now it works...
Maybe you can write the example better? There you write it pre-escaped. So I also do.

**Comment by jlevers** [comment]
@emelaz your IAM role is not related to your SP API roles – the SP API roles are based on the developer application you submitted in Seller Central. More info on SP API roles in the official docs, [here](https://developer-docs.amazon.com/sp-api/docs/roles-in-the-selling-partner-api).

`getOrderBuyerInfo` and `getOrderAddress` are also deprecated – please use `getOrder` and use the [`$data_elements`](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/OrdersV0Api.md#parameters-7) parameter to specify which PII you would like to retrieve, assuming you have been approved for PII access via one of the restricted SP API roles.

RDTs are automatically generated by the library, yes.
