### ISSUE TITLE
My client provided me grant_type, client_secret, client_id, iamarn and app Name credentials.  Are these credentials are enough  to connect to sp-api via your library?

### ISSUE THREAD

**Issue by ozddemir** [jlevers/selling-partner-api#589]
## Error:

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
You need an LWA client ID, LWA client secret, LWA refresh token, AWS access key ID, AWS secret access key, and (optionally, depending on how the SP API application is set up) the AWS IAM ARN.
