### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Aws\Sts\StsClient' not found 

### ISSUE THREAD

**Issue by salegoodluck** [jlevers/selling-partner-api#59]
Fatal error: Uncaught Error: Class 'Aws\Sts\StsClient' not found    in  jlevers/vendor/jlevers/selling-partner-api/lib/Authentication.php(167):

**Comment by RonJeremyR6** [comment]
Having the same problem (Windows 10):

Fatal error: Uncaught Error: Class 'Aws\Sts\StsClient' not found in \vendor\jlevers\selling-partner-api\lib\Authentication.php:231

**Comment by jlevers** [comment]
Could you both try running `composer update` and see if that fixes it?

**Comment by jordan26** [comment]
I had to install aws-sdk-php via composer too.

https://github.com/aws/aws-sdk-php
`composer require aws/aws-sdk-php`

**Comment by jlevers** [comment]
Sorry, this was a regression in the last release -- it should be fixed in `v3.0.6`, so just run `composer update` and you'll be good to go.

**Comment by RonJeremyR6** [comment]
It is working now, thank you for the quick change.
