### ISSUE TITLE
Get lowest offer listing excluding me

### ISSUE THREAD

**Issue by baltechies** [jlevers/selling-partner-api#591]
In Amazon MWS we had a request param to exclude me as request parameters when calling Get Lowest Offer Listing For SKU.
But I did not find this option in new API Request.

Is this option available? If yes, where I can find it? 
If not then what is alternative?

I am using getListingOffersBatch request (SellingPartnerApi\Model\ProductPricingV0\GetListingOffersBatchRequest).

**Comment by jlevers** [comment]
I don't know of any parameter that filters your own offers out of the response, but you can tell which offers in the results are yours with the `myOffer` attribute: https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v0-reference#offerdetail

**Comment by baltechies** [comment]
hmmm. previously there was an option in MWS API to filter lowest price excluding requester. I think now we need to filter offers other than myOffers from offers array.
