### ISSUE TITLE
getOrders 400 Invalid Input Could not match input argument

### ISSUE THREAD

**Issue by srees4** [jlevers/selling-partner-api#592]
## Problem description:

Similar to this ticket: https://github.com/jlevers/selling-partner-api/issues/551

We are coding an app for a customer. Customer is waiting for Amazon to activate/approve the production credentials but he was able to get sandbox credentials.

I followed the instruction from "Getting Started" section and I tested $apiInstance->getMarketplaceParticipations() using "endpoint" => Endpoint::NA_SANDBOX, I do get the marketplace participation, it worked, no issues at all... but when try using other methods, like CatalogItemsV0Api->listCatalogItems or OrdersV0Api->getOrders if get the "Could not match input arguments" error.

Exception when calling CatalogItemsV0Api->listCatalogItems: [400] { "errors": [ { "code": "InvalidInput", "message": "Could not match input arguments", "details": "" } ] }

Exception when calling OrdersV0Api->getOrders: [400] { "errors": [ { "code": "InvalidInput", "message": "Could not match input arguments", "details": "" } ] }

I found this ticket with similar issue [#551](https://github.com/jlevers/selling-partner-api/issues/551) and wonder if anyone knows how to get the library working with the sandbox.

## Error:
```
{ "errors": [ { "code": "InvalidInput", "message": "Could not match input arguments", "details": "" } ] }
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
You have to read through the OpenAPI models for each endpoint to figure out what the accepted sandbox parameters are...for nearly all endpoints, the sandbox requires a static set of parameters and returns a static response. You can find the OpenAPI models in the https://github.com/amzn/selling-partner-api-models repository. For example, the beginning of the spec for the `getOrders` sandbox call starts here:

https://github.com/amzn/selling-partner-api-models/blob/f3b0bc6c3949f791589b079e78b341f13f954b41/models/orders-api-model/ordersV0.json#L252

**Comment by srees4** [comment]
Thank you so much @jlevers!!!!

I was using a "valid" date instead of "TEST_CASE_200" for CreatedAfter.

I read the documentation carefully but never saw this, you saved me.

**Comment by blairk100** [comment]
"CreatedAfter": "TEST_CASE_200" worked for me. Thank you!
