### ISSUE TITLE
Sudden "InvalidInput" Error on ListFinancialEvents

### ISSUE THREAD

**Issue by titansoftime** [jlevers/selling-partner-api#594]
Everything was running great for a couple weeks since I got this up and running, however a couple days ago without any changes to code, I am getting this response on ListFinancialEvents call. It never happens on the first call and it happens seemingly at random on subsequent calls with NextToken.

It is odd though, my max_results_per_page set to 100, but each response now contains 33 records (pretty sure it previously had up to 100 records per call) until it errors with the following:

[400] { "errors": [ { "code": "InvalidInput", "message": "$errorResponse.Message", "details": "" } ] }

This was running just fine, and I have not changed anything. Any ideas? Is there anything that I could add that would be helpful?

Edit* Just wanted to add that I was on 5.8.4 version. I updated to 5.10.1 and am still getting same error.

**Comment by titansoftime** [comment]
I tried the finance pull not using this library and still oddly only get 33 records per call (even though default is 100), getting the exact same error.

![image](https://github.com/jlevers/selling-partner-api/assets/6549763/d6d15efc-1658-495e-aae9-7572387e8a70)


I wonder if there is an issue on Amazons end? Anyone else having any issues?

**Comment by ming0607** [comment]
I'm having the same problem and haven't found a solution yet, does anyone know why?

**Comment by ming0607** [comment]
Hey mate, I found this in the SP-API GitHub

https://github.com/amzn/selling-partner-api-docs/issues/550

But there doesn't seem to be a working solution at the moment

**Comment by tomfz** [comment]
don't use next token.

```php
        $i = 0;
        try {
            do {
                $i++;
                $result = $apiInstance->listFinancialEvents($max_results_per_page, $posted_after, $posted_before, $next_token);
                $ResshipmentEventLists = $result->getPayload()->getFinancialEvents()->getShipmentEventList();
                // get last record time
                foreach ($ResshipmentEventLists as $itm) {
                    $order_posted_after = $itm['posted_date'];
                }
                //add 1 second for next request
                $status = 1;
                $lastTime = strtotime($order_posted_after) + 1;
                $posted_after = date('Y-m-d\TH:i:s', $lastTime);
                if (count($ResshipmentEventLists) == 0) {
                    $status = 0;
                }
                if ($i == 30) {
                    $status = 0;
                }
            } while ($status);
        } catch (Exception $e) {
            echo 'Exception when calling FbaInventoryV1Api->getInventorySummaries: ', $e->getMessage(), PHP_EOL;
        }

**Comment by titansoftime** [comment]
> Hey mate, I found this in the SP-API GitHub
> 
> [amzn/selling-partner-api-docs#550](https://github.com/amzn/selling-partner-api-docs/issues/550)
> 
> But there doesn't seem to be a working solution at the moment

Ah, thank you. Yea seems to be on Amazon end. Closing.

![image](https://github.com/jlevers/selling-partner-api/assets/6549763/34c48def-02f4-4efa-b0a7-0066f34aa6e9)
