### ISSUE TITLE
Allowed memory size of 3145728000 bytes exhausted (tried to allocate 4096 bytes)

### ISSUE THREAD

**Issue by discover59** [jlevers/selling-partner-api#598]
I use ReportsV20210630Api for GET_MERCHANT_LISTINGS_ALL_DATA report and it gets failed with below error.

`Allowed memory size of 3145728000 bytes exhausted (tried to allocate 4096 bytes)`

```
$amz = new ReportsV20210630Api($this->config);
$docToDownload = new Document($reportDocumentInfo, $reportType);
$docToDownload->download();
```

This code works for small inventories.
Recently I got new seller market with huge inventory and above code crashes with the memory error.
The report size is about 15MB in gz and raw file is about 130MB.

Please let me know how I can avoid this error.

**Comment by discover59** [comment]
I think it happens on the line 176 of `lib\Documents.php`.

`$spreadsheet = $reader->load($this->tmpFilename);`

**Comment by jlevers** [comment]
This is the purpose of the `Document::downloadStream()` method (documented in the README, [here](https://github.com/jlevers/selling-partner-api#downloading-a-report-document)).

**Comment by discover59** [comment]
Thanks, @jlevers.
It works.
