### ISSUE TITLE
Client error: `POST https://api.amazon.com/auth/o2/token` resulted in a `401 Unauthorized` response

### ISSUE THREAD

**Issue by YunigeCDilip** [jlevers/selling-partner-api#602]
## Problem description:
As you have included `refresh_token` instead of `access_token` in whole API documentation, what if refresh_token is expired?
I followed the documentation present here. And used `refresh_token` in each API. And i 've been in rest for days, now i got this error.
How to renew my refresh token ? as `refresh_token` is used before now it is expired.
## Error:
Client error: `POST https://api.amazon.com/auth/o2/token` resulted in a `401 Unauthorized` response:\n{\"error_description\":\"Client authentication failed\",\"error\":\"invalid_client\"}\n
```
## Code
        $response = Http::post('https://api.amazon.com/auth/o2/token', [
            'grant_type' => 'refresh_token',
            'refresh_token' => '"Atzr|IwEBI******************",
            'client_id' => config('services.amazon.lwa_app_key'),
            'client_secret' => config('services.amazon.lwa_app_secret'),
        ]);
```

**Comment by jlevers** [comment]
Was this code working initially? The refresh token never expires, so that shouldn't be the issue.

**Comment by Vickyvignesh-01** [comment]
> Was this code working initially? The refresh token never expires, so that shouldn't be the issue.

Hi @jlevers i have the same problem as well, the below code was working fine previously but after 7th of november 2024 this getting a error of Client error: `POST https://api.amazon.com/auth/o2/token` resulted in a `400 Bad Request` response: {"error_index":"FapbAu_E1namJYUQ (truncated...)

            $response = $this->client->post('https://api.amazon.com/auth/o2/token', [
                'form_params' => [
                    'grant_type' => 'refresh_token',
                    'refresh_token' => $this->refreshToken,
                    'client_id' => $this->clientId,
                    'client_secret' => $this->clientSecret,
                ],
            ]);

**Comment by jlevers** [comment]
Which API endpoint are you using? I have a client who just started running into this issue with the Catalog Items API, but they're not having issues with calls to any other set of endpoints. I thought it was a fluke, but since you' re experiencing the exact same error starting on the same date, I wonder if it's an Amazon problem.

**Comment by Vickyvignesh-01** [comment]
Thanks for the response @jlevers ,  I have sorted out my problem its because of my cache, Now its works fine.

**Comment by JoeyGosson** [comment]
> 感谢您的回复[@jlevers](https://github.com/jlevers)，我已经解决了我的问题，这是因为我的缓存，现在它运行良好。

Hello! Is there any change at present? My attempt to run the code on your side is wrong.
