### ISSUE TITLE
I got an "Invalid request body" error when creating the report.

### ISSUE THREAD

**Issue by Abbotton** [jlevers/selling-partner-api#62]
When I create report, I got error:

```txt
[400] {
  "errors": [
    {
     "message": "Invalid request body: [instance type (boolean) does not match any allowed primitive type (allowed: [\"string\"])]",
     "code": "InvalidInput"
    }
  ]
}
```

Here is my code:
```php
$apiInstance = new ReportsApi($config);
$body = (new \SellingPartnerApi\Model\Reports\CreateReportSpecification())
    ->setReportType(ReportType::GET_XML_BROWSE_TREE_DATA['name'])
    ->setReportOptions(['RootNodesOnly' => true])
    ->setMarketplaceIds($shop->marketplace_id_list);
try {
    $result = $apiInstance->createReport($body);
    dd($result);
} catch (\Exception $e) {
   dd($e->getMessage());
}
```

And here is request body(JSON format):
```json
{"reportOptions":{"reportOptions":{"RootNodesOnly":true}},"reportType":"GET_XML_BROWSE_TREE_DATA","marketplaceIds":["A2EUQ1WTGCTBG2","A1AM78C64UM0Y8","A2Q3Y263D00KWC"]}
```

First, my seller account level is not Professional Selling Plan.
Second, I am sure that my configuration is correct, and the evidence is that the first example in Readme.md in this repo can be executed correctly and return the result.

Now I want ask:

1) Do I have to upgrade to the professional selling plan for testing in a sandbox environment?
2) Is my code above correct?

Please help , thank you very much.

**Comment by jlevers** [comment]
1. Yes, you do need a professional selling plan to access the SP API in any way.
2. I didn't run your code myself, but it looks correct to me. You can also set the properties of `CreateReportSpecification` this way:
```php
$body = new \SellingPartnerApi\Model\Reports\CreateReportSpecification([
    'reportType' => ReportType::GET_XML_BROWSE_TREE_DATA['name'],
    'reportOptions' => ['RootNodesOnly' => true],
    'marketplaceIds' => $shop->marketplace_id_list,
]);
```

**Comment by Abbotton** [comment]
thank you, jlevers.
