### ISSUE TITLE
[Order API] Invalid value 'KZ_VOEC' for 'deemed_reseller_category'

### ISSUE THREAD

**Issue by quazardous** [jlevers/selling-partner-api#620]
Hi,

new value `KZ_VOEC` for `deemed_reseller_category`

```php
SellingPartnerApi\Model\OrdersV0\OrderItem->setDeemedResellerCategory('KZ_VOEC')
```

**Comment by quazardous** [comment]
https://github.com/quazardous/selling-partner-api/tree/fix-620

**Comment by quazardous** [comment]
see #621

**Comment by jlevers** [comment]
This should be fixed in `v6`, since that value is no longer an enum (just a regular string).
