### ISSUE TITLE
Not Able to create the Feed but its giving invalid inputs 

### ISSUE THREAD

**Issue by MuhammadDanyal** [jlevers/selling-partner-api#624]
## Problem description:

I am trying to create the Feed but its giving the invalid input error

## Error:

Exception when calling FeedsV20210630Api->createFeedDocument: [400] { "errors": [ { "code": "400", "message": "Invalid input", "details": "Invalid input" } ] }

## Code

$feedType = [
  'contentType' => 'POST_FBA_INBOUND_CARTON_CONTENTS',
];

$apiInstance = new SellingPartnerApi\Api\FeedsV20210630Api($config);
$body = new \SellingPartnerApi\Model\FeedsV20210630\CreateFeedDocumentSpecification([
  'content_type' => $feedType['contentType'],
]);

try {
  $result = $apiInstance->createFeedDocument($body);
  echo "<pre>";
  print_r($result);
} catch (Exception $e) {
  echo 'Exception when calling FeedsV20210630Api->createFeedDocument: ', $e->getMessage(), PHP_EOL;
}
exit();

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by elburro1887** [comment]
Are you setting the ` $createFeedSpec->setMarketplaceIds()` correctly? That was the issue I just had.
