### ISSUE TITLE
[OrdersAPI] Why does the method signature change? (getOrders)

### ISSUE THREAD

**Issue by gugglegum** [jlevers/selling-partner-api#625]
Hi! I've been using this library for a couple of years and have noticed a feature that is causing problems for me and some other users. The `getOrders()` method (in `OrdersV0Api`) has a fairly large number of arguments. But the worst thing is that their order also changes from version to version. So if you have a working code and added this package to the `composer.json` simply as
```
    "jlevers/selling-partner-api": "^5.0",
```
Then at one point, your previously working code may simply stop working or start working incorrectly after regular `composer update` command. In accordance with established practice, versions of a library should remain backward compatible with existing code that uses it, within the same major version of the library (the first number in the version before dot, that is, 1 in our case).

Let's say you had code that received orders and that worked fine with version 5.2.5. But when updating to 5.3.0, the code broke; more precisely, the script stopped receiving the next pages of the list of orders due to the fact that the `$next_token` argument moved from 13 to 14 position.

Here is a signature of `getOrders` method in 5.2.5:

```
public function getOrders($marketplace_ids, $created_after = null, $created_before = null, $last_updated_after = null, $last_updated_before = null, $order_statuses = null, $fulfillment_channels = null, $payment_methods = null, $buyer_email = null, $seller_order_id = null, $max_results_per_page = null, $easy_ship_shipment_statuses = null, $next_token = null, $amazon_order_ids = null, $actual_fulfillment_supply_source_id = null, $is_ispu = null, $store_chain_store_id = null, $data_elements = null)
```
and here is in 5.3.0:
```
public function getOrders($marketplace_ids, $created_after = null, $created_before = null, $last_updated_after = null, $last_updated_before = null, $order_statuses = null, $fulfillment_channels = null, $payment_methods = null, $buyer_email = null, $seller_order_id = null, $max_results_per_page = null, $easy_ship_shipment_statuses = null, $electronic_invoice_statuses = null, $next_token = null, $amazon_order_ids = null, $actual_fulfillment_supply_source_id = null, $is_ispu = null, $store_chain_store_id = null, $data_elements = null)
```
You can see that there was added `$electronic_invoice_statuses` argument right before `$next_token`. The old code now tries to pass nextToken to `$electronic_invoice_statuses` which leads to a strange error. Not only me faced this problem (#454).

Okay, we fixed our code. Then in the version 5.6.0 there were added 2 new arguments `$item_approval_types` and `$item_approval_status` before `$data_elements`. So if you use `$data_elements` - your code is broken.

```
public function getOrders($marketplace_ids, $created_after = null, $created_before = null, $last_updated_after = null, $last_updated_before = null, $order_statuses = null, $fulfillment_channels = null, $payment_methods = null, $buyer_email = null, $seller_order_id = null, $max_results_per_page = null, $easy_ship_shipment_statuses = null, $electronic_invoice_statuses = null, $next_token = null, $amazon_order_ids = null, $actual_fulfillment_supply_source_id = null, $is_ispu = null, $store_chain_store_id = null, $item_approval_types = null, $item_approval_status = null, $data_elements = null)
```

Okay, you fixed your code again by adding 2 extra `null` arguments before `$data_elements`. Then in the version 5.10.0 these 2 arguments are removed. You code doesn't work again because you pass `null` in `$data_elements`.

```
public function getOrders($marketplace_ids, $created_after = null, $created_before = null, $last_updated_after = null, $last_updated_before = null, $order_statuses = null, $fulfillment_channels = null, $payment_methods = null, $buyer_email = null, $seller_order_id = null, $max_results_per_page = null, $easy_ship_shipment_statuses = null, $electronic_invoice_statuses = null, $next_token = null, $amazon_order_ids = null, $actual_fulfillment_supply_source_id = null, $is_ispu = null, $store_chain_store_id = null, $data_elements = null)
```

So my question is: why does the signature of this method change in a way that breaks backward compatibility?

Yes, named arguments introduced in PHP 8.0 can solve this problem. But what if developer did not use them or uses PHP 7.3 or 7.4 (according to a minimum supported version in `composer.json`)? Wouldn't it be better to use an associative array as the only argument to `getOrder()`? Again, for backward compatibility, inside `getOrder()` you can check whether the first argument is an associative array or ordered array with marketplace IDs. Or at least add new arguments to the end of the list so that the positions of the old arguments do not change.

**Comment by jlevers** [comment]
Hi @gugglegum,

That happened because I messed it up by accident multiple times, and by the time I noticed with each version I decided it was going to cause more harm than good to reverse the change. Sorry about the confusion.
