### ISSUE TITLE
SP-API no longer requires AWS IAM or AWS Signature Version 4

### ISSUE THREAD

**Issue by WebVooruit** [jlevers/selling-partner-api#627]
Message I received on 3rd of October. 

Starting October 2, 2023, SP-API no longer requires the use of AWS Identity and Access Management (IAM) or AWS Signature Version 4, which means developers will not need to register for IAM resources or sign SP-API requests with AWS Signature Version 4.

SP-API will continue to use Login with Amazon (LWA) access tokens for each SP-API request. LWA is based on OAuth 2.0, which has been broadly adopted for user-authorized exchanges across sites.

**Which marketplaces are affected?**
This change applies to all regions.

**Who is affected?**
All developers who registered with SP-API before October 2, 2023.

I am trying to get this working, in this lib - but seems it is not yet ready for this update. What are the plans to accomplish this update?

**Comment by jlevers** [comment]
Hi @WebVooruit, thanks for the report.

My understanding is that it will continue to be possible to make requests using AWS Signature V4, even if it's no longer required. That seems to be supported by the fact that this library is still working despite the October 2nd switchover already having passed. I plan to spend a significant chunk of time in November developing a v6 for this library which is long overdue, at which point I'll remove the Signature V4 code.
