### ISSUE TITLE
SP-API no longer requires AWS IAM or AWS Signature Version 4

### ISSUE THREAD

**Issue by ummira** [jlevers/selling-partner-api#631]
based on the update of October 2, aws signature in no longer needed.
So, how this update reflects in constructor configuration? Can olny pass lwaClientId, lwaClientSecret and lwaRefreshToken?

**Comment by jlevers** [comment]
I'm working on a v6 for the library that will include a lot of updates, including the removal of the LWA credentials. I'm going to pin this issue so that newcomers see it – I'll update here when v6 is ready to go.

**Comment by ummira** [comment]
hi, any news?

**Comment by haoxi911** [comment]
Thank you for working on this library! It is surely the best SP-API library for PHP.

**Comment by sherif807** [comment]
Hi thank you for your effort, so I just read your blog and registered my application with the seller account, But for me to start using it, do I need to register with AWS or can I just put null?

or continue to follow the blog anyway to retrieve AWS Credentials?

**Comment by fc-mbouzidi** [comment]
Hi,
Thank you for your update ! 
Can't wait the v6 to start my new developments :)

**Comment by tmsperera** [comment]
@jlevers any idea when v6 will released?

**Comment by jlevers** [comment]
This issue is addressed in the newly released `v6` :)
