### ISSUE TITLE
Error when calling confirmShipment with already confirmed order

### ISSUE THREAD

**Issue by Buyur** [jlevers/selling-partner-api#633]
when calling confirmShipment for an order where its already been confirmed it fails to return the error but generates an error in the OrdersV0Api when calling SellingPartnerApi\ObjectSerializer::deserialize

Fatal error: Uncaught Error: Class 'null' not found in /batch/includes/vendor/jlevers/selling-partner-api/lib/ObjectSerializer.php:366
Stack trace:
#0 /batch/includes/vendor/jlevers/selling-partner-api/lib/Api/OrdersV0Api.php(92): SellingPartnerApi\ObjectSerializer::deserialize(Object(stdClass), 'null', Array)
#1 /batch/includes/vendor/jlevers/selling-partner-api/lib/Api/OrdersV0Api.php(55): SellingPartnerApi\Api\OrdersV0Api->confirmShipmentWithHttpInfo('205-3390215-362...', Object(SellingPartnerApi\Model\OrdersV0\ConfirmShipmentRequest))
#2 /batch/orders/amazon_orders.php(1535): SellingPartnerApi\Api\OrdersV0Api->confirmShipment('205-3390215-362...', Object(SellingPartnerApi\Model\OrdersV0\ConfirmShipmentRequest))
#3 //batch/orders/amazon_orders.php(89): shipOrders()
#4 {main}
  thrown in /batch/includes/vendor/jlevers/selling-partner-api/lib/ObjectSerializer.php on line 366

             $apiInstance = new SellingPartnerApi\Api\OrdersV0Api($objSPAPI->config);
            try {
                $apiInstance->confirmShipment($order_id, $payload);
            } catch (Exception $e) {
                wl('Exception when calling OrdersV0Api->confirmShipment: ' . $e->getMessage());
            }

Debug showed this error which is what I would like to be able to handle:

  "errors": [
    {
      "code": "InvalidInput",
      "message": "Failed to create package due to not finding a matching package or order already fulfilled. ErrorMessage(errorCode\u003dGeneralError, errorDescription\u003dUnable to find package to update for order (205-33xxx15-xxxxxxx), errorMetric\u003dPackageToUpdateNotFound, packageIndex\u003dnull)",
      "details": ""
    }
  ]

**Comment by PRodO5lNk5** [comment]
Also having the exact same issue. 

A **"null"** string is passed to `deserialize` method in `lib/Api/OrdersV0Api.php:91` and I don't see any parsing within for that value.

**Comment by PRodO5lNk5** [comment]
I now see I've missed an update, this is fixed in latest version (`5.10.2`). @Buyur

**Comment by Buyur** [comment]
Seems to be a conflict with phpoffice....  not sure why 5.10.2 requires a specific version?  Anyone any solutions please?

  Problem 1
    - Root composer.json requires jlevers/selling-partner-api 5.10.2 -> satisfiable by jlevers/selling-partner-api[5.10.2].
    - jlevers/selling-partner-api 5.10.2 requires phpoffice/phpspreadsheet 1.25.2 -> found phpoffice/phpspreadsheet[1.25.2] but it conflicts with your root composer.json require (^1.29).
