### ISSUE TITLE
 Amazon is launching a new marketplace : South Africa

### ISSUE THREAD

**Issue by nhupham-commonservices** [jlevers/selling-partner-api#639]
Hi everyone

Amazon announces the launch of Amazon.co.za in South Africa in 2024
https://www.aboutamazon.com/news/retail/amazon-south-africa-store-launch
Can package be used in the South African market?

Thanks in advance.

**Comment by jlevers** [comment]
Hi @nhupham-commonservices – the SP API [supports South Africa](https://developer-docs.amazon.com/sp-api/changelog/november-2023-sp-api-release-announcement#seller-central-is-now-available-in-the-south-africa-marketplace-za), so this library does too :)
