### ISSUE TITLE
Important question for me: How much does it cost to use Amazon SP?

### ISSUE THREAD

**Issue by Lollichkeit** [jlevers/selling-partner-api#641]
AWS shows me costs and I wonder if Amazon-SP-API could be to blame.
Which services does SP-API use?

**Comment by da-mask** [comment]
I'm not sure what you are asking here, SP-API is used to manage product listings on amazon marketplaces. AWS is related to Amazon's cloud computing and related services.  You will usually only need to set up an AWS IAM to identify yourself, which you don't need to pay for.

**Comment by Lollichkeit** [comment]
Thank you very much for your reply.
