### ISSUE TITLE
Getting frequent cURL 35 & cURL 52

### ISSUE THREAD

**Issue by pawan1793** [jlevers/selling-partner-api#645]
We have app which helps to connect multiple merchants with spapi using jlevers libarary but recently we are facing multiple issue of cURL, 
sometimes api works sometimes it not 

Following error for reference 
cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to [sellingpartnerapi-na.amazon.com:443](http://sellingpartnerapi-na.amazon.com:443/)

cURL error 35: error:0A000126:SSL routines::unexpected eof while reading

cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.amazon.com/auth/o2/token

Need Help ! TIA

**Comment by lidawen1215** [comment]
Hello, I have also encountered this problem. May I ask if I have found a solution? Looking forward to your reply. Thank you

**Comment by jlevers** [comment]
This is either an issue with your connection or with Amazon's servers, but is unrelated to this library. Feel free to continue to troubleshoot here, but I'm going to close the issue.
