### ISSUE TITLE
Using targetApplication for RDT Token Calls? 

### ISSUE THREAD

**Issue by ShaneOH** [jlevers/selling-partner-api#647]
Hey @jlevers , 

We have a scenario in which our application is making some calls on behalf of a delagatee application. In this workflow ([which is outlined in an Amazon SP-API tutorial](https://developer-docs.amazon.com/sp-api/docs/tokens-api-use-case-guide#tutorial-delegate-authorization-to-access-pii)) we want to make some calls to `getOrders` etc. using their application ID/creds but we need the RDT token specifically to be generated with our own application ID. This can be passed into the `createRestrictedDataToken` call directly via the `targetApplication` optional parameter. 

Does the SDK support this? Right now all our calls to `getOrders` etc. have the RDT being generated automatically as you describe in your docs, because we pass in `$data_elements`. That works great for us, and we'd prefer to keep it that way, but we need a way to pass in a `targetApplication` param to the RDT token. Maybe that should be added as a parameter to the `getOrders` calls so that it can be filtered through to the underlying RDT call? 

What's the solution here to be able to work the the `targetApplication` parameter?

**Comment by jlevers** [comment]
This is now possible in `v6` by passing the delegatee application ID in the `delegatee` parameter of `SellingPartnerApi::make()`.
