### ISSUE TITLE
Can't get order address info in sandbox env.

### ISSUE THREAD

**Issue by Abbotton** [jlevers/selling-partner-api#65]
Hi, jlevers. Sorry, my English is very bad.

In the SP-API sandbox environment, I can get the order list and order details, but I cannot get the buyer information and delivery address information. Below I list some relevant information, please help me. Thank you.

These are the permissions of my app:
![微信截图_20210727230847](https://user-images.githubusercontent.com/16308633/127181494-eb734ddf-4322-4395-91ff-a2c0437a2187.png)

This is the code that I ran while testing (using the parameters provided by the [official documentation](https://github.com/amzn/selling-partner-api-models/blob/e3955b7f024b3703647288d8199ecacc0d4146e5/models/orders-api-model/ordersV0.json#L882-L899)):
```php
$config = [];
$app = new OrdersApi($config);
$result = $app->getOrderAddress('TEST_CASE_200');
dd($result);
```
This is the information returned by SP-API:
```html
"""
[403] {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": "The access token you provided is revoked, malformed or invalid."
    }
  ]
}
"""
```

At the same time, I checked [this issue](https://github.com/amzn/selling-partner-api-docs/issues/879), but the amazon support team hasn't responded yet.

In addition, my seller account did not get access to PII when applying for MWS.

Now I want to ask three questions:
1, Is this situation related to my account not having access to PII?
2, Is the code running during my test correct?
3. Can you share the code you used when accessing buyer information in the sandbox environment?

Thank you very much.

**Comment by jlevers** [comment]
1. Yes, you need access to PII in order to get order addresses.
2. The `$config` parameter to `OrdersApi` needs to be a `Configuration` object, [per the documentation](https://github.com/jlevers/selling-partner-api/blob/main/README.md#setup).
3. I get the same response as you when I try to call `getOrderAddress` via the sandbox. I think this may be an error on Amazon's end? Here's the code I'm using:
```php
use SellingPartnerApi\Api\OrdersApi;
use SellingPartnerApi\Configuration;
use SellingPartnerApi\Endpoint;

$config = new Configuration([
        'lwaClientId' => 'amzn1.application-oa2-client....',
        'lwaClientSecret' => 'df4e....',
        'lwaRefreshToken' => 'Atzr|IwEB....',
        'awsAccessKeyId' => 'AKIA....',
        'awsSecretAccessKey' => '4oi1q....',
        'endpoint' => Endpoint::NA_SANDBOX,
]);
$ordersApi = new OrdersApi($config);
$response = $ordersApi->getOrderAddress('TEST_CASE_200');
var_dump($response);
```

**Comment by Abbotton** [comment]
OK, thanks jlevers.
