### ISSUE TITLE
SellingPartnerApi\Model\OrdersV0\OrderItem missing DEEMED_RESELLER_CATEGORY_NG_VOEC ("NG_VOEC")

### ISSUE THREAD

**Issue by kpconnell** [jlevers/selling-partner-api#650]
I see a prior issue of the thread.  

Honestly I think this needs to be re-worked... just make it a string...

**Comment by kpconnell** [comment]
And yes I know this is openapi generated and I'd still make the argument inappropriate in the real world to need these to be up to date, this literally prevents us from retrieving a subset of orders which is mission critical.

**Comment by jlevers** [comment]
This is fixed in `v6` (I've gotten rid of automatic enums entirely).

**Comment by kpconnell** [comment]
Nice ty
