### ISSUE TITLE
Add MXN to CurrencyCode

### ISSUE THREAD

**Issue by pmccomb** [jlevers/selling-partner-api#651]
https://github.com/jlevers/selling-partner-api/blob/main/lib/Model/FbaInboundV0/CurrencyCode.php#L48-L53

It appears that MXN is a valid currency code. We had a customer with a MX shipment and when we called `getTransportContents`, it would log `Invalid value for enum '\SellingPartnerApi\Model\FbaInboundV0\CurrencyCode', must be one of: 'CAD', 'USD', 'GBP', 'EUR', 'PLN', 'USD', 'CAD', 'USD', 'GBP', 'EUR', 'PLN', 'USD'`. After adding MXN, it returned successfully

**Comment by jlevers** [comment]
This is fixed in `v6`, because that value is now a string instead of an enum.
