### ISSUE TITLE
Invalid value for enum '\SellingPartnerApi\Model\FbaOutboundV20200701\AdditionalLocationInfo' (GARAGE/OTHER DOOR/OTHER LOC)

### ISSUE THREAD

**Issue by lc-excell** [jlevers/selling-partner-api#652]
Response:
`currentStatus": "DELIVERED",     
"additionalLocationInfo": "GARAGE/OTHER DOOR/OTHER LOC`

`Invalid value for enum '\SellingPartnerApi\Model\FbaOutboundV20200701\AdditionalLocationInfo', must be one of: 'AS_INSTRUCTED', 'BACK_PORCH', 'CARPORT', 'CUSTOMER_PICKUP', 'DECK', 'DOOR_PERSON', 'FRONT_DESK', 'FRONT_DOOR', 'FRONT_DOOR/PORCH', 'GARAGE', 'GUARD', 'IN/AT_MAILBOX', 'MAIL_ROOM', 'MAIL_SLOT', 'MAILBOX', 'MC_BOY', 'MC_GIRL', 'MC_MAN', 'MC_WOMAN', 'NEIGHBOR', 'OFFICE', 'OUTBUILDING', 'PATIO', 'PORCH', 'REAR_DOOR', 'RECEPTIONIST', 'RECEIVER', 'SECURE_LOCATION', 'SIDE_DOOR', 'AS_INSTRUCTED', 'BACK_PORCH', 'CARPORT', 'CUSTOMER_PICKUP', 'DECK', 'DOOR_PERSON', 'FRONT_DESK', 'FRONT_DOOR', 'FRONT_DOOR/PORCH', 'GARAGE', 'GUARD', 'IN/AT_MAILBOX', 'MAIL_ROOM', 'MAIL_SLOT', 'MAILBOX', 'MC_BOY', 'MC_GIRL', 'MC_MAN', 'MC_WOMAN', 'NEIGHBOR', 'OFFICE', 'OUTBUILDING', 'PATIO', 'PORCH', 'REAR_DOOR', 'RECEPTIONIST', 'RECEIVER', 'SECURE_LOCATION', 'SIDE_DOOR'
`

**Comment by jlevers** [comment]
This should be fixed in `v6`, as enums have been removed entirely.
