### ISSUE TITLE
VendorShippingV1Api doesn't have endpoint '/vendor/shipping/v1/transportLabels'

### ISSUE THREAD

**Issue by underdpt** [jlevers/selling-partner-api#655]
Hello,

I've noticed that `VendorShippingV1Api` has methods like `getShipmentLabels` but those only get a 404 response, and there's no such endpoint on the API docs (https://developer-docs.amazon.com/sp-api/docs/vendor-shipments-api-v1-reference#operations).

Thanks for this tool!

**Comment by jlevers** [comment]
Interesting -- the Amazon OpenAPI model for `VendorShippingV1Api` includes those endpoints, but I see that they're not present in the documentation. Thanks for pointing this out.

**Comment by jlevers** [comment]
These now show up in the docs, so I'm guessing whatever was going on on Amazon's end is resolved. I'm gonna close this, but feel free to reopen.

**Comment by underdpt** [comment]
Hi, I've done a quick search and found nothing for `getShipmentLabels` , are you sure that's documented now? 

If so, a link would be very welcome :-)

**Comment by jlevers** [comment]
Ah, I realize I was looking at the Direct Fulfillment Shipping API. That said, I don't see the extra methods you're referring to in v6 – I think there must have been some generation bug in v5 that caused this to happen. Sorry for the confusion!
