### ISSUE TITLE
getOrders only processing the first marketplace_id when a list of marketplace ids is passed in the params

### ISSUE THREAD

**Issue by chartkandy** [jlevers/selling-partner-api#658]
## Problem description:

getOrders only processing the first marketplace_id when a list of marketplace ids is passed in the params. No error response but it ignore all but the first marketplace id passed. 

## Error:

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by jlevers** [comment]
Please share your code
