### ISSUE TITLE
License: BSD-3-Clause or GNU GENERAL PUBLIC LICENSE?

### ISSUE THREAD

**Issue by Helge-HBA** [jlevers/selling-partner-api#66]
Hi Jesse,

what is the license of this library? The license in composer.json is BSD-3-Clause but the provided license file is GPL. 
Thanks for clarification :-)

Cheers,
Helge

**Comment by jlevers** [comment]
Thanks for bringing this up! It's BSD-3-Clause, and I've updated `LICENSE.md` to reflect that.
