### ISSUE TITLE
Invalid value 'MY_VOEC' for 'deemed_reseller_category'

### ISSUE THREAD

**Issue by nhupham-commonservices** [jlevers/selling-partner-api#660]
I got an error while trying to get orders via API: 

`Fatal error: Uncaught InvalidArgumentException: Invalid value 'MY_VOEC' for 'deemed_reseller_category', must be one of 'IOSS', 'UOSS', 'SG_VOEC', 'GB_VOEC', 'NO_VOEC', 'CA_MPF', 'AU_VOEC', 'NZ_VOEC', 'JE_VOEC', 'CH_SUPPLIER_IMPORT' in /var/www/html/vendor/jlevers/selling-partner-api/lib/Model/OrdersV0/OrderItem.php:1138`

Can you please confirm that this is an error and that it needs to be fixed?
Thank you.

**Comment by jlevers** [comment]
This will be fixed by upgrading to `v6`.
