### ISSUE TITLE
 cURL error 35: OpenSSL SSL_connect

### ISSUE THREAD

**Issue by lidawen1215** [jlevers/selling-partner-api#661]
## Problem description:
The system will randomly display cURL error 35: OpenSSL SSL_connect, sometimes the interface can be called normally, and sometimes cURL error 35 error occurs when looping back
## Error:
![1709544913436](https://github.com/jlevers/selling-partner-api/assets/62378085/abe2da48-4ab0-4ada-8901-a742cc43a610)

**Comment by jlevers** [comment]
This is an Amazon server issue...closing since it's unrelated to this library.
