### ISSUE TITLE
Missing operation "getCompetitiveSummary" in ProductPricingV20220501Api

### ISSUE THREAD

**Issue by pierrefrugere-lulilo** [jlevers/selling-partner-api#664]
## Problem description:

Currently, in the _ProductPricingV20220501Api_, there seems to be a missing essential operation, namely "getCompetitiveSummary" in SPA API documentation ([link](https://developer-docs.amazon.com/sp-api/docs/product-pricing-api-v2022-05-01-reference#getcompetitivesummary)). This operation is crucial for obtaining a featured buying options for the ASIN and marketplaceId combination.

I haven't found any more information to suggest about this in issues or pull requests, are you planning to implement it or should I go through _getFeaturedOfferExpectedPriceBatch_ ?

In any case thank you for your wonderful work, best regards.

**Comment by jlevers** [comment]
Thanks for reporting – that method was added in v6.
