### ISSUE TITLE
Error using v6

### ISSUE THREAD

**Issue by bgarret** [jlevers/selling-partner-api#666]
## Problem description:

Every DTO seems to inherit `Crescat\SaloonSdkGenerator\BaseDto`, but it is not pulled when installing with `composer require jlevers/selling-partner-api`.

The dev dependencies mention  `"crescat-io/saloon-sdk-generator": "dev-master"`, but the BaseDto class is specific to your fork.

## Error:

```
Class "Crescat\SaloonSdkGenerator\BaseDto" not found
```

What can I do to resolve the problem?

**Comment by jlevers** [comment]
Sorry, I overlooked a `composer.json` change that I'd made locally but hadn't pushed. Give `v6.0.1` a try and let me know if that fixes the issue.

**Comment by bgarret** [comment]
Much better like this, thanks a lot for your work!

**Comment by Bouhnosaure** [comment]
Hi, 
I'll reopen this ticket as i encounter the same issue with all versions from 6.0.0 to 6.0.5 and also v6.x-dev
