### ISSUE TITLE
Moving to V6

### ISSUE THREAD

**Issue by nikgilbe** [jlevers/selling-partner-api#667]
## Problem description:
Hi. We have many scripts running with the pre V6 code. It looks like quite a significant change to move to V6. Is there an easy way to install V6 alongside the existing (via composer?) to start testing the new code ?

Thanks, Nik

**Comment by jlevers** [comment]
Hey Nik – I don't know a way to install two versions of the same library in parallel with Composer, although it may be possible. I'd recommend just creating a separate branch in your project, installing v6 there, and using that for testing. Please let me know if I can be of assistance with the upgrade – my email is [first name] [at] highsidelabs.co if you want it.

**Comment by nikgilbe** [comment]
Thanks Jesse - that makes sense.
