### ISSUE TITLE
Problems with download() method of Document class

### ISSUE THREAD

**Issue by jmichaelterenin** [jlevers/selling-partner-api#67]
Using v 3.0.7 (latest), I'm requesting a created GET_XML_BROWSE_TREE_DATA report, it gets created through:
\SellingPartnerApi\Api\ReportsApi->createReport(...)
the report document id is retrieved through
\SellingPartnerApi\Api\ReportsApi->getReport($report_id),
\SellingPartnerApi\Api\ReportsApi->getReportDocument(...) to get the document url, 
and the raw contents is retrieved in Document->download(), but when it's run through:
$maybeZippedContents = openssl_decrypt($rawContents, static::ENCRYPTION_SCHEME, $this->key, OPENSSL_RAW_DATA, $this->iv);
it returns multiple blanks, but no XML.

Is this what you are getting? Pretty sure I'm following standard protocol. 
NOTE: This is for GET_XML_BROWSE_TREE_DATA report type, it is working for GET_MERCHANT_LISTINGS_ALL_DATA.
I haven't tested any of the other report types.

**Comment by Abbotton** [comment]
I don’t think you need to decrypt it manually. After you call the `cest()` method, you can refer to the following code to handle your business.

Simple code:
```php
use SellingPartnerApi\Document;
use SellingPartnerApi\Model\Reports\ReportDocument;
use SellingPartnerApi\ReportType;
// ......
$documentResponse = $apiInstance->getReportDocument(
    $reportInstance->getReportDocumentId(), 
    ReportType::GET_XML_BROWSE_TREE_DATA['name']
);

$reportDocumentBody = (new ReportDocument())
    ->setReportDocumentId($documentResponse->getPayload()->getReportDocumentId())
    ->setCompressionAlgorithm($documentResponse->getPayload()->getCompressionAlgorithm())
    ->setEncryptionDetails($documentResponse->getPayload()->getEncryptionDetails())
    ->setUrl($documentResponse->getPayload()->getUrl());

$document = new Document($reportDocumentBody, ReportType::GET_XML_BROWSE_TREE_DATA);

// not automatically parse XML.
$document->download(false);
$xml = $document->getData();
```
