### ISSUE TITLE
sdk version

### ISSUE THREAD

**Issue by mavirehman** [jlevers/selling-partner-api#672]
I built my application using SDK version 5.0. Now, as I work on another API, I find myself needing to refer back to the documentation for an older version, SDK 5.0, can you please give me the  access to the documentation for the older version. am not able to get the documentation even I swtich to branch 5.0.

**Comment by jlevers** [comment]
You can browse the code of the last tagged `v5` release here: https://github.com/jlevers/selling-partner-api/tree/v5.10.2
