### ISSUE TITLE
Using my own Guzzle Client in V6

### ISSUE THREAD

**Issue by stevenbrookes** [jlevers/selling-partner-api#674]
In V5 I was able to use my own Guzzle Client to make the calls to the API.  This client has a bunch of middleware to do things like add logging, tracing, retry etc behaviour to the client.  I'm not seeing how to do this with V6.  I can pass in a client for the OAuth client.  If I could do the same with the API client then I'd be able to migrate easily enough I think.

Any thoughts on the best approach?

**Comment by jlevers** [comment]
Hey @stevenbrookes – one of my intentions in rewriting the library using [Saloon](https://docs.saloon.dev/) was to make it easier for people to override the default functionality of many parts of the library.

In the case of custom Guzzle middleware, the easiest option is probably to extend the `SellerConnector` class, and then add the middleware that the library is using as described here: https://docs.saloon.dev/digging-deeper/middleware#adding-guzzle-middleware

**Comment by stevenbrookes** [comment]
Ah OK I didn't spot that in the Saloon docs.  Looks like it'll work.  Thanks again

**Comment by michabbb** [comment]
@stevenbrookes in case you created a retry middleware, would be nice if you could share some code snippets here 😏 🙏

**Comment by stevenbrookes** [comment]
@michabbb I'm afraid I decide to not use the V6 library eventually.  I didn't find that Saloon fitted well into our overall infrastructure stack, so I've stuck to using a fork of V5 for the moment.

**Comment by michabbb** [comment]
in case this example is not wrong, it might help others trying to implement a retry (with v7):

```php
private function getAmazonConnector(): SellerConnector
{
    $config = $this->getConfig();

    return new class(
        $config['lwaClientId'],
        $config['lwaClientSecret'],
        $config['lwaRefreshToken'],
        $config['endpoint']
    ) extends SellerConnector {
        protected int  $tries                 = 3;
        protected int  $retryInterval         = 1000;
        protected bool $useExponentialBackoff = true;

        public function handleRetry(FatalRequestException|RequestException $exception, Request $request): bool
        {
            $status = $exception instanceof RequestException
                ? $exception->getResponse()?->status()
                : null;

            if ($status === 401) {
                new amazonTokenCache()->clear();
                return true;
            }

            if ($status === 429) {
                return true;
            }

            return false;
        }

        public function hasRequestFailed(Response $response): bool
        {
            return in_array($response->status(), [401, 429], true);
        }
    };
}
```
