### ISSUE TITLE
Unable to use multiple clients in a single application

### ISSUE THREAD

**Issue by spire-mike** [jlevers/selling-partner-api#678]
Hi @jlevers - in my application I am trying to use two instances of the `ProductPricingV0` api. One for the `na` region and one for the `eu` region.

```
$naInstance = SellingPartnerApi::make(...$app['config']['amazon-sp-api.na'])
                ->seller()
                ->productPricingV0();

$euInstance = SellingPartnerApi::make(...$app['config']['amazon-sp-api.eu'])
                ->seller()
                ->productPricingV0();
```

However, I am finding that there is some sort of configuration conflict going on that causes errors. For example, if I first make a call using the `naInstance`, it works fine and returns data:
```
$naInstance->getPricing('ATVPDKIKX0DER', 'Sku', [], ['MY-US-SKU']);
```
Next, if I make a call using the `euInstance`, it returns a 403 error that I am unauthorized.
```
$euInstance->getPricing('A1F83G8C2ARO7P', 'Sku', [], ['MY-UK-SKU']);
```

Now, if I restart the application, and make the same exact calls, but in reverse order, the `euInstance` call succeeds and returns data, but the `naInstance` call returns a 403 not authorized error. So I believe the code must be caching credentials or something like that even when a new instance is created. Is this intentional?

**Comment by jlevers** [comment]
Hey – sorry about this. There was a caching issue that I fixed in `v6.0.4`. Are you on an earlier version than that?

**Comment by spire-mike** [comment]
Ah interesting. Unfortunately I am still using `6.0.1` due to the issue we were discussing [here](https://github.com/jlevers/selling-partner-api/pull/659#issuecomment-2040502084).

**Comment by spire-mike** [comment]
Was it [this commit](https://github.com/jlevers/selling-partner-api/commit/70bb7703a4bb5570a65e6e6b85b0b86b1d46da37) that fixed it? Maybe I can just incorporate that commit myself in a fork for now.

**Comment by jlevers** [comment]
Ah, ok. Yep, it's that commit!
