### ISSUE TITLE
Incorrect php version requirements

### ISSUE THREAD

**Issue by Redominus** [jlevers/selling-partner-api#681]
Hi,
php version requirement from composer.json is too low for project's code. `const` in `traits` are not supported until `php 8.2`
https://github.com/jlevers/selling-partner-api/blob/804166c90434f3c3567bf180168acdbcc9992412/src/Traits/DownloadsDocument.php#L22-L24

**Comment by jlevers** [comment]
This was fixed a while back, closing.
