### ISSUE TITLE
 Class "Crescat\SaloonSdkGenerator\BaseDto" not found

### ISSUE THREAD

**Issue by fanJM** [jlevers/selling-partner-api#684]
Class "Crescat\SaloonSdkGenerator\BaseDto" not found

  at vendor/jlevers/selling-partner-api/src/Seller/ReportsV20210630/Dto/CreateReportSpecification.php:7
      3▕ namespace SellingPartnerApi\Seller\ReportsV20210630\Dto;
      4▕ 
      5▕ use Crescat\SaloonSdkGenerator\BaseDto;
      6▕ 
  ➜   7▕ final class CreateReportSpecification extends BaseDto

**Comment by bgarret** [comment]
Hello,

You should try to upgrade to 6.0.4, I had the same problem using the 6.0 version.

**Comment by fanJM** [comment]
> Hello,
> 
> You should try to upgrade to 6.0.4, I had the same problem using the 6.0 version.

think you

**Comment by fanJM** [comment]
> 你好，
> 
> 您应该尝试升级到6.0.4，我使用6.0版本也遇到了同样的问题。

hello

I upgraded but it still doesn't work

**Comment by FloZiegler** [comment]
Hey,
did you found a solution?

**Comment by jlevers** [comment]
This was an issue with the first few versions of v6. `highsidelabs/saloon-sdk-generator` is where `Cescat\SaloonSdkGenerator\BaseDto` was coming from, but now `BaseDto` is integrated into this package itself, so this problem should be gone.
