### ISSUE TITLE
createFeedDocument Error 400 on Endpoint::NA_SANDBOX

### ISSUE THREAD

**Issue by jrozzi** [jlevers/selling-partner-api#686]
## Problem description:
Using the "Uploading a feed" example, I'm getting an error when calling $feedsApi->createFeedDocument($createFeedDoc);

The connector credentials are correct, as I'm able to make other calls like $sellersApi->getMarketplaceParticipations(). Is this a permission scope issue or am I overlooking something simple?

## Error:
400 Bad Request 

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```
PHP Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://sandbox.sellingpartnerapi-na.amazon.com/feeds/2021-06-30/documents` resulted in a `400 Bad Request` response:
{
  "errors": [
    {
      "code": "400",
      "message": "Invalid input",
      "details": "Invalid input"
    }
  ]
 (truncated...)
 in /path/to/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /path/to/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /path/to/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /path/to/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /path/to/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /path/to/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /path/to/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /path/to/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /path/to/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /path/to/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /path/to/vendor/guzzlehttp/guzzle/src/Client.php(124): GuzzleHttp\Promise\Promise->wait()
#10 /path/to/vendor/saloonphp/saloon/src/Http/Senders/GuzzleSender.php(101): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 /path/to/vendor/saloonphp/saloon/src/Traits/Connector/SendsRequests.php(72): Saloon\Http\Senders\GuzzleSender->send(Object(Saloon\Http\PendingRequest))
#12 /path/to/vendor/jlevers/selling-partner-api/src/Seller/FeedsV20210630/Api.php(78): Saloon\Http\Connector->send(Object(SellingPartnerApi\Seller\FeedsV20210630\Requests\CreateFeedDocument))
#13 /path/to/amazon.php(133): SellingPartnerApi\Seller\FeedsV20210630\Api->createFeedDocument(Object(SellingPartnerApi\Seller\FeedsV20210630\Dto\CreateFeedDocumentSpecification))

## Code

```php
$connector = SellingPartnerApi::make(...)->seller();
$feedsApi = $connector->feeds();
$feedType = 'POST_PRODUCT_DATA';
$contentType = CreateFeedDocumentResponse::getContentType($feedType);
$createFeedDoc = new CreateFeedDocumentSpecification($contentType);
$createDocumentResponse = $feedsApi->createFeedDocument($createFeedDoc);
```

**Comment by jrozzi** [comment]
This error only happens when using Endpoint::NA_SANDBOX. Using Endpoint::NA does not reproduce the error I mentioned above.

**Comment by jrozzi** [comment]
@jlevers Any idea why $feedsApi->createFeedDocument($createFeedDoc) throws an error 400 in Endpoint::NA_SANDBOX only?

**Comment by jlevers** [comment]
Could you give this a shot in `v6.0.5`? I think it's possible that the faulty RDT generation flow was causing the problem.

**Comment by jrozzi** [comment]
@jlevers Thanks for the response and this project. Unfortunately I'm getting the same error after updating to 6.0.5:

Here is the error output if it helps:

`PHP Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://sandbox.sellingpartnerapi-na.amazon.com/feeds/2021-06-30/documents` resulted in a `400 Bad Request` response:
{
  "errors": [
    {
      "code": "400",
      "message": "Invalid input",
      "details": "Invalid input"
    }
  ]
 (truncated...)
 in /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response), NULL, Array, NULL)
#1 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(158): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Promise\TaskQueue->run(true)
#5 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /path/to/redacted/public_html/redacted/module/base/vendor/guzzlehttp/guzzle/src/Client.php(124): GuzzleHttp\Promise\Promise->wait()
#10 /path/to/redacted/public_html/redacted/module/base/vendor/saloonphp/saloon/src/Http/Senders/GuzzleSender.php(101): GuzzleHttp\Client->send(Object(GuzzleHttp\Psr7\Request), Array)
#11 /path/to/redacted/public_html/redacted/module/base/vendor/saloonphp/saloon/src/Traits/Connector/SendsRequests.php(72): Saloon\Http\Senders\GuzzleSender->send(Object(Saloon\Http\PendingRequest))
#12 /path/to/redacted/public_html/redacted/module/base/vendor/jlevers/selling-partner-api/src/Seller/FeedsV20210630/Api.php(78): Saloon\Http\Connector->send(Object(SellingPartnerApi\Seller\FeedsV20210630\Requests\CreateFeedDocument))
#13 /path/to/redacted/public_html/redacted/module/base/amazon.php(133): SellingPartnerApi\Seller\FeedsV20210630\Api->createFeedDocument(Object(SellingPartnerApi\Seller\FeedsV20210630\Dto\CreateFeedDocumentSpecification))
...
#17 {main}

Next Saloon\Exceptions\Request\ClientException: Bad Request (400) Response: {
  "errors": [
    {
      "code": "400",
      "message": "Invalid input",
      "details": "Invalid input"
    }
  ]
} in /path/to/redacted/public_html/redacted/module/base/vendor/saloonphp/saloon/src/Helpers/RequestExceptionHelper.php on line 51
`

Now that I know what's going on, I can work around it by using production, though this may cause issues for other developers. Please let me know if you want me to test or try anything else. It's unfortunate that Amazon has left PHP developers in this position with their MWS API deprecation.

**Comment by jlevers** [comment]
Are you using the supported `text/tab-separated-values; charset=UTF-8` content type argument in the sandbox call? The SP API does not support dynamic sandbox arguments for most calls.

**Comment by jrozzi** [comment]
XML is being sent for all data feeds. I believe the issue was the SP API doesn't support dynamic arguments in sandbox for most calls, which made things a bit difficult to work with. It was easiest for us to test these calls in production instead.
