### ISSUE TITLE
How to Update the Version

### ISSUE THREAD

**Issue by KemnaMOL** [jlevers/selling-partner-api#687]
I see that I must update to V6 to use it with SP-API.
Does it realy only work with php 8,2?
And how can I update the project?
composer require jlevers/selling-partner-api only tell me that I have the old version.

**Comment by misterakko** [comment]
Google "composer" for the full explanation, but...

At a guess, your composer.json file says that you only want version 5. It that's it, change it to:
```
    "require": {
        "jlevers/selling-partner-api": "^6.0"
    }
```

**Comment by jlevers** [comment]
I'm closing this due to age. Let me know if you need more support here.
