### ISSUE TITLE
Unknown keys when deserializing into FulfillmentPreview: scheduledDeliveryinfo

### ISSUE THREAD

**Issue by lc-excell** [jlevers/selling-partner-api#689]
## Problem description:
The response from amazon was **scheduledDeliveryinfo**, the attributeType in deserialization is **scheduledDeliveryInfo**.

I think the response should be **scheduledDeliveryInfo** since it is the parameter name specified in amazon sp-api docs. Or just a typo error on their end, i dont know, hehe.
https://developer-docs.amazon.com/sp-api/docs/fulfillment-outbound-api-v2020-07-01-reference#fulfillmentorderitem
## Error:

```
Unknown keys when deserializing into SellingPartnerApi\Seller\FBAOutboundV20200701\Dto\FulfillmentPreview: scheduledDeliveryinfo
```

## Code
![image](https://github.com/jlevers/selling-partner-api/assets/158118232/ff052222-8abb-4289-a94b-e25646fa2c00)

**Comment by Inbasecom** [comment]
please remove echo from traits...!

**Comment by lc-excell** [comment]
Yeah, maybe I should fork and remove it myself.

**Comment by jlevers** [comment]
The `echo` is removed in `v7.0.0`.
