### ISSUE TITLE
amazon order fetch api issue

### ISSUE THREAD

**Issue by ahmadali419** [jlevers/selling-partner-api#693]
i am using this url for getting orders but having the empty orders response so what i do for this case how i can get data about orders please help me
https://sellingpartnerapi-eu.amazon.com/orders/v0/orders?CreatedAfter=2024-01-01&MarketplaceIds=ATVPDKIKX0DER

{
"payload": {
"Orders": [],
"CreatedBefore": "2024-04-23T05:54:50Z"
}
}

**Comment by jlevers** [comment]
You're using a US marketplace ID on the EU endpoint. If you're trying to fetch orders from an EU country or countries, you'll need to specify those countries' marketplace ids. All marketplace IDs are documented [here](https://developer-docs.amazon.com/sp-api/docs/marketplace-ids).
