### ISSUE TITLE
[Question] CatalogApi::getCatalogItem doesn't return variations details 

### ISSUE THREAD

**Issue by tawfekov** [jlevers/selling-partner-api#70]
Hello, 
I'm trying to get my items with its all variations details + prices `getCatalogItem` seems to be returning an empty `relationships` data : 
I'm running this snippet : 

```
 $catalogItem = $catalogApi->getCatalogItem(
            $marketplace_id,
            $asin
        )->getPayload()
```
here is an example of what I'm getting 

```
 ["relationships"]=>
    array(1) {
      [0]=>
      object(SellingPartnerApi\Model\Catalog\RelationshipType)#1084 (1) {
        ["container":protected]=>
        array(22) {
          ["color"]=>
          NULL
          ["edition"]=>
          NULL
          ["flavor"]=>
          NULL
          ["gem_type"]=>
          NULL
          ["golf_club_flex"]=>
          NULL
          ["hand_orientation"]=>
          NULL
          ["hardware_platform"]=>
          NULL
          ["material_type"]=>
          NULL
          ["metal_type"]=>
          NULL
          ["model"]=>
          NULL
          ["operating_system"]=>
          NULL
          ["product_type_subcategory"]=>
          NULL
          ["ring_size"]=>
          NULL
          ["shaft_material"]=>
          NULL
          ["scent"]=>
          NULL
          ["size"]=>
          NULL
          ["size_per_pearl"]=>
          NULL
          ["golf_club_loft"]=>
          NULL
          ["total_diamond_weight"]=>
          NULL
          ["total_gem_weight"]=>
          NULL
          ["package_quantity"]=>
          NULL
          ["item_dimensions"]=>
          NULL
        }
      }
    }
```

am I doing something wrong here ? or I should getting it from some another API ? 

thanks for your help

**Comment by tawfekov** [comment]
I'm testing this asin : `B08ZH7L7RQ` and the SP API response was displaying this relationships : 

```
  "Relationships": [
            {
                "Identifiers": {
                    "MarketplaceASIN": {
                        "MarketplaceId": "ATVPDKIKX0DER",
                        "ASIN": "B07S3VKFKN"
                    }
                },
                "Size": "4 oz - 50 Cups"
            },
            {
                "Identifiers": {
                    "MarketplaceASIN": {
                        "MarketplaceId": "ATVPDKIKX0DER",
                        "ASIN": "B083JVHWFQ"
                    }
                },
                "Size": "4 oz - 200 Cups"
            },
            {
                "Identifiers": {
                    "MarketplaceASIN": {
                        "MarketplaceId": "ATVPDKIKX0DER",
                        "ASIN": "B08R885CVX"
                    }
                },
                "Size": "4 oz - 1000 Cups"
            }
        ],
```
its really strange, why this difference  between the relationships keys between 2 responses

**Comment by jlevers** [comment]
Is it possible that you were using different versions of this package across the two different calls? Amazon released a newer version of the Catalog API  -- the older version of the Catalog API was in v2.x of this library returned a relationships object when calling `getCatalogItem`, but the newer version of the Catalog API doesn't (v3.x of this library).

**Comment by jlevers** [comment]
@tawfekov try making these calls again with both the `CatalogApi` and the `OldCatalogApi`, and see if you get the results you're looking for with one of them and not the other. I'm guessing that some difference in the two API versions is what was causing your problem.

**Comment by tawfekov** [comment]
Hi @jlevers 
pardon me for my late response , actually  I was using the version `2.0.7` of the package , I've just upgraded to `3.0.7`
I've just tested the same asin and here is my response : 


```
object(SellingPartnerApi\Model\Catalog\Item)#1000 (1) {
  ["container":protected]=>
  array(9) {
    ["asin"]=>
    string(10) "B08ZH7L7RQ"
    ["attributes"]=>
    NULL
    ["identifiers"]=>
    NULL
    ["images"]=>
    NULL
    ["product_types"]=>
    NULL
    ["sales_ranks"]=>
    NULL
    ["summaries"]=>
    array(1) {
      [0]=>
      object(SellingPartnerApi\Model\Catalog\ItemSummaryByMarketplace)#987 (1) {
        ["container":protected]=>
        array(9) {
          ["marketplace_id"]=>
          string(13) "ATVPDKIKX0DER"
          ["brand_name"]=>
          string(34) "Art kups color your world art kups"
          ["browse_node"]=>
          NULL
          ["color_name"]=>
          NULL
          ["item_name"]=>
          string(177) "Art Kups - Espresso Paper Cups | Small Bathroom Cups | Disposable Bath Cups For Kids | Mini Paper Ice Cream Cups | Mouthwash Cups | Tiny Coffee Paper Shot Cups For Home & Office"
          ["manufacturer"]=>
          NULL
          ["model_number"]=>
          NULL
          ["size_name"]=>
          NULL
          ["style_name"]=>
          NULL
        }
      }
    }
    ["variations"]=>
    NULL
    ["vendor_details"]=>
    NULL
  }
}
``` 

as you may see the `variations` is still `null`
Thanks for your help

**Comment by jlevers** [comment]
Could you please try upgrading to `v3.1.0` and using the `OldCatalogApi` class, and see if that fixes the issue?

**Comment by tawfekov** [comment]
I've just upgraded to `3.1.1` and its working fine , here is simple response for the same mentioned asin 
```
[
   {
      "Identifiers":{
         "MarketplaceASIN":{
            "MarketplaceId":"ATVPDKIKX0DER",
            "ASIN":"B07S3VKFKN"
         }
      },
      "Size":"4 oz - 50 Cups"
   },
   {
      "Identifiers":{
         "MarketplaceASIN":{
            "MarketplaceId":"ATVPDKIKX0DER",
            "ASIN":"B083JVHWFQ"
         }
      },
      "Size":"4 oz - 200 Cups"
   },
   {
      "Identifiers":{
         "MarketplaceASIN":{
            "MarketplaceId":"ATVPDKIKX0DER",
            "ASIN":"B08R885CVX"
         }
      },
      "Size":"4 oz - 1000 Cups"
   }
]
```
-2 I've a question , @jlevers can you please create a `stable` tag release so we can  use it on production env 
-3 what can I do?   if I'm willing to help ( as a thank you ) and have some free time ! 


P.s  json encoded to remove null values to simplify output

**Comment by jlevers** [comment]
Great, glad it's working!

1. I'm a little reluctant to create a `stable` release, because Amazon is constantly releasing updates (often breaking updates) to the API. I'm afraid the stable release would get out of date pretty quickly. I'm currently using this library in several production environments -- I upgrade cautiously, but haven't had any major issues. Happy to discuss this more, though :)
2. I think I've got most of the help I need right now -- thanks for the offer! I'll definitely let you know if I need some assistance down the line.
