### ISSUE TITLE
FBA Inventory API (v1) endpoint fails when you enter details = true

### ISSUE THREAD

**Issue by sylarlocke** [jlevers/selling-partner-api#702]
## Problem description:
Problem when adding the "details" element of the call to the endpoint "$sellingPartnerApi->fbaInventory()" and specifically with "getInventorySummaries" it gives an error.
## Error:
Bad Request (400) Response: { "errors": [ { "code": "InvalidInput", "message": "Invalid Input", "details": "" } ] }

## Code

```'details' => $this->details,

public function defaultQuery(): array
    {
        return array_filter([
            'granularityType' => $this->granularityType,
            'granularityId' => $this->granularityId,
            'marketplaceIds' => $this->marketplaceIds,
            'details' => $this->details, //? 'true' : 'false',
            'startDateTime' => $this->startDateTime?->format(\DateTime::RFC3339),
            'sellerSkus' => $this->sellerSkus,
            'sellerSku' => $this->sellerSku,
            'nextToken' => $this->nextToken,
        ]);
```

## Solution
If I do not enter details, it automatically recognizes it as "false", but if I enter "details: true" it gives an error, I have had to solve it by modifying this file:
\vendor\jlevers\selling-partner-api\src\Seller\FBAInventoryV1\Requests\GetInventorySummaries.php

I have modified this line:
```'details' => $this->details```

For this:
```'details' => $this->details ? 'true' : 'false',```

And solved, the version I am using is:
```"jlevers/selling-partner-api": "^6.0.4",```

**Comment by lc-excell** [comment]
We've got same error and fix.

Here's another issue about **getInventorySummaries** upon deserializing it only accepts DateTime for $lastUpdatedTime, however there are instances that the $lastUpdatedTime = false and it causes an error. 
So I Temporarily used **->object()** instead of **->dto()**
`->fbaInventory()->getInventorySummaries(
                        self::GRANULARITY,
                        $this->marketplace->getAmazonMarketplaceId(),
                        [$this->marketplace->getAmazonMarketplaceId()],
                        $this->includeDetails,
                        null,
                        $chunk,
                    )->object()`
                    
https://developer-docs.amazon.com/sp-api/docs/fbainventory-api-v1-reference#inventorysummary
