### ISSUE TITLE
FbaInboundV0 : Response from getShipments throws attribute validation error "invalid length for $city when calling Address"

### ISSUE THREAD

**Issue by ajit-t-dev** [jlevers/selling-partner-api#704]
## Problem description:
When calling getShipments method of FbaInboundV0, the error given below is thrown. This occurs for .com marketplace. There is a validation set for 30 characters for the attribute city in Address class which is causing this error.
## Error:
```
invalid length for $city when calling Address., must be smaller than or equal to 30.
```

## Code

`$response = $this->service->getShipments($queryType, $marketplace, $status, $shipmentIds, $dataStartTime, $dataEndTime, $nextToken)`

**Comment by Inbasecom** [comment]
This is certainly the old problem that has now been added.
https://github.com/jlevers/selling-partner-api/pull/219

**Comment by jlevers** [comment]
@ajit-t-dev are you using v5 or v6?

**Comment by jlevers** [comment]
I'm going to close this since I haven't heard back from you. If you want to make a PR to the `v5.0` branch to fix this, I'm happy to merge it.
