### ISSUE TITLE
Class "Crescat\SaloonSdkGenerator\BaseDto" not found

### ISSUE THREAD

**Issue by Bouhnosaure** [jlevers/selling-partner-api#707]
Hi,

I'll reopen this ticket #666 as i encounter the same issue with all versions from 6.0.0 to 6.0.5 and also v6.x-dev

![image](https://github.com/jlevers/selling-partner-api/assets/3416579/beea3171-a4db-43c4-ba04-6750c83a7d36)

**Comment by Bouhnosaure** [comment]
Only going on the dev-main branch works

**Comment by Fantus** [comment]
same issue
