### ISSUE TITLE
Create Report

### ISSUE THREAD

**Issue by titansoftime** [jlevers/selling-partner-api#709]
I'm sorry for wasting anyone's time but how in the world are report documents created in this new v6 API? I read the readme and see how to download a report if you have the document id, but how do you actually create one?

I see the feed api upload, is that the same thing as creating a v2021-06-30 report document?

Sorry, I read the readme a few times and am not seeing how this works.

**Comment by mickas** [comment]
Example of generating GET_MERCHANT_LISTINGS_ALL_DATA report and waiting in a loop for completion.

## Code
```php
use SellingPartnerApi\Enums\Endpoint;
use SellingPartnerApi\Seller\ReportsV20210630\Dto\CreateReportSpecification;
use SellingPartnerApi\SellingPartnerApi;

require __DIR__ . "/vendor/autoload.php";

$marketplaceId = "***";
$reportType = "GET_MERCHANT_LISTINGS_ALL_DATA";

$connector = SellingPartnerApi::make(
    clientId    : "***",
    clientSecret: "***",
    refreshToken: "***",
    endpoint    : Endpoint::EU
);

$reportsApi = $connector->seller()->reports();

$createReportSpecification = new CreateReportSpecification(
    reportType    : $reportType,
    marketplaceIds: [$marketplaceId]
);

$createReportResponse = $reportsApi->createReport(
    createReportSpecification: $createReportSpecification
);

$reportId = $createReportResponse->dto()->reportId;
echo "reportId: $reportId\n";

$delay = 15;

$maxAttempts = 20;

for($attempt = 1; $attempt <= $maxAttempts; $attempt++)
{
    echo "Sleeping for $delay seconds...\n";
    sleep($delay);

    $reportDto = $reportsApi->getReport($reportId)->dtoOrFail();
    $status    = $reportDto->processingStatus;

    switch($status)
    {
        case "CANCELLED":
        case "FATAL":
            echo "Report generation failed with status $status.\n";
            break 2;

        case "IN_QUEUE":
        case "IN_PROGRESS":
            echo "Report not generated yet, status: " . $status . "\n";
            break;

        case "DONE":

            $documentId = $reportDto->reportDocumentId;
            echo "documentId: $documentId\n";

            $reportDocumentDto = $reportsApi->getReportDocument($documentId, $reportType)->dto();

            $reportContents = $reportDocumentDto->download
            (
                documentType: $reportType,
                encoding:     "UTF8",
                postProcess:  true
            );

            print_r($reportContents);
            break 2; // Exits the switch and the for loop
    }
}

```

## Output
reportId: *************
Sleeping for 15 seconds...
Report not generated yet, status: IN_QUEUE
Sleeping for 15 seconds...
Report not generated yet, status: IN_PROGRESS
Sleeping for 15 seconds...
Report not generated yet, status: IN_PROGRESS
Sleeping for 15 seconds...
Report not generated yet, status: IN_PROGRESS
Sleeping for 15 seconds...
documentId: amzn1.spdoc.****************************************************************
Array
(
    [0] => Array
    (
        [item-name] => **************
        [item-description] => ************
        ...
        ...

**Comment by dpash** [comment]
Rather than polling to see if the report is ready, you should set up a notification subscription for the `REPORT_PROCESSING_FINISHED` event.

https://developer-docs.amazon.com/sp-api/docs/notifications-api-v1-use-case-guide

**Comment by jlevers** [comment]
@dpash  thanks for pointing out the notifications option. It solves a lot of problems when you're dealing with report-heavy workflows. FWIW, for low-frequency use cases (say, less than 5 feeds an hour) I've found it's often easier and problem-free to poll instead of setting up notifications.

**Comment by jlevers** [comment]
I'm going to close this, since this question is also answered in the official Amazon documentation and I'm trying not to spend too much time duplicating their docs, but hopefully this issue still be a helpful resource for anyone else who's trying to figure this out.
