### ISSUE TITLE
Main readme refers to incorrect code for Document downloads

### ISSUE THREAD

**Issue by codesticle** [jlevers/selling-partner-api#71]
In the Main readme, for "Downloading a report document" it shows this incorrect line:

`$docToDownload = new SellingPartnerApi\Document($reportDocumentInfo, $reportType);`

whereas in the V3 readme, it shows this correct line:

`$docToDownload = new SellingPartnerApi\Document($reportDocumentInfo->getPayload(), $reportType);`

Just a heads up to possibly update the main readme to prevent confusion (like it did for me)

**Comment by jlevers** [comment]
I accidentally pushed updates to the README related to the changes in `v3.1.0` before I published the actual changes, which is what caused the discrepancy you noted here. Sorry about that!

I've sinced pushed v3.1.0, which includes updates to the Reports and Feeds APIs, and as a result required updating those code examples. If you install v3.1.0, the example code should work as expected.
