### ISSUE TITLE
Request should contain exactly one of SpdTrackingDetailInput or LtlTrackingDetailInput

### ISSUE THREAD

**Issue by liangfeng520** [jlevers/selling-partner-api#711]
Saloon\Exceptions\Request\ClientException: Bad Request (400) Response: {
  "errors": [
    {
      "code": "BadRequest",
      "message": "ERROR: Request should contain exactly one of SpdTrackingDetailInput or LtlTrackingDetailInput.",
      "details": ""
    }
  ]
}

**Comment by jlevers** [comment]
This should be resolved in v7, which will be released soon.

**Comment by jlevers** [comment]
Released in `v7.0.0`.
