### ISSUE TITLE
Possibility to save the accesstoken like the old callback Function onUpdateCredentials and give the accessToken to speed up the Calls

### ISSUE THREAD

**Issue by GWTorstenDEV** [jlevers/selling-partner-api#712]
Hello,

why it's not possible anymore in v6 to save the accesstoken like the old onUpdateCredentials (callback Function) and give this accessToken the inital Function to speed up the Calls?

The Request time is 3x times slower without accesstoken (autogenerated) than v5. When e.g. a PHP Scripts fire only one call. 
The Speed benefit of the autogenerated accessToken is only there when multiple calls are fired.

Greets
Torsten

**Comment by jlevers** [comment]
Thanks for pointing this out – I thought Saloon was caching tokens, but I was wrong. I just implemented a token caching system via the `tokenCache` parameter to `SellingPartnerApi`, which will be released in v7 relatively soon. There are more details in the README.

**Comment by jlevers** [comment]
Released in `v7.0.0`.
