### ISSUE TITLE
Problem with GetCatalogItem

### ISSUE THREAD

**Issue by MarcoZucc** [jlevers/selling-partner-api#713]
## Problem description:

recive a very strange error when execute a request with GetCatalogItem
i don't understand why the script ask to me $asin argument 

## Error:

SellingPartnerApi\Seller\CatalogItemsV20220401\Api::getCatalogItem(): Argument #1 ($asin) must be of type string, array given

## Code

$catalogApi = $connector->catalogItems();

try {
    // Codice EAN del prodotto da cercare
    $ean = "3578830113254";
    $marketplaceId = "APJ6JRA9NG5V4";
    $includedData = ["summaries", "productTypes", "identifiers",];

    // search with EAN
    $response = $catalogApi->GetCatalogItem( 
        [$marketplaceId], 
        [$ean], 
        "EAN",
        $includedData 
    );

    var_dump($response);

} catch (\Exception $e) {
    // Gestisci gli errori
    echo "Errore: ";
    var_dump($e->getMessage());
}

## Seller Central SP API config page screenshot

![AMZON SP API](https://github.com/jlevers/selling-partner-api/assets/68975347/bd59d9c9-b753-40bb-9ac9-e78ffc1cdbc1)

**Comment by MarcoZucc** [comment]
Could anyone confirm me that GetCatalogItem can do a search using EAN code ?

**Comment by jlevers** [comment]
Couple things going on here:
1. You can't use EANs with `getCatalogItem`
2. You're passing the arguments out of order:
    https://github.com/jlevers/selling-partner-api/blob/64c4b84a6a23c7071cdff7b7e64c89f678180c71/src/Seller/CatalogItemsV20220401/Api.php#L51-L56
