### ISSUE TITLE
Cannot Access PII Data in getOrders Method in v6

### ISSUE THREAD

**Issue by Julian3004** [jlevers/selling-partner-api#733]
**Summary**

In the new version v6 of the jlevers SP-API, I am unable to access Personally Identifiable Information (PII) data using the getOrders method. This functionality was available in version v5, where PII data could be retrieved by specifying data_elements in the method call.

**Code Examples**

Here is the code that worked in v5:
```php
$aZugangsdaten = getAWSZugangsdaten($db_shop);

$config = new SellingPartnerApi\Configuration([
    'lwaClientId' => $aZugangsdaten['lwaClientId'],
    'lwaClientSecret' => $aZugangsdaten['lwaClientSecret'],
    'lwaRefreshToken' => $aZugangsdaten['lwaRefreshToken'],
    'lwaAccessToken' => $aZugangsdaten['lwaAccessToken'],
    'awsAccessKeyId' => $aZugangsdaten['SP_API_ACCESS_KEY'],
    'awsSecretAccessKey' => $aZugangsdaten['SP_API_SECRET_KEY'],
    'endpoint' => $aZugangsdaten['SP_API_ENDPOINT'],
    'roleArn' => $aZugangsdaten['SP_API_ROLE_ARN']
]);

$oApiInstance = new SellingPartnerApi\Api\OrdersV0Api($config);

$oShippingAddress = $oApiInstance->getOrderAddress($r['import_trx_id']);

$aDataElements = ['shippingAddress', 'buyerInfo'];
$oOrdersResult = $oApiInstance->getOrders(
    $aZugangsdaten['aMarketplaceIDs'], 
    next_token: $sNextToken, 
    data_elements: $aDataElements
);
``` 

In version v6, the equivalent method call does not allow access to PII data:
```php
$aZugangsdaten = getAWSZugangsdaten($db_shop);

$connector = SellingPartnerApi\SellingPartnerApi::make(
    clientId: $aZugangsdaten['lwaClientId'],
    clientSecret: $aZugangsdaten['lwaClientSecret'],
    refreshToken: $aZugangsdaten['lwaRefreshToken'],
    endpoint: $aZugangsdaten['SP_API_ENDPOINT'],
);

$oApiInstance = $connector->seller()->ordersV0();
$oResult = $oApiInstance->getOrders(
    $aZugangsdaten['aMarketplaceIDs'],
    createdAfter: $sCreateAfter,
    orderStatuses: $aStatusAbfragen,
    sellerOrderId: $sSellerOrderId
)->dto();
``` 

**Problem Description**

In v5, the getOrders method included a data_elements parameter that allowed specifying an array of elements, such as ['shippingAddress', 'buyerInfo'], to access PII data. This functionality seems to be missing in v6, and consequently, I cannot access PII data using the getOrders method.

However, I can still access PII data using the getOrderAddress method in v6:
`$oShippingAddress = $oApiInstance->getOrderAddress($r['import_trx_id'])->dto();`

**Expected Behavior**

The getOrders method should provide a way to access PII data, similar to the data_elements parameter in v5.
Actual Behavior

The getOrders method in v6 does not provide access to PII data, and there is no equivalent parameter to data_elements for specifying the inclusion of PII data.
Steps to Reproduce

    Set up the SP-API with version v6.
    Attempt to retrieve orders with PII data using the getOrders method.
    Observe that the PII data is not included in the response.

**Possible Fix**

Reintroduce the functionality to specify data_elements or an equivalent parameter in the getOrders method in v6, allowing users to request PII data such as shippingAddress and buyerInfo.
Environment

**Additional Context**

This issue affects data retrieval processes that depend on accessing PII data from order information. Any guidance or updates on how to achieve this functionality in v6 would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by KhorneHoly** [comment]
In the v6 version you must set the dataElements in the creation of the Connector.
This is explained in the Getting Started guide: https://github.com/jlevers/selling-partner-api/blob/496e7edb2c659168f8a6022380f0f53029736b0e/README.md?plain=1#L125-L134

**Comment by Julian3004** [comment]
Thank you for your prompt response.

I apologize for missing that detail in the Getting Started guide. I appreciate your guidance on setting the dataElements during the creation of the Connector. I will review the guide again and update my implementation accordingly.

Thank you for your assistance.

**Comment by KhorneHoly** [comment]
> Thank you for your prompt response.
> 
> I apologize for missing that detail in the Getting Started guide. I appreciate your guidance on setting the dataElements during the creation of the Connector. I will review the guide again and update my implementation accordingly.
> 
> Thank you for your assistance.

No worries, I had to look twice as well.
