### ISSUE TITLE
Properties in some models do not match docs

### ISSUE THREAD

**Issue by ivaaaan** [jlevers/selling-partner-api#74]
Hey. I've noticed a couple of mismatchings between properties in the docs and modes in the library. 

For example, look at the [CreateFeedDocumentResponse](https://github.com/amzn/selling-partner-api-docs/blob/main/references/feeds-api/feeds_2021-06-30.md#createfeeddocumentresponse) definition. There's a property `feedDocumentId`, but in the library, you have this:

```
protected static $openAPITypes = [
    'feed_document_id' => 'string',
    'url' => 'string'
];
```

`feed_document_id` and `feedDocumentId` have different cases. 

Is this intended, or it's a mistake? If so, let me know, and I'll try to submit PRs whenever I notice this.

**Comment by jlevers** [comment]
Good question! All the code in the library is generated using OpenAPI and the JSON models that Amazon has provided. When generating code using OpenAPI, you can specify if you want the model parameters to be in `snake_case` or `camelCase`. Unfortunately, I didn't know about that option when I was first creating this library, so I left it as the default -- `snake_case`. If I were to do it again, I'd go with `camelCase` to match what Amazon shows in their docs, but making that change now would cause breaking changes across the entire library, so it'll have to wait for a new major version.

(Before sending requests to Amazon, the library converts all the `snake_case` parameter names to match what the SP API is actually expecting, which is `UpperCamelCase`. You can check out any of the model files to see the mapping of model attribute names to expected SP API parameter names.)
