### ISSUE TITLE
Need AWD Models / Requests / Responses

### ISSUE THREAD

**Issue by kpconnell** [jlevers/selling-partner-api#748]
## Problem description:
AWD SPAPI Topic was launched last week.     /awd/2024-05-09/. 

@jlevers  we have beta access to all the models they are launching for AWD this year- not just the ones they announced.  If you can let us know generation process, I can probably create a PR if that would help.  

## Error:

```
# Your error here. PLEASE make sure to redact secrets from your error log!
```

## Code

```php
// Your code here...PLEASE make sure to redact secrets from your code!
```

## Seller Central SP API config page screenshot

*your screenshot here*

**Comment by kpconnell** [comment]
@jlevers  i see the contributing details and api.json config, we'll branch and give it a go with our beta model files.

**Comment by jlevers** [comment]
Oh weird, I distinctly remember generating those files but I must have overwritten them somehow. If you'd like to do it yourself, happy to wait for a PR. Otherwise I can add em relatively quickly :)

**Comment by jlevers** [comment]
Ah sorry, just realized I missed the part of your original issue where you said this was a new beta version of the AWD APIs. My bad. I'm gonna close this, but let me know if you still need help.
