### ISSUE TITLE
Docs on how to get started with the library needs to be updated

### ISSUE THREAD

**Issue by anchetaWern** [jlevers/selling-partner-api#749]
## Problem description:

Hello. First off. thanks for this library.
I'm trying to figure how to use the new version, but somehow all the examples leads to an error. Previous version (5.8) works fine, but I just want to upgrade to the new version (6.0)

## Error:

This is the error I'm getting (I'm on PHP 8.1.27 and Laravel 11):

```
Object of type SellingPartnerApi\SellingPartnerApi is not callable
```

<img width="1399" alt="Screenshot 2024-06-27 at 2 54 17 PM" src="https://github.com/jlevers/selling-partner-api/assets/743603/7195da11-2333-412e-80ca-e2110deb9216">

## Code

This is the code I based from the upgrade guide here: https://github.com/jlevers/selling-partner-api/releases/tag/v6.0.0

```php
use SellingPartnerApi\SellingPartnerApi;
use SellingPartnerApi\Enums\Endpoint;

$seller_id = '';
$refresh_token = '';

$sku = '';
$marketplace_id = config('services.amazon.gb_marketplace');
$issue_locale = 'en_US';
$included_data = ['summaries', 'attributes', 'issues', 'offers', 'fulfillmentAvailability', 'procurement'];

$connector = SellingPartnerApi::make(
    clientId: config('services.amazon.client_id'),
    clientSecret: config('services.amazon.client_secret'),
    refreshToken: $refresh_token,
    endpoint: Endpoint::EU, 
);

$listingsItemsApi = $connector()->seller()->listings();

$response = $listingsItemsApi->getListingsItem($seller_id, $sku, [$marketplace_id], $issue_locale, $included_data);

$json = $response->json();
return $data;
```

I also tried the guide here: https://github.com/jlevers/selling-partner-api?tab=readme-ov-file#setup
but got the following error:

```
Non-static method SellingPartnerApi\SellingPartnerApi::seller() cannot be called statically
```

<img width="1389" alt="Screenshot 2024-06-27 at 2 55 57 PM" src="https://github.com/jlevers/selling-partner-api/assets/743603/33b3bee8-f94b-482a-b17c-14e8763aaac2">

Any ideas what's wrong?

**Comment by jlevers** [comment]
Looks like you're using v6, not v7. They're similar, but not the same...if you upgrade to v7 the README sample code will work .
