### ISSUE TITLE
How to Update Price for Repricer in a minutes???

### ISSUE THREAD

**Issue by Kernel1453** [jlevers/selling-partner-api#751]
Hello everyone,
Although I am using version 5.8.1, my question is for consultation. My customer stated that he wanted to use a repricer. I am examining the FeedAPI that I use for inventory management, but it is not enough for the repricer. Because Repricer users want price updates every 5 minutes at most. I activated SQS services for Repricer. Store and price information is coming. With which API can I constantly update these? SubmitFeed does not allow this.

Identify your rate of feed submission: Upload one feed of the same type no more than once every 20 minutes. Allow more time between larger feeds.

Identify the size of your feed submission file: Keep file size below 10 MiB (5*221, or 10,485,760 bytes). If your file exceeds the recommended size, please adjust by dividing it in different smaller submissions.

I'm asking for your help and information.
Best Regards

**Comment by jlevers** [comment]
I recommend using the `JSON_LISTINGS_FEED` – I'm not sure what the rate limit on it is, but I'm pretty sure it's lower than other types of reports, and I've had success doing high-volume inventory updates with it before.

**Comment by Oriontechamz** [comment]
Thank you very much. This is awsome.

**Comment by Kernel1453** [comment]
Thank You very much. this is the solution for me.
