### ISSUE TITLE
access token

### ISSUE THREAD

**Issue by jmshofstall** [jlevers/selling-partner-api#756]
## Problem description:

Trying to upgrade from v5, I already have a model that stores the refresh token and access token with a function to get new tokens that works fine in v5 for multiple users/amazon accounts. In v7 I don't see a way to use the access token so how am I supposed to keep my stored tokens in sync?

**Comment by jlevers** [comment]
You can pass an implementation of `TokenCache` to `SellingPartnerApi::seller()` via the `$cache` parameter...I think you should be able to implement the storage mechanism you need that way. The library handles fetching cached tokens for you, so all you need to do is implement the `TokenCache` interface and the library will automatically use it to cache and retrieve tokens.
