### ISSUE TITLE
Issue upgrading package to 7.0 in laravel 10.48

### ISSUE THREAD

**Issue by joelfrens** [jlevers/selling-partner-api#757]
## Problem description:
Please is it possbile to add support for Laravel 10? We're using Laravel 10.48 and trying to upgrade the package to v7.0 because of the fix available for confirmShipment date issue #698 

## Error:
Problem 1
    - Root composer.json requires jlevers/selling-partner-api 7.0.0 -> satisfiable by jlevers/selling-partner-api[v7.0.0].
    - jlevers/selling-partner-api v7.0.0 requires illuminate/support ^11.5 -> found illuminate/support[v11.5.0, ..., 11.x-dev] but these were not loaded, likely because it conflicts with another require.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Thank you

**Comment by kpconnell** [comment]
Same issue here with laravel 9.19 and we need to update this package for AWD.

**Comment by jlevers** [comment]
Sorry guys, there's dependency conflicts between Laravel `v10.x` and the package that builds this library, [highsidelabs/saloon-sdk-generator](https://github.com/highsidelabs/saloon-sdk-generator). It's unlikely that I'm going to get around to making v7 compatible with earlier versions of Laravel. 

If the thing keeping you from upgrading is just the Laravel upgrade itself (and not other dependencies that require older versions of Laravel), [Laravel Shift](https://laravelshift.com/shifts) is a good solution.

**Comment by joelfrens** [comment]
@jlevers I've managed to get around this issue by upgrading to laravel 11. The confirmShipment method works perfectly now. Thank you :)
