### ISSUE TITLE
Interface throwing exception cannot be resolved

### ISSUE THREAD

**Issue by Mrzhang00** [jlevers/selling-partner-api#761]
Interface response cannot be parsed

Next Saloon\Exceptions\Request\ClientException: Conflict (409) Response: {
  "errors": [
    {
      "code": "StateConflict",
      "message": "The resource specified conflicts with the current state.",
      "details": "Subscription already exists! SubscriptionId: a1a10db in

Expected return
[
  {
    "key": "value"
  },
  {
    "key": "value"
  }
]

**Comment by jlevers** [comment]
This appears to be an issue with your request or with the SP API itself, not with this library. Are you recreating an existing subscription?
