### ISSUE TITLE
Code Example for the Token Cache Implementation v7

### ISSUE THREAD

**Issue by GWTorstenDEV** [jlevers/selling-partner-api#764]
Hi @jlevers,

can you give me an code example for?

1. get the current accesstoken like the old v5 Function onUpdateCredentials on change.
2. set the accesstoken like the old v5 Parameter accessToken to speed up the calls.

I'll need to store the accesstoken in the database (no memory).

Greets
Torsten

**Comment by jlevers** [comment]
Unlike the old access token setup, the new caching mechanism caches all tokens (RDTs, grantless access tokens, and regular access tokens), which means that the setup is a little different. Rather than passing the cached token yourself, you just create a `TokenCache` implementation and the library uses it to store and retrieve the tokens. So you'll probably want a separate database table for this, with `key`, `token`, and `expires_at` fields. You could do something like:

```php
use SellingPartnerApi\Authentication\AccessTokenAuthenticator;
use SellingPartnerApi\TokenCache;

class Cache implements TokenCache
{
    public function get(string $key): AccessTokenAuthenticator|false
    {
        // Check for the presence of a record in the database where the key column = $key
        $record = DB::query('SELECT * FROM cache_table WHERE key = ? LIMIT 1', [$key]);
        if (! $record) {
            return false;
        }

        // If one exists, check that it hasn't expired
        if ($record['expires_at'] <= now()) {
            return false;
        }

        return unserialize($record['token']);
    }

    public function set(string $key, AccessTokenAuthenticator $authenticator): void
    {
        if ($this->get($key)) {
            $this->forget($key);
        }

        DB::query('INSERT INTO cache_table (key, token, expires_at) VALUES (?, ?, ?)', [$key, serialize($authenticator), $authenticator->expiresAt]);
    }

    public function forget(string $key): void
    {
        DB::query('DELETE FROM cache_table WHERE key = ?', [$key]);
    }

    public function clear(): void
    {
        DB::query('DELETE FROM cache_table');
    }
}
```

Then pass an instance of the cache class to your connector:

```php
$connector = SellingPartnerApi::seller(/* ...normal arguments... */, cache: new Cache());
```

I haven't tested this, as the cache implementation is basically pseudocode since I don't know your database interface, but that should give you the direction you need :)

**Comment by GWTorstenDEV** [comment]
> Unlike the old access token setup, the new caching mechanism caches all tokens (RDTs, grantless access tokens, and regular access tokens), which means that the setup is a little different. Rather than passing the cached token yourself, you just create a `TokenCache` implementation and the library uses it to store and retrieve the tokens. So you'll probably want a separate database table for this, with `key`, `token`, and `expires_at` fields. You could do something like:
> 
> ```
> use SellingPartnerApi\Authentication\AccessTokenAuthenticator;
> use SellingPartnerApi\TokenCache;
> 
> class Cache implements TokenCache
> {
>     public function get(string $key): AccessTokenAuthenticator|false
>     {
>         // Check for the presence of a record in the database where the key column = $key
>         $record = DB::query('SELECT * FROM cache_table WHERE key = ? LIMIT 1', [$key]);
>         if (! $record) {
>             return false;
>         }
> 
>         // If one exists, check that it hasn't expired
>         if ($record['expires_at'] <= now()) {
>             return false;
>         }
> 
>         return unserialize($record['token']);
>     }
> 
>     public function set(string $key, AccessTokenAuthenticator $authenticator): void
>     {
>         if ($this->get($key)) {
>             $this->forget($key);
>         }
> 
>         DB::query('INSERT INTO cache_table (key, token, expires_at) VALUES (?, ?, ?)', [$key, serialize($authenticator), $authenticator->expiresAt]);
>     }
> 
>     public function forget(string $key): void
>     {
>         DB::query('DELETE FROM cache_table WHERE key = ?', [$key]);
>     }
> 
>     public function clear(): void
>     {
>         DB::query('DELETE FROM cache_table');
>     }
> }
> ```
> 
> Then pass an instance of the cache class to your connector:
> 
> ```
> $connector = SellingPartnerApi::seller(/* ...normal arguments... */, cache: new Cache());
> ```
> 
> I haven't tested this, as the cache implementation is basically pseudocode since I don't know your database interface, but that should give you the direction you need :)

Thank you. Nice one. I'll got it.

Greets
Torsten
