### ISSUE TITLE
Can I downgrade the PHP version to 7.3?

### ISSUE THREAD

**Issue by geekworm-com** [jlevers/selling-partner-api#769]
## Problem description:
**This is not a bug report.** I just want to ask a question.

I have been using other SDKs and recently wanted to switch to this SDK. I found that the minimum PHP version required is 8.2. I want to know if I can downgrade PHP to 7.3?
## Error:

```
Does not work with PHP 7.3
```

**Comment by jlevers** [comment]
Nope, this will only work with PHP 8.2+. v5 will work with PHP 7.3 (I think), but you'll be missing a lot of functionality and I'm not releasing updates for it anymore.
