### ISSUE TITLE
getShipments() date problem

### ISSUE THREAD

**Issue by btdesign** [jlevers/selling-partner-api#77]
Hi,

There is an errors that I came across on this getShipments() in FBAInboundAPI

    $result = $apiInstance->getShipments($query_type, $marketplace_id, $shipment_status_list, $shipment_id_list, $last_updated_after, $last_updated_before, $next_token);

last_updated_after and last_updated_before, it gave me this error

Fatal error: Uncaught TypeError: rawurlencode(): Argument #1 ($string) must be of type string, DateTime given in C:\Users\Cory\vendor\guzzlehttp\psr7\src\Query.php:97 Stack trace: #0 C:\Users\Cory\vendor\guzzlehttp\psr7\src\Query.php(97): rawurlencode(Object(DateTime)) #1 C:\Users\Cory\vendor\jlevers\selling-partner-api\lib\Api\FbaInboundApi.php(5801): GuzzleHttp\Psr7\Query::build(Array) #2 C:\Users\Cory\vendor\jlevers\selling-partner-api\lib\Api\FbaInboundApi.php(5362): SellingPartnerApi\Api\FbaInboundApi->getShipmentsRequest('SHIPMENT', 'marketplace_id_...', 'CLOSED', NULL, NULL, Object(DateTime), 'token') #3 C:\Users\Cory\vendor\jlevers\selling-partner-api\lib\Api\FbaInboundApi.php(5341): SellingPartnerApi\Api\FbaInboundApi->getShipmentsWithHttpInfo('SHIPMENT', 'marketplace_id_...', Array, NULL, NULL, Object(DateTime), 'token') #4 C:\xampp\htdocs\adw-shipmentIDwithDate.php(29): SellingPartnerApi\Api\FbaInboundApi->getShipments('SHIPMENT', 'marketplace_id_...', Array, NULL, NULL, Object(DateTime), 'token') #5 {main} thrown in C:\Users\Cory\vendor\guzzlehttp\psr7\src\Query.php on line 97

Let me know if you can see what happen to the code.

Thank you,
Cory

**Comment by jlevers** [comment]
Hey @btdesign -- if you figured out what the problem was, would you mind describing the solution here to help other people who run into the same issue? Thanks :)

**Comment by btdesign** [comment]
From:
    $last_updated_after = new \DateTime("2021-08-11T19:20:30+01:00");
    $last_updated_before = new \DateTime("2021-08-16T19:20:30+01:00");

To:
    $last_updated_after = (new \DateTime("2021-08-11T19:20:30+01:00"))->format('c');
    $last_updated_before = (new \DateTime("2021-08-16T19:20:30+01:00"))->format('c');

You would need to format the DateTime.
