### ISSUE TITLE
Sample code in SETUP is out of date

### ISSUE THREAD

**Issue by TonyMarston** [jlevers/selling-partner-api#774]
## Problem description:
Sample code in SETUP (https://github.com/jlevers/selling-partner-api?tab=readme-ov-file#setup) is out of date.

## Error:
The SellingPartnerApi::seller method is called statically, but it is no longer static. The revised code is shown below

## Code
```php
$connector = new SellingPartnerApi(
    clientId: '<LWA client ID>',
    clientSecret: '<LWA client secret>',
    refreshToken: '<LWA refresh token>',
    endpoint: Endpoint::NA
);
$connector = $connector->seller();

$api = $connector->aPlusContentV20201101();
try {
    $result = $api->SearchContentDocuments($marketplace_id);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling aPlusContentV20201101->SearchContentDocuments: ',
        $e->getMessage(),
        PHP_EOL;
}

**Comment by jlevers** [comment]
Is it possible that you're using v6 instead of v7? The `SellingPartnerApi::seller()` method was not static in v6, but it definitely is in v7:

https://github.com/jlevers/selling-partner-api/blob/0915d8f57f7b4f43e97002855f0fe6e3ec8bc216/src/SellingPartnerApi.php#L67

**Comment by TonyMarston** [comment]
I am using the latest version available on https://github.com/jlevers/selling-partner-api which I installed using composer require jlevers/selling-partner-api
 
I am using PHP v8.3.10
 
Tony Marston
 
 <http://www.tonymarston.net> http://www.tonymarston.net
 <http://www.radicore.org> http://www.radicore.org

**Comment by jlevers** [comment]
Could you share your `composer.json`?

**Comment by TonyMarston** [comment]
Here it is:
 
{
    "require": {
        "phpoffice/phpspreadsheet": "^1.29",
        "firebase/php-jwt": "^5.5",
        "aws/aws-sdk-php": "^3.232",
        "symfony/mailer": "^6.3",
        "webklex/php-imap": "^5.4",
        "jlevers/selling-partner-api": "^6.0",
        "composer/semver": "^3.4"
    }
}
 
 
Tony Marston
 
 <http://www.tonymarston.net> http://www.tonymarston.net
 <http://www.radicore.org> http://www.radicore.org

**Comment by jlevers** [comment]
Yep, you're using v6. Change this line:

```
"jlevers/selling-partner-api": "^6.0",
```

to this:

```
"jlevers/selling-partner-api": "^7.1",
```
