### ISSUE TITLE
CURL error when calling aPlusContentV20201101->SearchContentDocuments

### ISSUE THREAD

**Issue by TonyMarston** [jlevers/selling-partner-api#775]
## Problem description:
I am getting an error when calling when calling aPlusContentV20201101->SearchContentDocuments

## Error:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.amazon.com/auth/o2/token 

## Code

```php
$connector = new SellingPartnerApi(
    clientId: '<LWA client ID>',
    clientSecret: '<LWA client secret>',
    refreshToken: '<LWA refresh token>',
    endpoint: Endpoint::{$endpoint}
);
$connector = $connector->seller();

$api = $connector->aPlusContentV20201101();
try {
    $result = $api->SearchContentDocuments($marketplace_id);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling aPlusContentV20201101->SearchContentDocuments: ',
        $e->getMessage(),
        PHP_EOL;
}

**Comment by jlevers** [comment]
This is some sort of network issue, and is unrelated to this library. I've seen quite a few people run into this issue, and typically there's some sort of missing CA certificate.

**Comment by TonyMarston** [comment]
I will have to raise this issue with Amazon.
 
Tony Marston
 
 <http://www.tonymarston.net> http://www.tonymarston.net
 <http://www.radicore.org> http://www.radicore.org
