### ISSUE TITLE
RDT code missing from updated ReportsAPI

### ISSUE THREAD

**Issue by markbeazley** [jlevers/selling-partner-api#78]
I might be missing something and not be able to test it yet, but it looks like after the update to the latest version of the ReportsAPI, none of the calls to `$this->config->signRequest` for any of the `getReportDocument()` functions include the parameters needed for the RDT signing, and the `$report_type` parameters have been removed from the `getReportDocument()` functions.

I'm guessing as these files are auto generated that the code will need to be added back manually.

**Comment by jlevers** [comment]
Thanks for pointing this out -- that's my bad. The new version of the Reports API came with a new OpenAPI model, and I forgot to modify the new model to work with RDTs. I'll try to get a fix out today or tomorrow.

**Comment by jlevers** [comment]
Should be fixed in `v3.1.3`.
