### ISSUE TITLE
Always same Report in other marketplace

### ISSUE THREAD

**Issue by ekaterina4952** [jlevers/selling-partner-api#79]
I am trying to get order report (GET_XML_ALL_ORDERS_DATA_BY_ORDER_DATE_GENERAL) using this SDK.
But always same report orders even if set other marketplace(same region). I hope your suggestion. maybe question and not issue.

Thanks
[code](https://drive.google.com/file/d/1L3rjTuopFT93KKSaP1ybphbvfama3A04/view?usp=sharing)

[error screen](https://ibb.co/hZ35yYz)

**Comment by jlevers** [comment]
Those report IDs aren't the same -- they start and end with the same numbers, but the numbers in the middle are different.

A report coming back cancelled generally means that the Seller account you're making the request for doesn't have any relevant data for that report during the time period you specified.

**Comment by businsolution** [comment]
Thanks

**Comment by ekaterina4952** [comment]
Thanks
