### ISSUE TITLE
Operation: listPrepDetails not available

### ISSUE THREAD

**Issue by lazarovicedo** [jlevers/selling-partner-api#796]
## Problem description:
In order to create an inbound plan and set the correct labelOwner and prepOwner Amazon provides a method called listPrepDetails available under the class fbaInboundV20240320. I don't see this method available yet on selling-partner-api. 
The problem is that the old method that still works and is available on the class fbaInboundV0 will be deprecated by amazon on december 20th 2024.
Do you plan to include listPrepDetails before december 20th? Would you need any help on this?

## Error:
Message: Call to undefined method SellingPartnerApi\Seller\FBAInboundV20240320\Api::listPrepDetails()

**Comment by Elibool** [comment]
+1,  /inbound/fba/2024-03-20/items/prepDetails ;  also not available

**Comment by GWTorstenDEV** [comment]
> +1, /inbound/fba/2024-03-20/items/prepDetails ; also not available

The Missing Call (Operation) is setPrepDetails

The Call https://developer-docs.amazon.com/sp-api/docs/fulfillment-inbound-api-v2024-03-20-reference#setprepdetails

**Comment by jlevers** [comment]
Those endpoints are added in `v7.2.3` :)
