### ISSUE TITLE
Issue with getCompetitivePricing in productPricing

### ISSUE THREAD

**Issue by misterakko** [jlevers/selling-partner-api#80]
There's something strange going on with this call.

First, in /Api/ProductPricingApi.php, line 127, it's declared as
`    public function getCompetitivePricing($marketplace_id, $item_type, $asins = null, $skus = null, $customer_type = null)
`
Notice that "item type" is the second parameter. But [the documentation ](https://github.com/amzn/selling-partner-api-docs/blob/main/references/product-pricing-api/productPricingV0.md#getcompetitivepricing) lists "item type" as the next-to-last parameter.

Even after shuffling the parameter, I'm unable to make it work.
`
// Usual initialisation
$api = new SellingPartnerApi\Api\ProductPricingApi($amazon->myConfig);
$request = $api->getCompetitivePricing(array('APJ6JRA9NG5V4'), 'New', array('B009GHNM5I'));`
returns:
Uncaught SellingPartnerApi\ApiException: [404] {
  "errors": [
    {
      "code": "NotFound",
      "message": "The requested resource doesn\u0027t exist."
    }
  ]
} in /var/www/sarat1300a1/SPAPI/vendor/jlevers/selling-partner-api/lib/Api/ProductPricingApi.php:158

You can easily verify that ASIN B009GHNM5I does exist on Amazon.it

**Comment by jlevers** [comment]
`$item_type`, per Amazon's documentation, should be either `'Asin'` or `'Sku'` based on whether you're looking up items using the `$asins` parameter or the `$skus` parameter. If you change `'New'` to `'Asin'`, your call should work.

You pointed out that the order of the parameters is different in the library vs in Amazon's documentation. To explain that: in the official documentation, they're just listing out all the possible query/body parameters. Query and body parameters are not ordered, _and_ the order of the parameters in this library's methods has no direct relationship to the order in which  those parameters are specified in the request to the API itself. Hope that makes sense :)

**Comment by yingyuhaonan** [comment]
hi,when i use getCompetitivePricing for get something by sku,but it return ClientError,do you know why?

**Comment by jlevers** [comment]
Could you please post your code, the exact error you're getting, and a screenshot of your app's settings page in Seller Central?
