### ISSUE TITLE
Rotating Client Credentials

### ISSUE THREAD

**Issue by sharat-rhinofish** [jlevers/selling-partner-api#814]
## Problem description:
Thank you for incorporating the Grantless Scope to Rotate Client credentials with SP API. The enum however has a minor typo error

The enum in src/Enums/GrantlessScope.php
case ROTATE_TOKEN = 'sellingpartnerapi::client_credentials:rotation';

needs to be changed to

case ROTATE_TOKEN = 'sellingpartnerapi::client_credential:rotation';

Note the singular for client_credential. Refer https://developer-docs.amazon.com/sp-api/docs/application-management-api-v2023-11-30-use-case-guide#step-2-call-the-rotateapplicationclientsecret-operation

**Comment by jlevers** [comment]
Fixed in `v7.2.4`.
