### ISSUE TITLE
Documentation is inadequate

### ISSUE THREAD

**Issue by TonyMarston** [jlevers/selling-partner-api#819]
## Error:

This is related to issue #782. I expect every API to be listed with accurate instructions on how to use it,Yyet when I am in the process of of using your library to interact with Aamzon's A+ Content API I find the instructions to be totally inadequate. The response to my issue #782 was to insert a missing 'use' statement, but I should have been informed that the API needed that use statement instead of wasting time dealing with an avoidable error message.

Your use of the autoloader is less than satisfactory. They were added to PHP in order to avoid the need of using multiple include statements, so I fully expect to require only a single use statement for each API call, and that single statement to automatically process any further include statements wiythout any further intervention on my behalf.

My confifdence in the viability is this library is sadly declining day by day.

## Code

no code

## Seller Central SP API config page screenshot

no screenshot

**Comment by jlevers** [comment]
Sorry you've found the documentation lacking. Do you have any specific suggestions for how I can improve it?

The issue with the `use` statement that you referenced is, IMO, a basic enough piece of knowledge about how to use a library that's loaded via Composer that it doesn't feel worth documenting. _Any_ namespaced class that you use in a Composer project needs to be imported with a `use` statement, and therefore every single class's `use` statement would need to be documented.

> [The autoloader was] added to PHP in order to avoid the need of using multiple include statements, so I fully expect to require only a single use statement for each API call, and that single statement to automatically process any further include statements wiythout any further intervention on my behalf.

This is just simply not true. Go take a look at any number of other large SDKs and you'll see that you need to import all sorts of different classes with `use` statements constantly. The autoloader's purpose is to make it easier to include other package's classes, and classes from other parts of your own project, without needing a ton of `require_once` calls all over the place.

Please keep in mind that this library is an entirely volunteer effort...if you think it has problems, you're more than welcome to contribute documentation or code that you think will improve it, or fork it and build your own version. But please do not open issues as if this was a paid service.

**Comment by iajrz** [comment]
@TonyMarston You seem to be confusing [`require`](https://www.php.net/manual/en/function.require.php) and [`include`](https://www.php.net/manual/en/function.include.php) with [`use`](https://www.php.net/manual/en/language.namespaces.importing.php).

You didn't even use the issue template properly: what you wrote should've been under the Problem Description header, and error should have been empty.

Try not to be rude in the future: It's an ugly garnish, especially on ignorance. Had you been earnest this could've turned into an amiable conversation and everyone could've learned something.

At least you got some links to read docs off of and a little bit of green in your github profile.

**Comment by jlevers** [comment]
I am totally open to constructive criticism, but I will not accept condescension in response to a tool I've put many hundreds of hours into (maybe a thousand?) over the course of years, and publish for free. I hope if you re-read what you've written in your past two comments with an open mind, you'll see what I'm referring to.

My last comment was an attempt to respond in good faith to what felt like a pretty rude issue, but you continue to act entitled to my time and the results of my effort. I'm not asking for a thank you, as obviously this is a totally optional project that I've taken on, I'm just asking for some basic courtesy.

I have no ill will towards you, but this is not a discussion I'm interested in continuing. As I said before, feel free to fork this repo and improve on what I've done. That is the beauty of OSS.
