### ISSUE TITLE
Incomplete exception messages

### ISSUE THREAD

**Issue by NoxArt** [jlevers/selling-partner-api#825]
Hi,
I'm not sure this is based on your package or Saloon or something, but it seems the error messages are incomplete, for example this is what I get in ->getMessage()

Bad Request (400) Response: {
  "errors": [
    {
      "code": "InvalidInput",
      "message": "1 validation error detected: Value \u0027[MskuPrepDetailInput(msku\u003d--censored--, prepCategory\u003dNONE, prepTypes\u003d[ITE

Would it be possible to improve it? Or can I do anything on my side?
Thank you

**Comment by NoxArt** [comment]
Thank you, it seems you're right, there's been a lengthy discussion about it here and apparently there's a way to get it working
https://github.com/guzzle/guzzle/issues/2185#issuecomment-800293420
although they decided against that being the default and I'm not sure SPA should go against that ... but it's quite confusing...

**Comment by jlevers** [comment]
I'm going to close this since it's not an issue with this SDK, but feel free to respond to the issue again if you find a better workaround, so that others can find it if they're looking for a solution.

**Comment by NoxArt** [comment]
fair enough

**Comment by NoxArt** [comment]
Looks like it's a bit more complicated, but like this
![image](https://github.com/user-attachments/assets/fa844ba7-204c-4613-9470-09c557487d34)
