### ISSUE TITLE
Access to requested resource is denied.

### ISSUE THREAD

**Issue by Bariskau** [jlevers/selling-partner-api#84]
Many thanks for the package Jesse. But I'm having a problem with my account. [SELLERAPIDOC](https://github.com/amzn/selling-partner-api-docs/blob/main/guides/en-US/developer-guide/SellingPartnerApiDeveloperGuide.md#step-1-create-an-aws-account) I created my account and application by following the steps. But I am getting 403 error. Any idea about the error?

```
 public function handle()
    {
        $options = [
            "lwaClientId" => env('LWA_CLIENT_ID'),
            "lwaClientSecret" => env('LWA_CLIENT_SECRET'),
            "lwaRefreshToken" => env('LWA_REFRESH_TOKEN'),
            "awsAccessKeyId" => env('AWS_ACCESS_KEY_ID'),
            "awsSecretAccessKey" => env('AWS_SECRET_ACCESS_KEY'),
            "endpoint" => Endpoint::EU_SANDBOX
        ];
        $config = new Configuration($options);

        $api = new Api\OrdersApi($config);
        try {
            $result = $api->getOrders(['A33AVAJ2PDY3EV']);
            print_r($result);
        } catch (\Exception $e) {
            echo 'Exception when calling SellersApi->getMarketplaceParticipations: ', $e->getMessage(), PHP_EOL;
        }    
    }
```

My Response:
```
 {
  "errors": [
    {
      "message": "Access to requested resource is denied.",
     "code": "Unauthorized",
     "details": ""
    }
  ]
}
```

**Comment by jlevers** [comment]
Which SP API roles do you have access to? Could you post a screenshot of your SP API application's settings page?

**Comment by Bariskau** [comment]
@jlevers , I solved the problem by reading your blog post. I was executing using role arn instead of user arn. I added the policy to the user as you said and skipped steps 3-5. Problem solved. Thank you so much. But I don't fully understand why

**Comment by jlevers** [comment]
If you created the SP API application using a role ARN, you need to pass that ARN to the `Configuration` constructor as the key `roleArn`. If you created the SP API application using a user ARN, you need to give that user permission to access the SP API directly by adding the policy to the user instead of the role in AWS.
