### ISSUE TITLE
Character problem in document 

### ISSUE THREAD

**Issue by Bariskau** [jlevers/selling-partner-api#85]
```
$reportDocumentInfo = $this->api->getReportDocument('-----');
$docToDownload = new Document($reportDocumentInfo);
$docToDownload->download();
return $docToDownload->getData();
```
Character problems occur in the reports I receive using the getdata() method.

Error [ss](https://imgur.com/lUVDGoo)

ubuntu 20.4, PHP7.4, PHPSTORM

**Comment by jlevers** [comment]
What language is the messed-up text in? This is clearly some sort of encoding issue. Maybe try calling `download()` with the `$postProcess` [argument](https://github.com/jlevers/selling-partner-api/blob/e52fb63c9b93647ac49ca989889eca2ecc0153c0/lib/Document.php#L79) set to `false`, and see if that fixes the issue.

**Comment by Bariskau** [comment]
Yes I noticed this is an encoding issue. I checked the Document class. $[contents](https://github.com/jlevers/selling-partner-api/blob/e52fb63c9b93647ac49ca989889eca2ecc0153c0/lib/Document.php#L101) mb_detect_encoding() function indicates that the $contents variable is already UTF-8.

**Comment by jlevers** [comment]
Interesting. What happens if you change this:

https://github.com/jlevers/selling-partner-api/blob/e52fb63c9b93647ac49ca989889eca2ecc0153c0/lib/Document.php#L100

to this:

```php
if (
  !($this->contentType === ContentType::XLSX || $this->contentType === ContentType::PDF)
  && !mb_detect_encoding($contents, 'UTF-8', true)
) {

**Comment by jlevers** [comment]
@Bariskau any update on this?

**Comment by jlevers** [comment]
Since I haven't heard anything in a while, I'm going to close this. Feel free to re-open it if you have more questions.

**Comment by jlevers** [comment]
If you could share your exact change, I can integrate it into the library so that your change won't go away next time you update :)

**Comment by Bariskau** [comment]
@jlevers 
If the content is utf-8, it does not change, otherwise it converts to utf-8.
`$contents = mb_convert_encoding($contents, "UTF-8")`

**Comment by Bariskau** [comment]
@jlevers yes i updated it like this. It works pretty well.
