### ISSUE TITLE
FbaInventoryApi::getInventorySummaries Access to requested resource is denied

### ISSUE THREAD

**Issue by SeintApril** [jlevers/selling-partner-api#87]
When I call getInventorySummaries, i got this error.

Exception when calling FbaInventoryApi->getInventorySummaries: [403] { "errors": [ { "message": "Access to requested resource is denied.", "code": "Unauthorized", "details": "" } ] }

My code is 

$apiInstance = new SellingPartnerApi\Api\FbaInventoryApi($config);
$result = $apiInstance->getInventorySummaries('Marketplace', 'A38JS57J8SUO4V', ['A38JS57J8SUO4V']);

I'm calling API from FE region, does this error related to the region?

**Comment by jlevers** [comment]
Hey @SeintApril! Unfortunately, Amazon doesn't support that call for the EU or FE regions yet, per this comment: https://github.com/amzn/selling-partner-api-docs/issues/1316#issuecomment-909433666. Sorry about that!
