### ISSUE TITLE
what is the id-warehouse for VendorDirectFulfillmentInventoryApi

### ISSUE THREAD

**Issue by Ernesto1998super** [jlevers/selling-partner-api#89]
First of all, I appreciate that the library is very complete. I hope you can help me.

**Comment by jlevers** [comment]
I haven't actually used that API personally, but I would guess that `id-warehouse` is the identifier for the Amazon warehouse that the order is being fulfilled from. Does that help?

**Comment by jlevers** [comment]
I'm going to assume you resolved this and close the issue, but feel free to reopen it if you need more help.
