### ISSUE TITLE
Create Feed InvalidInput

### ISSUE THREAD

**Issue by gokigoks** [jlevers/selling-partner-api#90]
Hi Sorry for bothering you guys..

I've been getting an Error 400 on the create feed endpoint when it was working a few weeks ago when I left it. Is anyone else having this issue where the createFeed endpoint returns this generic error? I'm wondering if the error is due to the file uploaded or from the parameters of the createFeed request.

Error:
```

{
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
}
```

I'm using a tab-separated file and I am able to upload it with a 200 response. I did everything trying to debug this like changing each parameter to show exactly which one is erroneous. Changing the marketplaceids and feedtype to invalid values for testing returns a more understandable error. I still can't find what exactly is wrong with my request.

Here's my request when dumped:

   ```
 [body] => {"feedType":"POST_FLAT_FILE_INVLOADER_DATA","marketplaceIds": 
    ["A2EUQ1WTGCTBG2"],"inputFeedDocumentId":"feed-id-sample"}
    [headers] => Array
        (
            [User-Agent] => jlevers/selling-partner-api/3.1.3 (Language=PHP)
            [Accept] => application/json
            [Content-Type] => application/json
            [Host] =>  sellingpartnerapi-na.amazon.com
        )

    [request] => https://sellingpartnerapi-na.amazon.com/feeds/2021-06-30/feeds
```

Desperate for any help I could get. Thank you for reading.

**Comment by jlevers** [comment]
Hey @gokigoks, could you post the actual code you're running?

**Comment by gokigoks** [comment]
@jlevers Thank you for your response. Sorry it's a simple script.. 

```

$feedType = FeedType::POST_FLAT_FILE_INVLOADER_DATA;
$feedsApi = new FeedsApi($config);

// Create feed document
$createFeedDocSpec = new Feeds\CreateFeedDocumentSpecification(['content_type' => $feedType['contentType']]);
$feedDocumentInfo = $feedsApi->createFeedDocument($createFeedDocSpec);
$feedDocumentId = $feedDocumentInfo->getFeedDocumentId();

$feedContents = file_get_contents(__DIR__ . "/file.txt");
$docToUpload = new SellingPartnerApi\Document($feedDocumentInfo, $feedType);
$docToUpload->upload($feedContents);

 
$createFeedSpecs = [
    'feed_type' => $feedType['name'],
    'input_feed_document_id' => $feedDocumentId,
    'marketplace_ids' => array("A2EUQ1WTGCTBG2"),
];

$body = new \SellingPartnerApi\Model\Feeds\CreateFeedSpecification($createFeedSpecs);

try {
    $result = $feedsApi->createFeed($body);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling FeedsApi->createFeed: ', $e->getMessage(), PHP_EOL;
}
```

**Comment by HiraoNotCoffee** [comment]
I'm having the same problem...

**Comment by gokigoks** [comment]
I kinda deduced the issue to either the `input_feed_document_id` or the document being uploaded. I tested changing both parameters to invalid values and the errors returned were the generic error message. Can anyone help me?

My only other option would be to test other feed types but it's so much work in the code. Also not sure if other feed types supports adding products, and changing price, quantity, and availability in a single update as `POST_FLAT_FILE_INVLOADER_DATA`

**Comment by gokigoks** [comment]
Finally saw the issue causing this. When logged on to the seller account, I tried using the 'add product via upload' process but it was interrupted with: 
`"Sorry, the seller is blocked and cannot upload feeds in this marketplace (MERCHANT_STATUS_BLOCKED)". `

Added this info to the current ticket we have on Amazon and awaiting a reply to see if our account gets unblocked. It's mind-boggling how awful the state of SP API is at the moment.. The original error message we get from the API is not close to this issue we found out now. 

Closing this issue for now as it's not related to the package. That said, I'll be back for a final update as the info might help other users getting the generic error in my original post.

**Comment by cybersholt** [comment]
I figured since this topic is the closest to the issue I was experiencing I would add what happened here, I was getting the exact same error:

`{"errors":[{"code":"InvalidInput","message":"Invalid request parameters","details":""}]}`

With basically identical code, it wasn't until I tried uploading an inventory file through seller central that I received the error:

`To protect your account, we have temporarily marked it as inactive. You can reactivate your account by verifying your account information and [updating your charge method.](https://sellercentral.amazon.com/sw/AccountInfo/ChargeMethod/step/View)
ACCOUNT_DORMANT`

**Comment by PengBridgeMedia** [comment]
I also got this error when I calling createFeed().
"errors": [
    {
      "code": "InvalidInput",
      "message": "Invalid request parameters",
      "details": ""
    }
  ]

I already set up the charge method and deposit method in the amazon seller central, and the account is active status. But I still got this error.
Has anyone solved this problem?
