### ISSUE TITLE
Inventory listings and quantities?

### ISSUE THREAD

**Issue by siktec-lab** [jlevers/selling-partner-api#91]
Hi, Can't find out how to get the current listings and their inventory levels.
I can see the endpoints implemented for the FBA inventory, But nothing for FBM inventory.

What am I missing?

**Comment by jlevers** [comment]
Unfortunately, I don't have a good answer for you here -- as far as I know, there aren't any endpoints for fetching FBM inventory. I typically retrieve FBM inventory inventory via a report ([here's a link](https://github.com/amzn/selling-partner-api-docs/blob/main/references/reports-api/reporttype-values.md#inventory-reports) to the relevant report types).
