### ISSUE TITLE
Access to requested resource is denied

### ISSUE THREAD

**Issue by plastic-craft** [jlevers/selling-partner-api#93]
I am trying to develop an application to create and print Amazon shipping labels, but we are running into issues when trying to call either the getEligibleShipmentServices or createShipment operations. I am receiving the following 403 error:

```
{
  "errors":[
    {
      "message":"Access to requested resource is denied.",
      "code":"Unauthorized",
      "details":""
    }
  ]
}
```

We have already applied and been approved for the “Direct-to-Consumer Shipping” roles and it is selected under our app registration page.

The app’s status is however showing as “Current edit is saved as draft”. Does this have anything to do with why we are getting this error when trying to call these restricted operations or should this have no effect? If it makes any difference, we have no intentions on publishing this app to the Marketplace appstore as it is created specifically for our business use cases and only used internally.

Other API calls such as the createFeedDocument, createFeed, createReport, getReportDocument operations work perfectly fine without errors.

Here in an example of a working API call:

```
public function createReport() {
  $apiInstance = new \SellingPartnerApi\Api\ReportsApi();
  $body = new \SellingPartnerApi\Model\Reports\CreateReportSpecification([
    "report_type" => "GET_FLAT_FILE_OPEN_LISTINGS_DATA",
    "marketplace_ids" => [
      "ATVPDKIKX0DER"
    ]
  ]);

  $result = $apiInstance->createReport($body);

  $response = json_decode($result, true);
  $reportId = $response['payload']['reportId'];

  $this->getReport($reportId);
}
```

And here is very basic example of getEligibleShipmentServices call that is resulting in the error, excluding the body:

```
public function getEligibleShipmentServices() {
  $apiInstance = new \SellingPartnerApi\Api\MerchantFulfillmentApi();
  $body = new \SellingPartnerApi\Model\MerchantFulfillment\GetEligibleShipmentServicesRequest();

  $result = $apiInstance->getEligibleShipmentServices($body);

  $response = json_decode($result, true);
  error_log($response);
  }
}
```

I'm unsure if this is an issue on Amazon's side or something I'm doing wrong (maybe needing to use RDT tokens or something), but any help or assistance on this would be appreciated

**Comment by jlevers** [comment]
It shouldn't matter that your app is in draft state.

As far as RDTs go, `createShipment` requires one, but my library should generate that for you. You could dump out the response to make sure there's actually an RDT being passed with the `createShipment` request (the request's `x-amz-access-token` header should begin with `Azt.`), but I'm guessing that's not the problem either. `getEligibleShipmentServices` doesn't require an RDT.

I'm wondering if the `createShipment` and `getEligibleShipmentServices` actually require access to another role other than `Direct-to-Consumer Shipping`. That wouldn't make much sense, but I'm struggling to think of another explanation.

**Comment by plastic-craft** [comment]
Got this resolved after creating a support ticket on Amazon and receiving the following response:

"Once the role is added, re-authorize your application i.e. Generate a new Login with Amazon Refresh token to make valid API calls."

I had added the "Direct-to-Consumer Shipping" role to the app but did not re-authorize it. Simply generating a new LWA refresh token seems to have worked.

**Comment by jordan26** [comment]
Hi @plastic-craft - I'm also trying to use this library for the getEligibleShipmentServices endpoint. If you have a working example of that call, I'd greatly appreciate if you wouldn't mind sharing? Yet to understand how best to approach using that with this library so far.

**Comment by plastic-craft** [comment]
> Hi @plastic-craft - I'm also trying to use this library for the `getEligibleShipmentServices` endpoint. If you have a working example of that call, I'd greatly appreciate if you wouldn't mind sharing? Yet to understand how best to approach using that with this library so far.
> 
> I have a Postman API collection which connects to the Amazon API if it's of any use to you too.

@jordan26 Will get back to you as soon as I figure it out myself, trying to get the correct request body parameters sorted to make a successful call as I'm currently having some validation issues.

**Comment by Dakror** [comment]
I'm experiencing the same issue, re-generating the refresh token did not solve it for me.
