### ISSUE TITLE
Find seller partner is using MFN or FBA or both for shipping?

### ISSUE THREAD

**Issue by Nilanth** [jlevers/selling-partner-api#94]
Does anyone done this?
https://github.com/amzn/selling-partner-api-docs/discussions/1418

**Comment by jlevers** [comment]
This doesn't exist that I know of. The only way I know of to retrieve info about Selling Partners is through the Selling Partner Insights API, and the only call in that API is [getMarketplaceParticipations](https://github.com/jlevers/selling-partner-api/blob/main/docs/Api/SellersApi.md#getMarketplaceParticipations).
