### ISSUE TITLE
Proper usage of the FBMItem Model?

### ISSUE THREAD

**Issue by plastic-craft** [jlevers/selling-partner-api#95]
I'm trying to set all of the required attributes for the FBMItem model prior to calling the getEligibleShipmentServices API but getting the following error:

```
"errors": [
  {
    "code": "InvalidInput",
    "message": "4 validation errors detected: Value \u00270\u0027 at \u0027shipmentRequestDetails.itemList.1.member.quantity\u0027 failed to satisfy constraint: Member must have value greater than or equal to 1; Value \u0027\u0027 at \u0027shipmentRequestDetails.itemList.1.member.orderItemId\u0027 failed to satisfy constraint: Member must have length greater than or equal to 1; Value \u00270\u0027 at \u0027shipmentRequestDetails.itemList.2.member.quantity\u0027 failed to satisfy constraint: Member must have value greater than or equal to 1; Value \u0027\u0027 at \u0027shipmentRequestDetails.itemList.2.member.orderItemId\u0027 failed to satisfy constraint: Member must have length greater than or equal to 1",
    "details": "
  }
]
```

I'm sure this should be an array of some sort since there could potentially be multiple items in the shipment but I can't seem to figure it out how to actually do this. If anybody could provide a basic example for how this should be done that would be much appreciated. Here's what I'm trying to do now: 

```
$item_list = new \SellingPartnerApi\Model\MerchantFulfillment\FBMItem([
  "order_item_id" => $orderID,
  "quantity" => $quantity
]);
```

**Comment by jlevers** [comment]
It looks like there are some strange values (maybe they have the wrong encoding?) in your `$orderID` and `$quantity` variables. `\u0027` is an apostrophe (`'`), and `\u00270` is an upside-down "m" (`ɰ`). Is it possible that you're encoding those values incorrectly?

**Comment by plastic-craft** [comment]
Thought that might be the case but even when just hardcoding these two attributes to valid values (as both strings and integers) I am getting the same thing.

If it helps, here is an example body GetEligibleShipmentServicesRequest body with the full shipment_request_details (just with modified IDs):

```
{
  "AmazonOrderId": "111-1111111-1111111",
  "ItemList": {
    "OrderItemId": "111111111",
    "Quantity": "1
  },
  "ShipFromAddress": {
    "Name": "Plastic-Craft Products ",
    "AddressLine1": "744 West Nyack Rd",
    "Email": "ecom@plastic-craft.com",
    "City": "West Nyack ",
    "PostalCode": "10994",
    "CountryCode": "US",
    "Phone": "845-358-3010
  },
  "PackageDimensions": {
    "Length": "10",
    "Width": "7",
    "Height": "3.5",
    "Unit": "inches
  },
  "Weight": {
    "Value": 17.23651006,
    "Unit": "g
  }
}
```

For some reason, the last values seem to drop off a closing quotation mark but it doesn't seem to throw any errors for that if removing the ItemList from the body.

If I don't include the ItemList in the body I receive the following error, which just implies that it is a required field that is not included. Although it still shows the same strange values `\u0027`

```
{
  "errors": [
    {
      "code": "InvalidInput",
      "message": "1 validation error detected: Value \u0027[]\u0027 at \u0027shipmentRequestDetails.itemList\u0027 failed to satisfy constraint: Member must have length greater than or equal to 1",
      "details": "
    }
  ]
}
```

**Comment by plastic-craft** [comment]
I guess a related question would be how to include multiple items in a single ItemList, since I'm sure something like this wouldn't work:

```
$item_list = new \SellingPartnerApi\Model\MerchantFulfillment\FBMItem([
  "order_item_id" => $orderID1,
  "quantity" => $quantity1,
  "order_item_id" => $orderID2,
  "quantity" => $quantity2,
]);
```

I've also tried doing something like this, but have had no luck either:

```
$item_list = new \SellingPartnerApi\Model\MerchantFulfillment\FBMItem([
  "item" => ([
    "order_item_id" => $orderID1,
    "quantity" => $quantity1
  ]),
  "item" => ([
    "order_item_id" => $orderID2,
    "quantity" => $quantity2
  ])
]);
```
However when doing it this way, the ItemList in the full shipment_request_details body appears to be empty `"ItemList": {}`

**Comment by jlevers** [comment]
To send multiple items, you make an array of `FBMItem` objects:

```php
use SellingPartnerApi\Model\MerchantFulfillment;

$request = new MerchantFulfillment\GetEligibleShipmentServicesRequest([
    'shipment_request_details' => new MerchantFulfillment\ShipmentRequestDetails([
        ....
        'item_list' => [
            new MerchantFulfillment\FBMItem([
                'order_item_id' => 'qwerty',
                'quantity' => 1
            ]),
            new MerchantFulfillment\FBMItem([
                'order_item_id' => 'asdf',
                'quantity' => 1
            ])
        ],
        ....
    ])
]);

**Comment by plastic-craft** [comment]
I'm going to close this issue for now as that example you provided seems to have fixed the original error message regarding the validation issues.

I was simply not putting each `FBMItem` object into an array, like so:

```php
"item_list" => [
  new \SellingPartnerApi\Model\MerchantFulfillment\FBMItem([
    "order_item_id" => $orderID,
    "quantity" => $quantity
  ])
]
```

I am still unable to make a successful getEligibleShipmentServices call despite this fix and now just getting a new error message of "Invalid Input" which provides no details on what is wrong. However, I believe the issue is on Amazon's end as I have every required field filled in properly and the JSON request body looks correct.

@jlevers I am going to create an Amazon support ticket for further help with this but just wanted to know if there is a way to get the response headers (x-amzn-date and x-amzn-requestId) from the response?

**Comment by jlevers** [comment]
I've been meaning to create a way to get those headers easily for quite a while (see #33), but currently the only way to get that info is to add `var_dump($response->getHeaders())` in the actual `*Api` file. In your case, you would need to do that around this section of `MerchantFulfillmentApi.php` in `vendor/jlevers/selling-partner-api/lib/Api`:

https://github.com/jlevers/selling-partner-api/blob/6867bb965b3d660c65066db0e63232c233fbb537/lib/Api/MerchantFulfillmentApi.php#L2223
