### ISSUE TITLE
Do not provide boilerplate examples that do not work

### ISSUE THREAD

**Issue by kpconnell** [jlevers/selling-partner-api#96]
There are many examples like so:

```
$apiInstance = new SellingPartnerApi\Api\ReportsApi($config);
$body = new \SellingPartnerApi\Model\Reports\CreateReportSpecification(); // \SellingPartnerApi\Model\Reports\CreateReportSpecification

try {
    $result = $apiInstance->createReport($body);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ReportsApi->createReport: ', $e->getMessage(), PHP_EOL;
}

```
Without passing data to the constructors for the requests ($body), or calling all the setters, those requests would never succeed, and make all of these examples essentially wrong.

**Comment by jlevers** [comment]
All the examples are auto-generated, and providing real data in all the `$body` models would take a ton of time. I think that given the rest of the documentation, most people are able to infer what they need to do from the existing examples, so I'm marking this as wontfix.

**Comment by kpconnell** [comment]
The irony of an autogenerated example seems to be lost here.
