### ISSUE TITLE
getOrderItems method wont work anymore 

### ISSUE THREAD

**Issue by yassersebai** [jlevers/selling-partner-api#97]
I used to get order items data using the ```getOrderItems``` method, suppling both the amazon order id and the next token for it, at some point, this is not working anymore, when using it the thrown error would be :
```
Call to a member function getBareHost() on null {"exception":"[object] (Error(code: 0): Call to a member function getBareHost() on null at APP_DIRECTORY\\vendor\\jlevers\\selling-partner-api\\lib\\HeaderSelector.php:54)
```
here's the line where the error is thrown : 
```
$res = $orderApi->getOrderItems(
            $this->order['amazon_order_id'],
            $this->next_token
);
```
note that the order id is definitely not null, and the next_token is optional.

**Comment by jlevers** [comment]
Is it possible that you passed a null value to the `OrdersApi` constructor instead of a `Configuration` object? I just noticed that it's possible to pass `null` for the `*Api` classes' `$config` constructor parameter, which shouldn't be allowed (I need to fix that).

**Comment by jlevers** [comment]
This should be resolved by the `getHeaders()` method I added to response models in `v4.0.0`. Please let me know if you run into any issues with this solution :)

**Comment by yassersebai** [comment]
actually the problem was solved, thanks!
